insert into public.topics (
  id,
  subject,
  title,
  description,
  level,
  class_levels,
  series,
  question_count,
  estimated_minutes
) values
('math-number-algebra', 'Mathematics', 'Number and algebra', 'Indices, surds, logarithms, sequences, inequalities, and algebraic manipulation.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science', 'commercial', 'technical'], 0, 35),
('math-geometry-measurement', 'Mathematics', 'Geometry and measurement', 'Angles, polygons, circles, loci, mensuration, bearings, and scale drawing.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science', 'commercial', 'technical'], 0, 35),
('math-trigonometry', 'Mathematics', 'Trigonometry', 'Ratios, identities, sine rule, cosine rule, bearings, heights, and distances.', 'ordinary', array['form_4', 'form_5'], array['general', 'science', 'technical'], 0, 40),
('math-statistics-probability', 'Mathematics', 'Statistics and probability', 'Data presentation, averages, dispersion, probability, and interpretation.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science', 'commercial', 'technical'], 0, 30),
('addmath-functions', 'Additional Mathematics', 'Functions and graphs', 'Mappings, composite functions, inverse functions, curve sketching, and transformations.', 'ordinary', array['form_4', 'form_5'], array['science', 'technical'], 0, 40),
('addmath-calculus', 'Additional Mathematics', 'Introductory calculus', 'Limits, differentiation, integration, tangents, normals, maxima, and minima.', 'ordinary', array['form_4', 'form_5'], array['science', 'technical'], 0, 45),
('puremath-mechanics', 'Pure Mathematics with Mechanics', 'Pure mathematics with mechanics', 'Algebra, calculus, vectors, kinematics, forces, moments, energy, and motion.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_science'], 0, 60),
('puremath-statistics', 'Pure Mathematics with Statistics', 'Pure mathematics with statistics', 'Algebra, calculus, probability, distributions, correlation, regression, and statistical inference.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_science'], 0, 60),
('furthermath-pure', 'Further Mathematics', 'Pure mathematics', 'Complex numbers, matrices, vectors, proof, series, and advanced algebra.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_science'], 0, 55),
('furthermath-mechanics-statistics', 'Further Mathematics', 'Mechanics and statistics', 'Forces, motion, moments, probability distributions, and statistical inference.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_science'], 0, 55),
('eng-comprehension-summary', 'English Language', 'Comprehension and summary', 'Reading comprehension, inference, vocabulary, and concise summary writing.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science', 'arts', 'commercial', 'technical'], 0, 30),
('eng-grammar-vocabulary', 'English Language', 'Grammar and vocabulary', 'Sentence structure, tenses, clauses, concord, punctuation, and word use.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science', 'arts', 'commercial', 'technical'], 0, 30),
('eng-essay-writing', 'English Language', 'Composition and essay writing', 'Narrative, descriptive, argumentative, expository, and formal writing.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science', 'arts', 'commercial', 'technical'], 0, 35),
('lit-poetry-drama-prose', 'English Literature', 'Poetry, drama, and prose', 'Literary devices, character, theme, setting, plot, and critical appreciation.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['arts'], 0, 40),
('alit-textual-analysis', 'English Literature', 'Advanced textual analysis', 'Close reading, comparison, literary periods, criticism, and structured essays.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_arts'], 0, 50),
('french-grammar', 'French', 'Grammaire et conjugaison', 'Accords, temps verbaux, pronoms, syntaxe, discours direct et indirect.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science', 'arts', 'commercial', 'technical'], 0, 30),
('french-comprehension-expression', 'French', 'Comprehension et expression ecrite', 'Lecture, vocabulaire, resume, redaction, lettre, dialogue, et traduction.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science', 'arts', 'commercial', 'technical'], 0, 35),
('special-bilingual-french', 'Special Bilingual Education French', 'Special bilingual French', 'Advanced bilingual comprehension, grammar, translation, writing, and oral expression.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_arts'], 0, 45),
('religion-bible-ethics', 'Religious Studies', 'Biblical studies and ethics', 'Old Testament, New Testament, moral issues, worship, and religious values.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'arts'], 0, 35),
('philosophy-logic-ethics', 'Philosophy', 'Logic, ethics, and philosophy', 'Arguments, fallacies, epistemology, metaphysics, ethics, political philosophy, and African philosophy.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_arts'], 0, 50),
('logic-reasoning', 'Logic', 'Formal and critical reasoning', 'Propositions, syllogisms, truth tables, validity, fallacies, and argument analysis.', 'ordinary', array['form_4', 'form_5'], array['general', 'arts'], 0, 35),
('citizenship-civics', 'Citizenship Education', 'Citizenship and civic life', 'Rights, duties, constitution, democracy, elections, peace, and national integration.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'arts'], 0, 25),
('physics-mechanics', 'Physics', 'Mechanics', 'Motion, forces, work, energy, power, pressure, moments, and machines.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['science', 'technical'], 0, 40),
('physics-waves-electricity', 'Physics', 'Waves, electricity, and magnetism', 'Light, sound, heat, current electricity, circuits, magnetism, and electromagnetism.', 'ordinary', array['form_4', 'form_5'], array['science', 'technical'], 0, 45),
('aphysics-fields-modern', 'Physics', 'Advanced physics', 'Fields, oscillations, thermal physics, atomic physics, electronics, and nuclear physics.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_science'], 0, 55),
('chem-structure-bonding', 'Chemistry', 'Atomic structure and bonding', 'Atoms, periodicity, ionic bonding, covalent bonding, metallic bonding, and structure.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['science', 'technical'], 0, 40),
('chem-stoichiometry-reactions', 'Chemistry', 'Stoichiometry and reactions', 'Moles, equations, acids, bases, salts, redox, rates, and equilibrium.', 'ordinary', array['form_4', 'form_5'], array['science', 'technical'], 0, 45),
('achem-organic-physical', 'Chemistry', 'Advanced organic and physical chemistry', 'Hydrocarbons, functional groups, energetics, kinetics, equilibrium, and electrochemistry.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_science'], 0, 55),
('bio-cell-transport', 'Biology', 'Cells and transport', 'Cell structure, microscopy, diffusion, osmosis, active transport, and enzymes.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science'], 0, 35),
('bio-nutrition-respiration', 'Biology', 'Nutrition, respiration, and excretion', 'Photosynthesis, food tests, digestion, gas exchange, respiration, kidneys, and homeostasis.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science'], 0, 40),
('bio-reproduction-ecology', 'Biology', 'Reproduction, genetics, and ecology', 'Reproduction, inheritance, variation, evolution, ecosystems, cycles, and conservation.', 'ordinary', array['form_4', 'form_5'], array['general', 'science'], 0, 45),
('abio-physiology-genetics', 'Biology', 'Advanced physiology and genetics', 'Cell biochemistry, physiology, coordination, inheritance, ecology, and evolution.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_science'], 0, 55),
('human-biology-systems', 'Human Biology', 'Human body systems', 'Support, movement, circulation, respiration, digestion, reproduction, and health.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science'], 0, 40),
('geology-earth-materials', 'Geology', 'Earth materials and processes', 'Minerals, rocks, plate tectonics, structures, fossils, geological maps, and earth history.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_science', 'a_arts'], 0, 50),
('geography-physical', 'Geography', 'Physical geography', 'Rocks, weathering, climate, rivers, coasts, soils, vegetation, and natural hazards.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'arts'], 0, 40),
('geography-human-cameroon', 'Geography', 'Human and Cameroon geography', 'Population, settlement, agriculture, industry, transport, trade, maps, and Cameroon regions.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'arts'], 0, 45),
('ageography-regional-skills', 'Geography', 'Advanced geography and map skills', 'Geomorphology, climatology, regional geography, statistics, fieldwork, and map interpretation.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_arts'], 0, 55),
('history-cameroon-africa', 'History', 'Cameroon and African history', 'Pre-colonial societies, colonial rule, nationalism, reunification, and post-independence Cameroon.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'arts'], 0, 45),
('history-world', 'History', 'World history', 'European contact, imperialism, world wars, international organizations, and global change.', 'ordinary', array['form_4', 'form_5'], array['general', 'arts'], 0, 45),
('ahistory-cameroon-world', 'History', 'Advanced Cameroon, Africa, and world history', 'Historiography, political development, diplomacy, conflicts, and modern state formation.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_arts'], 0, 55),
('econ-microeconomics', 'Economics', 'Microeconomics', 'Scarcity, demand, supply, elasticity, production, costs, markets, and price determination.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_arts', 'a_commercial'], 0, 50),
('econ-macroeconomics-development', 'Economics', 'Macroeconomics and development', 'National income, money, banking, inflation, trade, public finance, growth, and development.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_arts', 'a_commercial'], 0, 55),
('commerce-trade-documents', 'Commerce', 'Trade and business documents', 'Home trade, foreign trade, retailing, wholesaling, invoices, receipts, and transport.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['commercial', 'technical'], 0, 35),
('commerce-finance-insurance', 'Commerce', 'Finance, banking, and insurance', 'Money, banking, credit, insurance, communication, advertising, and consumer protection.', 'ordinary', array['form_4', 'form_5'], array['commercial', 'technical'], 0, 40),
('accounting-principles', 'Accounting', 'Accounting principles', 'Double entry, source documents, ledgers, trial balance, errors, and control accounts.', 'ordinary', array['form_4', 'form_5'], array['commercial'], 0, 45),
('aaccounting-financial-statements', 'Accounting', 'Advanced accounting', 'Final accounts, partnerships, companies, incomplete records, ratios, budgets, and cash flow.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_commercial'], 0, 55),
('business-enterprise-management', 'Business Studies', 'Enterprise and management', 'Business ownership, objectives, management, marketing, operations, finance, and entrepreneurship.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['commercial', 'technical'], 0, 40),
('abusiness-strategy', 'Business Studies', 'Advanced business management', 'Strategy, human resources, marketing, operations, finance, business environment, and decision making.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_commercial'], 0, 55),
('cs-computer-systems', 'Computer Science', 'Computer systems', 'Hardware, software, data representation, operating systems, networks, security, and databases.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['science', 'technical'], 0, 40),
('cs-programming-algorithms', 'Computer Science', 'Programming and algorithms', 'Problem solving, flowcharts, pseudocode, variables, control structures, arrays, and testing.', 'ordinary', array['form_4', 'form_5'], array['science', 'technical'], 0, 45),
('acs-software-data', 'Computer Science', 'Advanced software and data', 'Algorithms, programming paradigms, databases, computer architecture, networks, and systems analysis.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_science'], 0, 55),
('ict-productivity-tools', 'ICT', 'Productivity tools and digital communication', 'Word processing, spreadsheets, presentations, internet, email, collaboration, and digital citizenship.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['science', 'commercial', 'technical'], 0, 35),
('ict-data-web', 'ICT', 'Data, web, and information systems', 'Databases, web concepts, networks, information systems, security, and practical ICT tasks.', 'ordinary', array['form_4', 'form_5'], array['science', 'commercial', 'technical'], 0, 40),
('food-nutrition', 'Food and Nutrition', 'Food science and meal planning', 'Nutrients, digestion, food hygiene, preservation, meal planning, practical cookery, and budgeting.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general'], 0, 40),
('food-science-nutrition', 'Food Science and Nutrition', 'Advanced food science and nutrition', 'Food chemistry, dietetics, meal planning, preservation, hygiene, practical work, and food service.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_science'], 0, 50),
('agric-crop-animal', 'Agricultural Science', 'Crop and animal production', 'Soils, crops, pests, livestock, farm tools, management, and agricultural economics.', 'ordinary', array['form_3', 'form_4', 'form_5'], array['general', 'science'], 0, 45),
('aagric-production-economics', 'Agricultural Science', 'Advanced agricultural science', 'Crop physiology, animal production, soil science, farm management, and agricultural economics.', 'advanced', array['lower_sixth', 'upper_sixth'], array['a_science'], 0, 55)
on conflict (id) do update set
  subject = excluded.subject,
  title = excluded.title,
  description = excluded.description,
  level = excluded.level,
  class_levels = excluded.class_levels,
  series = excluded.series,
  question_count = excluded.question_count,
  estimated_minutes = excluded.estimated_minutes;

notify pgrst, 'reload schema';
