begin;

-- English GCE hard practice papers: topic-wise structural sets and MCQ sets.
-- Generated by scripts/generate-hard-papers.mjs.
-- Every row carries an explicit topic_id so topic-wise papers land on the
-- correct syllabus topic instead of a subject-level default.

insert into public.course_documents (
  id, topic_id, subject, title, language, level, class_levels, series, status,
  markdown_content, content_kind, doc_type, curriculum_path, exam, content_year,
  source_type, source_reference, permission_status, review_status, content_version, change_note
)
values
(
  'e48e6cff-6159-54af-8a12-14a21a3a846e',
  'eng-comprehension-summary',
  'English Language',
  'CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P2 SET 4',
  'english',
  'ordinary',
  array['form_5']::text[],
  array['general', 'science', 'arts', 'commercial', 'technical']::text[],
  'published',
  $md$
# CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P2 SET 4

## Structural Question Bank — Comprehension and summary

**Level:** Ordinary Level
**Class:** FORM 5
**Series:** general, science, arts, commercial, technical
**Subject:** English Language

**Instructions:**

- Answer all questions in a clear and organized manner.
- Show all working where calculations are required.
- Use correct subject terminology and Cameroon GCE presentation standards.
- Diagrams, tables, maps, labelled sketches, and examples should be included where useful.

---

## SECTION 1: COMPREHENSION AND SUMMARY

**Q1.** Read the passage below and answer the questions that follow.

*"The village market was more than a place of trade; it was the beating heart of the community. Here, farmers exchanged news with traders, and children learned the value of honest dealing. Yet in recent years, the market has been shrinking as young people migrate to the cities, leaving behind ageing vendors and empty stalls."*

(a) In one sentence, state the main idea of the passage. *(3 marks)*

(b) Give two reasons the writer gives for the market's decline. *(4 marks)*

(c) Explain what the writer means by "the beating heart of the community". *(4 marks)*

---

**Q2.** Summarise the following passage in not more than 60 words.

*"Rainwater harvesting is an ancient practice that is regaining importance in Cameroon. By collecting runoff from rooftops into storage tanks, households can reduce their dependence on erratic municipal supplies. The water is ideal for gardening, washing, and, after proper treatment, even drinking. Critics argue that the initial cost of tanks and guttering is prohibitive, but supporters point out that the investment pays for itself within a few years through lower water bills and greater self-reliance."*

Your summary must be in continuous prose and must not include direct quotations. *(10 marks)*

---

**Q3.** Read the passage and answer the questions that follow.

*"The examination results were posted at dawn. For Amina, the moment was both terrifying and liberating. She had spent three sleepless nights rehearsing the worst-case scenario, yet when her name appeared on the list of successful candidates, she felt a surge of relief so powerful it left her breathless."*

(a) Identify the dominant emotion in the passage and quote one phrase that supports your answer. *(4 marks)*

(b) What does the phrase "rehearsing the worst-case scenario" reveal about Amina's character? *(4 marks)*

(c) Suggest a suitable title for the passage. *(2 marks)*

---

**Q4.** Read the passage and answer the questions that follow.

*"Cameroon's forests are among the most biodiverse on the continent, sheltering elephants, gorillas, and thousands of plant species. However, illegal logging and slash-and-burn farming are destroying these habitats at an alarming rate. Conservationists argue that protecting the forests is not merely an environmental concern but an economic one, since ecotourism and sustainable harvesting can generate lasting income for local communities."*

(a) State two threats to Cameroon's forests mentioned in the passage. *(4 marks)*

(b) Explain why the writer describes forest protection as "an economic one". *(4 marks)*

(c) Give the meaning of "biodiverse" as used in the passage. *(2 marks)*

---

**Q5.** Summarise the following passage in not more than 70 words.

*"Mobile money has transformed financial life in Cameroon. Before its arrival, many rural families had no access to banks and relied on risky methods of storing and transferring cash. Today, a farmer can sell his cocoa, receive payment on his phone, and pay his children's school fees without travelling to a town. Mobile money has also created jobs, as agents earn commissions on every transaction. Nevertheless, concerns remain about fraud, network failures, and the exclusion of the elderly who struggle with the technology."*

Your summary must be in continuous prose. *(10 marks)*

---

**Q6.** Read the passage and answer the questions that follow.

*"The old woman refused to be rushed. Each morning she swept her compound with slow, deliberate strokes, as if the dust were an enemy she had known for years. Her neighbours, who hurried past with phones pressed to their ears, did not understand that for her, sweeping was not a chore but a meditation."*

(a) What does the writer suggest about the difference between the old woman and her neighbours? *(4 marks)*

(b) Explain the meaning of "a meditation" in the context of the passage. *(4 marks)*

(c) Identify one figure of speech used in the passage and explain its effect. *(4 marks)*

---

**Q7.** Read the passage and answer the questions that follow.

*"The river had always been generous, giving the village fish, water, and fertile soil. But generosity, the elders warned, must never be taken for granted. When the rains failed and the river shrank to a muddy trickle, the village learned that nature's gifts come with conditions."*

(a) State the lesson the village learned. *(3 marks)*

(b) Explain how the writer uses personification in the passage. *(4 marks)*

(c) What is the writer's attitude towards the river? Support your answer with evidence. *(4 marks)*

---

**Q8.** Summarise the following passage in not more than 60 words.

*"School feeding programmes in Cameroon serve a dual purpose. For children, a guaranteed midday meal improves concentration, attendance, and overall health. For farmers, the programmes provide a reliable market for their produce, since schools purchase staples such as maize, beans, and groundnuts from local cooperatives. Critics note that the programmes are expensive to run and vulnerable to corruption, but supporters argue that the long-term benefits to education and agriculture outweigh the costs."*

Your summary must be in continuous prose. *(10 marks)*

---

**Q9.** Read the passage and answer the questions that follow.

*"He had rehearsed the speech a hundred times, yet when he stood before the crowd, the words evaporated. His palms were slick, his throat dry. Then he remembered his father's advice: 'The audience wants you to succeed.' He took a breath, and the first sentence came out steady."*

(a) Describe the speaker's state of mind at the start of the passage. *(3 marks)*

(b) What effect does the father's advice have on the speaker? *(4 marks)*

(c) Explain the meaning of "the words evaporated". *(3 marks)*

---

**Q10.** Read the passage and answer the questions that follow.

*"Plastic waste is choking Cameroon's cities. Discarded bottles clog drainage channels, causing floods during the rainy season, while burning the waste releases toxic fumes. Some entrepreneurs have begun collecting plastics and recycling them into paving blocks, creating jobs and cleaning the streets. The challenge, they say, is not a lack of solutions but a lack of will."*

(a) State two problems caused by plastic waste. *(4 marks)*

(b) How have some entrepreneurs responded to the problem? *(3 marks)*

(c) Explain the final sentence: "The challenge... is not a lack of solutions but a lack of will." *(4 marks)*

---

**Q11.** Summarise the following passage in not more than 65 words.

*"Community health workers are the backbone of rural healthcare in Cameroon. Trained to diagnose common illnesses, administer vaccines, and advise on hygiene, they bring medical care to villages that would otherwise travel hours to reach a clinic. Their work has reduced infant mortality and improved maternal health in many regions. Yet these workers are often unpaid volunteers, and many leave the profession once they find better-paying work. Health experts argue that investing in community health workers is one of the most cost-effective ways to strengthen the health system."*

Your summary must be in continuous prose. *(10 marks)*

---

**Q12.** Read the passage and answer the questions that follow.

*"The two brothers inherited the same plot of land. One planted cocoa and prospered; the other planted nothing and waited for the land to feed him. Years later, the first brother built a house, while the second still waited, blaming the soil for his poverty."*

(a) What is the moral of the passage? *(4 marks)*

(b) Contrast the attitudes of the two brothers. *(4 marks)*

(c) Explain the irony in the final sentence. *(4 marks)*

---

**Q13.** Read the passage and answer the questions that follow.

*"Tourism in Cameroon is a sleeping giant. The country boasts beaches, mountains, wildlife parks, and a rich cultural heritage, yet it attracts a fraction of the visitors that smaller neighbours receive. Poor infrastructure, limited marketing, and safety concerns are often cited as reasons. Those who have visited, however, speak of a country that rewards the adventurous traveller."*

(a) What does the writer mean by calling tourism "a sleeping giant"? *(4 marks)*

(b) Give two reasons why Cameroon attracts few tourists. *(4 marks)*

(c) What is the writer's overall attitude towards Cameroon's tourism potential? *(3 marks)*

---

**Q14.** Summarise the following passage in not more than 60 words.

*"The traditional African family is often described as an extended family, where uncles, aunts, and grandparents share in raising children. This system provides a safety net: when parents fall ill or travel, relatives step in. It also transmits values, history, and skills across generations. However, urbanisation and economic pressures are weakening these ties, as families become smaller and more mobile. Sociologists warn that the loss of the extended family could leave many children without the support they once enjoyed."*

Your summary must be in continuous prose. *(10 marks)*

---

**Q15.** Read the passage and answer the questions that follow.

*"The teacher wrote a single word on the board: 'Why?' For a moment the class was silent. Then hands shot up. The question, she explained, was more important than any answer, because it was the beginning of every discovery. From that day, her students stopped memorising and started questioning."*

(a) What change does the teacher bring about in her students? *(4 marks)*

(b) Explain the significance of the word "Why?" in the passage. *(4 marks)*

(c) What does the passage suggest about the difference between memorising and questioning? *(4 marks)*

---

**Q16.** Read the passage and answer the questions that follow.

*"The harvest festival drew people from every village in the district. Drummers led the procession, dancers in bright cloth followed, and elders presided over the ceremony with quiet dignity. For the young, it was a spectacle; for the old, a memory renewed. The festival was not merely entertainment; it was the community's way of giving thanks and reaffirming its identity."*

(a) State two purposes of the harvest festival. *(4 marks)*

(b) Explain the difference between how the young and the old view the festival. *(4 marks)*

(c) What does the phrase "a memory renewed" suggest? *(3 marks)*

---

**Q17.** Summarise the following passage in not more than 70 words.

*"Reading is a habit that is dying among young people, replaced by short videos and instant messages. Yet reading offers what these distractions cannot: the ability to follow a complex argument, to enter another person's mind, and to build the vocabulary that examinations reward. Teachers report that students who read widely write better essays and score higher in comprehension. Parents can help by setting aside time for reading at home and by letting children choose books that interest them, rather than forcing classics upon them."*

Your summary must be in continuous prose. *(10 marks)*

---

**Q18.** Read the passage and answer the questions that follow.

*"The bridge collapsed without warning, cutting off the only road to the hospital. For three days, the sick were carried across the river in canoes, and the dead were buried on the wrong side of the water. When the government finally announced plans to rebuild, the villagers did not celebrate; they had heard such promises before."*

(a) What were the consequences of the bridge's collapse? *(4 marks)*

(b) Why did the villagers not celebrate the government's announcement? *(4 marks)*

(c) What does the passage reveal about the relationship between the villagers and the government? *(4 marks)*

---

**Q19.** Read the passage and answer the questions that follow.

*"Success, the speaker told the graduates, is not a destination but a journey. It is measured not by the certificates on your wall but by the obstacles you overcome and the people you help along the way. The audience applauded, though some wondered privately whether the speaker, who had inherited his father's business, truly understood the obstacles they faced."*

(a) State the speaker's definition of success. *(3 marks)*

(b) Explain the irony in the final sentence. *(4 marks)*

(c) Do you agree with the speaker's view? Give a reason. *(3 marks)*

---

**Q20.** Read the passage and answer the questions that follow.

*"The baobab tree stood at the centre of the village, older than anyone could remember. Its trunk was a storehouse of water, its bark a source of medicine, its leaves a vegetable for the evening pot. When developers proposed cutting it down to widen the road, the village united in protest. They had lost many things to progress; they would not lose the baobab."*

(a) List three uses of the baobab tree mentioned in the passage. *(3 marks)*

(b) Why did the village protest against the developers? *(4 marks)*

(c) What does the final sentence reveal about the villagers' attitude towards progress? *(4 marks)*
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds English Language topic-wise hard structural paper set 4 (Comprehension and summary)'
),
(
  'edcd5b14-6c41-51ce-b3b0-f2d28cc6b6b6',
  'eng-grammar-vocabulary',
  'English Language',
  'CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P2 SET 5',
  'english',
  'ordinary',
  array['form_5']::text[],
  array['general', 'science', 'arts', 'commercial', 'technical']::text[],
  'published',
  $md$
# CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P2 SET 5

## Structural Question Bank — Grammar and vocabulary

**Level:** Ordinary Level
**Class:** FORM 5
**Series:** general, science, arts, commercial, technical
**Subject:** English Language

**Instructions:**

- Answer all questions in a clear and organized manner.
- Show all working where calculations are required.
- Use correct subject terminology and Cameroon GCE presentation standards.
- Diagrams, tables, maps, labelled sketches, and examples should be included where useful.

---

## SECTION 1: GRAMMAR AND VOCABULARY

**Q1.** Rewrite the following sentences, correcting the errors:

(a) "Neither of the boys were present at the meeting." *(2 marks)*

(b) "The committee have decided to postpone the event." *(2 marks)*

(c) "Each of the students have submitted their assignment." *(2 marks)*

(d) "The number of accidents are increasing every year." *(2 marks)*

---

**Q2.** Change the following sentences from direct to indirect speech:

(a) "I will visit you tomorrow," she said. *(3 marks)*

(b) "Have you finished the report?" the manager asked. *(3 marks)*

(c) "Do not touch the exhibits," the guard warned. *(3 marks)*

---

**Q3.** Fill in each blank with the correct form of the verb in brackets:

(a) By the time we arrived, the ceremony ____ (already begin). *(2 marks)*

(b) She ____ (live) in Douala for ten years before she moved to Yaoundé. *(2 marks)*

(c) If I ____ (know) the answer, I would have told you. *(2 marks)*

(d) The children ____ (play) in the yard when it started to rain. *(2 marks)*

---

**Q4.** Combine each pair of sentences using the conjunction in brackets:

(a) He was tired. He continued working. (although) *(3 marks)*

(b) The rain stopped. We went out. (as soon as) *(3 marks)*

(c) She studied hard. She failed the examination. (even though) *(3 marks)*

---

**Q5.** Choose the word that is closest in meaning to the word in bold:

(a) The meeting was **adjourned** until the following week. *(2 marks)*

(b) His **arrogant** behaviour offended his colleagues. *(2 marks)*

(c) The evidence was **inconclusive**, so the case was dismissed. *(2 marks)*

(d) She gave a **lucid** explanation of the difficult concept. *(2 marks)*

---

**Q6.** Rewrite the following sentences in the passive voice:

(a) The government built the new bridge last year. *(2 marks)*

(b) Someone has stolen my bicycle. *(2 marks)*

(c) They will announce the results on Friday. *(2 marks)*

(d) The chef is preparing the meal. *(2 marks)*

---

**Q7.** Identify the grammatical function of the underlined words in the following sentences:

(a) The **runner** won the race. *(2 marks)*

(b) She gave **him** a gift. *(2 marks)*

(c) The book on the table is **mine**. *(2 marks)*

(d) **Running** is good exercise. *(2 marks)*

---

**Q8.** Complete each sentence with the correct preposition:

(a) She is good ____ mathematics. *(1 mark)*

(b) He was accused ____ theft. *(1 mark)*

(c) The committee consists ____ ten members. *(1 mark)*

(d) We arrived ____ the station just in time. *(1 mark)*

(e) She is interested ____ learning French. *(1 mark)*

(f) The cat jumped ____ the table. *(1 mark)*

---

**Q9.** Rewrite the following sentences, using the correct form of the word in brackets:

(a) The ____ (decide) was made unanimously. *(2 marks)*

(b) Her ____ (perform) in the examination was outstanding. *(2 marks)*

(c) The ____ (manage) of the company resigned. *(2 marks)*

(d) We were impressed by his ____ (honest). *(2 marks)*

---

**Q10.** Punctuate the following passage correctly:

*"the minister said the government will build a new hospital in bamenda next year the project will create hundreds of jobs and improve healthcare in the region"* *(8 marks)*

---

**Q11.** Choose the correct word to complete each sentence:

(a) The principal gave the students ____ (advice / advise) on how to prepare for the examination. *(2 marks)*

(b) The new policy will ____ (affect / effect) all workers. *(2 marks)*

(c) Please ____ (bring / take) this letter to the post office. *(2 marks)*

(d) The company's ____ (principal / principle) concern is customer satisfaction. *(2 marks)*

---

**Q12.** Rewrite the following sentences, beginning with the word given:

(a) "It is unlikely that he will pass the examination." → "He is unlikely ____." *(3 marks)*

(b) "She is too young to travel alone." → "She is not ____." *(3 marks)*

(c) "The problem was so difficult that nobody could solve it." → "It was such ____." *(3 marks)*

---

**Q13.** Identify and correct the error in each of the following sentences:

(a) "The two girls are very different from each other." *(2 marks)*

(b) "He is one of the students who has won the prize." *(2 marks)*

(c) "I look forward to hear from you." *(2 marks)*

(d) "The news are good." *(2 marks)*

---

**Q14.** Complete each sentence with the correct form of the word in brackets:

(a) The ____ (long) of the river is over 1,000 kilometres. *(2 marks)*

(b) She spoke with great ____ (confident). *(2 marks)*

(c) The ____ (fail) of the plan surprised everyone. *(2 marks)*

(d) His ____ (refuse) to cooperate delayed the project. *(2 marks)*

---

**Q15.** Rewrite the following sentences, replacing the underlined words with a suitable phrasal verb:

(a) He **postponed** the meeting until Monday. *(2 marks)*

(b) She **discovered** the truth by accident. *(2 marks)*

(c) The plane **departed** at noon. *(2 marks)*

(d) They **continued** working despite the noise. *(2 marks)*

---

**Q16.** Change the following sentences from active to passive, or vice versa:

(a) The letter was written by the secretary. *(2 marks)*

(b) The children are being taught by a new teacher. *(2 marks)*

(c) The manager will interview the candidates tomorrow. *(2 marks)*

(d) The bridge was being repaired when we crossed it. *(2 marks)*

---

**Q17.** Complete each sentence with the correct form of the word in brackets:

(a) The ____ (arrive) of the delegation was delayed. *(2 marks)*

(b) She has a strong ____ (believe) in hard work. *(2 marks)*

(c) The ____ (compare) between the two products was interesting. *(2 marks)*

(d) His ____ (behave) at the meeting was unacceptable. *(2 marks)*

---

**Q18.** Rewrite the following sentences, using the correct tense:

(a) "I have seen that film yesterday." *(2 marks)*

(b) "She has been working here since five years." *(2 marks)*

(c) "When I arrived, he already left." *(2 marks)*

(d) "I will call you when I will arrive." *(2 marks)*

---

**Q19.** Choose the correct word to complete each sentence:

(a) The ____ (weather / whether) was perfect for the picnic. *(2 marks)*

(b) ____ (Their / There / They're) going to the market. *(2 marks)*

(c) The dog wagged ____ (its / it's) tail. *(2 marks)*

(d) ____ (Who's / Whose) book is this? *(2 marks)*

---

**Q20.** Rewrite the following sentences, correcting the errors:

(a) "The teacher, along with her students, are going on the trip." *(2 marks)*

(b) "He is the tallest of the two brothers." *(2 marks)*

(c) "I have less money than him." *(2 marks)*

(d) "She is more taller than her sister." *(2 marks)*
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds English Language topic-wise hard structural paper set 5 (Grammar and vocabulary)'
),
(
  'bc39cf8f-66a6-58ec-8e22-15a3c1ae1351',
  'eng-essay-writing',
  'English Language',
  'CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P2 SET 6',
  'english',
  'ordinary',
  array['form_5']::text[],
  array['general', 'science', 'arts', 'commercial', 'technical']::text[],
  'published',
  $md$
# CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P2 SET 6

## Structural Question Bank — Composition and essay writing

**Level:** Ordinary Level
**Class:** FORM 5
**Series:** general, science, arts, commercial, technical
**Subject:** English Language

**Instructions:**

- Answer all questions in a clear and organized manner.
- Show all working where calculations are required.
- Use correct subject terminology and Cameroon GCE presentation standards.
- Diagrams, tables, maps, labelled sketches, and examples should be included where useful.

---

## SECTION 1: COMPOSITION AND ESSAY WRITING

**Q1.** Write an essay of about 450 words on the following topic:

"Describe a journey you will never forget. Explain why it remains memorable."

Your essay should have a clear introduction, body, and conclusion. *(20 marks)*

---

**Q2.** Write an argumentative essay of about 450 words on the topic:

"Mobile phones should be banned in secondary schools."

Present a clear argument, support it with reasons and examples, and address at least one counter-argument. *(20 marks)*

---

**Q3.** Write a narrative essay of about 450 words beginning with the sentence:

*"It was the last day of the school year, and nothing had gone as planned."*

Use vivid description and a clear sequence of events. *(20 marks)*

---

**Q4.** Write an expository essay of about 450 words on the topic:

"Explain the importance of agriculture to the economy of Cameroon."

Organise your ideas logically and support them with specific examples. *(20 marks)*

---

**Q5.** Write a descriptive essay of about 450 words on the topic:

"Describe your favourite place and explain why it is special to you."

Use sensory details (sight, sound, smell, touch, taste) to bring the place to life. *(20 marks)*

---

**Q6.** Write an argumentative essay of about 450 words on the topic:

"Examinations are not the best way to measure a student's ability."

Give reasons for your position and consider the opposing view. *(20 marks)*

---

**Q7.** Write a narrative essay of about 450 words ending with the sentence:

*"That was the day I learned that honesty is always the best policy."*

Build your story towards this conclusion. *(20 marks)*

---

**Q8.** Write a formal letter to the mayor of your town, complaining about the poor state of the roads in your area. Your letter should be about 350 words and should include:

(a) Your address and the date. *(2 marks)*

(b) A clear statement of the problem. *(6 marks)*

(c) The effects of the problem on the community. *(6 marks)*

(d) A request for action. *(6 marks)*

---

**Q9.** Write an expository essay of about 450 words on the topic:

"Discuss the causes and effects of drug abuse among young people."

Structure your essay with clear paragraphs. *(20 marks)*

---

**Q10.** Write a narrative essay of about 450 words on the topic:

"Write a story that illustrates the saying: 'A friend in need is a friend indeed.'"

Your story should have a clear plot, characters, and a lesson. *(20 marks)*

---

**Q11.** Write an argumentative essay of about 450 words on the topic:

"Social media does more harm than good to young people."

Support your argument with evidence and address the opposing view. *(20 marks)*

---

**Q12.** Write a descriptive essay of about 450 words on the topic:

"Describe the scene at a busy market in your town."

Use vivid language to convey the sights, sounds, and atmosphere. *(20 marks)*

---

**Q13.** Write a formal letter of application for the post of a sales assistant in a supermarket. Your letter should be about 350 words and should include:

(a) Your address and the date. *(2 marks)*

(b) The post you are applying for and where you saw it advertised. *(4 marks)*

(c) Your qualifications and relevant experience. *(8 marks)*

(d) A request for an interview. *(6 marks)*

---

**Q14.** Write an expository essay of about 450 words on the topic:

"Explain the causes of road accidents in Cameroon and suggest ways to reduce them."

Organise your answer into causes and solutions. *(20 marks)*

---

**Q15.** Write a narrative essay of about 450 words on the topic:

"Write a story about a time when you had to make a difficult decision."

Describe the situation, the options you faced, and the outcome. *(20 marks)*

---

**Q16.** Write an argumentative essay of about 450 words on the topic:

"University education should be free for all students in Cameroon."

Present a clear position with supporting arguments and counter-arguments. *(20 marks)*

---

**Q17.** Write a descriptive essay of about 450 words on the topic:

"Describe a traditional ceremony you have witnessed."

Include details of the setting, the participants, and the significance of the ceremony. *(20 marks)*

---

**Q18.** Write a formal letter to the editor of a national newspaper, expressing your views on the topic:

"The importance of preserving Cameroon's cultural heritage."

Your letter should be about 350 words and should include a clear introduction, body, and conclusion. *(20 marks)*

---

**Q19.** Write an expository essay of about 450 words on the topic:

"Discuss the benefits of learning a second language."

Support your points with specific examples. *(20 marks)*

---

**Q20.** Write a narrative essay of about 450 words on the topic:

"Write a story that ends with the sentence: 'Sometimes the smallest act of kindness means the most.'"

Build your story towards this ending. *(20 marks)*
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds English Language topic-wise hard structural paper set 6 (Composition and essay writing)'
),
(
  '232ad1e6-ee66-5e5b-a7aa-2daaa018ac46',
  'eng-comprehension-summary',
  'English Language',
  'CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P2 SET 7',
  'english',
  'ordinary',
  array['form_5']::text[],
  array['general', 'science', 'arts', 'commercial', 'technical']::text[],
  'published',
  $md$
# CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P2 SET 7

## Structural Question Bank — Comprehension and summary

**Level:** Ordinary Level
**Class:** FORM 5
**Series:** general, science, arts, commercial, technical
**Subject:** English Language

**Instructions:**

- Answer all questions in a clear and organized manner.
- Show all working where calculations are required.
- Use correct subject terminology and Cameroon GCE presentation standards.
- Diagrams, tables, maps, labelled sketches, and examples should be included where useful.

---

## SECTION 1: COMPREHENSION AND SUMMARY

**Q1.** Read the passage below and answer the questions that follow.

*"The village market was more than a place of trade; it was the beating heart of the community. Here, farmers exchanged news with traders, and children learned the value of honest dealing. Yet in recent years, the market has been shrinking as young people migrate to the cities, leaving behind ageing vendors and empty stalls."*

(a) In one sentence, state the main idea of the passage. *(3 marks)*

(b) Give two reasons the writer gives for the market's decline. *(4 marks)*

(c) Explain what the writer means by "the beating heart of the community". *(4 marks)*

---

**Q2.** Summarise the following passage in not more than 60 words.

*"Rainwater harvesting is an ancient practice that is regaining importance in Cameroon. By collecting runoff from rooftops into storage tanks, households can reduce their dependence on erratic municipal supplies. The water is ideal for gardening, washing, and, after proper treatment, even drinking. Critics argue that the initial cost of tanks and guttering is prohibitive, but supporters point out that the investment pays for itself within a few years through lower water bills and greater self-reliance."*

Your summary must be in continuous prose and must not include direct quotations. *(10 marks)*

---

**Q3.** Read the passage and answer the questions that follow.

*"The examination results were posted at dawn. For Amina, the moment was both terrifying and liberating. She had spent three sleepless nights rehearsing the worst-case scenario, yet when her name appeared on the list of successful candidates, she felt a surge of relief so powerful it left her breathless."*

(a) Identify the dominant emotion in the passage and quote one phrase that supports your answer. *(4 marks)*

(b) What does the phrase "rehearsing the worst-case scenario" reveal about Amina's character? *(4 marks)*

(c) Suggest a suitable title for the passage. *(2 marks)*

---

**Q4.** Read the passage and answer the questions that follow.

*"Cameroon's forests are among the most biodiverse on the continent, sheltering elephants, gorillas, and thousands of plant species. However, illegal logging and slash-and-burn farming are destroying these habitats at an alarming rate. Conservationists argue that protecting the forests is not merely an environmental concern but an economic one, since ecotourism and sustainable harvesting can generate lasting income for local communities."*

(a) State two threats to Cameroon's forests mentioned in the passage. *(4 marks)*

(b) Explain why the writer describes forest protection as "an economic one". *(4 marks)*

(c) Give the meaning of "biodiverse" as used in the passage. *(2 marks)*

---

**Q5.** Summarise the following passage in not more than 70 words.

*"Mobile money has transformed financial life in Cameroon. Before its arrival, many rural families had no access to banks and relied on risky methods of storing and transferring cash. Today, a farmer can sell his cocoa, receive payment on his phone, and pay his children's school fees without travelling to a town. Mobile money has also created jobs, as agents earn commissions on every transaction. Nevertheless, concerns remain about fraud, network failures, and the exclusion of the elderly who struggle with the technology."*

Your summary must be in continuous prose. *(10 marks)*

---

**Q6.** Read the passage and answer the questions that follow.

*"The old woman refused to be rushed. Each morning she swept her compound with slow, deliberate strokes, as if the dust were an enemy she had known for years. Her neighbours, who hurried past with phones pressed to their ears, did not understand that for her, sweeping was not a chore but a meditation."*

(a) What does the writer suggest about the difference between the old woman and her neighbours? *(4 marks)*

(b) Explain the meaning of "a meditation" in the context of the passage. *(4 marks)*

(c) Identify one figure of speech used in the passage and explain its effect. *(4 marks)*

---

**Q7.** Read the passage and answer the questions that follow.

*"The river had always been generous, giving the village fish, water, and fertile soil. But generosity, the elders warned, must never be taken for granted. When the rains failed and the river shrank to a muddy trickle, the village learned that nature's gifts come with conditions."*

(a) State the lesson the village learned. *(3 marks)*

(b) Explain how the writer uses personification in the passage. *(4 marks)*

(c) What is the writer's attitude towards the river? Support your answer with evidence. *(4 marks)*

---

**Q8.** Summarise the following passage in not more than 60 words.

*"School feeding programmes in Cameroon serve a dual purpose. For children, a guaranteed midday meal improves concentration, attendance, and overall health. For farmers, the programmes provide a reliable market for their produce, since schools purchase staples such as maize, beans, and groundnuts from local cooperatives. Critics note that the programmes are expensive to run and vulnerable to corruption, but supporters argue that the long-term benefits to education and agriculture outweigh the costs."*

Your summary must be in continuous prose. *(10 marks)*

---

**Q9.** Read the passage and answer the questions that follow.

*"He had rehearsed the speech a hundred times, yet when he stood before the crowd, the words evaporated. His palms were slick, his throat dry. Then he remembered his father's advice: 'The audience wants you to succeed.' He took a breath, and the first sentence came out steady."*

(a) Describe the speaker's state of mind at the start of the passage. *(3 marks)*

(b) What effect does the father's advice have on the speaker? *(4 marks)*

(c) Explain the meaning of "the words evaporated". *(3 marks)*

---

**Q10.** Read the passage and answer the questions that follow.

*"Plastic waste is choking Cameroon's cities. Discarded bottles clog drainage channels, causing floods during the rainy season, while burning the waste releases toxic fumes. Some entrepreneurs have begun collecting plastics and recycling them into paving blocks, creating jobs and cleaning the streets. The challenge, they say, is not a lack of solutions but a lack of will."*

(a) State two problems caused by plastic waste. *(4 marks)*

(b) How have some entrepreneurs responded to the problem? *(3 marks)*

(c) Explain the final sentence: "The challenge... is not a lack of solutions but a lack of will." *(4 marks)*

---

**Q11.** Summarise the following passage in not more than 65 words.

*"Community health workers are the backbone of rural healthcare in Cameroon. Trained to diagnose common illnesses, administer vaccines, and advise on hygiene, they bring medical care to villages that would otherwise travel hours to reach a clinic. Their work has reduced infant mortality and improved maternal health in many regions. Yet these workers are often unpaid volunteers, and many leave the profession once they find better-paying work. Health experts argue that investing in community health workers is one of the most cost-effective ways to strengthen the health system."*

Your summary must be in continuous prose. *(10 marks)*

---

**Q12.** Read the passage and answer the questions that follow.

*"The two brothers inherited the same plot of land. One planted cocoa and prospered; the other planted nothing and waited for the land to feed him. Years later, the first brother built a house, while the second still waited, blaming the soil for his poverty."*

(a) What is the moral of the passage? *(4 marks)*

(b) Contrast the attitudes of the two brothers. *(4 marks)*

(c) Explain the irony in the final sentence. *(4 marks)*

---

**Q13.** Read the passage and answer the questions that follow.

*"Tourism in Cameroon is a sleeping giant. The country boasts beaches, mountains, wildlife parks, and a rich cultural heritage, yet it attracts a fraction of the visitors that smaller neighbours receive. Poor infrastructure, limited marketing, and safety concerns are often cited as reasons. Those who have visited, however, speak of a country that rewards the adventurous traveller."*

(a) What does the writer mean by calling tourism "a sleeping giant"? *(4 marks)*

(b) Give two reasons why Cameroon attracts few tourists. *(4 marks)*

(c) What is the writer's overall attitude towards Cameroon's tourism potential? *(3 marks)*

---

**Q14.** Summarise the following passage in not more than 60 words.

*"The traditional African family is often described as an extended family, where uncles, aunts, and grandparents share in raising children. This system provides a safety net: when parents fall ill or travel, relatives step in. It also transmits values, history, and skills across generations. However, urbanisation and economic pressures are weakening these ties, as families become smaller and more mobile. Sociologists warn that the loss of the extended family could leave many children without the support they once enjoyed."*

Your summary must be in continuous prose. *(10 marks)*

---

**Q15.** Read the passage and answer the questions that follow.

*"The teacher wrote a single word on the board: 'Why?' For a moment the class was silent. Then hands shot up. The question, she explained, was more important than any answer, because it was the beginning of every discovery. From that day, her students stopped memorising and started questioning."*

(a) What change does the teacher bring about in her students? *(4 marks)*

(b) Explain the significance of the word "Why?" in the passage. *(4 marks)*

(c) What does the passage suggest about the difference between memorising and questioning? *(4 marks)*

---

**Q16.** Read the passage and answer the questions that follow.

*"The harvest festival drew people from every village in the district. Drummers led the procession, dancers in bright cloth followed, and elders presided over the ceremony with quiet dignity. For the young, it was a spectacle; for the old, a memory renewed. The festival was not merely entertainment; it was the community's way of giving thanks and reaffirming its identity."*

(a) State two purposes of the harvest festival. *(4 marks)*

(b) Explain the difference between how the young and the old view the festival. *(4 marks)*

(c) What does the phrase "a memory renewed" suggest? *(3 marks)*

---

**Q17.** Summarise the following passage in not more than 70 words.

*"Reading is a habit that is dying among young people, replaced by short videos and instant messages. Yet reading offers what these distractions cannot: the ability to follow a complex argument, to enter another person's mind, and to build the vocabulary that examinations reward. Teachers report that students who read widely write better essays and score higher in comprehension. Parents can help by setting aside time for reading at home and by letting children choose books that interest them, rather than forcing classics upon them."*

Your summary must be in continuous prose. *(10 marks)*

---

**Q18.** Read the passage and answer the questions that follow.

*"The bridge collapsed without warning, cutting off the only road to the hospital. For three days, the sick were carried across the river in canoes, and the dead were buried on the wrong side of the water. When the government finally announced plans to rebuild, the villagers did not celebrate; they had heard such promises before."*

(a) What were the consequences of the bridge's collapse? *(4 marks)*

(b) Why did the villagers not celebrate the government's announcement? *(4 marks)*

(c) What does the passage reveal about the relationship between the villagers and the government? *(4 marks)*

---

**Q19.** Read the passage and answer the questions that follow.

*"Success, the speaker told the graduates, is not a destination but a journey. It is measured not by the certificates on your wall but by the obstacles you overcome and the people you help along the way. The audience applauded, though some wondered privately whether the speaker, who had inherited his father's business, truly understood the obstacles they faced."*

(a) State the speaker's definition of success. *(3 marks)*

(b) Explain the irony in the final sentence. *(4 marks)*

(c) Do you agree with the speaker's view? Give a reason. *(3 marks)*

---

**Q20.** Read the passage and answer the questions that follow.

*"The baobab tree stood at the centre of the village, older than anyone could remember. Its trunk was a storehouse of water, its bark a source of medicine, its leaves a vegetable for the evening pot. When developers proposed cutting it down to widen the road, the village united in protest. They had lost many things to progress; they would not lose the baobab."*

(a) List three uses of the baobab tree mentioned in the passage. *(3 marks)*

(b) Why did the village protest against the developers? *(4 marks)*

(c) What does the final sentence reveal about the villagers' attitude towards progress? *(4 marks)*
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds English Language topic-wise hard structural paper set 7 (Comprehension and summary)'
),
(
  '27588af3-5a43-5b91-9087-c3627099f669',
  'eng-grammar-vocabulary',
  'English Language',
  'CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P2 SET 8',
  'english',
  'ordinary',
  array['form_5']::text[],
  array['general', 'science', 'arts', 'commercial', 'technical']::text[],
  'published',
  $md$
# CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P2 SET 8

## Structural Question Bank — Grammar and vocabulary

**Level:** Ordinary Level
**Class:** FORM 5
**Series:** general, science, arts, commercial, technical
**Subject:** English Language

**Instructions:**

- Answer all questions in a clear and organized manner.
- Show all working where calculations are required.
- Use correct subject terminology and Cameroon GCE presentation standards.
- Diagrams, tables, maps, labelled sketches, and examples should be included where useful.

---

## SECTION 1: GRAMMAR AND VOCABULARY

**Q1.** Rewrite the following sentences, correcting the errors:

(a) "Neither of the boys were present at the meeting." *(2 marks)*

(b) "The committee have decided to postpone the event." *(2 marks)*

(c) "Each of the students have submitted their assignment." *(2 marks)*

(d) "The number of accidents are increasing every year." *(2 marks)*

---

**Q2.** Change the following sentences from direct to indirect speech:

(a) "I will visit you tomorrow," she said. *(3 marks)*

(b) "Have you finished the report?" the manager asked. *(3 marks)*

(c) "Do not touch the exhibits," the guard warned. *(3 marks)*

---

**Q3.** Fill in each blank with the correct form of the verb in brackets:

(a) By the time we arrived, the ceremony ____ (already begin). *(2 marks)*

(b) She ____ (live) in Douala for ten years before she moved to Yaoundé. *(2 marks)*

(c) If I ____ (know) the answer, I would have told you. *(2 marks)*

(d) The children ____ (play) in the yard when it started to rain. *(2 marks)*

---

**Q4.** Combine each pair of sentences using the conjunction in brackets:

(a) He was tired. He continued working. (although) *(3 marks)*

(b) The rain stopped. We went out. (as soon as) *(3 marks)*

(c) She studied hard. She failed the examination. (even though) *(3 marks)*

---

**Q5.** Choose the word that is closest in meaning to the word in bold:

(a) The meeting was **adjourned** until the following week. *(2 marks)*

(b) His **arrogant** behaviour offended his colleagues. *(2 marks)*

(c) The evidence was **inconclusive**, so the case was dismissed. *(2 marks)*

(d) She gave a **lucid** explanation of the difficult concept. *(2 marks)*

---

**Q6.** Rewrite the following sentences in the passive voice:

(a) The government built the new bridge last year. *(2 marks)*

(b) Someone has stolen my bicycle. *(2 marks)*

(c) They will announce the results on Friday. *(2 marks)*

(d) The chef is preparing the meal. *(2 marks)*

---

**Q7.** Identify the grammatical function of the underlined words in the following sentences:

(a) The **runner** won the race. *(2 marks)*

(b) She gave **him** a gift. *(2 marks)*

(c) The book on the table is **mine**. *(2 marks)*

(d) **Running** is good exercise. *(2 marks)*

---

**Q8.** Complete each sentence with the correct preposition:

(a) She is good ____ mathematics. *(1 mark)*

(b) He was accused ____ theft. *(1 mark)*

(c) The committee consists ____ ten members. *(1 mark)*

(d) We arrived ____ the station just in time. *(1 mark)*

(e) She is interested ____ learning French. *(1 mark)*

(f) The cat jumped ____ the table. *(1 mark)*

---

**Q9.** Rewrite the following sentences, using the correct form of the word in brackets:

(a) The ____ (decide) was made unanimously. *(2 marks)*

(b) Her ____ (perform) in the examination was outstanding. *(2 marks)*

(c) The ____ (manage) of the company resigned. *(2 marks)*

(d) We were impressed by his ____ (honest). *(2 marks)*

---

**Q10.** Punctuate the following passage correctly:

*"the minister said the government will build a new hospital in bamenda next year the project will create hundreds of jobs and improve healthcare in the region"* *(8 marks)*

---

**Q11.** Choose the correct word to complete each sentence:

(a) The principal gave the students ____ (advice / advise) on how to prepare for the examination. *(2 marks)*

(b) The new policy will ____ (affect / effect) all workers. *(2 marks)*

(c) Please ____ (bring / take) this letter to the post office. *(2 marks)*

(d) The company's ____ (principal / principle) concern is customer satisfaction. *(2 marks)*

---

**Q12.** Rewrite the following sentences, beginning with the word given:

(a) "It is unlikely that he will pass the examination." → "He is unlikely ____." *(3 marks)*

(b) "She is too young to travel alone." → "She is not ____." *(3 marks)*

(c) "The problem was so difficult that nobody could solve it." → "It was such ____." *(3 marks)*

---

**Q13.** Identify and correct the error in each of the following sentences:

(a) "The two girls are very different from each other." *(2 marks)*

(b) "He is one of the students who has won the prize." *(2 marks)*

(c) "I look forward to hear from you." *(2 marks)*

(d) "The news are good." *(2 marks)*

---

**Q14.** Complete each sentence with the correct form of the word in brackets:

(a) The ____ (long) of the river is over 1,000 kilometres. *(2 marks)*

(b) She spoke with great ____ (confident). *(2 marks)*

(c) The ____ (fail) of the plan surprised everyone. *(2 marks)*

(d) His ____ (refuse) to cooperate delayed the project. *(2 marks)*

---

**Q15.** Rewrite the following sentences, replacing the underlined words with a suitable phrasal verb:

(a) He **postponed** the meeting until Monday. *(2 marks)*

(b) She **discovered** the truth by accident. *(2 marks)*

(c) The plane **departed** at noon. *(2 marks)*

(d) They **continued** working despite the noise. *(2 marks)*

---

**Q16.** Change the following sentences from active to passive, or vice versa:

(a) The letter was written by the secretary. *(2 marks)*

(b) The children are being taught by a new teacher. *(2 marks)*

(c) The manager will interview the candidates tomorrow. *(2 marks)*

(d) The bridge was being repaired when we crossed it. *(2 marks)*

---

**Q17.** Complete each sentence with the correct form of the word in brackets:

(a) The ____ (arrive) of the delegation was delayed. *(2 marks)*

(b) She has a strong ____ (believe) in hard work. *(2 marks)*

(c) The ____ (compare) between the two products was interesting. *(2 marks)*

(d) His ____ (behave) at the meeting was unacceptable. *(2 marks)*

---

**Q18.** Rewrite the following sentences, using the correct tense:

(a) "I have seen that film yesterday." *(2 marks)*

(b) "She has been working here since five years." *(2 marks)*

(c) "When I arrived, he already left." *(2 marks)*

(d) "I will call you when I will arrive." *(2 marks)*

---

**Q19.** Choose the correct word to complete each sentence:

(a) The ____ (weather / whether) was perfect for the picnic. *(2 marks)*

(b) ____ (Their / There / They're) going to the market. *(2 marks)*

(c) The dog wagged ____ (its / it's) tail. *(2 marks)*

(d) ____ (Who's / Whose) book is this? *(2 marks)*

---

**Q20.** Rewrite the following sentences, correcting the errors:

(a) "The teacher, along with her students, are going on the trip." *(2 marks)*

(b) "He is the tallest of the two brothers." *(2 marks)*

(c) "I have less money than him." *(2 marks)*

(d) "She is more taller than her sister." *(2 marks)*
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds English Language topic-wise hard structural paper set 8 (Grammar and vocabulary)'
),
(
  '2e711638-10ce-5920-bd3b-81cc03373553',
  'eng-comprehension-summary',
  'English Language',
  'CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P1 SET 1',
  'english',
  'ordinary',
  array['form_5']::text[],
  array['general', 'science', 'arts', 'commercial', 'technical']::text[],
  'published',
  $md$
# CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P1 SET 1

## Multiple Choice Question Bank

**Level:** Ordinary Level
**Class:** FORM 5
**Series:** general, science, arts, commercial, technical
**Subject:** English Language

**Instructions:**

- Choose the correct option A, B, C or D for each question.
- Record your answers clearly on the answer sheet provided.
- Each question carries equal marks. No marks is deducted for wrong answers.
- Use the answer key at the end of the paper to check your responses.

---

## QUESTIONS

**Q1.** Read: 'The market was the beating heart of the community.' The phrase 'beating heart' suggests the market was:

A. the centre of community life  
B. a noisy place  
C. a place of conflict  
D. a modern building  

---

**Q2.** In summary writing, the first step is to:

A. read the passage carefully to understand the main ideas  
B. copy the first sentence of each paragraph  
C. write your own opinions about the topic  
D. count the words in the passage  

---

**Q3.** A summary should be written:

A. in your own words  
B. in note form only  
C. using long quotations from the passage  
D. as a list of examples  

---

**Q4.** The main idea of a passage is best described as:

A. the central point the writer is making  
B. the most difficult word in the passage  
C. the writer's personal opinion only  
D. the first sentence of the passage  

---

**Q5.** Read: 'The words evaporated.' This means the speaker:

A. forgot what he wanted to say  
B. was interrupted by the crowd  
C. spoke very quietly  
D. wrote his speech down  

---

**Q6.** When asked to 'state the main idea in one sentence', you should:

A. summarise the whole passage briefly  
B. list all the details  
C. repeat the title  
D. quote the longest sentence  

---

**Q7.** An inference is:

A. a fact stated directly in the text  
B. a conclusion drawn from evidence in the text  
C. a quotation from the text  
D. a question about the text  

---

**Q8.** Read: 'The river had always been generous.' The word 'generous' here suggests the river:

A. was very wide  
B. provided many benefits  
C. was polluted  
D. flowed very fast  

---

**Q9.** In a summary, you should NOT include:

A. the main points  
B. the key facts  
C. your personal opinions  
D. the essential ideas  

---

**Q10.** The word 'biodiverse' in 'Cameroon's forests are among the most biodiverse' means:

A. very large in size  
B. completely untouched  
C. difficult to reach  
D. containing many different species  

---

**Q11.** Read: 'The audience wants you to succeed.' This advice helped the speaker to:

A. leave the stage  
B. change his topic  
C. feel calmer and begin speaking  
D. memorise his speech  

---

**Q12.** When summarising, the word limit means you must:

A. write exactly the same number of words as the passage  
B. ignore the word limit  
C. write as many words as possible  
D. keep your summary within the stated number of words  

---

**Q13.** Read: 'Tourism in Cameroon is a sleeping giant.' This means tourism:

A. is declining rapidly  
B. has great potential that is not yet realised  
C. is completely absent  
D. is too expensive for visitors  

---

**Q14.** The purpose of a comprehension passage is usually to:

A. teach grammar rules  
B. test understanding of the text  
C. list vocabulary words  
D. provide entertainment only  

---

**Q15.** Read: 'The villagers did not celebrate; they had heard such promises before.' This suggests the villagers:

A. had never heard promises before  
B. were happy with the announcement  
C. did not trust the government's promises  
D. were celebrating quietly  

---

**Q16.** A good summary should be:

A. the same length as the original passage  
B. longer than the original passage  
C. a copy of the original passage  
D. shorter than the original passage  

---

**Q17.** Read: 'For her, sweeping was not a chore but a meditation.' This means the old woman:

A. swept very quickly  
B. hired someone to sweep  
C. found peace in sweeping  
D. disliked sweeping  

---

**Q18.** When a question asks you to 'explain in your own words', you should:

A. write a longer version of the passage  
B. give your own opinion  
C. quote the passage directly  
D. rephrase the idea without copying  

---

**Q19.** Read: 'Success is not a destination but a journey.' The writer means success is:

A. measured by certificates  
B. a continuous process  
C. a final goal  
D. impossible to achieve  

---

**Q20.** The best title for a passage about plastic waste clogging drainage channels would be:

A. A Day at the Market  
B. The Problem of Plastic Waste in Our Cities  
C. The History of Plastic  
D. How to Build Drainage Channels  

---

**Q21.** Choose the correct sentence:

A. Neither of the boys have been present.  
B. Neither of the boys were present.  
C. Neither of the boys was present.  
D. Neither of the boys are present.  

---

**Q22.** Choose the correct sentence:

A. The committee were deciding to postpone the event.  
B. The committee have decided to postpone the event.  
C. The committee are deciding to postpone the event.  
D. The committee has decided to postpone the event.  

---

**Q23.** Choose the correct sentence:

A. Each of the students were submitting the assignment.  
B. Each of the students are submitting the assignment.  
C. Each of the students has submitted the assignment.  
D. Each of the students have submitted the assignment.  

---

**Q24.** Choose the correct sentence:

A. The number of accidents have been increasing.  
B. The number of accidents were increasing.  
C. The number of accidents are increasing.  
D. The number of accidents is increasing.  

---

**Q25.** Choose the correct sentence:

A. She is good at mathematics.  
B. She is good in mathematics.  
C. She is good on mathematics.  
D. She is good for mathematics.  

---

**Q26.** Choose the correct sentence:

A. He was accused of theft.  
B. He was accused for theft.  
C. He was accused on theft.  
D. He was accused with theft.  

---

**Q27.** Choose the correct sentence:

A. The committee consists of ten members.  
B. The committee consists with ten members.  
C. The committee consists in ten members.  
D. The committee consists on ten members.  

---

**Q28.** Choose the correct sentence:

A. She is interested in learning French.  
B. She is interested for learning French.  
C. She is interested at learning French.  
D. She is interested on learning French.  

---

**Q29.** Choose the correct word: The principal gave the students some useful ____.

A. advice  
B. advising  
C. advise  
D. advices  

---

**Q30.** Choose the correct word: The new policy will ____ all workers.

A. affect  
B. effects  
C. affects  
D. effect  

---

**Q31.** Choose the correct word: Please ____ this letter to the post office.

A. bring  
B. take  
C. carry  
D. fetch  

---

**Q32.** Choose the correct word: The company's ____ concern is customer satisfaction.

A. principle  
B. principal  
C. principles  
D. principally  

---

**Q33.** Choose the correct sentence:

A. The news are good.  
B. The news were good.  
C. The news is good.  
D. The news have been good.  

---

**Q34.** Choose the correct sentence:

A. I look forward to hear from you.  
B. I look forward to heard from you.  
C. I look forward to hears from you.  
D. I look forward to hearing from you.  

---

**Q35.** Choose the correct sentence:

A. He is the tallest of the two brothers.  
B. He is most tallest of the two brothers.  
C. He is the taller of the two brothers.  
D. He is more taller of the two brothers.  

---

**Q36.** Choose the correct sentence:

A. She is more taller than her sister.  
B. She is tallest than her sister.  
C. She is most taller than her sister.  
D. She is taller than her sister.  

---

**Q37.** Choose the correct word: The dog wagged ____ tail.

A. its'  
B. its  
C. it's  
D. itses  

---

**Q38.** Choose the correct word: ____ going to the market.

A. There  
B. They're  
C. Theirs  
D. Their  

---

**Q39.** Choose the correct word: ____ book is this?

A. Whom  
B. Who's  
C. Whose  
D. Who  

---

**Q40.** Choose the correct sentence:

A. The teacher, along with her students, were going on the trip.  
B. The teacher, along with her students, are going on the trip.  
C. The teacher, along with her students, have been going on the trip.  
D. The teacher, along with her students, is going on the trip.  

---

**Q41.** An essay that tells a story is called:

A. an expository essay  
B. a descriptive essay  
C. a narrative essay  
D. an argumentative essay  

---

**Q42.** An essay that presents reasons for and against a position is called:

A. a descriptive essay  
B. a letter  
C. a narrative essay  
D. an argumentative essay  

---

**Q43.** An essay that explains or informs is called:

A. a poem  
B. an expository essay  
C. a narrative essay  
D. a story  

---

**Q44.** An essay that uses sensory details to paint a picture is called:

A. a summary  
B. a descriptive essay  
C. an expository essay  
D. an argumentative essay  

---

**Q45.** The first paragraph of an essay is called the:

A. title  
B. conclusion  
C. introduction  
D. body  

---

**Q46.** The final paragraph of an essay is called the:

A. heading  
B. introduction  
C. body  
D. conclusion  

---

**Q47.** A formal letter should begin with:

A. a joke  
B. a greeting like 'Hi'  
C. the sender's address and the date  
D. the recipient's name only  

---

**Q48.** The main paragraphs of an essay form the:

A. title  
B. conclusion  
C. introduction  
D. body  

---

**Q49.** A letter of application should include:

A. your qualifications and experience  
B. only your name  
C. a list of your friends  
D. your favourite hobbies  

---

**Q50.** When writing an argumentative essay, you should:

A. support your argument with reasons and examples  
B. avoid giving any reasons  
C. write without paragraphs  
D. only state the opposing view  

---

**Q51.** A narrative essay should have:

A. a clear sequence of events  
B. no setting  
C. no characters  
D. only statistics  

---

**Q52.** The purpose of an introduction is to:

A. present the topic and capture the reader's interest  
B. list all the details  
C. repeat the title  
D. give the conclusion  

---

**Q53.** A descriptive essay about a market should include:

A. sights, sounds, and smells  
B. mathematical calculations  
C. only prices  
D. a list of items  

---

**Q54.** A formal letter to the editor should:

A. express a clear opinion on an issue  
B. be very short  
C. have no address  
D. be written in slang  

---

**Q55.** The best way to organise an expository essay is:

A. random ideas  
B. logical paragraphs with clear points  
C. a single long paragraph  
D. a list without explanation  

---

**Q56.** A story that illustrates a proverb should:

A. state the proverb only  
B. show the lesson through events  
C. be about animals only  
D. avoid any lesson  

---

**Q57.** When writing an essay, you should:

A. start writing without a plan  
B. copy from a friend  
C. plan your ideas before writing  
D. write only one paragraph  

---

**Q58.** The word count of an essay refers to:

A. the number of paragraphs  
B. the number of pages  
C. the number of sentences  
D. the number of words in the essay  

---

**Q59.** A letter of complaint should:

A. only greet the recipient  
B. be written in verse  
C. clearly state the problem and request action  
D. avoid mentioning the problem  

---

**Q60.** To make an essay interesting, a writer should:

A. repeat the same word  
B. avoid examples  
C. use only short sentences  
D. use vivid and varied language  

---

## ANSWER KEY

1. A
2. A
3. A
4. A
5. A
6. A
7. B
8. B
9. C
10. D
11. C
12. D
13. B
14. B
15. C
16. D
17. C
18. D
19. B
20. B
21. C
22. D
23. C
24. D
25. A
26. A
27. A
28. A
29. A
30. A
31. B
32. B
33. C
34. D
35. C
36. D
37. B
38. B
39. C
40. D
41. C
42. D
43. B
44. B
45. C
46. D
47. C
48. D
49. A
50. A
51. A
52. A
53. A
54. A
55. B
56. B
57. C
58. D
59. C
60. D
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds English Language MCQ practice paper set 1 (60 questions)'
),
(
  '38deca0a-f4b8-5e14-8d1d-ba7052547d5e',
  'eng-comprehension-summary',
  'English Language',
  'CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P1 SET 2',
  'english',
  'ordinary',
  array['form_5']::text[],
  array['general', 'science', 'arts', 'commercial', 'technical']::text[],
  'published',
  $md$
# CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P1 SET 2

## Multiple Choice Question Bank

**Level:** Ordinary Level
**Class:** FORM 5
**Series:** general, science, arts, commercial, technical
**Subject:** English Language

**Instructions:**

- Choose the correct option A, B, C or D for each question.
- Record your answers clearly on the answer sheet provided.
- Each question carries equal marks. No marks is deducted for wrong answers.
- Use the answer key at the end of the paper to check your responses.

---

## QUESTIONS

**Q1.** The main idea of a passage is best described as:

A. the central point the writer is making  
B. the first sentence of the passage  
C. the most difficult word in the passage  
D. the writer's personal opinion only  

---

**Q2.** Read: 'The words evaporated.' This means the speaker:

A. forgot what he wanted to say  
B. spoke very quietly  
C. was interrupted by the crowd  
D. wrote his speech down  

---

**Q3.** When asked to 'state the main idea in one sentence', you should:

A. summarise the whole passage briefly  
B. repeat the title  
C. quote the longest sentence  
D. list all the details  

---

**Q4.** An inference is:

A. a conclusion drawn from evidence in the text  
B. a quotation from the text  
C. a question about the text  
D. a fact stated directly in the text  

---

**Q5.** Read: 'The river had always been generous.' The word 'generous' here suggests the river:

A. provided many benefits  
B. was polluted  
C. was very wide  
D. flowed very fast  

---

**Q6.** In a summary, you should NOT include:

A. your personal opinions  
B. the essential ideas  
C. the key facts  
D. the main points  

---

**Q7.** The word 'biodiverse' in 'Cameroon's forests are among the most biodiverse' means:

A. very large in size  
B. containing many different species  
C. completely untouched  
D. difficult to reach  

---

**Q8.** Read: 'The audience wants you to succeed.' This advice helped the speaker to:

A. leave the stage  
B. feel calmer and begin speaking  
C. change his topic  
D. memorise his speech  

---

**Q9.** When summarising, the word limit means you must:

A. write exactly the same number of words as the passage  
B. write as many words as possible  
C. keep your summary within the stated number of words  
D. ignore the word limit  

---

**Q10.** Read: 'Tourism in Cameroon is a sleeping giant.' This means tourism:

A. is completely absent  
B. is declining rapidly  
C. is too expensive for visitors  
D. has great potential that is not yet realised  

---

**Q11.** The purpose of a comprehension passage is usually to:

A. provide entertainment only  
B. list vocabulary words  
C. test understanding of the text  
D. teach grammar rules  

---

**Q12.** Read: 'The villagers did not celebrate; they had heard such promises before.' This suggests the villagers:

A. were happy with the announcement  
B. were celebrating quietly  
C. had never heard promises before  
D. did not trust the government's promises  

---

**Q13.** A good summary should be:

A. the same length as the original passage  
B. shorter than the original passage  
C. longer than the original passage  
D. a copy of the original passage  

---

**Q14.** Read: 'For her, sweeping was not a chore but a meditation.' This means the old woman:

A. swept very quickly  
B. found peace in sweeping  
C. hired someone to sweep  
D. disliked sweeping  

---

**Q15.** When a question asks you to 'explain in your own words', you should:

A. write a longer version of the passage  
B. quote the passage directly  
C. rephrase the idea without copying  
D. give your own opinion  

---

**Q16.** Read: 'Success is not a destination but a journey.' The writer means success is:

A. impossible to achieve  
B. a final goal  
C. measured by certificates  
D. a continuous process  

---

**Q17.** The best title for a passage about plastic waste clogging drainage channels would be:

A. The History of Plastic  
B. A Day at the Market  
C. The Problem of Plastic Waste in Our Cities  
D. How to Build Drainage Channels  

---

**Q18.** Read: 'The market was the beating heart of the community.' The phrase 'beating heart' suggests the market was:

A. a place of conflict  
B. a modern building  
C. a noisy place  
D. the centre of community life  

---

**Q19.** In summary writing, the first step is to:

A. write your own opinions about the topic  
B. read the passage carefully to understand the main ideas  
C. copy the first sentence of each paragraph  
D. count the words in the passage  

---

**Q20.** A summary should be written:

A. as a list of examples  
B. in your own words  
C. in note form only  
D. using long quotations from the passage  

---

**Q21.** Choose the correct sentence:

A. The number of accidents have been increasing.  
B. The number of accidents are increasing.  
C. The number of accidents is increasing.  
D. The number of accidents were increasing.  

---

**Q22.** Choose the correct sentence:

A. She is good for mathematics.  
B. She is good in mathematics.  
C. She is good on mathematics.  
D. She is good at mathematics.  

---

**Q23.** Choose the correct sentence:

A. He was accused on theft.  
B. He was accused with theft.  
C. He was accused of theft.  
D. He was accused for theft.  

---

**Q24.** Choose the correct sentence:

A. The committee consists on ten members.  
B. The committee consists with ten members.  
C. The committee consists in ten members.  
D. The committee consists of ten members.  

---

**Q25.** Choose the correct sentence:

A. She is interested in learning French.  
B. She is interested on learning French.  
C. She is interested for learning French.  
D. She is interested at learning French.  

---

**Q26.** Choose the correct word: The principal gave the students some useful ____.

A. advice  
B. advise  
C. advising  
D. advices  

---

**Q27.** Choose the correct word: The new policy will ____ all workers.

A. affect  
B. affects  
C. effect  
D. effects  

---

**Q28.** Choose the correct word: Please ____ this letter to the post office.

A. take  
B. carry  
C. fetch  
D. bring  

---

**Q29.** Choose the correct word: The company's ____ concern is customer satisfaction.

A. principal  
B. principles  
C. principle  
D. principally  

---

**Q30.** Choose the correct sentence:

A. The news is good.  
B. The news have been good.  
C. The news were good.  
D. The news are good.  

---

**Q31.** Choose the correct sentence:

A. I look forward to hear from you.  
B. I look forward to hearing from you.  
C. I look forward to heard from you.  
D. I look forward to hears from you.  

---

**Q32.** Choose the correct sentence:

A. He is the tallest of the two brothers.  
B. He is the taller of the two brothers.  
C. He is most tallest of the two brothers.  
D. He is more taller of the two brothers.  

---

**Q33.** Choose the correct sentence:

A. She is more taller than her sister.  
B. She is most taller than her sister.  
C. She is taller than her sister.  
D. She is tallest than her sister.  

---

**Q34.** Choose the correct word: The dog wagged ____ tail.

A. it's  
B. its'  
C. itses  
D. its  

---

**Q35.** Choose the correct word: ____ going to the market.

A. Their  
B. Theirs  
C. They're  
D. There  

---

**Q36.** Choose the correct word: ____ book is this?

A. Who's  
B. Who  
C. Whom  
D. Whose  

---

**Q37.** Choose the correct sentence:

A. The teacher, along with her students, were going on the trip.  
B. The teacher, along with her students, is going on the trip.  
C. The teacher, along with her students, are going on the trip.  
D. The teacher, along with her students, have been going on the trip.  

---

**Q38.** Choose the correct sentence:

A. Neither of the boys are present.  
B. Neither of the boys was present.  
C. Neither of the boys have been present.  
D. Neither of the boys were present.  

---

**Q39.** Choose the correct sentence:

A. The committee are deciding to postpone the event.  
B. The committee have decided to postpone the event.  
C. The committee has decided to postpone the event.  
D. The committee were deciding to postpone the event.  

---

**Q40.** Choose the correct sentence:

A. Each of the students are submitting the assignment.  
B. Each of the students have submitted the assignment.  
C. Each of the students were submitting the assignment.  
D. Each of the students has submitted the assignment.  

---

**Q41.** An essay that uses sensory details to paint a picture is called:

A. an expository essay  
B. a summary  
C. a descriptive essay  
D. an argumentative essay  

---

**Q42.** The first paragraph of an essay is called the:

A. body  
B. title  
C. conclusion  
D. introduction  

---

**Q43.** The final paragraph of an essay is called the:

A. heading  
B. conclusion  
C. introduction  
D. body  

---

**Q44.** A formal letter should begin with:

A. a joke  
B. the sender's address and the date  
C. a greeting like 'Hi'  
D. the recipient's name only  

---

**Q45.** The main paragraphs of an essay form the:

A. title  
B. introduction  
C. body  
D. conclusion  

---

**Q46.** A letter of application should include:

A. your favourite hobbies  
B. only your name  
C. a list of your friends  
D. your qualifications and experience  

---

**Q47.** When writing an argumentative essay, you should:

A. write without paragraphs  
B. only state the opposing view  
C. support your argument with reasons and examples  
D. avoid giving any reasons  

---

**Q48.** A narrative essay should have:

A. only statistics  
B. no setting  
C. no characters  
D. a clear sequence of events  

---

**Q49.** The purpose of an introduction is to:

A. present the topic and capture the reader's interest  
B. give the conclusion  
C. list all the details  
D. repeat the title  

---

**Q50.** A descriptive essay about a market should include:

A. sights, sounds, and smells  
B. only prices  
C. mathematical calculations  
D. a list of items  

---

**Q51.** A formal letter to the editor should:

A. express a clear opinion on an issue  
B. have no address  
C. be written in slang  
D. be very short  

---

**Q52.** The best way to organise an expository essay is:

A. logical paragraphs with clear points  
B. a single long paragraph  
C. a list without explanation  
D. random ideas  

---

**Q53.** A story that illustrates a proverb should:

A. show the lesson through events  
B. be about animals only  
C. state the proverb only  
D. avoid any lesson  

---

**Q54.** When writing an essay, you should:

A. plan your ideas before writing  
B. write only one paragraph  
C. copy from a friend  
D. start writing without a plan  

---

**Q55.** The word count of an essay refers to:

A. the number of paragraphs  
B. the number of words in the essay  
C. the number of pages  
D. the number of sentences  

---

**Q56.** A letter of complaint should:

A. only greet the recipient  
B. clearly state the problem and request action  
C. be written in verse  
D. avoid mentioning the problem  

---

**Q57.** To make an essay interesting, a writer should:

A. repeat the same word  
B. use only short sentences  
C. use vivid and varied language  
D. avoid examples  

---

**Q58.** An essay that tells a story is called:

A. an argumentative essay  
B. an expository essay  
C. a descriptive essay  
D. a narrative essay  

---

**Q59.** An essay that presents reasons for and against a position is called:

A. a narrative essay  
B. a letter  
C. an argumentative essay  
D. a descriptive essay  

---

**Q60.** An essay that explains or informs is called:

A. a narrative essay  
B. a poem  
C. a story  
D. an expository essay  

---

## ANSWER KEY

1. A
2. A
3. A
4. A
5. A
6. A
7. B
8. B
9. C
10. D
11. C
12. D
13. B
14. B
15. C
16. D
17. C
18. D
19. B
20. B
21. C
22. D
23. C
24. D
25. A
26. A
27. A
28. A
29. A
30. A
31. B
32. B
33. C
34. D
35. C
36. D
37. B
38. B
39. C
40. D
41. C
42. D
43. B
44. B
45. C
46. D
47. C
48. D
49. A
50. A
51. A
52. A
53. A
54. A
55. B
56. B
57. C
58. D
59. C
60. D
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds English Language MCQ practice paper set 2 (60 questions)'
),
(
  'ed3bb501-1993-5367-b97e-c3b721e6b389',
  'eng-comprehension-summary',
  'English Language',
  'CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P1 SET 3',
  'english',
  'ordinary',
  array['form_5']::text[],
  array['general', 'science', 'arts', 'commercial', 'technical']::text[],
  'published',
  $md$
# CAMEROON GCE ORDINARY LEVEL ENGLISH LANGUAGE P1 SET 3

## Multiple Choice Question Bank

**Level:** Ordinary Level
**Class:** FORM 5
**Series:** general, science, arts, commercial, technical
**Subject:** English Language

**Instructions:**

- Choose the correct option A, B, C or D for each question.
- Record your answers clearly on the answer sheet provided.
- Each question carries equal marks. No marks is deducted for wrong answers.
- Use the answer key at the end of the paper to check your responses.

---

## QUESTIONS

**Q1.** An inference is:

A. a conclusion drawn from evidence in the text  
B. a fact stated directly in the text  
C. a quotation from the text  
D. a question about the text  

---

**Q2.** Read: 'The river had always been generous.' The word 'generous' here suggests the river:

A. provided many benefits  
B. was very wide  
C. was polluted  
D. flowed very fast  

---

**Q3.** In a summary, you should NOT include:

A. your personal opinions  
B. the key facts  
C. the main points  
D. the essential ideas  

---

**Q4.** The word 'biodiverse' in 'Cameroon's forests are among the most biodiverse' means:

A. containing many different species  
B. completely untouched  
C. difficult to reach  
D. very large in size  

---

**Q5.** Read: 'The audience wants you to succeed.' This advice helped the speaker to:

A. feel calmer and begin speaking  
B. change his topic  
C. leave the stage  
D. memorise his speech  

---

**Q6.** When summarising, the word limit means you must:

A. keep your summary within the stated number of words  
B. ignore the word limit  
C. write as many words as possible  
D. write exactly the same number of words as the passage  

---

**Q7.** Read: 'Tourism in Cameroon is a sleeping giant.' This means tourism:

A. is completely absent  
B. has great potential that is not yet realised  
C. is declining rapidly  
D. is too expensive for visitors  

---

**Q8.** The purpose of a comprehension passage is usually to:

A. provide entertainment only  
B. test understanding of the text  
C. list vocabulary words  
D. teach grammar rules  

---

**Q9.** Read: 'The villagers did not celebrate; they had heard such promises before.' This suggests the villagers:

A. were happy with the announcement  
B. had never heard promises before  
C. did not trust the government's promises  
D. were celebrating quietly  

---

**Q10.** A good summary should be:

A. longer than the original passage  
B. the same length as the original passage  
C. a copy of the original passage  
D. shorter than the original passage  

---

**Q11.** Read: 'For her, sweeping was not a chore but a meditation.' This means the old woman:

A. disliked sweeping  
B. hired someone to sweep  
C. found peace in sweeping  
D. swept very quickly  

---

**Q12.** When a question asks you to 'explain in your own words', you should:

A. quote the passage directly  
B. give your own opinion  
C. write a longer version of the passage  
D. rephrase the idea without copying  

---

**Q13.** Read: 'Success is not a destination but a journey.' The writer means success is:

A. impossible to achieve  
B. a continuous process  
C. a final goal  
D. measured by certificates  

---

**Q14.** The best title for a passage about plastic waste clogging drainage channels would be:

A. The History of Plastic  
B. The Problem of Plastic Waste in Our Cities  
C. A Day at the Market  
D. How to Build Drainage Channels  

---

**Q15.** Read: 'The market was the beating heart of the community.' The phrase 'beating heart' suggests the market was:

A. a place of conflict  
B. a noisy place  
C. the centre of community life  
D. a modern building  

---

**Q16.** In summary writing, the first step is to:

A. count the words in the passage  
B. copy the first sentence of each paragraph  
C. write your own opinions about the topic  
D. read the passage carefully to understand the main ideas  

---

**Q17.** A summary should be written:

A. in note form only  
B. as a list of examples  
C. in your own words  
D. using long quotations from the passage  

---

**Q18.** The main idea of a passage is best described as:

A. the most difficult word in the passage  
B. the writer's personal opinion only  
C. the first sentence of the passage  
D. the central point the writer is making  

---

**Q19.** Read: 'The words evaporated.' This means the speaker:

A. was interrupted by the crowd  
B. forgot what he wanted to say  
C. spoke very quietly  
D. wrote his speech down  

---

**Q20.** When asked to 'state the main idea in one sentence', you should:

A. list all the details  
B. summarise the whole passage briefly  
C. repeat the title  
D. quote the longest sentence  

---

**Q21.** Choose the correct sentence:

A. The committee consists on ten members.  
B. The committee consists in ten members.  
C. The committee consists of ten members.  
D. The committee consists with ten members.  

---

**Q22.** Choose the correct sentence:

A. She is interested at learning French.  
B. She is interested on learning French.  
C. She is interested for learning French.  
D. She is interested in learning French.  

---

**Q23.** Choose the correct word: The principal gave the students some useful ____.

A. advising  
B. advices  
C. advice  
D. advise  

---

**Q24.** Choose the correct word: The new policy will ____ all workers.

A. effects  
B. affects  
C. effect  
D. affect  

---

**Q25.** Choose the correct word: Please ____ this letter to the post office.

A. take  
B. bring  
C. carry  
D. fetch  

---

**Q26.** Choose the correct word: The company's ____ concern is customer satisfaction.

A. principal  
B. principle  
C. principles  
D. principally  

---

**Q27.** Choose the correct sentence:

A. The news is good.  
B. The news were good.  
C. The news are good.  
D. The news have been good.  

---

**Q28.** Choose the correct sentence:

A. I look forward to hearing from you.  
B. I look forward to heard from you.  
C. I look forward to hears from you.  
D. I look forward to hear from you.  

---

**Q29.** Choose the correct sentence:

A. He is the taller of the two brothers.  
B. He is most tallest of the two brothers.  
C. He is the tallest of the two brothers.  
D. He is more taller of the two brothers.  

---

**Q30.** Choose the correct sentence:

A. She is taller than her sister.  
B. She is tallest than her sister.  
C. She is most taller than her sister.  
D. She is more taller than her sister.  

---

**Q31.** Choose the correct word: The dog wagged ____ tail.

A. it's  
B. its  
C. its'  
D. itses  

---

**Q32.** Choose the correct word: ____ going to the market.

A. Their  
B. They're  
C. Theirs  
D. There  

---

**Q33.** Choose the correct word: ____ book is this?

A. Who's  
B. Whom  
C. Whose  
D. Who  

---

**Q34.** Choose the correct sentence:

A. The teacher, along with her students, are going on the trip.  
B. The teacher, along with her students, were going on the trip.  
C. The teacher, along with her students, have been going on the trip.  
D. The teacher, along with her students, is going on the trip.  

---

**Q35.** Choose the correct sentence:

A. Neither of the boys were present.  
B. Neither of the boys have been present.  
C. Neither of the boys was present.  
D. Neither of the boys are present.  

---

**Q36.** Choose the correct sentence:

A. The committee have decided to postpone the event.  
B. The committee were deciding to postpone the event.  
C. The committee are deciding to postpone the event.  
D. The committee has decided to postpone the event.  

---

**Q37.** Choose the correct sentence:

A. Each of the students are submitting the assignment.  
B. Each of the students has submitted the assignment.  
C. Each of the students have submitted the assignment.  
D. Each of the students were submitting the assignment.  

---

**Q38.** Choose the correct sentence:

A. The number of accidents were increasing.  
B. The number of accidents is increasing.  
C. The number of accidents have been increasing.  
D. The number of accidents are increasing.  

---

**Q39.** Choose the correct sentence:

A. She is good on mathematics.  
B. She is good in mathematics.  
C. She is good at mathematics.  
D. She is good for mathematics.  

---

**Q40.** Choose the correct sentence:

A. He was accused with theft.  
B. He was accused for theft.  
C. He was accused on theft.  
D. He was accused of theft.  

---

**Q41.** A formal letter should begin with:

A. a greeting like 'Hi'  
B. a joke  
C. the sender's address and the date  
D. the recipient's name only  

---

**Q42.** The main paragraphs of an essay form the:

A. conclusion  
B. title  
C. introduction  
D. body  

---

**Q43.** A letter of application should include:

A. your favourite hobbies  
B. your qualifications and experience  
C. only your name  
D. a list of your friends  

---

**Q44.** When writing an argumentative essay, you should:

A. write without paragraphs  
B. support your argument with reasons and examples  
C. only state the opposing view  
D. avoid giving any reasons  

---

**Q45.** A narrative essay should have:

A. only statistics  
B. no characters  
C. a clear sequence of events  
D. no setting  

---

**Q46.** The purpose of an introduction is to:

A. repeat the title  
B. give the conclusion  
C. list all the details  
D. present the topic and capture the reader's interest  

---

**Q47.** A descriptive essay about a market should include:

A. mathematical calculations  
B. a list of items  
C. sights, sounds, and smells  
D. only prices  

---

**Q48.** A formal letter to the editor should:

A. be very short  
B. have no address  
C. be written in slang  
D. express a clear opinion on an issue  

---

**Q49.** The best way to organise an expository essay is:

A. logical paragraphs with clear points  
B. random ideas  
C. a single long paragraph  
D. a list without explanation  

---

**Q50.** A story that illustrates a proverb should:

A. show the lesson through events  
B. state the proverb only  
C. be about animals only  
D. avoid any lesson  

---

**Q51.** When writing an essay, you should:

A. plan your ideas before writing  
B. copy from a friend  
C. start writing without a plan  
D. write only one paragraph  

---

**Q52.** The word count of an essay refers to:

A. the number of words in the essay  
B. the number of pages  
C. the number of sentences  
D. the number of paragraphs  

---

**Q53.** A letter of complaint should:

A. clearly state the problem and request action  
B. be written in verse  
C. only greet the recipient  
D. avoid mentioning the problem  

---

**Q54.** To make an essay interesting, a writer should:

A. use vivid and varied language  
B. avoid examples  
C. use only short sentences  
D. repeat the same word  

---

**Q55.** An essay that tells a story is called:

A. an argumentative essay  
B. a narrative essay  
C. an expository essay  
D. a descriptive essay  

---

**Q56.** An essay that presents reasons for and against a position is called:

A. a narrative essay  
B. an argumentative essay  
C. a letter  
D. a descriptive essay  

---

**Q57.** An essay that explains or informs is called:

A. a narrative essay  
B. a story  
C. an expository essay  
D. a poem  

---

**Q58.** An essay that uses sensory details to paint a picture is called:

A. an argumentative essay  
B. an expository essay  
C. a summary  
D. a descriptive essay  

---

**Q59.** The first paragraph of an essay is called the:

A. conclusion  
B. title  
C. introduction  
D. body  

---

**Q60.** The final paragraph of an essay is called the:

A. introduction  
B. heading  
C. body  
D. conclusion  

---

## ANSWER KEY

1. A
2. A
3. A
4. A
5. A
6. A
7. B
8. B
9. C
10. D
11. C
12. D
13. B
14. B
15. C
16. D
17. C
18. D
19. B
20. B
21. C
22. D
23. C
24. D
25. A
26. A
27. A
28. A
29. A
30. A
31. B
32. B
33. C
34. D
35. C
36. D
37. B
38. B
39. C
40. D
41. C
42. D
43. B
44. B
45. C
46. D
47. C
48. D
49. A
50. A
51. A
52. A
53. A
54. A
55. B
56. B
57. C
58. D
59. C
60. D
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds English Language MCQ practice paper set 3 (60 questions)'
)
on conflict (id) do update set
  topic_id = excluded.topic_id,
  subject = excluded.subject,
  title = excluded.title,
  language = excluded.language,
  level = excluded.level,
  class_levels = excluded.class_levels,
  series = excluded.series,
  status = excluded.status,
  markdown_content = excluded.markdown_content,
  content_kind = excluded.content_kind,
  doc_type = excluded.doc_type,
  curriculum_path = excluded.curriculum_path,
  exam = excluded.exam,
  content_year = excluded.content_year,
  source_type = excluded.source_type,
  source_reference = excluded.source_reference,
  permission_status = excluded.permission_status,
  review_status = excluded.review_status,
  content_version = excluded.content_version,
  change_note = excluded.change_note,
  updated_at = now();

notify pgrst, 'reload schema';

commit;
