begin;

-- English GCE hard practice papers: topic-wise structural sets and MCQ sets.
-- Generated by scripts/generate-hard-papers.mjs.
-- Every row carries an explicit topic_id so topic-wise papers land on the
-- correct syllabus topic instead of a subject-level default.

insert into public.course_documents (
  id, topic_id, subject, title, language, level, class_levels, series, status,
  markdown_content, content_kind, doc_type, curriculum_path, exam, content_year,
  source_type, source_reference, permission_status, review_status, content_version, change_note
)
values
(
  '59068310-1e48-5ad1-829b-2d2a11ce64c5',
  'furthermath-pure',
  'Further Mathematics',
  'CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P2 SET 4',
  'english',
  'advanced',
  array['upper_sixth']::text[],
  array['a_science']::text[],
  'published',
  $md$
# CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P2 SET 4

## Structural Question Bank — Pure mathematics

**Level:** Advanced Level
**Class:** UPPER SIXTH
**Series:** a_science
**Subject:** Further Mathematics

**Instructions:**

- Answer all questions in a clear and organized manner.
- Show all working where calculations are required.
- Use correct subject terminology and Cameroon GCE presentation standards.
- Diagrams, tables, maps, labelled sketches, and examples should be included where useful.

---

## SECTION 1: PURE MATHEMATICS

**Q1.** (a) Express $z = 3 + 4i$ in modulus-argument form. *(4 marks)*

(b) Find the modulus and argument of $z^2$. *(4 marks)*

(c) Solve the equation $z^2 + 2z + 5 = 0$, giving your answers in the form $a + bi$. *(4 marks)*

---

**Q2.** (a) Given $z_1 = 2 + 3i$ and $z_2 = 1 - i$, find $z_1 z_2$ and $\frac{z_1}{z_2}$. *(6 marks)*

(b) Find the square roots of $-8 + 6i$. *(6 marks)*

---

**Q3.** (a) Express $z = 2(\cos 60^\circ + i\sin 60^\circ)$ in the form $a + bi$. *(3 marks)*

(b) Use De Moivre's theorem to find $(1 + i)^8$. *(5 marks)*

(c) Solve $z^3 = 8$, giving all three roots. *(5 marks)*

---

**Q4.** (a) State the conditions for two matrices to be multiplied. *(2 marks)*

(b) Given $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ and $B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}$, find $AB$ and $BA$. *(6 marks)*

(c) Show that $AB \neq BA$. *(2 marks)*

---

**Q5.** (a) Find the determinant and inverse of $A = \begin{pmatrix} 2 & 3 \\ 1 & 4 \end{pmatrix}$. *(5 marks)*

(b) Use the inverse matrix method to solve the simultaneous equations $2x + 3y = 7$ and $x + 4y = 6$. *(5 marks)*

---

**Q6.** (a) Find the eigenvalues and eigenvectors of $A = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$. *(6 marks)*

(b) State the trace and determinant of $A$. *(2 marks)*

(c) Verify that the sum of the eigenvalues equals the trace. *(2 marks)*

---

**Q7.** (a) Given $\mathbf{a} = 2\mathbf{i} + 3\mathbf{j} - \mathbf{k}$ and $\mathbf{b} = \mathbf{i} - 2\mathbf{j} + 4\mathbf{k}$, find $\mathbf{a} \cdot \mathbf{b}$. *(3 marks)*

(b) Find the angle between $\mathbf{a}$ and $\mathbf{b}$. *(4 marks)*

(c) Find $\mathbf{a} \times \mathbf{b}$. *(4 marks)*

---

**Q8.** (a) Find the equation of the plane passing through the points $(1, 2, 3)$, $(2, 0, 1)$, and $(0, 1, 2)$. *(6 marks)*

(b) Find the distance from the point $(1, 1, 1)$ to this plane. *(4 marks)*

---

**Q9.** (a) Prove by induction that $1^2 + 2^2 + 3^2 + \cdots + n^2 = \frac{n(n+1)(2n+1)}{6}$. *(6 marks)*

(b) Prove by induction that $3^n > n^2$ for all positive integers $n$. *(5 marks)*

---

**Q10.** (a) Prove by contradiction that $\sqrt{2}$ is irrational. *(5 marks)*

(b) Prove that the sum of two odd numbers is even. *(3 marks)*

(c) Prove that $n^3 - n$ is divisible by 6 for all positive integers $n$. *(5 marks)*

---

**Q11.** (a) Find the sum of the series $1 + 2 + 3 + \cdots + n$. *(3 marks)*

(b) Find the sum of the series $1^2 + 3^2 + 5^2 + \cdots + (2n-1)^2$. *(5 marks)*

(c) Determine whether the series $\sum_{n=1}^{\infty} \frac{1}{n(n+1)}$ converges, and find its sum. *(5 marks)*

---

**Q12.** (a) State the binomial theorem. *(2 marks)*

(b) Expand $(1 + x)^{10}$ up to the term in $x^3$. *(4 marks)*

(c) Find the coefficient of $x^5$ in the expansion of $(2 - 3x)^8$. *(5 marks)*

---

**Q13.** (a) Find the first three terms in the binomial expansion of $\frac{1}{\sqrt{1 + x}}$ for $|x| < 1$. *(5 marks)*

(b) Use your expansion to approximate $\frac{1}{\sqrt{1.1}}$. *(3 marks)*

(c) State the range of validity of the expansion. *(2 marks)*

---

**Q14.** (a) Find the general solution of the differential equation $\frac{dy}{dx} = \frac{y}{x}$. *(4 marks)*

(b) Solve the differential equation $\frac{dy}{dx} + 2y = e^{-x}$ given that $y = 1$ when $x = 0$. *(6 marks)*

---

**Q15.** (a) Solve the differential equation $\frac{d^2y}{dx^2} - 3\frac{dy}{dx} + 2y = 0$. *(5 marks)*

(b) Given that $y = 1$ and $\frac{dy}{dx} = 0$ when $x = 0$, find the particular solution. *(4 marks)*

---

**Q16.** (a) Express $f(x) = \frac{3x + 1}{(x-1)(x+2)}$ in partial fractions. *(5 marks)*

(b) Express $\frac{2x^2 + 3x + 1}{(x+1)(x^2 + 1)}$ in partial fractions. *(6 marks)*

---

**Q17.** (a) Find the roots of the equation $x^3 - 6x^2 + 11x - 6 = 0$. *(5 marks)*

(b) Given that $1 - i$ is a root of $x^3 - 3x^2 + 4x - 2 = 0$, find the other roots. *(5 marks)*

---

**Q18.** (a) State the remainder theorem. *(2 marks)*

(b) Find the remainder when $x^4 - 3x^3 + 2x - 1$ is divided by $x - 2$. *(4 marks)*

(c) Given that $x - 1$ is a factor of $x^3 + ax^2 + bx - 6$, and the remainder is 4 when divided by $x - 2$, find $a$ and $b$. *(6 marks)*

---

**Q19.** (a) Find $\lim_{x \to 0} \frac{\sin 3x}{x}$. *(3 marks)*

(b) Find $\lim_{x \to \infty} \frac{3x^2 + 2x}{x^2 - 1}$. *(3 marks)*

(c) Find $\lim_{x \to 0} \frac{e^x - 1}{x}$. *(3 marks)*

---

**Q20.** (a) Find the sum to infinity of the geometric series $1 + \frac{1}{2} + \frac{1}{4} + \cdots$. *(3 marks)*

(b) Find the sum of the first $n$ terms of the arithmetic series $3 + 7 + 11 + \cdots$. *(4 marks)*

(c) The sum of the first $n$ terms of a series is $n^2 + 3n$. Find the $n$th term. *(4 marks)*
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds Further Mathematics topic-wise hard structural paper set 4 (Pure mathematics)'
),
(
  'eca9f784-5d5b-50b2-93b0-f795f89ba9d6',
  'furthermath-mechanics-statistics',
  'Further Mathematics',
  'CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P2 SET 5',
  'english',
  'advanced',
  array['upper_sixth']::text[],
  array['a_science']::text[],
  'published',
  $md$
# CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P2 SET 5

## Structural Question Bank — Mechanics and statistics

**Level:** Advanced Level
**Class:** UPPER SIXTH
**Series:** a_science
**Subject:** Further Mathematics

**Instructions:**

- Answer all questions in a clear and organized manner.
- Show all working where calculations are required.
- Use correct subject terminology and Cameroon GCE presentation standards.
- Diagrams, tables, maps, labelled sketches, and examples should be included where useful.

---

## SECTION 1: MECHANICS AND STATISTICS

**Q1.** (a) State Newton's second law of motion. *(2 marks)*

(b) A force of 10 N acts on a body of mass 2 kg. Calculate the acceleration. *(3 marks)*

(c) A body of mass 5 kg is pulled along a rough horizontal surface by a force of 20 N. If the frictional force is 8 N, calculate the acceleration. *(5 marks)*

---

**Q2.** (a) Define the terms "momentum" and "impulse". *(4 marks)*

(b) A ball of mass 0.2 kg moving at 5 m/s strikes a wall and rebounds at 4 m/s. Calculate the impulse. *(4 marks)*

(c) State the principle of conservation of momentum. *(2 marks)*

---

**Q3.** (a) A projectile is fired at 50 m/s at an angle of $30^\circ$ to the horizontal. Calculate the time of flight. *(4 marks)*

(b) Calculate the maximum height reached. *(4 marks)*

(c) Calculate the horizontal range. *(4 marks)*

---

**Q4.** (a) A particle moves in a straight line with acceleration $a = 2t$ m/s². Given that its velocity is 3 m/s when $t = 0$, find its velocity at time $t$. *(4 marks)*

(b) Find its displacement at time $t$ given that it starts from the origin. *(4 marks)*

(c) Find the displacement when $t = 3$ s. *(3 marks)*

---

**Q5.** (a) State the principle of moments. *(2 marks)*

(b) A uniform rod AB of length 4 m and weight 40 N is pivoted at its centre. A weight of 20 N is placed at A. Calculate the force needed at B to balance the rod. *(5 marks)*

(c) A uniform ladder of weight 200 N rests against a smooth vertical wall. Find the reactions at the wall and the ground. *(6 marks)*

---

**Q6.** (a) Define the terms "centre of mass" and "centre of gravity". *(4 marks)*

(b) Find the centre of mass of a uniform triangular lamina. *(4 marks)*

(c) A uniform rod of length 6 m and weight 60 N has a 30 N weight attached at one end. Find the position of the centre of mass. *(5 marks)*

---

**Q7.** (a) Define the term "work done". *(2 marks)*

(b) A force of 30 N acts at an angle of $60^\circ$ to the direction of motion. Calculate the work done in moving the body 10 m. *(4 marks)*

(c) A body of mass 4 kg is raised through 5 m. Calculate the work done against gravity. (Take $g = 10$ m/s²) *(4 marks)*

---

**Q8.** (a) State the work-energy theorem. *(2 marks)*

(b) A body of mass 2 kg moving at 4 m/s is brought to rest by a constant force. Calculate the work done. *(4 marks)*

(c) A car of mass 1000 kg accelerates from 10 m/s to 20 m/s. Calculate the work done. *(5 marks)*

---

**Q9.** (a) Define the terms "kinetic energy" and "potential energy". *(4 marks)*

(b) A body of mass 3 kg is projected vertically upwards with a speed of 20 m/s. Calculate its maximum height. (Take $g = 10$ m/s²) *(5 marks)*

(c) Calculate the kinetic energy of the body when it has risen 10 m. *(5 marks)*

---

**Q10.** (a) Define the term "power". *(2 marks)*

(b) A motor lifts a load of 500 kg through 20 m in 25 s. Calculate the power output. (Take $g = 10$ m/s²) *(5 marks)*

(c) A car of mass 1200 kg moves at a constant speed of 30 m/s against a resistance of 400 N. Calculate the power developed. *(5 marks)*

---

**Q11.** (a) Define the terms "discrete" and "continuous" random variables. *(4 marks)*

(b) A discrete random variable $X$ has the probability distribution $P(X = x) = kx$ for $x = 1, 2, 3, 4$. Find $k$. *(4 marks)*

(c) Find $E(X)$ and $Var(X)$ for this distribution. *(5 marks)*

---

**Q12.** (a) State the conditions for a binomial distribution. *(3 marks)*

(b) A fair coin is tossed 10 times. Find the probability of getting exactly 6 heads. *(4 marks)*

(c) Find the mean and variance of this binomial distribution. *(3 marks)*

---

**Q13.** (a) State the probability density function of a normal distribution. *(2 marks)*

(b) Given that $X \sim N(50, 16)$, find $P(46 < X < 54)$. *(5 marks)*

(c) Find the value of $x$ such that $P(X < x) = 0.95$. *(5 marks)*

---

**Q14.** (a) Define the term "Poisson distribution". *(2 marks)*

(b) The number of accidents per day at a junction follows a Poisson distribution with mean 2. Find the probability of exactly 3 accidents in a day. *(4 marks)*

(c) Find the probability of at least 1 accident in a day. *(4 marks)*

---

**Q15.** (a) Define the terms "population" and "sample". *(4 marks)*

(b) State three methods of sampling. *(3 marks)*

(c) Explain the difference between a parameter and a statistic. *(4 marks)*

---

**Q16.** (a) Define the term "confidence interval". *(2 marks)*

(b) A sample of 100 students has a mean score of 60 with a standard deviation of 8. Construct a 95% confidence interval for the population mean. *(6 marks)*

(c) State the effect of increasing the sample size on the confidence interval. *(3 marks)*

---

**Q17.** (a) State the null and alternative hypotheses for a two-tailed test of a population mean. *(4 marks)*

(b) A sample of 50 items has a mean of 102 and standard deviation 10. Test at the 5% level whether the population mean differs from 100. *(6 marks)*

---

**Q18.** (a) Define the term "correlation". *(2 marks)*

(b) Calculate the Pearson correlation coefficient for the data: $x = 1, 2, 3, 4, 5$; $y = 2, 4, 5, 4, 5$. *(6 marks)*

(c) Interpret your result. *(3 marks)*

---

**Q19.** (a) Define the term "regression". *(2 marks)*

(b) Find the equation of the least squares regression line of $y$ on $x$ for the data: $x = 1, 2, 3, 4, 5$; $y = 2, 4, 5, 4, 5$. *(6 marks)*

(c) Estimate $y$ when $x = 6$. *(3 marks)*

---

**Q20.** (a) Define the term "probability". *(2 marks)*

(b) Two dice are thrown. Find the probability that the sum is 7. *(4 marks)*

(c) A bag contains 3 red and 5 blue balls. Two balls are drawn without replacement. Find the probability that both are red. *(5 marks)*
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds Further Mathematics topic-wise hard structural paper set 5 (Mechanics and statistics)'
),
(
  '5473ef98-3ffc-5edf-a3a6-d1a0ed0f15f5',
  'furthermath-pure',
  'Further Mathematics',
  'CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P2 SET 6',
  'english',
  'advanced',
  array['upper_sixth']::text[],
  array['a_science']::text[],
  'published',
  $md$
# CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P2 SET 6

## Structural Question Bank — Pure mathematics

**Level:** Advanced Level
**Class:** UPPER SIXTH
**Series:** a_science
**Subject:** Further Mathematics

**Instructions:**

- Answer all questions in a clear and organized manner.
- Show all working where calculations are required.
- Use correct subject terminology and Cameroon GCE presentation standards.
- Diagrams, tables, maps, labelled sketches, and examples should be included where useful.

---

## SECTION 1: PURE MATHEMATICS

**Q1.** (a) Express $z = 3 + 4i$ in modulus-argument form. *(4 marks)*

(b) Find the modulus and argument of $z^2$. *(4 marks)*

(c) Solve the equation $z^2 + 2z + 5 = 0$, giving your answers in the form $a + bi$. *(4 marks)*

---

**Q2.** (a) Given $z_1 = 2 + 3i$ and $z_2 = 1 - i$, find $z_1 z_2$ and $\frac{z_1}{z_2}$. *(6 marks)*

(b) Find the square roots of $-8 + 6i$. *(6 marks)*

---

**Q3.** (a) Express $z = 2(\cos 60^\circ + i\sin 60^\circ)$ in the form $a + bi$. *(3 marks)*

(b) Use De Moivre's theorem to find $(1 + i)^8$. *(5 marks)*

(c) Solve $z^3 = 8$, giving all three roots. *(5 marks)*

---

**Q4.** (a) State the conditions for two matrices to be multiplied. *(2 marks)*

(b) Given $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ and $B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}$, find $AB$ and $BA$. *(6 marks)*

(c) Show that $AB \neq BA$. *(2 marks)*

---

**Q5.** (a) Find the determinant and inverse of $A = \begin{pmatrix} 2 & 3 \\ 1 & 4 \end{pmatrix}$. *(5 marks)*

(b) Use the inverse matrix method to solve the simultaneous equations $2x + 3y = 7$ and $x + 4y = 6$. *(5 marks)*

---

**Q6.** (a) Find the eigenvalues and eigenvectors of $A = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$. *(6 marks)*

(b) State the trace and determinant of $A$. *(2 marks)*

(c) Verify that the sum of the eigenvalues equals the trace. *(2 marks)*

---

**Q7.** (a) Given $\mathbf{a} = 2\mathbf{i} + 3\mathbf{j} - \mathbf{k}$ and $\mathbf{b} = \mathbf{i} - 2\mathbf{j} + 4\mathbf{k}$, find $\mathbf{a} \cdot \mathbf{b}$. *(3 marks)*

(b) Find the angle between $\mathbf{a}$ and $\mathbf{b}$. *(4 marks)*

(c) Find $\mathbf{a} \times \mathbf{b}$. *(4 marks)*

---

**Q8.** (a) Find the equation of the plane passing through the points $(1, 2, 3)$, $(2, 0, 1)$, and $(0, 1, 2)$. *(6 marks)*

(b) Find the distance from the point $(1, 1, 1)$ to this plane. *(4 marks)*

---

**Q9.** (a) Prove by induction that $1^2 + 2^2 + 3^2 + \cdots + n^2 = \frac{n(n+1)(2n+1)}{6}$. *(6 marks)*

(b) Prove by induction that $3^n > n^2$ for all positive integers $n$. *(5 marks)*

---

**Q10.** (a) Prove by contradiction that $\sqrt{2}$ is irrational. *(5 marks)*

(b) Prove that the sum of two odd numbers is even. *(3 marks)*

(c) Prove that $n^3 - n$ is divisible by 6 for all positive integers $n$. *(5 marks)*

---

**Q11.** (a) Find the sum of the series $1 + 2 + 3 + \cdots + n$. *(3 marks)*

(b) Find the sum of the series $1^2 + 3^2 + 5^2 + \cdots + (2n-1)^2$. *(5 marks)*

(c) Determine whether the series $\sum_{n=1}^{\infty} \frac{1}{n(n+1)}$ converges, and find its sum. *(5 marks)*

---

**Q12.** (a) State the binomial theorem. *(2 marks)*

(b) Expand $(1 + x)^{10}$ up to the term in $x^3$. *(4 marks)*

(c) Find the coefficient of $x^5$ in the expansion of $(2 - 3x)^8$. *(5 marks)*

---

**Q13.** (a) Find the first three terms in the binomial expansion of $\frac{1}{\sqrt{1 + x}}$ for $|x| < 1$. *(5 marks)*

(b) Use your expansion to approximate $\frac{1}{\sqrt{1.1}}$. *(3 marks)*

(c) State the range of validity of the expansion. *(2 marks)*

---

**Q14.** (a) Find the general solution of the differential equation $\frac{dy}{dx} = \frac{y}{x}$. *(4 marks)*

(b) Solve the differential equation $\frac{dy}{dx} + 2y = e^{-x}$ given that $y = 1$ when $x = 0$. *(6 marks)*

---

**Q15.** (a) Solve the differential equation $\frac{d^2y}{dx^2} - 3\frac{dy}{dx} + 2y = 0$. *(5 marks)*

(b) Given that $y = 1$ and $\frac{dy}{dx} = 0$ when $x = 0$, find the particular solution. *(4 marks)*

---

**Q16.** (a) Express $f(x) = \frac{3x + 1}{(x-1)(x+2)}$ in partial fractions. *(5 marks)*

(b) Express $\frac{2x^2 + 3x + 1}{(x+1)(x^2 + 1)}$ in partial fractions. *(6 marks)*

---

**Q17.** (a) Find the roots of the equation $x^3 - 6x^2 + 11x - 6 = 0$. *(5 marks)*

(b) Given that $1 - i$ is a root of $x^3 - 3x^2 + 4x - 2 = 0$, find the other roots. *(5 marks)*

---

**Q18.** (a) State the remainder theorem. *(2 marks)*

(b) Find the remainder when $x^4 - 3x^3 + 2x - 1$ is divided by $x - 2$. *(4 marks)*

(c) Given that $x - 1$ is a factor of $x^3 + ax^2 + bx - 6$, and the remainder is 4 when divided by $x - 2$, find $a$ and $b$. *(6 marks)*

---

**Q19.** (a) Find $\lim_{x \to 0} \frac{\sin 3x}{x}$. *(3 marks)*

(b) Find $\lim_{x \to \infty} \frac{3x^2 + 2x}{x^2 - 1}$. *(3 marks)*

(c) Find $\lim_{x \to 0} \frac{e^x - 1}{x}$. *(3 marks)*

---

**Q20.** (a) Find the sum to infinity of the geometric series $1 + \frac{1}{2} + \frac{1}{4} + \cdots$. *(3 marks)*

(b) Find the sum of the first $n$ terms of the arithmetic series $3 + 7 + 11 + \cdots$. *(4 marks)*

(c) The sum of the first $n$ terms of a series is $n^2 + 3n$. Find the $n$th term. *(4 marks)*
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds Further Mathematics topic-wise hard structural paper set 6 (Pure mathematics)'
),
(
  'd4b8be6f-4e00-594b-9c8e-39a27e41bd96',
  'furthermath-mechanics-statistics',
  'Further Mathematics',
  'CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P2 SET 7',
  'english',
  'advanced',
  array['upper_sixth']::text[],
  array['a_science']::text[],
  'published',
  $md$
# CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P2 SET 7

## Structural Question Bank — Mechanics and statistics

**Level:** Advanced Level
**Class:** UPPER SIXTH
**Series:** a_science
**Subject:** Further Mathematics

**Instructions:**

- Answer all questions in a clear and organized manner.
- Show all working where calculations are required.
- Use correct subject terminology and Cameroon GCE presentation standards.
- Diagrams, tables, maps, labelled sketches, and examples should be included where useful.

---

## SECTION 1: MECHANICS AND STATISTICS

**Q1.** (a) State Newton's second law of motion. *(2 marks)*

(b) A force of 10 N acts on a body of mass 2 kg. Calculate the acceleration. *(3 marks)*

(c) A body of mass 5 kg is pulled along a rough horizontal surface by a force of 20 N. If the frictional force is 8 N, calculate the acceleration. *(5 marks)*

---

**Q2.** (a) Define the terms "momentum" and "impulse". *(4 marks)*

(b) A ball of mass 0.2 kg moving at 5 m/s strikes a wall and rebounds at 4 m/s. Calculate the impulse. *(4 marks)*

(c) State the principle of conservation of momentum. *(2 marks)*

---

**Q3.** (a) A projectile is fired at 50 m/s at an angle of $30^\circ$ to the horizontal. Calculate the time of flight. *(4 marks)*

(b) Calculate the maximum height reached. *(4 marks)*

(c) Calculate the horizontal range. *(4 marks)*

---

**Q4.** (a) A particle moves in a straight line with acceleration $a = 2t$ m/s². Given that its velocity is 3 m/s when $t = 0$, find its velocity at time $t$. *(4 marks)*

(b) Find its displacement at time $t$ given that it starts from the origin. *(4 marks)*

(c) Find the displacement when $t = 3$ s. *(3 marks)*

---

**Q5.** (a) State the principle of moments. *(2 marks)*

(b) A uniform rod AB of length 4 m and weight 40 N is pivoted at its centre. A weight of 20 N is placed at A. Calculate the force needed at B to balance the rod. *(5 marks)*

(c) A uniform ladder of weight 200 N rests against a smooth vertical wall. Find the reactions at the wall and the ground. *(6 marks)*

---

**Q6.** (a) Define the terms "centre of mass" and "centre of gravity". *(4 marks)*

(b) Find the centre of mass of a uniform triangular lamina. *(4 marks)*

(c) A uniform rod of length 6 m and weight 60 N has a 30 N weight attached at one end. Find the position of the centre of mass. *(5 marks)*

---

**Q7.** (a) Define the term "work done". *(2 marks)*

(b) A force of 30 N acts at an angle of $60^\circ$ to the direction of motion. Calculate the work done in moving the body 10 m. *(4 marks)*

(c) A body of mass 4 kg is raised through 5 m. Calculate the work done against gravity. (Take $g = 10$ m/s²) *(4 marks)*

---

**Q8.** (a) State the work-energy theorem. *(2 marks)*

(b) A body of mass 2 kg moving at 4 m/s is brought to rest by a constant force. Calculate the work done. *(4 marks)*

(c) A car of mass 1000 kg accelerates from 10 m/s to 20 m/s. Calculate the work done. *(5 marks)*

---

**Q9.** (a) Define the terms "kinetic energy" and "potential energy". *(4 marks)*

(b) A body of mass 3 kg is projected vertically upwards with a speed of 20 m/s. Calculate its maximum height. (Take $g = 10$ m/s²) *(5 marks)*

(c) Calculate the kinetic energy of the body when it has risen 10 m. *(5 marks)*

---

**Q10.** (a) Define the term "power". *(2 marks)*

(b) A motor lifts a load of 500 kg through 20 m in 25 s. Calculate the power output. (Take $g = 10$ m/s²) *(5 marks)*

(c) A car of mass 1200 kg moves at a constant speed of 30 m/s against a resistance of 400 N. Calculate the power developed. *(5 marks)*

---

**Q11.** (a) Define the terms "discrete" and "continuous" random variables. *(4 marks)*

(b) A discrete random variable $X$ has the probability distribution $P(X = x) = kx$ for $x = 1, 2, 3, 4$. Find $k$. *(4 marks)*

(c) Find $E(X)$ and $Var(X)$ for this distribution. *(5 marks)*

---

**Q12.** (a) State the conditions for a binomial distribution. *(3 marks)*

(b) A fair coin is tossed 10 times. Find the probability of getting exactly 6 heads. *(4 marks)*

(c) Find the mean and variance of this binomial distribution. *(3 marks)*

---

**Q13.** (a) State the probability density function of a normal distribution. *(2 marks)*

(b) Given that $X \sim N(50, 16)$, find $P(46 < X < 54)$. *(5 marks)*

(c) Find the value of $x$ such that $P(X < x) = 0.95$. *(5 marks)*

---

**Q14.** (a) Define the term "Poisson distribution". *(2 marks)*

(b) The number of accidents per day at a junction follows a Poisson distribution with mean 2. Find the probability of exactly 3 accidents in a day. *(4 marks)*

(c) Find the probability of at least 1 accident in a day. *(4 marks)*

---

**Q15.** (a) Define the terms "population" and "sample". *(4 marks)*

(b) State three methods of sampling. *(3 marks)*

(c) Explain the difference between a parameter and a statistic. *(4 marks)*

---

**Q16.** (a) Define the term "confidence interval". *(2 marks)*

(b) A sample of 100 students has a mean score of 60 with a standard deviation of 8. Construct a 95% confidence interval for the population mean. *(6 marks)*

(c) State the effect of increasing the sample size on the confidence interval. *(3 marks)*

---

**Q17.** (a) State the null and alternative hypotheses for a two-tailed test of a population mean. *(4 marks)*

(b) A sample of 50 items has a mean of 102 and standard deviation 10. Test at the 5% level whether the population mean differs from 100. *(6 marks)*

---

**Q18.** (a) Define the term "correlation". *(2 marks)*

(b) Calculate the Pearson correlation coefficient for the data: $x = 1, 2, 3, 4, 5$; $y = 2, 4, 5, 4, 5$. *(6 marks)*

(c) Interpret your result. *(3 marks)*

---

**Q19.** (a) Define the term "regression". *(2 marks)*

(b) Find the equation of the least squares regression line of $y$ on $x$ for the data: $x = 1, 2, 3, 4, 5$; $y = 2, 4, 5, 4, 5$. *(6 marks)*

(c) Estimate $y$ when $x = 6$. *(3 marks)*

---

**Q20.** (a) Define the term "probability". *(2 marks)*

(b) Two dice are thrown. Find the probability that the sum is 7. *(4 marks)*

(c) A bag contains 3 red and 5 blue balls. Two balls are drawn without replacement. Find the probability that both are red. *(5 marks)*
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds Further Mathematics topic-wise hard structural paper set 7 (Mechanics and statistics)'
),
(
  '87de72e2-2c8f-561e-a868-f56d38e9426b',
  'furthermath-pure',
  'Further Mathematics',
  'CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P2 SET 8',
  'english',
  'advanced',
  array['upper_sixth']::text[],
  array['a_science']::text[],
  'published',
  $md$
# CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P2 SET 8

## Structural Question Bank — Pure mathematics

**Level:** Advanced Level
**Class:** UPPER SIXTH
**Series:** a_science
**Subject:** Further Mathematics

**Instructions:**

- Answer all questions in a clear and organized manner.
- Show all working where calculations are required.
- Use correct subject terminology and Cameroon GCE presentation standards.
- Diagrams, tables, maps, labelled sketches, and examples should be included where useful.

---

## SECTION 1: PURE MATHEMATICS

**Q1.** (a) Express $z = 3 + 4i$ in modulus-argument form. *(4 marks)*

(b) Find the modulus and argument of $z^2$. *(4 marks)*

(c) Solve the equation $z^2 + 2z + 5 = 0$, giving your answers in the form $a + bi$. *(4 marks)*

---

**Q2.** (a) Given $z_1 = 2 + 3i$ and $z_2 = 1 - i$, find $z_1 z_2$ and $\frac{z_1}{z_2}$. *(6 marks)*

(b) Find the square roots of $-8 + 6i$. *(6 marks)*

---

**Q3.** (a) Express $z = 2(\cos 60^\circ + i\sin 60^\circ)$ in the form $a + bi$. *(3 marks)*

(b) Use De Moivre's theorem to find $(1 + i)^8$. *(5 marks)*

(c) Solve $z^3 = 8$, giving all three roots. *(5 marks)*

---

**Q4.** (a) State the conditions for two matrices to be multiplied. *(2 marks)*

(b) Given $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ and $B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}$, find $AB$ and $BA$. *(6 marks)*

(c) Show that $AB \neq BA$. *(2 marks)*

---

**Q5.** (a) Find the determinant and inverse of $A = \begin{pmatrix} 2 & 3 \\ 1 & 4 \end{pmatrix}$. *(5 marks)*

(b) Use the inverse matrix method to solve the simultaneous equations $2x + 3y = 7$ and $x + 4y = 6$. *(5 marks)*

---

**Q6.** (a) Find the eigenvalues and eigenvectors of $A = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$. *(6 marks)*

(b) State the trace and determinant of $A$. *(2 marks)*

(c) Verify that the sum of the eigenvalues equals the trace. *(2 marks)*

---

**Q7.** (a) Given $\mathbf{a} = 2\mathbf{i} + 3\mathbf{j} - \mathbf{k}$ and $\mathbf{b} = \mathbf{i} - 2\mathbf{j} + 4\mathbf{k}$, find $\mathbf{a} \cdot \mathbf{b}$. *(3 marks)*

(b) Find the angle between $\mathbf{a}$ and $\mathbf{b}$. *(4 marks)*

(c) Find $\mathbf{a} \times \mathbf{b}$. *(4 marks)*

---

**Q8.** (a) Find the equation of the plane passing through the points $(1, 2, 3)$, $(2, 0, 1)$, and $(0, 1, 2)$. *(6 marks)*

(b) Find the distance from the point $(1, 1, 1)$ to this plane. *(4 marks)*

---

**Q9.** (a) Prove by induction that $1^2 + 2^2 + 3^2 + \cdots + n^2 = \frac{n(n+1)(2n+1)}{6}$. *(6 marks)*

(b) Prove by induction that $3^n > n^2$ for all positive integers $n$. *(5 marks)*

---

**Q10.** (a) Prove by contradiction that $\sqrt{2}$ is irrational. *(5 marks)*

(b) Prove that the sum of two odd numbers is even. *(3 marks)*

(c) Prove that $n^3 - n$ is divisible by 6 for all positive integers $n$. *(5 marks)*

---

**Q11.** (a) Find the sum of the series $1 + 2 + 3 + \cdots + n$. *(3 marks)*

(b) Find the sum of the series $1^2 + 3^2 + 5^2 + \cdots + (2n-1)^2$. *(5 marks)*

(c) Determine whether the series $\sum_{n=1}^{\infty} \frac{1}{n(n+1)}$ converges, and find its sum. *(5 marks)*

---

**Q12.** (a) State the binomial theorem. *(2 marks)*

(b) Expand $(1 + x)^{10}$ up to the term in $x^3$. *(4 marks)*

(c) Find the coefficient of $x^5$ in the expansion of $(2 - 3x)^8$. *(5 marks)*

---

**Q13.** (a) Find the first three terms in the binomial expansion of $\frac{1}{\sqrt{1 + x}}$ for $|x| < 1$. *(5 marks)*

(b) Use your expansion to approximate $\frac{1}{\sqrt{1.1}}$. *(3 marks)*

(c) State the range of validity of the expansion. *(2 marks)*

---

**Q14.** (a) Find the general solution of the differential equation $\frac{dy}{dx} = \frac{y}{x}$. *(4 marks)*

(b) Solve the differential equation $\frac{dy}{dx} + 2y = e^{-x}$ given that $y = 1$ when $x = 0$. *(6 marks)*

---

**Q15.** (a) Solve the differential equation $\frac{d^2y}{dx^2} - 3\frac{dy}{dx} + 2y = 0$. *(5 marks)*

(b) Given that $y = 1$ and $\frac{dy}{dx} = 0$ when $x = 0$, find the particular solution. *(4 marks)*

---

**Q16.** (a) Express $f(x) = \frac{3x + 1}{(x-1)(x+2)}$ in partial fractions. *(5 marks)*

(b) Express $\frac{2x^2 + 3x + 1}{(x+1)(x^2 + 1)}$ in partial fractions. *(6 marks)*

---

**Q17.** (a) Find the roots of the equation $x^3 - 6x^2 + 11x - 6 = 0$. *(5 marks)*

(b) Given that $1 - i$ is a root of $x^3 - 3x^2 + 4x - 2 = 0$, find the other roots. *(5 marks)*

---

**Q18.** (a) State the remainder theorem. *(2 marks)*

(b) Find the remainder when $x^4 - 3x^3 + 2x - 1$ is divided by $x - 2$. *(4 marks)*

(c) Given that $x - 1$ is a factor of $x^3 + ax^2 + bx - 6$, and the remainder is 4 when divided by $x - 2$, find $a$ and $b$. *(6 marks)*

---

**Q19.** (a) Find $\lim_{x \to 0} \frac{\sin 3x}{x}$. *(3 marks)*

(b) Find $\lim_{x \to \infty} \frac{3x^2 + 2x}{x^2 - 1}$. *(3 marks)*

(c) Find $\lim_{x \to 0} \frac{e^x - 1}{x}$. *(3 marks)*

---

**Q20.** (a) Find the sum to infinity of the geometric series $1 + \frac{1}{2} + \frac{1}{4} + \cdots$. *(3 marks)*

(b) Find the sum of the first $n$ terms of the arithmetic series $3 + 7 + 11 + \cdots$. *(4 marks)*

(c) The sum of the first $n$ terms of a series is $n^2 + 3n$. Find the $n$th term. *(4 marks)*
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds Further Mathematics topic-wise hard structural paper set 8 (Pure mathematics)'
),
(
  '7389e474-70ee-5a68-b638-d4d3acf298b9',
  'furthermath-pure',
  'Further Mathematics',
  'CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P1 SET 1',
  'english',
  'advanced',
  array['upper_sixth']::text[],
  array['a_science']::text[],
  'published',
  $md$
# CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P1 SET 1

## Multiple Choice Question Bank

**Level:** Advanced Level
**Class:** UPPER SIXTH
**Series:** a_science
**Subject:** Further Mathematics

**Instructions:**

- Choose the correct option A, B, C or D for each question.
- Record your answers clearly on the answer sheet provided.
- Each question carries equal marks. No marks is deducted for wrong answers.
- Use the answer key at the end of the paper to check your responses.

---

## QUESTIONS

**Q1.** The modulus of $3 + 4i$ is:

A. 5  
B. 7  
C. 1  
D. 25  

---

**Q2.** The argument of $1 + i$ is:

A. 45°  
B. 90°  
C. 30°  
D. 135°  

---

**Q3.** The complex conjugate of $2 - 3i$ is:

A. 2 + 3i  
B. -2 + 3i  
C. 2 - 3i  
D. -2 - 3i  

---

**Q4.** The product $(1 + i)(1 - i)$ equals:

A. 2  
B. 1  
C. -2  
D. 0  

---

**Q5.** The roots of $z^2 + 4 = 0$ are:

A. ±2i  
B. ±4  
C. ±2  
D. ±4i  

---

**Q6.** The value of $i^2$ is:

A. -1  
B. -i  
C. i  
D. 1  

---

**Q7.** The value of $i^4$ is:

A. -1  
B. 1  
C. i  
D. -i  

---

**Q8.** The determinant of $\begin{pmatrix} 2 & 3 \\ 1 & 4 \end{pmatrix}$ is:

A. 11  
B. 5  
C. 6  
D. 10  

---

**Q9.** The inverse of $\begin{pmatrix} 2 & 0 \\ 0 & 4 \end{pmatrix}$ is:

A. $\begin{pmatrix} 2 & 0 \\ 0 & 4 \end{pmatrix}$  
B. $\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$  
C. $\begin{pmatrix} 1/2 & 0 \\ 0 & 1/4 \end{pmatrix}$  
D. $\begin{pmatrix} 0 & 2 \\ 4 & 0 \end{pmatrix}$  

---

**Q10.** The trace of $\begin{pmatrix} 2 & 3 \\ 1 & 4 \end{pmatrix}$ is:

A. 5  
B. 11  
C. 10  
D. 6  

---

**Q11.** The eigenvalues of $\begin{pmatrix} 2 & 0 \\ 0 & 3 \end{pmatrix}$ are:

A. 5 and 6  
B. 0 and 1  
C. 2 and 3  
D. 1 and 2  

---

**Q12.** The dot product of $\mathbf{i} + 2\mathbf{j}$ and $2\mathbf{i} + 3\mathbf{j}$ is:

A. 7  
B. 5  
C. 6  
D. 8  

---

**Q13.** The vectors $\mathbf{a} = 2\mathbf{i} + \mathbf{j}$ and $\mathbf{b} = \mathbf{i} - 2\mathbf{j}$ are:

A. equal  
B. perpendicular  
C. parallel  
D. opposite  

---

**Q14.** The sum $1 + 2 + 3 + \cdots + n$ equals:

A. $n^2$  
B. $\frac{n(n+1)}{2}$  
C. $\frac{n(n+1)(2n+1)}{6}$  
D. $\frac{n(n-1)}{2}$  

---

**Q15.** The sum $1^2 + 2^2 + \cdots + n^2$ equals:

A. $n^3$  
B. $\frac{n(n+1)}{2}$  
C. $\frac{n(n+1)(2n+1)}{6}$  
D. $\frac{n^2(n+1)}{2}$  

---

**Q16.** The sum to infinity of $1 + \frac{1}{2} + \frac{1}{4} + \cdots$ is:

A. 3  
B. 1  
C. $\frac{3}{2}$  
D. 2  

---

**Q17.** The coefficient of $x^2$ in $(1 + x)^4$ is:

A. 12  
B. 8  
C. 6  
D. 4  

---

**Q18.** The remainder when $x^3 - 2x + 1$ is divided by $x - 1$ is:

A. 2  
B. -1  
C. 1  
D. 0  

---

**Q19.** Given that $x - 1$ is a factor of $x^3 - 1$, the other factor is:

A. $x^2 - 1$  
B. $x^2 + x + 1$  
C. $x^2 - x + 1$  
D. $x^2 + 1$  

---

**Q20.** The value of $\lim_{x \to 0} \frac{\sin x}{x}$ is:

A. undefined  
B. 1  
C. ∞  
D. 0  

---

**Q21.** The value of $\lim_{x \to \infty} \frac{1}{x}$ is:

A. undefined  
B. 1  
C. 0  
D. ∞  

---

**Q22.** The general solution of $\frac{dy}{dx} = \frac{y}{x}$ is:

A. $y = e^{kx}$  
B. $y = k/x$  
C. $y = kx^2$  
D. $y = kx$  

---

**Q23.** The roots of $x^2 - 5x + 6 = 0$ are:

A. 5 and 6  
B. -2 and -3  
C. 2 and 3  
D. 1 and 6  

---

**Q24.** The sum of the roots of $x^2 - 5x + 6 = 0$ is:

A. -6  
B. -5  
C. 6  
D. 5  

---

**Q25.** The product of the roots of $x^2 - 5x + 6 = 0$ is:

A. 6  
B. 5  
C. -6  
D. -5  

---

**Q26.** The partial fractions of $\frac{1}{(x-1)(x+1)}$ are:

A. $\frac{1/2}{x-1} - \frac{1/2}{x+1}$  
B. $\frac{1}{x-1} + \frac{1}{x+1}$  
C. $\frac{1}{x-1} - \frac{1}{x+1}$  
D. $\frac{1/2}{x-1} + \frac{1/2}{x+1}$  

---

**Q27.** The value of $(1 + i)^2$ is:

A. 2i  
B. -2i  
C. 2  
D. -2  

---

**Q28.** The value of $(1 + i)^4$ is:

A. -4  
B. 4i  
C. -4i  
D. 4  

---

**Q29.** The modulus of $\frac{1}{i}$ is:

A. 1  
B. -1  
C. 0  
D. i  

---

**Q30.** The argument of $-1$ is:

A. 180°  
B. 270°  
C. 90°  
D. 0°  

---

**Q31.** The SI unit of force is the:

A. joule  
B. newton  
C. watt  
D. pascal  

---

**Q32.** The SI unit of momentum is:

A. kg m/s²  
B. kg m/s  
C. J  
D. N m  

---

**Q33.** The SI unit of impulse is:

A. N m  
B. J  
C. N s  
D. W  

---

**Q34.** The acceleration of a body of mass 2 kg under a force of 10 N is:

A. 2 m/s²  
B. 20 m/s²  
C. 0.2 m/s²  
D. 5 m/s²  

---

**Q35.** The momentum of a 3 kg body moving at 4 m/s is:

A. 7 kg m/s  
B. 48 kg m/s  
C. 12 kg m/s  
D. 1 kg m/s  

---

**Q36.** The kinetic energy of a 2 kg body moving at 3 m/s is:

A. 6 J  
B. 12 J  
C. 18 J  
D. 9 J  

---

**Q37.** The work done by a force of 10 N moving a body 5 m is:

A. 15 J  
B. 50 J  
C. 2 J  
D. 0.5 J  

---

**Q38.** The power of a machine doing 300 J of work in 10 s is:

A. 3 W  
B. 30 W  
C. 0.03 W  
D. 3000 W  

---

**Q39.** The maximum height reached by a body projected at 20 m/s (g = 10 m/s²) is:

A. 40 m  
B. 10 m  
C. 20 m  
D. 2 m  

---

**Q40.** The time of flight of a projectile fired at 50 m/s at 30° to the horizontal (g = 10 m/s²) is:

A. 2.5 s  
B. 10 s  
C. 50 s  
D. 5 s  

---

**Q41.** The horizontal range of a projectile fired at 50 m/s at 30° (g = 10 m/s²) is:

A. 250 m  
B. 433 m  
C. 216.5 m  
D. 125 m  

---

**Q42.** A uniform rod is balanced at its centre. The principle of moments states:

A. work = force × distance  
B. power = work ÷ time  
C. sum of forces = 0  
D. sum of clockwise moments = sum of anticlockwise moments  

---

**Q43.** The centre of mass of a uniform rod is at its:

A. centre of gravity of the rod  
B. midpoint  
C. end  
D. one-quarter point  

---

**Q44.** The probability of getting exactly 6 heads in 10 tosses of a fair coin is:

A. $6/10$  
B. $\binom{10}{6}(1/2)^{10}$  
C. $\binom{10}{6}(1/2)^6$  
D. $(1/2)^6$  

---

**Q45.** The mean of a binomial distribution with n = 10 and p = 0.5 is:

A. 0.5  
B. 2.5  
C. 5  
D. 10  

---

**Q46.** The variance of a binomial distribution with n = 10 and p = 0.5 is:

A. 0.5  
B. 5  
C. 10  
D. 2.5  

---

**Q47.** The mean of a Poisson distribution with parameter λ is:

A. 1/λ  
B. √λ  
C. λ  
D. λ²  

---

**Q48.** The variance of a Poisson distribution with parameter λ is:

A. 1/λ  
B. √λ  
C. λ²  
D. λ  

---

**Q49.** For a standard normal distribution, the mean is:

A. 0  
B. 1  
C. 50  
D. 100  

---

**Q50.** For a standard normal distribution, the variance is:

A. 1  
B. 0  
C. 100  
D. 50  

---

**Q51.** The z-score of a value 60 from a normal distribution with mean 50 and standard deviation 5 is:

A. 2  
B. 0.5  
C. 10  
D. 1.2  

---

**Q52.** The 95% confidence interval for a mean uses the z-value:

A. 1.96  
B. 2.58  
C. 0.95  
D. 1.64  

---

**Q53.** The 99% confidence interval for a mean uses the z-value:

A. 2.58  
B. 0.99  
C. 1.96  
D. 1.64  

---

**Q54.** A sample of 100 items has mean 60 and standard deviation 8. The standard error of the mean is:

A. 0.8  
B. 80  
C. 0.08  
D. 8  

---

**Q55.** The Pearson correlation coefficient ranges from:

A. 0 to 1  
B. -1 to 1  
C. -∞ to ∞  
D. 0 to 100  

---

**Q56.** A correlation coefficient of 0 indicates:

A. perfect positive correlation  
B. no linear correlation  
C. strong correlation  
D. perfect negative correlation  

---

**Q57.** The probability of getting a sum of 7 when two dice are thrown is:

A. 1/36  
B. 7/36  
C. 6/36  
D. 1/6  

---

**Q58.** The probability of drawing a red ball from a bag of 3 red and 5 blue balls is:

A. 5/8  
B. 3/5  
C. 1/8  
D. 3/8  

---

**Q59.** Two events are independent if:

A. P(A∩B) = P(A) + P(B)  
B. P(A) = P(B)  
C. P(A∩B) = P(A)P(B)  
D. P(A∪B) = P(A)P(B)  

---

**Q60.** The probability of an impossible event is:

A. 1  
B. undefined  
C. 0.5  
D. 0  

---

## ANSWER KEY

1. A
2. A
3. A
4. A
5. A
6. A
7. B
8. B
9. C
10. D
11. C
12. D
13. B
14. B
15. C
16. D
17. C
18. D
19. B
20. B
21. C
22. D
23. C
24. D
25. A
26. A
27. A
28. A
29. A
30. A
31. B
32. B
33. C
34. D
35. C
36. D
37. B
38. B
39. C
40. D
41. C
42. D
43. B
44. B
45. C
46. D
47. C
48. D
49. A
50. A
51. A
52. A
53. A
54. A
55. B
56. B
57. C
58. D
59. C
60. D
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds Further Mathematics MCQ practice paper set 1 (60 questions)'
),
(
  'f6fd628e-e6c0-5121-9cfa-9de8b474d9f7',
  'furthermath-pure',
  'Further Mathematics',
  'CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P1 SET 2',
  'english',
  'advanced',
  array['upper_sixth']::text[],
  array['a_science']::text[],
  'published',
  $md$
# CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P1 SET 2

## Multiple Choice Question Bank

**Level:** Advanced Level
**Class:** UPPER SIXTH
**Series:** a_science
**Subject:** Further Mathematics

**Instructions:**

- Choose the correct option A, B, C or D for each question.
- Record your answers clearly on the answer sheet provided.
- Each question carries equal marks. No marks is deducted for wrong answers.
- Use the answer key at the end of the paper to check your responses.

---

## QUESTIONS

**Q1.** The product $(1 + i)(1 - i)$ equals:

A. 2  
B. 0  
C. 1  
D. -2  

---

**Q2.** The roots of $z^2 + 4 = 0$ are:

A. ±2i  
B. ±2  
C. ±4  
D. ±4i  

---

**Q3.** The value of $i^2$ is:

A. -1  
B. i  
C. 1  
D. -i  

---

**Q4.** The value of $i^4$ is:

A. 1  
B. i  
C. -i  
D. -1  

---

**Q5.** The determinant of $\begin{pmatrix} 2 & 3 \\ 1 & 4 \end{pmatrix}$ is:

A. 5  
B. 6  
C. 11  
D. 10  

---

**Q6.** The inverse of $\begin{pmatrix} 2 & 0 \\ 0 & 4 \end{pmatrix}$ is:

A. $\begin{pmatrix} 1/2 & 0 \\ 0 & 1/4 \end{pmatrix}$  
B. $\begin{pmatrix} 0 & 2 \\ 4 & 0 \end{pmatrix}$  
C. $\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$  
D. $\begin{pmatrix} 2 & 0 \\ 0 & 4 \end{pmatrix}$  

---

**Q7.** The trace of $\begin{pmatrix} 2 & 3 \\ 1 & 4 \end{pmatrix}$ is:

A. 5  
B. 6  
C. 11  
D. 10  

---

**Q8.** The eigenvalues of $\begin{pmatrix} 2 & 0 \\ 0 & 3 \end{pmatrix}$ are:

A. 5 and 6  
B. 2 and 3  
C. 0 and 1  
D. 1 and 2  

---

**Q9.** The dot product of $\mathbf{i} + 2\mathbf{j}$ and $2\mathbf{i} + 3\mathbf{j}$ is:

A. 7  
B. 6  
C. 8  
D. 5  

---

**Q10.** The vectors $\mathbf{a} = 2\mathbf{i} + \mathbf{j}$ and $\mathbf{b} = \mathbf{i} - 2\mathbf{j}$ are:

A. parallel  
B. equal  
C. opposite  
D. perpendicular  

---

**Q11.** The sum $1 + 2 + 3 + \cdots + n$ equals:

A. $\frac{n(n-1)}{2}$  
B. $\frac{n(n+1)(2n+1)}{6}$  
C. $\frac{n(n+1)}{2}$  
D. $n^2$  

---

**Q12.** The sum $1^2 + 2^2 + \cdots + n^2$ equals:

A. $\frac{n(n+1)}{2}$  
B. $\frac{n^2(n+1)}{2}$  
C. $n^3$  
D. $\frac{n(n+1)(2n+1)}{6}$  

---

**Q13.** The sum to infinity of $1 + \frac{1}{2} + \frac{1}{4} + \cdots$ is:

A. 3  
B. 2  
C. 1  
D. $\frac{3}{2}$  

---

**Q14.** The coefficient of $x^2$ in $(1 + x)^4$ is:

A. 12  
B. 6  
C. 8  
D. 4  

---

**Q15.** The remainder when $x^3 - 2x + 1$ is divided by $x - 1$ is:

A. 2  
B. 1  
C. 0  
D. -1  

---

**Q16.** Given that $x - 1$ is a factor of $x^3 - 1$, the other factor is:

A. $x^2 + 1$  
B. $x^2 - x + 1$  
C. $x^2 - 1$  
D. $x^2 + x + 1$  

---

**Q17.** The value of $\lim_{x \to 0} \frac{\sin x}{x}$ is:

A. ∞  
B. undefined  
C. 1  
D. 0  

---

**Q18.** The value of $\lim_{x \to \infty} \frac{1}{x}$ is:

A. ∞  
B. undefined  
C. 1  
D. 0  

---

**Q19.** The general solution of $\frac{dy}{dx} = \frac{y}{x}$ is:

A. $y = e^{kx}$  
B. $y = kx$  
C. $y = k/x$  
D. $y = kx^2$  

---

**Q20.** The roots of $x^2 - 5x + 6 = 0$ are:

A. 5 and 6  
B. 2 and 3  
C. -2 and -3  
D. 1 and 6  

---

**Q21.** The sum of the roots of $x^2 - 5x + 6 = 0$ is:

A. -6  
B. 6  
C. 5  
D. -5  

---

**Q22.** The product of the roots of $x^2 - 5x + 6 = 0$ is:

A. -5  
B. 5  
C. -6  
D. 6  

---

**Q23.** The partial fractions of $\frac{1}{(x-1)(x+1)}$ are:

A. $\frac{1}{x-1} - \frac{1}{x+1}$  
B. $\frac{1/2}{x-1} + \frac{1/2}{x+1}$  
C. $\frac{1/2}{x-1} - \frac{1/2}{x+1}$  
D. $\frac{1}{x-1} + \frac{1}{x+1}$  

---

**Q24.** The value of $(1 + i)^2$ is:

A. -2  
B. -2i  
C. 2  
D. 2i  

---

**Q25.** The value of $(1 + i)^4$ is:

A. -4  
B. 4  
C. 4i  
D. -4i  

---

**Q26.** The modulus of $\frac{1}{i}$ is:

A. 1  
B. 0  
C. -1  
D. i  

---

**Q27.** The argument of $-1$ is:

A. 180°  
B. 90°  
C. 0°  
D. 270°  

---

**Q28.** The modulus of $3 + 4i$ is:

A. 5  
B. 1  
C. 25  
D. 7  

---

**Q29.** The argument of $1 + i$ is:

A. 45°  
B. 30°  
C. 90°  
D. 135°  

---

**Q30.** The complex conjugate of $2 - 3i$ is:

A. 2 + 3i  
B. -2 - 3i  
C. -2 + 3i  
D. 2 - 3i  

---

**Q31.** The acceleration of a body of mass 2 kg under a force of 10 N is:

A. 2 m/s²  
B. 5 m/s²  
C. 20 m/s²  
D. 0.2 m/s²  

---

**Q32.** The momentum of a 3 kg body moving at 4 m/s is:

A. 7 kg m/s  
B. 12 kg m/s  
C. 48 kg m/s  
D. 1 kg m/s  

---

**Q33.** The kinetic energy of a 2 kg body moving at 3 m/s is:

A. 6 J  
B. 18 J  
C. 9 J  
D. 12 J  

---

**Q34.** The work done by a force of 10 N moving a body 5 m is:

A. 2 J  
B. 15 J  
C. 0.5 J  
D. 50 J  

---

**Q35.** The power of a machine doing 300 J of work in 10 s is:

A. 3000 W  
B. 0.03 W  
C. 30 W  
D. 3 W  

---

**Q36.** The maximum height reached by a body projected at 20 m/s (g = 10 m/s²) is:

A. 10 m  
B. 2 m  
C. 40 m  
D. 20 m  

---

**Q37.** The time of flight of a projectile fired at 50 m/s at 30° to the horizontal (g = 10 m/s²) is:

A. 2.5 s  
B. 5 s  
C. 10 s  
D. 50 s  

---

**Q38.** The horizontal range of a projectile fired at 50 m/s at 30° (g = 10 m/s²) is:

A. 250 m  
B. 216.5 m  
C. 433 m  
D. 125 m  

---

**Q39.** A uniform rod is balanced at its centre. The principle of moments states:

A. work = force × distance  
B. sum of forces = 0  
C. sum of clockwise moments = sum of anticlockwise moments  
D. power = work ÷ time  

---

**Q40.** The centre of mass of a uniform rod is at its:

A. one-quarter point  
B. end  
C. centre of gravity of the rod  
D. midpoint  

---

**Q41.** The probability of getting exactly 6 heads in 10 tosses of a fair coin is:

A. $\binom{10}{6}(1/2)^6$  
B. $6/10$  
C. $\binom{10}{6}(1/2)^{10}$  
D. $(1/2)^6$  

---

**Q42.** The mean of a binomial distribution with n = 10 and p = 0.5 is:

A. 10  
B. 0.5  
C. 2.5  
D. 5  

---

**Q43.** The variance of a binomial distribution with n = 10 and p = 0.5 is:

A. 0.5  
B. 2.5  
C. 5  
D. 10  

---

**Q44.** The mean of a Poisson distribution with parameter λ is:

A. 1/λ  
B. λ  
C. √λ  
D. λ²  

---

**Q45.** The variance of a Poisson distribution with parameter λ is:

A. 1/λ  
B. λ²  
C. λ  
D. √λ  

---

**Q46.** For a standard normal distribution, the mean is:

A. 100  
B. 1  
C. 50  
D. 0  

---

**Q47.** For a standard normal distribution, the variance is:

A. 100  
B. 50  
C. 1  
D. 0  

---

**Q48.** The z-score of a value 60 from a normal distribution with mean 50 and standard deviation 5 is:

A. 1.2  
B. 0.5  
C. 10  
D. 2  

---

**Q49.** The 95% confidence interval for a mean uses the z-value:

A. 1.96  
B. 1.64  
C. 2.58  
D. 0.95  

---

**Q50.** The 99% confidence interval for a mean uses the z-value:

A. 2.58  
B. 1.96  
C. 0.99  
D. 1.64  

---

**Q51.** A sample of 100 items has mean 60 and standard deviation 8. The standard error of the mean is:

A. 0.8  
B. 0.08  
C. 8  
D. 80  

---

**Q52.** The Pearson correlation coefficient ranges from:

A. -1 to 1  
B. -∞ to ∞  
C. 0 to 100  
D. 0 to 1  

---

**Q53.** A correlation coefficient of 0 indicates:

A. no linear correlation  
B. strong correlation  
C. perfect positive correlation  
D. perfect negative correlation  

---

**Q54.** The probability of getting a sum of 7 when two dice are thrown is:

A. 6/36  
B. 1/6  
C. 7/36  
D. 1/36  

---

**Q55.** The probability of drawing a red ball from a bag of 3 red and 5 blue balls is:

A. 5/8  
B. 3/8  
C. 3/5  
D. 1/8  

---

**Q56.** Two events are independent if:

A. P(A∩B) = P(A) + P(B)  
B. P(A∩B) = P(A)P(B)  
C. P(A) = P(B)  
D. P(A∪B) = P(A)P(B)  

---

**Q57.** The probability of an impossible event is:

A. 1  
B. 0.5  
C. 0  
D. undefined  

---

**Q58.** The probability of a certain event is:

A. 0  
B. 0.5  
C. undefined  
D. 1  

---

**Q59.** The SI unit of force is the:

A. joule  
B. pascal  
C. newton  
D. watt  

---

**Q60.** The SI unit of momentum is:

A. kg m/s²  
B. J  
C. N m  
D. kg m/s  

---

## ANSWER KEY

1. A
2. A
3. A
4. A
5. A
6. A
7. B
8. B
9. C
10. D
11. C
12. D
13. B
14. B
15. C
16. D
17. C
18. D
19. B
20. B
21. C
22. D
23. C
24. D
25. A
26. A
27. A
28. A
29. A
30. A
31. B
32. B
33. C
34. D
35. C
36. D
37. B
38. B
39. C
40. D
41. C
42. D
43. B
44. B
45. C
46. D
47. C
48. D
49. A
50. A
51. A
52. A
53. A
54. A
55. B
56. B
57. C
58. D
59. C
60. D
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds Further Mathematics MCQ practice paper set 2 (60 questions)'
),
(
  'c71898a5-19f3-52b9-9182-c99ff26447e8',
  'furthermath-pure',
  'Further Mathematics',
  'CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P1 SET 3',
  'english',
  'advanced',
  array['upper_sixth']::text[],
  array['a_science']::text[],
  'published',
  $md$
# CAMEROON GCE ADVANCED LEVEL FURTHER MATHEMATICS P1 SET 3

## Multiple Choice Question Bank

**Level:** Advanced Level
**Class:** UPPER SIXTH
**Series:** a_science
**Subject:** Further Mathematics

**Instructions:**

- Choose the correct option A, B, C or D for each question.
- Record your answers clearly on the answer sheet provided.
- Each question carries equal marks. No marks is deducted for wrong answers.
- Use the answer key at the end of the paper to check your responses.

---

## QUESTIONS

**Q1.** The value of $i^4$ is:

A. 1  
B. -1  
C. i  
D. -i  

---

**Q2.** The determinant of $\begin{pmatrix} 2 & 3 \\ 1 & 4 \end{pmatrix}$ is:

A. 5  
B. 11  
C. 6  
D. 10  

---

**Q3.** The inverse of $\begin{pmatrix} 2 & 0 \\ 0 & 4 \end{pmatrix}$ is:

A. $\begin{pmatrix} 1/2 & 0 \\ 0 & 1/4 \end{pmatrix}$  
B. $\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$  
C. $\begin{pmatrix} 2 & 0 \\ 0 & 4 \end{pmatrix}$  
D. $\begin{pmatrix} 0 & 2 \\ 4 & 0 \end{pmatrix}$  

---

**Q4.** The trace of $\begin{pmatrix} 2 & 3 \\ 1 & 4 \end{pmatrix}$ is:

A. 6  
B. 11  
C. 10  
D. 5  

---

**Q5.** The eigenvalues of $\begin{pmatrix} 2 & 0 \\ 0 & 3 \end{pmatrix}$ are:

A. 2 and 3  
B. 0 and 1  
C. 5 and 6  
D. 1 and 2  

---

**Q6.** The dot product of $\mathbf{i} + 2\mathbf{j}$ and $2\mathbf{i} + 3\mathbf{j}$ is:

A. 8  
B. 5  
C. 6  
D. 7  

---

**Q7.** The vectors $\mathbf{a} = 2\mathbf{i} + \mathbf{j}$ and $\mathbf{b} = \mathbf{i} - 2\mathbf{j}$ are:

A. parallel  
B. perpendicular  
C. equal  
D. opposite  

---

**Q8.** The sum $1 + 2 + 3 + \cdots + n$ equals:

A. $\frac{n(n-1)}{2}$  
B. $\frac{n(n+1)}{2}$  
C. $\frac{n(n+1)(2n+1)}{6}$  
D. $n^2$  

---

**Q9.** The sum $1^2 + 2^2 + \cdots + n^2$ equals:

A. $\frac{n(n+1)}{2}$  
B. $n^3$  
C. $\frac{n(n+1)(2n+1)}{6}$  
D. $\frac{n^2(n+1)}{2}$  

---

**Q10.** The sum to infinity of $1 + \frac{1}{2} + \frac{1}{4} + \cdots$ is:

A. 1  
B. 3  
C. $\frac{3}{2}$  
D. 2  

---

**Q11.** The coefficient of $x^2$ in $(1 + x)^4$ is:

A. 4  
B. 8  
C. 6  
D. 12  

---

**Q12.** The remainder when $x^3 - 2x + 1$ is divided by $x - 1$ is:

A. 1  
B. -1  
C. 2  
D. 0  

---

**Q13.** Given that $x - 1$ is a factor of $x^3 - 1$, the other factor is:

A. $x^2 + 1$  
B. $x^2 + x + 1$  
C. $x^2 - x + 1$  
D. $x^2 - 1$  

---

**Q14.** The value of $\lim_{x \to 0} \frac{\sin x}{x}$ is:

A. ∞  
B. 1  
C. undefined  
D. 0  

---

**Q15.** The value of $\lim_{x \to \infty} \frac{1}{x}$ is:

A. ∞  
B. 1  
C. 0  
D. undefined  

---

**Q16.** The general solution of $\frac{dy}{dx} = \frac{y}{x}$ is:

A. $y = kx^2$  
B. $y = k/x$  
C. $y = e^{kx}$  
D. $y = kx$  

---

**Q17.** The roots of $x^2 - 5x + 6 = 0$ are:

A. -2 and -3  
B. 5 and 6  
C. 2 and 3  
D. 1 and 6  

---

**Q18.** The sum of the roots of $x^2 - 5x + 6 = 0$ is:

A. -5  
B. -6  
C. 6  
D. 5  

---

**Q19.** The product of the roots of $x^2 - 5x + 6 = 0$ is:

A. -5  
B. 6  
C. 5  
D. -6  

---

**Q20.** The partial fractions of $\frac{1}{(x-1)(x+1)}$ are:

A. $\frac{1}{x-1} - \frac{1}{x+1}$  
B. $\frac{1/2}{x-1} - \frac{1/2}{x+1}$  
C. $\frac{1/2}{x-1} + \frac{1/2}{x+1}$  
D. $\frac{1}{x-1} + \frac{1}{x+1}$  

---

**Q21.** The value of $(1 + i)^2$ is:

A. -2  
B. 2  
C. 2i  
D. -2i  

---

**Q22.** The value of $(1 + i)^4$ is:

A. -4i  
B. 4  
C. 4i  
D. -4  

---

**Q23.** The modulus of $\frac{1}{i}$ is:

A. -1  
B. i  
C. 1  
D. 0  

---

**Q24.** The argument of $-1$ is:

A. 270°  
B. 90°  
C. 0°  
D. 180°  

---

**Q25.** The modulus of $3 + 4i$ is:

A. 5  
B. 7  
C. 1  
D. 25  

---

**Q26.** The argument of $1 + i$ is:

A. 45°  
B. 90°  
C. 30°  
D. 135°  

---

**Q27.** The complex conjugate of $2 - 3i$ is:

A. 2 + 3i  
B. -2 + 3i  
C. 2 - 3i  
D. -2 - 3i  

---

**Q28.** The product $(1 + i)(1 - i)$ equals:

A. 2  
B. 1  
C. -2  
D. 0  

---

**Q29.** The roots of $z^2 + 4 = 0$ are:

A. ±2i  
B. ±4  
C. ±2  
D. ±4i  

---

**Q30.** The value of $i^2$ is:

A. -1  
B. -i  
C. i  
D. 1  

---

**Q31.** The work done by a force of 10 N moving a body 5 m is:

A. 2 J  
B. 50 J  
C. 15 J  
D. 0.5 J  

---

**Q32.** The power of a machine doing 300 J of work in 10 s is:

A. 3000 W  
B. 30 W  
C. 0.03 W  
D. 3 W  

---

**Q33.** The maximum height reached by a body projected at 20 m/s (g = 10 m/s²) is:

A. 10 m  
B. 40 m  
C. 20 m  
D. 2 m  

---

**Q34.** The time of flight of a projectile fired at 50 m/s at 30° to the horizontal (g = 10 m/s²) is:

A. 10 s  
B. 2.5 s  
C. 50 s  
D. 5 s  

---

**Q35.** The horizontal range of a projectile fired at 50 m/s at 30° (g = 10 m/s²) is:

A. 125 m  
B. 433 m  
C. 216.5 m  
D. 250 m  

---

**Q36.** A uniform rod is balanced at its centre. The principle of moments states:

A. sum of forces = 0  
B. power = work ÷ time  
C. work = force × distance  
D. sum of clockwise moments = sum of anticlockwise moments  

---

**Q37.** The centre of mass of a uniform rod is at its:

A. one-quarter point  
B. midpoint  
C. end  
D. centre of gravity of the rod  

---

**Q38.** The probability of getting exactly 6 heads in 10 tosses of a fair coin is:

A. $\binom{10}{6}(1/2)^6$  
B. $\binom{10}{6}(1/2)^{10}$  
C. $6/10$  
D. $(1/2)^6$  

---

**Q39.** The mean of a binomial distribution with n = 10 and p = 0.5 is:

A. 10  
B. 2.5  
C. 5  
D. 0.5  

---

**Q40.** The variance of a binomial distribution with n = 10 and p = 0.5 is:

A. 10  
B. 5  
C. 0.5  
D. 2.5  

---

**Q41.** The mean of a Poisson distribution with parameter λ is:

A. √λ  
B. 1/λ  
C. λ  
D. λ²  

---

**Q42.** The variance of a Poisson distribution with parameter λ is:

A. √λ  
B. 1/λ  
C. λ²  
D. λ  

---

**Q43.** For a standard normal distribution, the mean is:

A. 100  
B. 0  
C. 1  
D. 50  

---

**Q44.** For a standard normal distribution, the variance is:

A. 100  
B. 1  
C. 50  
D. 0  

---

**Q45.** The z-score of a value 60 from a normal distribution with mean 50 and standard deviation 5 is:

A. 1.2  
B. 10  
C. 2  
D. 0.5  

---

**Q46.** The 95% confidence interval for a mean uses the z-value:

A. 0.95  
B. 1.64  
C. 2.58  
D. 1.96  

---

**Q47.** The 99% confidence interval for a mean uses the z-value:

A. 0.99  
B. 1.64  
C. 2.58  
D. 1.96  

---

**Q48.** A sample of 100 items has mean 60 and standard deviation 8. The standard error of the mean is:

A. 80  
B. 0.08  
C. 8  
D. 0.8  

---

**Q49.** The Pearson correlation coefficient ranges from:

A. -1 to 1  
B. 0 to 1  
C. -∞ to ∞  
D. 0 to 100  

---

**Q50.** A correlation coefficient of 0 indicates:

A. no linear correlation  
B. perfect positive correlation  
C. strong correlation  
D. perfect negative correlation  

---

**Q51.** The probability of getting a sum of 7 when two dice are thrown is:

A. 6/36  
B. 7/36  
C. 1/36  
D. 1/6  

---

**Q52.** The probability of drawing a red ball from a bag of 3 red and 5 blue balls is:

A. 3/8  
B. 3/5  
C. 1/8  
D. 5/8  

---

**Q53.** Two events are independent if:

A. P(A∩B) = P(A)P(B)  
B. P(A) = P(B)  
C. P(A∩B) = P(A) + P(B)  
D. P(A∪B) = P(A)P(B)  

---

**Q54.** The probability of an impossible event is:

A. 0  
B. undefined  
C. 0.5  
D. 1  

---

**Q55.** The probability of a certain event is:

A. 0  
B. 1  
C. 0.5  
D. undefined  

---

**Q56.** The SI unit of force is the:

A. joule  
B. newton  
C. pascal  
D. watt  

---

**Q57.** The SI unit of momentum is:

A. kg m/s²  
B. N m  
C. kg m/s  
D. J  

---

**Q58.** The SI unit of impulse is:

A. N m  
B. J  
C. W  
D. N s  

---

**Q59.** The acceleration of a body of mass 2 kg under a force of 10 N is:

A. 2 m/s²  
B. 0.2 m/s²  
C. 5 m/s²  
D. 20 m/s²  

---

**Q60.** The momentum of a 3 kg body moving at 4 m/s is:

A. 7 kg m/s  
B. 48 kg m/s  
C. 1 kg m/s  
D. 12 kg m/s  

---

## ANSWER KEY

1. A
2. A
3. A
4. A
5. A
6. A
7. B
8. B
9. C
10. D
11. C
12. D
13. B
14. B
15. C
16. D
17. C
18. D
19. B
20. B
21. C
22. D
23. C
24. D
25. A
26. A
27. A
28. A
29. A
30. A
31. B
32. B
33. C
34. D
35. C
36. D
37. B
38. B
39. C
40. D
41. C
42. D
43. B
44. B
45. C
46. D
47. C
48. D
49. A
50. A
51. A
52. A
53. A
54. A
55. B
56. B
57. C
58. D
59. C
60. D
$md$,
  'paper',
  'paper',
  'gce',
  'GCE',
  '2026',
  'teacher_authored',
  'StudySpark authored GCE practice paper',
  'approved',
  'approved',
  '1.0.0',
  'Adds Further Mathematics MCQ practice paper set 3 (60 questions)'
)
on conflict (id) do update set
  topic_id = excluded.topic_id,
  subject = excluded.subject,
  title = excluded.title,
  language = excluded.language,
  level = excluded.level,
  class_levels = excluded.class_levels,
  series = excluded.series,
  status = excluded.status,
  markdown_content = excluded.markdown_content,
  content_kind = excluded.content_kind,
  doc_type = excluded.doc_type,
  curriculum_path = excluded.curriculum_path,
  exam = excluded.exam,
  content_year = excluded.content_year,
  source_type = excluded.source_type,
  source_reference = excluded.source_reference,
  permission_status = excluded.permission_status,
  review_status = excluded.review_status,
  content_version = excluded.content_version,
  change_note = excluded.change_note,
  updated_at = now();

notify pgrst, 'reload schema';

commit;
