#!/usr/bin/env python3
"""
Generate French content for the missing class levels:
- Collège: Sixième, Cinquième, Quatrième (ordinary)
- Lycée: Seconde, Première (advanced)
Core subjects get 3 MCQ + 4 structural sets at each level.
"""

from pathlib import Path

BASE = Path("/home/victoire-ws/Documents/ChatGPT/productivity - goals/study-spark/content/papers")

# (dir, subject, level_label, class, series, exam, level)
CLASSES = [
    # Lycée (advanced) — Seconde & Première (Probatoire)
    ("mathematiques-seconde", "Mathématiques", "Advanced Level (Lycée)", "Seconde", "C, D, E, TI", "Probatoire", "advanced"),
    ("mathematiques-premiere", "Mathématiques", "Advanced Level (Lycée)", "Première", "C, D, E, TI", "Probatoire", "advanced"),
    ("francais-seconde", "Français", "Advanced Level (Lycée)", "Seconde", "A1, A2, A4, ABI, C, D", "Probatoire", "advanced"),
    ("francais-premiere", "Français", "Advanced Level (Lycée)", "Première", "A1, A2, A4, ABI, C, D", "Probatoire", "advanced"),
    ("physique-seconde", "Physique", "Advanced Level (Lycée)", "Seconde", "C, D, E, TI", "Probatoire", "advanced"),
    ("physique-premiere", "Physique", "Advanced Level (Lycée)", "Première", "C, D, E, TI", "Probatoire", "advanced"),
    ("chimie-seconde", "Chimie", "Advanced Level (Lycée)", "Seconde", "C, D, E, TI", "Probatoire", "advanced"),
    ("chimie-premiere", "Chimie", "Advanced Level (Lycée)", "Première", "C, D, E, TI", "Probatoire", "advanced"),
    ("svt-seconde", "Sciences de la Vie et de la Terre", "Advanced Level (Lycée)", "Seconde", "C, D, TI", "Probatoire", "advanced"),
    ("svt-premiere", "Sciences de la Vie et de la Terre", "Advanced Level (Lycée)", "Première", "C, D, TI", "Probatoire", "advanced"),
    ("histoire-geographie-seconde", "Histoire-Géographie", "Advanced Level (Lycée)", "Seconde", "A1, A2, A4, ABI, C, D", "Probatoire", "advanced"),
    ("histoire-geographie-premiere", "Histoire-Géographie", "Advanced Level (Lycée)", "Première", "A1, A2, A4, ABI, C, D", "Probatoire", "advanced"),
    ("informatique-seconde", "Informatique", "Advanced Level (Lycée)", "Seconde", "TI, C, D, E", "Probatoire", "advanced"),
    ("informatique-premiere", "Informatique", "Advanced Level (Lycée)", "Première", "TI, C, D, E", "Probatoire", "advanced"),
    ("philosophie-seconde", "Philosophie", "Advanced Level (Lycée)", "Seconde", "A1, A2, A4, ABI", "Probatoire", "advanced"),
    ("philosophie-premiere", "Philosophie", "Advanced Level (Lycée)", "Première", "A1, A2, A4, ABI", "Probatoire", "advanced"),
]

# Generic MCQ question banks per subject (reused across class levels)
MCQ_BANKS = {
    "Mathématiques": [
        ("Résoudre l'équation : $3x - 7 = 2x + 5$.", ["$x = 12$", "$x = 2$", "$x = -2$", "$x = 5$"], 0),
        ("La valeur de $\\sqrt{144}$ est :", ["12", "14", "11", "13"], 0),
        ("Simplifier : $\\frac{3}{4} + \\frac{5}{6}$.", ["$\\frac{19}{12}$", "$\\frac{8}{10}$", "$\\frac{9}{12}$", "$\\frac{15}{24}$"], 0),
        ("Le PGCD de 24 et 36 est :", ["12", "6", "18", "72"], 0),
        ("Résoudre : $2x + 3 = 15$.", ["$x = 6$", "$x = 9$", "$x = 5$", "$x = 7$"], 0),
        ("$10\\%$ de 250 est :", ["25", "2,5", "250", "50"], 0),
        ("L'aire d'un carré de côté 5 cm est :", ["25 cm²", "20 cm²", "10 cm²", "50 cm²"], 0),
        ("Le volume d'un cube d'arête 3 cm est :", ["27 cm³", "9 cm³", "18 cm³", "12 cm³"], 0),
        ("Résoudre : $x^2 = 49$.", ["$x = 7$ ou $x = -7$", "$x = 7$", "$x = -7$", "$x = 24,5$"], 0),
        ("La médiane de la série 3, 5, 7, 9, 11 est :", ["7", "5", "9", "6"], 0),
        ("$\\frac{2}{3}$ de 90 est :", ["60", "30", "45", "135"], 0),
        ("Le périmètre d'un rectangle de 8 cm sur 5 cm est :", ["26 cm", "40 cm", "13 cm", "80 cm"], 0),
        ("Résoudre le système : $x + y = 10$ et $x - y = 4$.", ["$x = 7$, $y = 3$", "$x = 3$, $y = 7$", "$x = 6$, $y = 4$", "$x = 5$, $y = 5$"], 0),
        ("$3^4$ est égal à :", ["81", "12", "64", "27"], 0),
        ("La moyenne de 4, 6, 8, 10 est :", ["7", "6", "8", "9"], 0),
        ("Un angle droit mesure :", ["90°", "180°", "45°", "360°"], 0),
        ("Résoudre : $5x - 2 = 3x + 8$.", ["$x = 5$", "$x = 3$", "$x = 10$", "$x = 6$"], 0),
        ("Le nombre premier parmi les suivants est :", ["17", "15", "21", "9"], 0),
        ("$\\frac{1}{2} + \\frac{1}{3}$ est égal à :", ["$\\frac{5}{6}$", "$\\frac{2}{5}$", "$\\frac{1}{6}$", "$\\frac{3}{5}$"], 0),
        ("L'équation de la droite passant par l'origine et de pente 2 est :", ["$y = 2x$", "$y = x + 2$", "$y = 2x + 1$", "$x = 2y$"], 0),
        ("Le complément de 35° est :", ["55°", "145°", "65°", "125°"], 0),
        ("$0,5$ en fraction est :", ["$\\frac{1}{2}$", "$\\frac{5}{10}$", "$\\frac{1}{5}$", "$\\frac{2}{5}$"], 0),
        ("Le PPCM de 4 et 6 est :", ["12", "24", "6", "2"], 0),
        ("Résoudre : $\\frac{x}{4} = 3$.", ["$x = 12$", "$x = 7$", "$x = 1$", "$x = 3$"], 0),
        ("L'aire d'un triangle de base 10 cm et hauteur 6 cm est :", ["30 cm²", "60 cm²", "16 cm²", "15 cm²"], 0),
        ("$2^5$ est égal à :", ["32", "25", "10", "16"], 0),
        ("Le plus grand nombre parmi : 0,25 ; 0,5 ; 0,125 ; 0,75 est :", ["0,75", "0,5", "0,25", "0,125"], 0),
        ("Résoudre : $3(x - 2) = 9$.", ["$x = 5$", "$x = 3$", "$x = 11$", "$x = 1$"], 0),
        ("La somme des angles d'un triangle est :", ["180°", "90°", "360°", "270°"], 0),
        ("$\\sqrt{81}$ est égal à :", ["9", "8", "7", "10"], 0),
        ("Le coefficient de $x$ dans $5x + 3$ est :", ["5", "3", "8", "x"], 0),
        ("Résoudre : $x - 8 = 12$.", ["$x = 20$", "$x = 4$", "$x = 96$", "$x = 12$"], 0),
        ("$25\\%$ de 80 est :", ["20", "25", "40", "5"], 0),
        ("Le symétrique de 7 par rapport à 0 est :", ["-7", "7", "0", "14"], 0),
        ("L'aire d'un cercle de rayon 3 cm (π ≈ 3,14) est :", ["28,26 cm²", "18,84 cm²", "9,42 cm²", "56,52 cm²"], 0),
        ("Résoudre : $2x^2 = 32$.", ["$x = 4$ ou $x = -4$", "$x = 4$", "$x = 16$", "$x = 8$"], 0),
        ("Le nombre 0,75 en pourcentage est :", ["75%", "7,5%", "0,75%", "750%"], 0),
        ("La distance entre -3 et 5 sur la droite numérique est :", ["8", "2", "-8", "15"], 0),
        ("$\\frac{7}{8} - \\frac{3}{8}$ est égal à :", ["$\\frac{1}{2}$", "$\\frac{4}{8}$", "$\\frac{10}{8}$", "$\\frac{1}{4}$"], 0),
        ("Le périmètre d'un cercle de rayon 5 cm (π ≈ 3,14) est :", ["31,4 cm", "15,7 cm", "78,5 cm", "25 cm"], 0),
        ("Résoudre : $4x + 1 = 2x + 9$.", ["$x = 4$", "$x = 5$", "$x = 8$", "$x = 2$"], 0),
        ("Le plus petit multiple commun de 3 et 5 est :", ["15", "8", "30", "3"], 0),
        ("$(-3) \\times (-4)$ est égal à :", ["12", "-12", "7", "-7"], 0),
        ("L'aire d'un parallélogramme de base 8 cm et hauteur 5 cm est :", ["40 cm²", "13 cm²", "26 cm²", "80 cm²"], 0),
        ("Résoudre : $\\frac{2x}{3} = 8$.", ["$x = 12$", "$x = 24$", "$x = 6$", "$x = 4$"], 0),
        ("Le nombre 0,2 en fraction irréductible est :", ["$\\frac{1}{5}$", "$\\frac{2}{10}$", "$\\frac{1}{2}$", "$\\frac{2}{5}$"], 0),
        ("La valeur de $5!$ (factorielle) est :", ["120", "25", "15", "720"], 0),
        ("Résoudre : $x + 3 = 2x - 1$.", ["$x = 4$", "$x = 2$", "$x = -4$", "$x = 1$"], 0),
        ("Le PGCD de 18 et 27 est :", ["9", "3", "6", "54"], 0),
        ("L'aire d'un losange de diagonales 6 cm et 8 cm est :", ["24 cm²", "48 cm²", "14 cm²", "28 cm²"], 0),
        ("$\\frac{3}{5}$ de 100 est :", ["60", "40", "35", "65"], 0),
        ("Résoudre : $x^2 - 9 = 0$.", ["$x = 3$ ou $x = -3$", "$x = 3$", "$x = 9$", "$x = 4,5$"], 0),
        ("Le nombre 0,125 en fraction est :", ["$\\frac{1}{8}$", "$\\frac{1}{4}$", "$\\frac{1}{5}$", "$\\frac{1}{12}$"], 0),
        ("La somme de 2,5 et 3,75 est :", ["6,25", "5,25", "6,5", "5,75"], 0),
        ("Résoudre : $7x = 49$.", ["$x = 7$", "$x = 42$", "$x = 56$", "$x = 343$"], 0),
        ("Le volume d'un pavé droit de 4 cm × 3 cm × 2 cm est :", ["24 cm³", "9 cm³", "12 cm³", "48 cm³"], 0),
        ("$\\frac{2}{5} \\times \\frac{3}{4}$ est égal à :", ["$\\frac{3}{10}$", "$\\frac{6}{20}$", "$\\frac{5}{9}$", "$\\frac{1}{10}$"], 0),
        ("Le nombre 0,6 en pourcentage est :", ["60%", "6%", "0,6%", "600%"], 0),
        ("Résoudre : $x + 5 = 2x - 3$.", ["$x = 8$", "$x = 2$", "$x = -8$", "$x = 5$"], 0),
    ],
    "Français": [
        ("Le pluriel de « cheval » est :", ["chevaux", "chevals", "chevaus", "cheveaux"], 0),
        ("Le féminin de « acteur » est :", ["actrice", "acteuse", "actrice", "acteur"], 0),
        ("Le synonyme de « rapide » est :", ["vite", "lent", "lourd", "haut"], 0),
        ("L'antonyme de « chaud » est :", ["froid", "tiède", "brûlant", "doux"], 0),
        ("Le participe passé de « prendre » est :", ["pris", "prendu", "pris", "prenu"], 0),
        ("Le verbe « aller » au futur simple (je) est :", ["j'irai", "j'allai", "j'aille", "j'allais"], 0),
        ("Le verbe « être » au présent (nous) est :", ["nous sommes", "nous étions", "nous serons", "nous soyons"], 0),
        ("Le verbe « avoir » au présent (ils) est :", ["ils ont", "ils avaient", "ils auront", "ils aient"], 0),
        ("La phrase « Il fait beau » est :", ["une phrase déclarative", "une phrase interrogative", "une phrase impérative", "une phrase exclamative"], 0),
        ("La phrase « Viens ici ! » est :", ["impérative", "déclarative", "interrogative", "exclamative"], 0),
        ("Le nom commun de « beau » est :", ["la beauté", "le beau", "la beauté", "le bel"], 0),
        ("Le complément d'objet direct répond à la question :", ["quoi ?", "où ?", "quand ?", "comment ?"], 0),
        ("Le complément circonstanciel de lieu répond à la question :", ["où ?", "quoi ?", "qui ?", "combien ?"], 0),
        ("Le sujet de la phrase « Les enfants jouent » est :", ["les enfants", "jouent", "les", "enfants jouent"], 0),
        ("Le verbe « finir » au passé composé (il) est :", ["il a fini", "il finit", "il finira", "il finissait"], 0),
        ("Le mot « rapidement » est :", ["un adverbe", "un adjectif", "un nom", "un verbe"], 0),
        ("Le mot « joli » est :", ["un adjectif", "un adverbe", "un nom", "un verbe"], 0),
        ("Le mot « table » est :", ["un nom", "un verbe", "un adjectif", "un adverbe"], 0),
        ("Le mot « manger » est :", ["un verbe", "un nom", "un adjectif", "un adverbe"], 0),
        ("La comparaison utilise :", ["comme, tel, semblable à", "mais, ou, et", "car, donc", "ni, or"], 0),
        ("La métaphore est :", ["une comparaison sans outil", "une exagération", "une atténuation", "une répétition"], 0),
        ("L'hyperbole est :", ["une exagération", "une atténuation", "une comparaison", "une répétition"], 0),
        ("La litote est :", ["une atténuation", "une exagération", "une comparaison", "une métaphore"], 0),
        ("La personnification donne :", ["des attributs humains à un objet", "des attributs d'objet à un humain", "des attributs animaux", "aucun attribut"], 0),
        ("Le registre de langue familier utilise :", ["des expressions familières", "un vocabulaire soutenu", "un vocabulaire courant", "des termes techniques"], 0),
        ("Le registre soutenu utilise :", ["un vocabulaire recherché", "des expressions familières", "un langage courant", "de l'argot"], 0),
        ("Le texte narratif :", ["raconte une histoire", "explique une idée", "décrit un lieu", "convainc"], 0),
        ("Le texte argumentatif :", ["convainc et persuade", "raconte une histoire", "décrit", "donne des ordres"], 0),
        ("Le texte descriptif :", ["décrit un lieu, une personne", "raconte", "argumente", "explique"], 0),
        ("Le texte explicatif :", ["explique un phénomène", "raconte", "convainc", "décrit"], 0),
        ("Le discours direct utilise :", ["les guillemets et tirets", "les parenthèses", "les crochets", "les points de suspension"], 0),
        ("Le discours indirect introduit par :", ["que, si, de", "mais, ou", "et, donc", "ni, car"], 0),
        ("Le passé simple est utilisé :", ["dans le récit écrit", "dans la conversation", "au futur", "au présent"], 0),
        ("L'imparfait exprime :", ["une action passée en cours", "une action future", "une action présente", "une action terminée"], 0),
        ("Le futur simple exprime :", ["une action future", "une action passée", "une action présente", "une action habituelle"], 0),
        ("Le conditionnel présent exprime :", ["un souhait, une hypothèse", "une certitude", "un ordre", "une action passée"], 0),
        ("Le subjonctif exprime :", ["le doute, le souhait", "la certitude", "l'ordre", "la réalité"], 0),
        ("Le mot « néanmoins » est :", ["un adverbe de concession", "une conjonction", "un nom", "un adjectif"], 0),
        ("La proposition subordonnée relative est introduite par :", ["qui, que, dont, où", "parce que, si", "et, ou", "mais, donc"], 0),
        ("La proposition subordonnée complétive est introduite par :", ["que", "qui", "dont", "où"], 0),
        ("Le complément du nom est introduit par :", ["de, à, en", "et, ou", "mais, donc", "ni, car"], 0),
        ("L'attribut du sujet se construit avec :", ["être, paraître, sembler", "manger, boire", "courir, sauter", "voir, entendre"], 0),
        ("Le COD se place généralement :", ["après le verbe", "avant le verbe", "au début", "à la fin"], 0),
        ("Le COI est introduit par :", ["à, de", "et, ou", "mais, donc", "ni, car"], 0),
        ("Le mot « où » peut être :", ["un pronom relatif ou un adverbe", "une conjonction", "un nom", "un adjectif"], 0),
        ("La voix passive se forme avec :", ["être + participe passé", "avoir + participe passé", "aller + infinitif", "venir de + infinitif"], 0),
        ("Le participe présent se termine par :", ["-ant", "-é", "-ir", "-re"], 0),
        ("Le gérondif se forme avec :", ["en + participe présent", "avoir + participe passé", "être + participe passé", "aller + infinitif"], 0),
        ("Le mot « cependant » exprime :", ["l'opposition", "la cause", "la conséquence", "le but"], 0),
        ("Le mot « parce que » exprime :", ["la cause", "la conséquence", "l'opposition", "le but"], 0),
        ("Le mot « donc » exprime :", ["la conséquence", "la cause", "l'opposition", "le but"], 0),
        ("Le mot « afin que » exprime :", ["le but", "la cause", "la conséquence", "l'opposition"], 0),
        ("La ponctuation qui marque une pause courte est :", ["la virgule", "le point", "le point-virgule", "les deux-points"], 0),
        ("Le point d'interrogation termine :", ["une phrase interrogative", "une phrase déclarative", "une phrase impérative", "une phrase exclamative"], 0),
        ("Le point d'exclamation termine :", ["une phrase exclamative", "une phrase interrogative", "une phrase déclarative", "une phrase impérative"], 0),
        ("Le mot « hélas » exprime :", ["la tristesse, le regret", "la joie", "la colère", "la surprise"], 0),
        ("Le mot « bravo » exprime :", ["la félicitation", "la tristesse", "la colère", "la peur"], 0),
        ("Le nom « courage » est :", ["abstrait", "concret", "propre", "collectif"], 0),
        ("Le nom « table » est :", ["concret", "abstrait", "propre", "collectif"], 0),
        ("Le nom « Cameroun » est :", ["un nom propre", "un nom commun", "un nom abstrait", "un nom collectif"], 0),
    ],
    "Sciences de la Vie et de la Terre": [
        ("L'unité de base du vivant est :", ["la cellule", "l'atome", "la molécule", "l'organe"], 0),
        ("La photosynthèse se déroule dans :", ["les chloroplastes", "les mitochondries", "le noyau", "la membrane"], 0),
        ("Le dioxygène est produit par :", ["la photosynthèse", "la respiration", "la digestion", "la fermentation"], 0),
        ("L'organe de la respiration chez l'homme est :", ["le poumon", "le cœur", "le foie", "le rein"], 0),
        ("Le sang est pompé par :", ["le cœur", "le poumon", "le cerveau", "le foie"], 0),
        ("L'unité de filtration du rein est :", ["le néphron", "le neurone", "l'alvéole", "le glomérule"], 0),
        ("La cellule nerveuse s'appelle :", ["le neurone", "le néphron", "le globule", "le gamète"], 0),
        ("L'ADN se trouve dans :", ["le noyau", "le cytoplasme", "la membrane", "la paroi"], 0),
        ("La reproduction sexuée fait intervenir :", ["deux gamètes", "un seul gamète", "aucun gamète", "des spores"], 0),
        ("Le gamète mâle chez l'homme est :", ["le spermatozoïde", "l'ovule", "le globule rouge", "le neurone"], 0),
        ("Le gamète femelle chez la femme est :", ["l'ovule", "le spermatozoïde", "le globule blanc", "le neurone"], 0),
        ("L'écosystème est constitué de :", ["le biotope et la biocénose", "uniquement des plantes", "uniquement des animaux", "uniquement de l'eau"], 0),
        ("Le prédateur est un être qui :", ["chasse et se nourrit d'autres êtres", "est chassé", "se nourrit de plantes", "décompose la matière"], 0),
        ("La chaîne alimentaire commence par :", ["un producteur", "un consommateur", "un décomposeur", "un prédateur"], 0),
        ("Le décomposeur transforme la matière organique en :", ["matière minérale", "matière organique", "énergie", "gaz carbonique"], 0),
        ("La fécondation est la fusion de :", ["deux gamètes", "deux cellules somatiques", "deux neurones", "deux globules"], 0),
        ("Le groupe sanguin universel donneur est :", ["O", "A", "B", "AB"], 0),
        ("Le groupe sanguin universel receveur est :", ["AB", "O", "A", "B"], 0),
        ("La vaccination consiste à :", ["injecter un antigène atténué", "injecter des anticorps", "prendre des antibiotiques", "faire une transfusion"], 0),
        ("L'antibiotique agit contre :", ["les bactéries", "les virus", "les parasites", "les champignons"], 0),
        ("Le virus du SIDA s'appelle :", ["le VIH", "le VHB", "le VHC", "le VPH"], 0),
        ("La digestion commence dans :", ["la bouche", "l'estomac", "l'intestin", "l'œsophage"], 0),
        ("L'enzyme digestive de la salive est :", ["l'amylase", "la pepsine", "la lipase", "la trypsine"], 0),
        ("La bile est produite par :", ["le foie", "l'estomac", "le pancréas", "la vésicule"], 0),
        ("L'insuline est produite par :", ["le pancréas", "le foie", "le rein", "la thyroïde"], 0),
        ("Le diabète est dû à un problème de :", ["l'insuline", "l'adrénaline", "la thyroxine", "l'œstrogène"], 0),
        ("La cellule végétale possède en plus de la cellule animale :", ["une paroi et des chloroplastes", "un noyau", "une membrane", "des mitochondries"], 0),
        ("La mitose permet :", ["la division cellulaire", "la formation des gamètes", "la respiration", "la digestion"], 0),
        ("La méiose permet :", ["la formation des gamètes", "la division cellulaire", "la croissance", "la régénération"], 0),
        ("Le chromosome est constitué de :", ["ADN et protéines", "ARN et lipides", "glucides et protéines", "eau et sels minéraux"], 0),
        ("Le nombre de chromosomes chez l'homme est :", ["46", "44", "48", "23"], 0),
        ("Le caryotype humain normal possède :", ["23 paires de chromosomes", "46 paires", "22 paires", "24 paires"], 0),
        ("La transpiration se fait par :", ["la peau", "le rein", "le poumon", "le foie"], 0),
        ("L'homéostasie est :", ["le maintien de l'équilibre interne", "la croissance", "la reproduction", "la digestion"], 0),
        ("Le réflexe est :", ["une réponse rapide et involontaire", "une réponse lente", "une action volontaire", "une pensée"], 0),
        ("L'arc réflexe passe par :", ["la moelle épinière", "le cerveau", "le cervelet", "le bulbe"], 0),
        ("Le cervelet contrôle :", ["l'équilibre", "la mémoire", "la respiration", "la digestion"], 0),
        ("Le bulbe rachidien contrôle :", ["la respiration", "la mémoire", "l'équilibre", "la vision"], 0),
        ("La géologie étudie :", ["la Terre", "les étoiles", "les plantes", "les animaux"], 0),
        ("Les roches magmatiques proviennent :", ["du refroidissement du magma", "de la sédimentation", "du métamorphisme", "de l'érosion"], 0),
        ("Le basalte est une roche :", ["volcanique", "sédimentaire", "métamorphique", "organique"], 0),
        ("Le granite est une roche :", ["plutonique", "volcanique", "sédimentaire", "métamorphique"], 0),
        ("Le calcaire est une roche :", ["sédimentaire", "volcanique", "plutonique", "métamorphique"], 0),
        ("Le fossile est :", ["un reste d'être vivant conservé", "une roche", "un minéral", "un volcan"], 0),
        ("La tectonique des plaques explique :", ["les séismes et volcans", "la photosynthèse", "la digestion", "la respiration"], 0),
        ("Le séisme est dû à :", ["la rupture des roches en profondeur", "la pluie", "le vent", "la chaleur"], 0),
        ("L'échelle de Richter mesure :", ["la magnitude d'un séisme", "la température", "la pression", "l'altitude"], 0),
        ("Le volcanisme est lié à :", ["la remontée du magma", "la pluie", "le vent", "la neige"], 0),
        ("L'érosion est :", ["l'usure des roches", "la formation des roches", "la fusion des roches", "la cristallisation"], 0),
        ("Le sol est formé par :", ["l'altération des roches", "la photosynthèse", "la respiration", "la transpiration"], 0),
        ("L'humus est :", ["de la matière organique décomposée", "une roche", "un minéral", "de l'eau"], 0),
        ("La couche d'ozone protège contre :", ["les UV", "les rayons X", "les infrarouges", "la lumière visible"], 0),
        ("L'effet de serre est dû à :", ["l'accumulation de CO₂", "la couche d'ozone", "les UV", "la pluie"], 0),
        ("Le réchauffement climatique est causé par :", ["l'augmentation des gaz à effet de serre", "la diminution de l'oxygène", "l'augmentation de l'azote", "la baisse du CO₂"], 0),
        ("La biodiversité est :", ["la variété des êtres vivants", "la quantité d'eau", "la température", "la pression"], 0),
        ("L'espèce menacée est :", ["une espèce en danger de disparition", "une espèce abondante", "une espèce nouvelle", "une espèce domestique"], 0),
        ("La contraception permet :", ["d'éviter une grossesse", "de favoriser la grossesse", "de guérir une maladie", "de stimuler la croissance"], 0),
        ("Le préservatif protège contre :", ["les IST et le VIH", "la grossesse uniquement", "le diabète", "le paludisme"], 0),
        ("Le paludisme est transmis par :", ["le moustique", "la mouche", "le rat", "le pou"], 0),
        ("Le plasmodium est :", ["le parasite du paludisme", "un virus", "une bactérie", "un champignon"], 0),
    ],
    "Histoire-Géographie": [
        ("Le Cameroun est situé en :", ["Afrique centrale", "Afrique de l'Ouest", "Afrique de l'Est", "Afrique du Nord"], 0),
        ("La capitale politique du Cameroun est :", ["Yaoundé", "Douala", "Bafoussam", "Garoua"], 0),
        ("La capitale économique du Cameroun est :", ["Douala", "Yaoundé", "Kribi", "Buea"], 0),
        ("Le Cameroun a obtenu son indépendance en :", ["1960", "1958", "1962", "1972"], 0),
        ("Le premier président du Cameroun fut :", ["Ahmadou Ahidjo", "Paul Biya", "Ruben Um Nyobé", "Ernest Ouandié"], 0),
        ("Le Cameroun compte combien de régions ?", ["10", "8", "12", "6"], 0),
        ("Le fleuve le plus long du Cameroun est :", ["la Sanaga", "le Wouri", "le Nyong", "la Bénoué"], 0),
        ("Le mont Cameroun est :", ["un volcan", "un fleuve", "une ville", "un lac"], 0),
        ("L'altitude du mont Cameroun est environ :", ["4095 m", "2000 m", "5000 m", "3000 m"], 0),
        ("Le climat équatorial se caractérise par :", ["des pluies abondantes toute l'année", "une saison sèche longue", "des températures froides", "peu de pluie"], 0),
        ("Le Cameroun est surnommé :", ["l'Afrique en miniature", "le pays des mille collines", "la perle de l'Afrique", "le grenier de l'Afrique"], 0),
        ("La première guerre mondiale a eu lieu en :", ["1914-1918", "1939-1945", "1870-1871", "1918-1920"], 0),
        ("La deuxième guerre mondiale a eu lieu en :", ["1939-1945", "1914-1918", "1945-1950", "1929-1933"], 0),
        ("La Révolution française a eu lieu en :", ["1789", "1776", "1804", "1815"], 0),
        ("Napoléon Bonaparte a été couronné empereur en :", ["1804", "1789", "1815", "1799"], 0),
        ("La traite négrière transatlantique concernait :", ["l'Afrique et l'Amérique", "l'Europe et l'Asie", "l'Afrique et l'Asie", "l'Europe et l'Amérique"], 0),
        ("La colonisation du Cameroun par l'Allemagne a commencé en :", ["1884", "1916", "1900", "1870"], 0),
        ("Après la Première Guerre mondiale, le Cameroun fut partagé entre :", ["la France et l'Angleterre", "l'Allemagne et la France", "la France et l'Espagne", "l'Angleterre et l'Italie"], 0),
        ("Le Cameroun oriental était sous mandat :", ["français", "anglais", "allemand", "belge"], 0),
        ("Le Cameroun occidental était sous mandat :", ["anglais", "français", "allemand", "belge"], 0),
        ("Le référendum de 1961 a permis :", ["la réunification du Cameroun", "l'indépendance", "la colonisation", "la partition"], 0),
        ("La République fédérale du Cameroun a été créée en :", ["1961", "1960", "1972", "1984"], 0),
        ("Le Cameroun est devenu République unie en :", ["1972", "1961", "1984", "1960"], 0),
        ("Le Cameroun est devenu République du Cameroun en :", ["1984", "1972", "1961", "1990"], 0),
        ("Le multipartisme a été rétabli au Cameroun en :", ["1990", "1980", "1972", "2000"], 0),
        ("L'ONU a été créée en :", ["1945", "1919", "1939", "1950"], 0),
        ("La SDN a été créée en :", ["1919", "1945", "1939", "1900"], 0),
        ("L'OUA a été créée en :", ["1963", "1945", "1975", "1955"], 0),
        ("L'Union africaine a remplacé l'OUA en :", ["2002", "1990", "1980", "2010"], 0),
        ("La CEMAC est une organisation :", ["économique et monétaire", "politique", "militaire", "culturelle"], 0),
        ("Le siège de la CEMAC est à :", ["Yaoundé", "Douala", "Libreville", "N'Djamena"], 0),
        ("La monnaie utilisée au Cameroun est :", ["le franc CFA", "le dollar", "l'euro", "le naira"], 0),
        ("Le Cameroun est membre de :", ["l'ONU, l'UA et la CEMAC", "l'OTAN", "l'UE", "l'ALENA"], 0),
        ("Le relief du Cameroun comprend :", ["des montagnes, plateaux et plaines", "uniquement des plaines", "uniquement des montagnes", "uniquement des déserts"], 0),
        ("Le lac Tchad se situe au :", ["nord du Cameroun", "sud du Cameroun", "est du Cameroun", "ouest du Cameroun"], 0),
        ("La principale culture d'exportation du Cameroun est :", ["le cacao", "le blé", "le riz", "la pomme de terre"], 0),
        ("Le Cameroun est un grand producteur de :", ["café et cacao", "pétrole et diamant", "or et argent", "blé et maïs"], 0),
        ("Le port le plus important du Cameroun est :", ["Douala", "Kribi", "Limbé", "Garoua"], 0),
        ("Le barrage de Lagdo se trouve sur :", ["la Bénoué", "la Sanaga", "le Wouri", "le Nyong"], 0),
        ("Le barrage de Song Loulou se trouve sur :", ["la Sanaga", "la Bénoué", "le Wouri", "le Nyong"], 0),
        ("La population du Cameroun est d'environ :", ["27 millions", "10 millions", "50 millions", "5 millions"], 0),
        ("La densité de population est la plus forte :", ["dans les grandes villes", "dans le désert", "en montagne", "en forêt dense"], 0),
        ("L'exode rural est :", ["le départ des campagnes vers les villes", "le départ des villes vers les campagnes", "l'immigration", "l'émigration"], 0),
        ("Le taux de natalité est :", ["le nombre de naissances pour 1000 habitants", "le nombre de décès", "la croissance", "la densité"], 0),
        ("Le taux de mortalité est :", ["le nombre de décès pour 1000 habitants", "le nombre de naissances", "la densité", "la croissance"], 0),
        ("L'accroissement naturel est :", ["natalité - mortalité", "natalité + mortalité", "immigration - émigration", "densité × surface"], 0),
        ("La savane se trouve principalement :", ["au nord du Cameroun", "au sud du Cameroun", "à l'ouest", "sur le littoral"], 0),
        ("La forêt dense se trouve principalement :", ["au sud du Cameroun", "au nord", "à l'extrême-nord", "sur les hauts plateaux"], 0),
        ("Le climat soudano-sahélien se trouve :", ["au nord du Cameroun", "au sud", "à l'ouest", "sur le littoral"], 0),
        ("Le climat équatorial se trouve :", ["au sud du Cameroun", "au nord", "à l'extrême-nord", "sur les hauts plateaux"], 0),
        ("Le climat tropical humide se trouve :", ["dans le centre du Cameroun", "au nord", "au sud", "sur le littoral"], 0),
        ("L'agriculture vivrière produit :", ["du manioc, maïs et banane", "du cacao et café", "du coton et arachide", "du pétrole"], 0),
        ("L'agriculture de rente produit :", ["du cacao, café et coton", "du manioc et maïs", "de la banane plantain", "des légumes"], 0),
        ("Le pétrole est exploité :", ["dans le bassin du Rio del Rey", "au mont Cameroun", "à Yaoundé", "à Bafoussam"], 0),
        ("Le tourisme au Cameroun est favorisé par :", ["la diversité des paysages", "le désert", "la neige", "les glaciers"], 0),
        ("Le parc national de Waza se trouve :", ["à l'extrême-nord", "au sud", "à l'ouest", "sur le littoral"], 0),
        ("Le parc national de Korup se trouve :", ["au sud-ouest", "au nord", "à l'est", "au centre"], 0),
        ("La déforestation est :", ["la destruction de la forêt", "la plantation d'arbres", "la protection de la forêt", "la culture"], 0),
        ("Le développement durable vise :", ["à satisfaire les besoins sans compromettre l'avenir", "la croissance rapide", "l'exploitation maximale", "la consommation"], 0),
        ("La mondialisation est :", ["l'interdépendance croissante des économies", "l'isolement des pays", "la guerre", "la colonisation"], 0),
    ],
    "Physique-Chimie": [
        ("L'unité de la tension électrique est :", ["le volt", "l'ampère", "l'ohm", "le watt"], 0),
        ("L'intensité du courant se mesure avec :", ["un ampèremètre", "un voltmètre", "un ohmmètre", "un wattmètre"], 0),
        ("La formule de la loi d'Ohm est :", ["U = R × I", "U = R / I", "I = U × R", "R = U × I"], 0),
        ("L'unité de la résistance électrique est :", ["l'ohm", "le volt", "l'ampère", "le joule"], 0),
        ("La masse volumique se calcule par :", ["ρ = m / V", "ρ = m × V", "ρ = V / m", "ρ = m + V"], 0),
        ("L'unité de la force est :", ["le newton", "le kilogramme", "le pascal", "le joule"], 0),
        ("La pression se calcule par :", ["P = F / S", "P = F × S", "P = S / F", "P = F + S"], 0),
        ("L'unité de la pression est :", ["le pascal", "le newton", "le joule", "le watt"], 0),
        ("Le symbole chimique de l'eau est :", ["H₂O", "CO₂", "O₂", "H₂"], 0),
        ("Le pH d'une solution acide est :", ["inférieur à 7", "supérieur à 7", "égal à 7", "égal à 0"], 0),
        ("L'énergie cinétique se calcule par :", ["Ec = ½ mv²", "Ec = mv", "Ec = mgh", "Ec = ½ mgh"], 0),
        ("L'unité de l'énergie est :", ["le joule", "le watt", "le newton", "le pascal"], 0),
        ("La vitesse se calcule par :", ["v = d / t", "v = d × t", "v = t / d", "v = d + t"], 0),
        ("Le symbole chimique du dioxyde de carbone est :", ["CO₂", "O₂", "CO", "C₂O"], 0),
        ("Un corps pur est :", ["constitué d'une seule espèce chimique", "un mélange", "un alliage", "une solution"], 0),
        ("La température se mesure avec :", ["un thermomètre", "un baromètre", "un manomètre", "un hygromètre"], 0),
        ("L'unité de la température en SI est :", ["le kelvin", "le degré Celsius", "le degré Fahrenheit", "le joule"], 0),
        ("Le courant électrique est un déplacement de :", ["charges électriques", "molécules", "atomes", "neutrons"], 0),
        ("Dans un circuit en série, l'intensité est :", ["la même partout", "différente partout", "nulle", "maximale au début"], 0),
        ("Le symbole chimique du sel de cuisine (chlorure de sodium) est :", ["NaCl", "NaCl₂", "Na₂Cl", "ClNa₂"], 0),
        ("La puissance électrique se calcule par :", ["P = U × I", "P = U / I", "P = I / U", "P = U + I"], 0),
        ("L'unité de la puissance est :", ["le watt", "le joule", "le volt", "l'ampère"], 0),
        ("Le poids d'un corps se calcule par :", ["P = m × g", "P = m / g", "P = g / m", "P = m + g"], 0),
        ("La valeur de g (accélération de pesanteur) sur Terre est environ :", ["9,8 N/kg", "10 N/kg", "98 N/kg", "0,98 N/kg"], 0),
        ("Une solution basique a un pH :", ["supérieur à 7", "inférieur à 7", "égal à 7", "égal à 14"], 0),
        ("Le symbole chimique de l'oxygène est :", ["O", "O₂", "Ox", "Og"], 0),
        ("La distillation permet de :", ["séparer les constituants d'un mélange homogène", "mélanger deux liquides", "solidifier un liquide", "filtrer un solide"], 0),
        ("L'aimant attire :", ["le fer", "le cuivre", "l'aluminium", "le verre"], 0),
        ("Le courant alternatif change de sens :", ["périodiquement", "jamais", "une seule fois", "aléatoirement"], 0),
        ("L'unité de la fréquence est :", ["le hertz", "le watt", "le volt", "l'ohm"], 0),
        ("Le symbole chimique du carbone est :", ["C", "Ca", "Co", "Cr"], 0),
        ("La fusion est le passage de :", ["solide à liquide", "liquide à gaz", "gaz à liquide", "solide à gaz"], 0),
        ("La vaporisation est le passage de :", ["liquide à gaz", "solide à liquide", "gaz à solide", "liquide à solide"], 0),
        ("Le symbole chimique de l'azote est :", ["N", "Az", "Na", "Ni"], 0),
        ("Un isolant électrique est :", ["le plastique", "le cuivre", "le fer", "l'aluminium"], 0),
        ("Un conducteur électrique est :", ["le cuivre", "le verre", "le plastique", "le bois"], 0),
        ("L'énergie potentielle de pesanteur se calcule par :", ["Ep = mgh", "Ep = ½ mv²", "Ep = mv", "Ep = mgh²"], 0),
        ("Le symbole chimique du fer est :", ["Fe", "F", "Fr", "Ir"], 0),
        ("La condensation est le passage de :", ["gaz à liquide", "liquide à gaz", "solide à liquide", "gaz à solide"], 0),
        ("L'unité de la charge électrique est :", ["le coulomb", "le volt", "l'ampère", "l'ohm"], 0),
        ("Le symbole chimique de l'hydrogène est :", ["H", "Hy", "He", "Hg"], 0),
        ("La dilution consiste à :", ["ajouter de l'eau à une solution", "concentrer une solution", "chauffer une solution", "refroidir une solution"], 0),
        ("Le symbole chimique du calcium est :", ["Ca", "C", "Cl", "Cr"], 0),
        ("Un aimant possède :", ["deux pôles", "un pôle", "trois pôles", "aucun pôle"], 0),
        ("La sublimation est le passage de :", ["solide à gaz", "gaz à liquide", "liquide à solide", "gaz à solide"], 0),
        ("Le symbole chimique du sodium est :", ["Na", "So", "S", "N"], 0),
        ("L'énergie mécanique est la somme de :", ["l'énergie cinétique et potentielle", "l'énergie thermique et électrique", "l'énergie chimique et nucléaire", "l'énergie lumineuse et sonore"], 0),
        ("Le symbole chimique du chlore est :", ["Cl", "Ch", "C", "Cr"], 0),
        ("Un circuit électrique fermé permet :", ["le passage du courant", "l'arrêt du courant", "la coupure du courant", "aucun courant"], 0),
        ("Le symbole chimique du potassium est :", ["K", "P", "Po", "Ka"], 0),
        ("La masse se mesure avec :", ["une balance", "un thermomètre", "un baromètre", "un voltmètre"], 0),
        ("Le symbole chimique du zinc est :", ["Zn", "Z", "Zi", "Zr"], 0),
        ("L'unité de la masse en SI est :", ["le kilogramme", "le gramme", "la tonne", "le newton"], 0),
        ("Le symbole chimique du cuivre est :", ["Cu", "Co", "C", "Cp"], 0),
        ("La solidification est le passage de :", ["liquide à solide", "solide à liquide", "gaz à liquide", "liquide à gaz"], 0),
        ("Le symbole chimique de l'aluminium est :", ["Al", "A", "Am", "Ar"], 0),
        ("L'ampèremètre se branche :", ["en série", "en dérivation", "en parallèle", "n'importe comment"], 0),
        ("Le voltmètre se branche :", ["en dérivation", "en série", "en parallèle", "n'importe comment"], 0),
        ("Le symbole chimique du plomb est :", ["Pb", "Pl", "P", "Po"], 0),
        ("La lumière se propage :", ["en ligne droite", "en courbe", "en zigzag", "en cercle"], 0),
    ],
    "Anglais": [
        ("The plural of « book » is :", ["books", "bookes", "book", "bookies"], 0),
        ("The past tense of « go » is :", ["went", "goed", "gone", "going"], 0),
        ("The past participle of « eat » is :", ["eaten", "ate", "eated", "eating"], 0),
        ("« She ___ a student. » (present of to be)", ["is", "are", "am", "be"], 0),
        ("« They ___ playing football. » (present continuous)", ["are", "is", "am", "be"], 0),
        ("The opposite of « big » is :", ["small", "large", "huge", "tall"], 0),
        ("The synonym of « happy » is :", ["glad", "sad", "angry", "tired"], 0),
        ("« I ___ to school every day. » (present simple)", ["go", "goes", "going", "gone"], 0),
        ("« He ___ his homework. » (present simple, 3rd person)", ["does", "do", "doing", "done"], 0),
        ("The plural of « child » is :", ["children", "childs", "childes", "childrens"], 0),
        ("The plural of « man » is :", ["men", "mans", "menes", "man"], 0),
        ("The plural of « woman » is :", ["women", "womans", "womens", "woman"], 0),
        ("The plural of « foot » is :", ["feet", "foots", "feets", "foot"], 0),
        ("The plural of « tooth » is :", ["teeth", "tooths", "teeths", "tooth"], 0),
        ("« There ___ a book on the table. »", ["is", "are", "am", "be"], 0),
        ("« There ___ many students in the class. »", ["are", "is", "am", "be"], 0),
        ("The comparative of « tall » is :", ["taller", "more tall", "tallest", "most tall"], 0),
        ("The superlative of « tall » is :", ["tallest", "taller", "more tall", "most tall"], 0),
        ("« I have ___ apple. »", ["an", "a", "the", "some"], 0),
        ("« He is ___ engineer. »", ["an", "a", "the", "some"], 0),
        ("The past tense of « see » is :", ["saw", "seen", "seed", "seeing"], 0),
        ("The past tense of « come » is :", ["came", "comed", "come", "coming"], 0),
        ("The past tense of « buy » is :", ["bought", "buyed", "boughten", "buying"], 0),
        ("The past tense of « think » is :", ["thought", "thinked", "thunk", "thinking"], 0),
        ("« She ___ to the market yesterday. »", ["went", "goes", "go", "going"], 0),
        ("« We ___ watching TV now. »", ["are", "is", "am", "be"], 0),
        ("The question form of « You like tea. » is :", ["Do you like tea?", "You like tea?", "Does you like tea?", "Are you like tea?"], 0),
        ("The negative of « He works. » is :", ["He does not work.", "He not works.", "He do not work.", "He works not."], 0),
        ("« I ___ a letter yesterday. » (write, past)", ["wrote", "written", "writed", "writing"], 0),
        ("The future of « go » is :", ["will go", "went", "gone", "going"], 0),
        ("« She will ___ to school. »", ["go", "goes", "going", "gone"], 0),
        ("The possessive of « John » is :", ["John's", "Johns", "John", "Johnes"], 0),
        ("« This is ___ book. » (belonging to me)", ["my", "mine", "me", "I"], 0),
        ("« This book is ___. » (belonging to me)", ["mine", "my", "me", "I"], 0),
        ("The pronoun for « the teacher » (he/she) is :", ["he or she", "it", "they", "we"], 0),
        ("The pronoun for « the books » is :", ["they", "it", "he", "she"], 0),
        ("« How ___ are you? » (age)", ["old", "tall", "big", "much"], 0),
        ("« How ___ does it cost? »", ["much", "many", "old", "tall"], 0),
        ("« How ___ books do you have? »", ["many", "much", "old", "tall"], 0),
        ("The time « 7:30 » is :", ["half past seven", "seven thirty", "thirty past seven", "half seven"], 0),
        ("The time « 8:15 » is :", ["quarter past eight", "eight fifteen", "quarter eight", "fifteen eight"], 0),
        ("« Good morning » is said :", ["in the morning", "at night", "in the afternoon", "in the evening"], 0),
        ("« Thank you » means :", ["merci", "bonjour", "au revoir", "s'il vous plaît"], 0),
        ("« Please » means :", ["s'il vous plaît", "merci", "bonjour", "excusez-moi"], 0),
        ("The color of the sky is :", ["blue", "red", "green", "black"], 0),
        ("The color of blood is :", ["red", "blue", "green", "yellow"], 0),
        ("« I am hungry » means :", ["j'ai faim", "j'ai soif", "j'ai sommeil", "j'ai chaud"], 0),
        ("« I am thirsty » means :", ["j'ai soif", "j'ai faim", "j'ai sommeil", "j'ai froid"], 0),
        ("The day after Monday is :", ["Tuesday", "Wednesday", "Sunday", "Friday"], 0),
        ("The first month of the year is :", ["January", "February", "March", "December"], 0),
        ("« She is taller than me » means :", ["elle est plus grande que moi", "elle est plus petite que moi", "elle est aussi grande que moi", "elle est grande"], 0),
        ("The past tense of « have » is :", ["had", "haved", "has", "having"], 0),
        ("« I have lived here ___ 2010. »", ["since", "for", "from", "at"], 0),
        ("« I have lived here ___ five years. »", ["for", "since", "from", "at"], 0),
        ("The present perfect of « finish » (I) is :", ["I have finished", "I finished", "I finish", "I am finishing"], 0),
        ("« ___ you like some tea? »", ["Would", "Do", "Are", "Is"], 0),
        ("The word « beautiful » is :", ["an adjective", "a noun", "a verb", "an adverb"], 0),
        ("The word « quickly » is :", ["an adverb", "an adjective", "a noun", "a verb"], 0),
        ("The word « happiness » is :", ["a noun", "an adjective", "a verb", "an adverb"], 0),
        ("« I am going to the market » — the market is :", ["a place", "a person", "a thing", "an idea"], 0),
    ],
    "Physique": [
        ("L'unité de la force est :", ["le newton", "le joule", "le watt", "le pascal"], 0),
        ("La formule de l'énergie cinétique est :", ["Ec = ½ mv²", "Ec = mv", "Ec = mgh", "Ec = ½ mgh"], 0),
        ("La loi de Coulomb s'écrit :", ["F = k·q₁q₂/r²", "F = k·r²/q₁q₂", "F = q₁q₂·r²", "F = k·q₁q₂·r"], 0),
        ("L'unité de la charge électrique est :", ["le coulomb", "le volt", "l'ampère", "l'ohm"], 0),
        ("La force de Lorentz s'exerce sur :", ["une charge en mouvement dans un champ", "une charge immobile", "un aimant", "un conducteur"], 0),
        ("La loi de Faraday concerne :", ["l'induction électromagnétique", "la gravitation", "l'optique", "la thermique"], 0),
        ("L'unité de la fréquence est :", ["le hertz", "le watt", "le volt", "l'ohm"], 0),
        ("La période T et la fréquence f sont liées par :", ["T = 1/f", "T = f", "T = 2f", "T = f²"], 0),
        ("La longueur d'onde λ et la fréquence f sont liées par :", ["λ = v/f", "λ = v·f", "λ = f/v", "λ = v+f"], 0),
        ("La vitesse de la lumière dans le vide est environ :", ["3×10⁸ m/s", "3×10⁶ m/s", "3×10¹⁰ m/s", "300 m/s"], 0),
        ("La loi de Snell-Descartes concerne :", ["la réfraction", "la gravitation", "l'induction", "la thermique"], 0),
        ("L'indice de réfraction du vide est :", ["1", "0", "1,5", "3"], 0),
        ("La vergence d'une lentille s'exprime en :", ["dioptries", "newtons", "watts", "ohms"], 0),
        ("La quantité de mouvement est :", ["p = mv", "p = m/v", "p = v/m", "p = m+v"], 0),
        ("Le théorème de l'énergie cinétique :", ["ΔEc = W", "ΔEc = P", "ΔEc = F", "ΔEc = m"], 0),
        ("Le travail d'une force constante est :", ["W = F·d·cos(θ)", "W = F·d", "W = F/d", "W = d/F"], 0),
        ("L'unité du travail est :", ["le joule", "le watt", "le newton", "le pascal"], 0),
        ("La puissance est :", ["P = W/t", "P = W·t", "P = t/W", "P = W+t"], 0),
        ("L'unité de la puissance est :", ["le watt", "le joule", "le newton", "le volt"], 0),
        ("Le moment d'une force s'exprime en :", ["N·m", "N/m", "N·m²", "N"], 0),
        ("L'équilibre d'un solide exige :", ["la somme des forces et moments nulle", "une force nulle", "un moment nul", "une vitesse nulle"], 0),
        ("Le champ gravitationnel est :", ["g = G·M/r²", "g = G·M·r²", "g = r²/G·M", "g = G·r²/M"], 0),
        ("La constante de gravitation G vaut :", ["6,67×10⁻¹¹ N·m²/kg²", "9,8 N/kg", "3×10⁸ m/s", "1,6×10⁻¹⁹ C"], 0),
        ("Le mouvement uniforme a :", ["une vitesse constante", "une accélération constante", "une vitesse nulle", "une accélération nulle"], 0),
        ("Le mouvement uniformément accéléré a :", ["une accélération constante", "une vitesse constante", "une vitesse nulle", "une accélération nulle"], 0),
        ("L'accélération est :", ["a = Δv/Δt", "a = Δv·Δt", "a = Δt/Δv", "a = v·t"], 0),
        ("L'unité de l'accélération est :", ["m/s²", "m/s", "m", "s"], 0),
        ("La radioactivité α émet :", ["un noyau d'hélium", "un électron", "un photon", "un neutron"], 0),
        ("La radioactivité β⁻ émet :", ["un électron", "un positron", "un photon", "un neutron"], 0),
        ("La radioactivité γ émet :", ["un photon", "un électron", "un proton", "un neutron"], 0),
        ("La demi-vie est :", ["le temps pour que la moitié se désintègre", "le temps total de désintégration", "la moitié de la masse", "la moitié de l'énergie"], 0),
        ("L'énergie de liaison est :", ["l'énergie pour séparer les nucléons", "l'énergie cinétique", "l'énergie potentielle", "l'énergie thermique"], 0),
        ("Le défaut de masse est :", ["la différence entre masse des nucléons et du noyau", "la masse totale", "la masse des électrons", "la masse nulle"], 0),
        ("L'équivalence masse-énergie est :", ["E = mc²", "E = mc", "E = m/c²", "E = c²/m"], 0),
        ("La fission nucléaire :", ["divise un noyau lourd", "fusionne des noyaux légers", "émet des électrons", "absorbe des photons"], 0),
        ("La fusion nucléaire :", ["fusionne des noyaux légers", "divise un noyau lourd", "émet des électrons", "absorbe des photons"], 0),
        ("Le circuit RLC série :", ["contient résistance, bobine et condensateur", "contient uniquement une résistance", "contient uniquement une bobine", "contient uniquement un condensateur"], 0),
        ("La résonance dans un circuit RLC :", ["l'impédance est minimale", "l'impédance est maximale", "le courant est nul", "la tension est nulle"], 0),
        ("L'impédance Z d'un circuit :", ["Z = U/I", "Z = U·I", "Z = I/U", "Z = U+I"], 0),
        ("L'unité de l'impédance est :", ["l'ohm", "le volt", "l'ampère", "le watt"], 0),
        ("Le facteur de puissance est :", ["cos(φ)", "sin(φ)", "tan(φ)", "φ"], 0),
        ("L'énergie électrique est :", ["E = P·t", "E = P/t", "E = t/P", "E = P+t"], 0),
        ("L'effet photoélectrique :", ["émission d'électrons par la lumière", "absorption de photons", "émission de photons", "réflexion"], 0),
        ("Le photon a une énergie :", ["E = h·f", "E = h/f", "E = f/h", "E = h+f"], 0),
        ("La constante de Planck h vaut :", ["6,63×10⁻³⁴ J·s", "6,67×10⁻¹¹", "9,8", "3×10⁸"], 0),
        ("L'effet Doppler concerne :", ["le changement de fréquence d'une onde", "la réfraction", "la réflexion", "l'absorption"], 0),
        ("Les ondes mécaniques :", ["nécessitent un milieu", "se propagent dans le vide", "sont des particules", "sont des charges"], 0),
        ("Les ondes électromagnétiques :", ["se propagent dans le vide", "nécessitent un milieu", "sont des particules", "sont des charges"], 0),
        ("Le son est :", ["une onde mécanique", "une onde électromagnétique", "une particule", "une charge"], 0),
        ("La vitesse du son dans l'air est environ :", ["340 m/s", "3×10⁸ m/s", "1500 m/s", "100 m/s"], 0),
        ("L'intensité sonore se mesure en :", ["décibels", "watts", "newtons", "pascals"], 0),
        ("Le champ électrique E s'exprime en :", ["V/m", "V", "A", "Ω"], 0),
        ("Le potentiel électrique s'exprime en :", ["volts", "ampères", "ohms", "watts"], 0),
        ("La capacité d'un condensateur s'exprime en :", ["farads", "ohms", "henrys", "volts"], 0),
        ("L'inductance d'une bobine s'exprime en :", ["henrys", "farads", "ohms", "volts"], 0),
        ("Le flux magnétique s'exprime en :", ["webers", "teslas", "henrys", "farads"], 0),
        ("Le champ magnétique s'exprime en :", ["teslas", "webers", "henrys", "farads"], 0),
    ],
    "Chimie": [
        ("Le nombre d'Avogadro est :", ["6,02×10²³", "6,67×10⁻¹¹", "3×10⁸", "9,8"], 0),
        ("La mole est :", ["l'unité de quantité de matière", "l'unité de masse", "l'unité de volume", "l'unité de température"], 0),
        ("La masse molaire s'exprime en :", ["g/mol", "g", "mol", "kg"], 0),
        ("Le volume molaire d'un gaz dans les CNTP est :", ["22,4 L/mol", "1 L/mol", "6,02 L/mol", "100 L/mol"], 0),
        ("La concentration molaire est :", ["C = n/V", "C = n·V", "C = V/n", "C = n+V"], 0),
        ("La concentration massique est :", ["Cm = m/V", "Cm = m·V", "Cm = V/m", "Cm = m+V"], 0),
        ("Le pH d'une solution est :", ["pH = -log[H⁺]", "pH = log[H⁺]", "pH = [H⁺]", "pH = 1/[H⁺]"], 0),
        ("Une solution neutre a un pH :", ["égal à 7", "inférieur à 7", "supérieur à 7", "égal à 0"], 0),
        ("La constante d'acidité Ka :", ["mesure la force d'un acide", "mesure la température", "mesure la masse", "mesure le volume"], 0),
        ("Un acide fort :", ["se dissocie totalement", "se dissocie partiellement", "ne se dissocie pas", "est basique"], 0),
        ("Une base faible :", ["se dissocie partiellement", "se dissocie totalement", "ne se dissocie pas", "est acide"], 0),
        ("La réaction d'oxydoréduction :", ["échange des électrons", "échange des protons", "échange des neutrons", "échange de la chaleur"], 0),
        ("L'oxydation est :", ["une perte d'électrons", "un gain d'électrons", "un gain de protons", "une perte de protons"], 0),
        ("La réduction est :", ["un gain d'électrons", "une perte d'électrons", "un gain de protons", "une perte de protons"], 0),
        ("L'oxydant est :", ["l'espèce qui capte des électrons", "l'espèce qui cède des électrons", "l'espèce neutre", "l'espèce chargée"], 0),
        ("Le réducteur est :", ["l'espèce qui cède des électrons", "l'espèce qui capte des électrons", "l'espèce neutre", "l'espèce chargée"], 0),
        ("Le nombre d'oxydation :", ["mesure l'état d'oxydation", "mesure la masse", "mesure le volume", "mesure la température"], 0),
        ("L'électrolyse :", ["transforme l'énergie électrique en chimique", "produit de l'électricité", "est une combustion", "est une distillation"], 0),
        ("La pile électrochimique :", ["transforme l'énergie chimique en électrique", "consomme de l'électricité", "est une électrolyse", "est une combustion"], 0),
        ("L'anode est :", ["l'électrode où a lieu l'oxydation", "l'électrode où a lieu la réduction", "l'électrode neutre", "le pôle négatif"], 0),
        ("La cathode est :", ["l'électrode où a lieu la réduction", "l'électrode où a lieu l'oxydation", "l'électrode neutre", "le pôle positif"], 0),
        ("La cinétique chimique étudie :", ["la vitesse des réactions", "l'équilibre", "la thermodynamique", "la structure"], 0),
        ("La vitesse d'une réaction :", ["diminue avec le temps", "augmente avec le temps", "est constante", "est nulle"], 0),
        ("Un catalyseur :", ["accélère la réaction sans être consommé", "ralentit la réaction", "est consommé", "n'a aucun effet"], 0),
        ("La température :", ["augmente la vitesse de réaction", "diminue la vitesse", "n'a aucun effet", "arrête la réaction"], 0),
        ("L'équilibre chimique :", ["les vitesses directe et inverse sont égales", "la réaction s'arrête", "les concentrations sont nulles", "la réaction est totale"], 0),
        ("La constante d'équilibre K :", ["caractérise l'équilibre", "mesure la vitesse", "mesure la température", "mesure la masse"], 0),
        ("Le principe de Le Chatelier :", ["un système réagit pour s'opposer à une perturbation", "un système ne réagit pas", "un système accélère", "un système s'arrête"], 0),
        ("La thermochimie étudie :", ["les échanges de chaleur", "la vitesse", "l'équilibre", "la structure"], 0),
        ("Une réaction exothermique :", ["libère de la chaleur", "absorbe de la chaleur", "ne dégage rien", "est froide"], 0),
        ("Une réaction endothermique :", ["absorbe de la chaleur", "libère de la chaleur", "ne dégage rien", "est chaude"], 0),
        ("L'enthalpie de réaction ΔH :", ["mesure la chaleur échangée", "mesure la vitesse", "mesure la masse", "mesure le volume"], 0),
        ("La chimie organique étudie :", ["les composés du carbone", "les métaux", "les gaz rares", "les sels"], 0),
        ("Le carbone a une valence :", ["4", "2", "3", "1"], 0),
        ("L'isomérie :", ["même formule brute, structure différente", "formule différente", "même structure", "même masse"], 0),
        ("Les alcanes ont pour formule générale :", ["CnH₂n₊₂", "CnH₂n", "CnH₂n₋₂", "CnHn"], 0),
        ("Les alcènes ont pour formule générale :", ["CnH₂n", "CnH₂n₊₂", "CnH₂n₋₂", "CnHn"], 0),
        ("Les alcynes ont pour formule générale :", ["CnH₂n₋₂", "CnH₂n", "CnH₂n₊₂", "CnHn"], 0),
        ("Le groupe fonctionnel des alcools est :", ["-OH", "-COOH", "-CHO", "-NH₂"], 0),
        ("Le groupe fonctionnel des acides carboxyliques est :", ["-COOH", "-OH", "-CHO", "-NH₂"], 0),
        ("Le groupe fonctionnel des aldéhydes est :", ["-CHO", "-OH", "-COOH", "-NH₂"], 0),
        ("Le groupe fonctionnel des amines est :", ["-NH₂", "-OH", "-COOH", "-CHO"], 0),
        ("L'estérification :", ["acide + alcool → ester + eau", "acide + base → sel", "alcool → alcène", "alcane → alcool"], 0),
        ("L'hydrolyse d'un ester :", ["ester + eau → acide + alcool", "ester → alcool", "ester → acide", "ester → sel"], 0),
        ("La saponification :", ["ester + base → savon + alcool", "acide + alcool → ester", "alcool → alcène", "alcane → alcool"], 0),
        ("La polymérisation :", ["assemble des monomères", "divise des polymères", "est une combustion", "est une distillation"], 0),
        ("Le monomère est :", ["l'unité de base du polymère", "le polymère", "le produit final", "un catalyseur"], 0),
        ("La distillation :", ["sépare les constituants d'un mélange", "mélange deux liquides", "solidifie", "cristallise"], 0),
        ("La chromatographie :", ["sépare les constituants d'un mélange", "mélange", "solidifie", "cristallise"], 0),
        ("Le titrage :", ["détermine une concentration", "mesure la masse", "mesure le volume", "mesure la température"], 0),
        ("Le point d'équivalence :", ["les réactifs sont en proportions stœchiométriques", "la réaction s'arrête", "le pH est nul", "la température est maximale"], 0),
        ("La spectrophotométrie :", ["mesure l'absorbance", "mesure la masse", "mesure le volume", "mesure la température"], 0),
        ("La loi de Beer-Lambert :", ["A = ε·l·C", "A = ε·l/C", "A = C/ε·l", "A = ε·C/l"], 0),
        ("L'absorbance est :", ["proportionnelle à la concentration", "inversement proportionnelle", "constante", "nulle"], 0),
        ("Le tableau d'avancement :", ["suit l'évolution d'une réaction", "mesure la vitesse", "mesure la température", "mesure la masse"], 0),
        ("L'avancement maximal :", ["quand le réactif limitant est consommé", "quand la réaction s'arrête", "quand le pH est nul", "quand la température est maximale"], 0),
        ("Le réactif limitant :", ["est entièrement consommé", "reste en excès", "est le catalyseur", "est le produit"], 0),
        ("Le rendement d'une réaction :", ["quantité obtenue / quantité théorique", "quantité théorique / obtenue", "quantité obtenue × théorique", "quantité théorique"], 0),
        ("La chimie verte :", ["réduit l'impact environnemental", "augmente les déchets", "utilise des toxiques", "est polluante"], 0),
        ("L'atome de carbone peut former :", ["4 liaisons", "2 liaisons", "3 liaisons", "1 liaison"], 0),
    ],
    "Informatique": [
        ("Un algorithme est :", ["une suite d'instructions", "un périphérique", "une mémoire", "un composant"], 0),
        ("La variable est :", ["un espace mémoire nommé", "un périphérique", "une mémoire", "un composant"], 0),
        ("Le type entier :", ["représente des nombres entiers", "représente des nombres décimaux", "représente du texte", "représente un booléen"], 0),
        ("Le type réel :", ["représente des nombres décimaux", "représente des entiers", "représente du texte", "représente un booléen"], 0),
        ("Le type chaîne :", ["représente du texte", "représente des entiers", "représente des décimaux", "représente un booléen"], 0),
        ("Le type booléen :", ["vrai ou faux", "des nombres", "du texte", "des caractères"], 0),
        ("La structure conditionnelle :", ["si... alors... sinon", "pour... faire", "tant que... faire", "répéter... jusqu'à"], 0),
        ("La boucle « pour » :", ["répète un nombre fixe de fois", "répète tant qu'une condition est vraie", "est une condition", "est une variable"], 0),
        ("La boucle « tant que » :", ["répète tant qu'une condition est vraie", "répète un nombre fixe de fois", "est une condition", "est une variable"], 0),
        ("L'opérateur de comparaison est :", ["=", "+", "*", "/"], 0),
        ("L'opérateur d'affectation :", ["attribue une valeur à une variable", "compare deux valeurs", "additionne", "multiplie"], 0),
        ("Le tableau :", ["une collection de valeurs", "une variable", "une condition", "une boucle"], 0),
        ("L'indice d'un tableau commence à :", ["0 ou 1", "10", "-1", "n'importe où"], 0),
        ("La fonction :", ["un bloc de code réutilisable", "une variable", "une condition", "une boucle"], 0),
        ("Le paramètre d'une fonction :", ["une donnée d'entrée", "une sortie", "une condition", "une boucle"], 0),
        ("La récursivité :", ["une fonction qui s'appelle elle-même", "une boucle", "une condition", "une variable"], 0),
        ("La complexité algorithmique :", ["mesure l'efficacité", "mesure la taille", "mesure la vitesse du processeur", "mesure la mémoire"], 0),
        ("Le tri à bulles :", ["un algorithme de tri", "une recherche", "une boucle", "une condition"], 0),
        ("La recherche dichotomique :", ["recherche dans un tableau trié", "recherche aléatoire", "un tri", "une boucle"], 0),
        ("La structure de données Pile :", ["LIFO (dernier entré, premier sorti)", "FIFO (premier entré, premier sorti)", "une file", "un tableau"], 0),
        ("La structure de données File :", ["FIFO (premier entré, premier sorti)", "LIFO (dernier entré, premier sorti)", "une pile", "un tableau"], 0),
        ("L'arbre binaire :", ["une structure hiérarchique", "une pile", "une file", "un tableau"], 0),
        ("Le graphe :", ["un ensemble de nœuds et d'arêtes", "une pile", "une file", "un tableau"], 0),
        ("La base de données :", ["un ensemble structuré de données", "un fichier", "un programme", "un périphérique"], 0),
        ("Le SGBD :", ["système de gestion de base de données", "un fichier", "un programme", "un périphérique"], 0),
        ("Le langage SQL :", ["interroge les bases de données", "crée des pages web", "est un système d'exploitation", "est un périphérique"], 0),
        ("La requête SELECT :", ["interroge les données", "insère des données", "supprime des données", "modifie des données"], 0),
        ("La requête INSERT :", ["insère des données", "interroge les données", "supprime des données", "modifie des données"], 0),
        ("La requête UPDATE :", ["modifie des données", "interroge les données", "insère des données", "supprime des données"], 0),
        ("La requête DELETE :", ["supprime des données", "interroge les données", "insère des données", "modifie des données"], 0),
        ("La clé primaire :", ["identifie de façon unique une ligne", "est une colonne", "est une table", "est une requête"], 0),
        ("La clé étrangère :", ["relie deux tables", "identifie une ligne", "est une colonne", "est une requête"], 0),
        ("Le réseau informatique :", ["connecte des ordinateurs", "est un fichier", "est un programme", "est une mémoire"], 0),
        ("Le protocole :", ["règle de communication", "un fichier", "un programme", "une mémoire"], 0),
        ("Le protocole TCP/IP :", ["la base d'Internet", "un fichier", "un programme", "une mémoire"], 0),
        ("L'adresse IP :", ["identifie un ordinateur sur un réseau", "un fichier", "un programme", "une mémoire"], 0),
        ("Le DNS :", ["traduit les noms en adresses IP", "un fichier", "un programme", "une mémoire"], 0),
        ("Le HTML :", ["langage de création de pages web", "un système d'exploitation", "un protocole", "une base de données"], 0),
        ("Le CSS :", ["met en forme les pages web", "crée le contenu", "est un système d'exploitation", "est un protocole"], 0),
        ("Le JavaScript :", ["rend les pages web interactives", "crée le contenu", "met en forme", "est un système d'exploitation"], 0),
        ("Le client-serveur :", ["un modèle de communication", "un fichier", "un programme", "une mémoire"], 0),
        ("Le cloud computing :", ["le stockage et le calcul à distance", "un fichier", "un programme", "une mémoire"], 0),
        ("La cybersécurité :", ["protège les systèmes", "crée des virus", "est un jeu", "est un fichier"], 0),
        ("Le chiffrement :", ["protège les données", "crée des virus", "est un jeu", "est un fichier"], 0),
        ("L'authentification :", ["vérifie l'identité", "crée des virus", "est un jeu", "est un fichier"], 0),
        ("Le pare-feu :", ["protège le réseau", "crée des virus", "est un jeu", "est un fichier"], 0),
        ("L'intelligence artificielle :", ["simule l'intelligence humaine", "est un jeu", "est un fichier", "est une mémoire"], 0),
        ("Le machine learning :", ["l'apprentissage automatique", "est un jeu", "est un fichier", "est une mémoire"], 0),
        ("Le système d'exploitation :", ["gère les ressources de l'ordinateur", "est un fichier", "est un jeu", "est une mémoire"], 0),
        ("Le processus :", ["un programme en cours d'exécution", "un fichier", "un jeu", "une mémoire"], 0),
        ("Le thread :", ["un fil d'exécution", "un fichier", "un jeu", "une mémoire"], 0),
        ("La mémoire virtuelle :", ["étend la mémoire physique", "est un fichier", "est un jeu", "est un périphérique"], 0),
        ("Le compilateur :", ["traduit le code en langage machine", "exécute le code", "est un fichier", "est un jeu"], 0),
        ("L'interpréteur :", ["exécute le code ligne par ligne", "traduit tout le code", "est un fichier", "est un jeu"], 0),
        ("Le débogage :", ["corrige les erreurs", "crée des erreurs", "est un jeu", "est un fichier"], 0),
        ("Le test unitaire :", ["teste une unité de code", "teste tout le système", "est un jeu", "est un fichier"], 0),
        ("La documentation :", ["explique le code", "est inutile", "est un jeu", "est un fichier"], 0),
        ("Le versionnage :", ["gère les versions du code", "est inutile", "est un jeu", "est un fichier"], 0),
        ("Git est :", ["un outil de versionnage", "un jeu", "un fichier", "une mémoire"], 0),
        ("Le dépôt (repository) :", ["stocke le code versionné", "est un jeu", "est un fichier", "est une mémoire"], 0),
    ],
    "Philosophie": [
        ("La philosophie signifie étymologiquement :", ["l'amour de la sagesse", "la science", "la religion", "la politique"], 0),
        ("Le premier philosophe grec est souvent considéré :", ["Thalès", "Socrate", "Platon", "Aristote"], 0),
        ("Socrate est connu pour :", ["la maïeutique", "la théorie des idées", "la logique", "le doute"], 0),
        ("Platon a écrit :", ["La République", "L'Éthique à Nicomaque", "Le Discours de la méthode", "Le Contrat social"], 0),
        ("Aristote est le fondateur de :", ["la logique", "le scepticisme", "l'idéalisme", "l'empirisme"], 0),
        ("Descartes est connu pour :", ["le cogito « je pense donc je suis »", "la théorie des idées", "la logique", "le contrat social"], 0),
        ("Le cogito de Descartes est :", ["« je pense donc je suis »", "« connais-toi toi-même »", "« tout est nombre »", "« rien ne se perd »"], 0),
        ("Kant a écrit :", ["La Critique de la raison pure", "La République", "Le Contrat social", "L'Éthique"], 0),
        ("Rousseau a écrit :", ["Le Contrat social", "La République", "La Critique", "Le Discours de la méthode"], 0),
        ("L'empirisme affirme que :", ["toute connaissance vient de l'expérience", "la raison est la seule source", "les idées sont innées", "rien n'est connaissable"], 0),
        ("Le rationalisme affirme que :", ["la raison est la source de la connaissance", "l'expérience est la seule source", "les idées sont innées", "rien n'est connaissable"], 0),
        ("Le scepticisme affirme que :", ["la connaissance certaine est impossible", "tout est connaissable", "la raison est la source", "l'expérience est la source"], 0),
        ("L'éthique étudie :", ["les principes moraux", "la nature", "la société", "la connaissance"], 0),
        ("La morale est :", ["l'ensemble des règles de conduite", "la science", "la politique", "la religion"], 0),
        ("Le devoir est :", ["une obligation morale", "un droit", "un choix", "une liberté"], 0),
        ("La liberté est :", ["la capacité d'agir selon sa volonté", "l'absence de choix", "une contrainte", "un devoir"], 0),
        ("Le libre arbitre est :", ["la liberté de choisir", "l'absence de choix", "une contrainte", "un devoir"], 0),
        ("La responsabilité est :", ["répondre de ses actes", "un droit", "une liberté", "un choix"], 0),
        ("La justice est :", ["le respect des droits de chacun", "la force", "la vengeance", "l'égalité"], 0),
        ("L'égalité signifie :", ["les mêmes droits pour tous", "les mêmes richesses", "la même force", "le même âge"], 0),
        ("L'équité est :", ["la justice adaptée aux situations", "l'égalité stricte", "la force", "la vengeance"], 0),
        ("La vérité est :", ["la conformité avec la réalité", "une opinion", "une croyance", "une illusion"], 0),
        ("L'opinion est :", ["une croyance non démontrée", "une vérité", "une certitude", "un fait"], 0),
        ("La démonstration est :", ["une preuve logique", "une opinion", "une croyance", "une illusion"], 0),
        ("Le doute méthodique de Descartes :", ["douter de tout pour trouver la vérité", "ne jamais douter", "croire sans preuve", "refuser la raison"], 0),
        ("La conscience est :", ["la connaissance de soi et du monde", "l'inconscience", "la mémoire", "l'imagination"], 0),
        ("L'inconscient est :", ["ce qui échappe à la conscience", "la conscience", "la mémoire", "l'imagination"], 0),
        ("Freud a développé :", ["la psychanalyse", "la logique", "l'idéalisme", "l'empirisme"], 0),
        ("La perception est :", ["la connaissance par les sens", "la raison", "la mémoire", "l'imagination"], 0),
        ("L'imagination est :", ["la capacité de créer des images", "la perception", "la raison", "la mémoire"], 0),
        ("La mémoire est :", ["la capacité de conserver le passé", "l'imagination", "la perception", "la raison"], 0),
        ("Le langage est :", ["un système de signes pour communiquer", "la pensée", "la perception", "la mémoire"], 0),
        ("Le travail est :", ["une activité de transformation de la nature", "un loisir", "une contrainte", "un jeu"], 0),
        ("La technique est :", ["l'ensemble des moyens de production", "la science", "l'art", "la religion"], 0),
        ("L'art est :", ["la création de la beauté", "la technique", "la science", "la religion"], 0),
        ("La beauté est :", ["ce qui plaît universellement", "ce qui est utile", "ce qui est vrai", "ce qui est bon"], 0),
        ("La religion est :", ["un système de croyances", "une science", "une technique", "un art"], 0),
        ("La foi est :", ["une croyance sans preuve", "une certitude", "une démonstration", "une opinion"], 0),
        ("La politique est :", ["l'organisation de la vie en société", "la religion", "la science", "l'art"], 0),
        ("L'État est :", ["une organisation politique de la société", "une famille", "une entreprise", "une religion"], 0),
        ("Le contrat social de Rousseau :", ["l'accord des citoyens pour vivre ensemble", "un contrat commercial", "une loi", "un décret"], 0),
        ("La souveraineté est :", ["le pouvoir suprême de l'État", "un droit", "une liberté", "un devoir"], 0),
        ("La démocratie est :", ["le pouvoir du peuple", "le pouvoir d'un seul", "le pouvoir des riches", "le pouvoir des militaires"], 0),
        ("La philosophie africaine :", ["réfléchit sur les réalités africaines", "est une religion", "est une science", "est un art"], 0),
        ("L'ubuntu est :", ["une valeur africaine de solidarité", "une religion", "une science", "un art"], 0),
        ("La sagesse est :", ["la connaissance pratique de la vie", "la science", "la richesse", "le pouvoir"], 0),
        ("Le bonheur est :", ["le but de la vie selon les philosophes", "la richesse", "le pouvoir", "la gloire"], 0),
        ("L'hédonisme affirme que :", ["le plaisir est le bien suprême", "le devoir est suprême", "la raison est suprême", "la foi est suprême"], 0),
        ("Le stoïcisme affirme que :", ["la vertu est le bien suprême", "le plaisir est suprême", "la richesse est suprême", "le pouvoir est suprême"], 0),
        ("L'utilitarisme affirme que :", ["l'utile est le critère du bien", "le devoir est suprême", "le plaisir est suprême", "la foi est suprême"], 0),
        ("L'éthique de Kant repose sur :", ["l'impératif catégorique", "le plaisir", "l'utilité", "la foi"], 0),
        ("L'impératif catégorique de Kant :", ["agis selon une maxime universalisable", "agis pour ton plaisir", "agis pour ton intérêt", "agis par peur"], 0),
        ("La raison est :", ["la faculté de penser et de juger", "la mémoire", "l'imagination", "la perception"], 0),
        ("L'intelligence est :", ["la capacité de comprendre et résoudre", "la mémoire", "l'imagination", "la perception"], 0),
        ("La philosophie des sciences étudie :", ["les fondements de la science", "la religion", "l'art", "la politique"], 0),
        ("La science est :", ["une connaissance méthodique et vérifiable", "une opinion", "une croyance", "une illusion"], 0),
        ("L'hypothèse scientifique est :", ["une supposition à vérifier", "une certitude", "une opinion", "une croyance"], 0),
        ("L'expérience scientifique :", ["vérifie les hypothèses", "crée des opinions", "est inutile", "est une croyance"], 0),
        ("La philosophie morale étudie :", ["les principes du bien et du mal", "la nature", "la société", "la connaissance"], 0),
        ("Le temps est :", ["une réalité mesurable et vécue", "une illusion", "un objet", "une idée"], 0),
        ("La mort est :", ["la fin de la vie", "une illusion", "un objet", "une idée"], 0),
    ],
}


def build_mcq(subject, cfg, set_num):
    level_label, class_label, series, exam = cfg
    questions = MCQ_BANKS[subject]
    n = len(questions)
    start = (set_num - 1) * 20 % n
    selected = [questions[(start + i) % n] for i in range(20)]

    lines = [
        f"# CAMEROON {exam} {subject.upper()} P1 SET {set_num}",
        "",
        "## Multiple Choice Question Bank",
        "",
        f"**Level:** {level_label}",
        f"**Class:** {class_label}",
        f"**Series:** {series}",
        f"**Subject:** {subject}",
        f"**Exam:** {exam}",
        "",
        "**Instructions:**",
        "",
        "- Choisis la bonne réponse A, B, C ou D pour chaque question.",
        "- Reporte clairement tes réponses sur la feuille de réponses fournie.",
        "- Chaque question vaut le même nombre de points. Aucun point n'est retiré pour une mauvaise réponse.",
        "- Utilise le corrigé à la fin de l'épreuve pour vérifier tes réponses.",
        "",
        "---",
        "",
        "## QUESTIONS",
        "",
    ]

    for i, (q, options, correct) in enumerate(selected, 1):
        lines.append(f"**Q{i}.** {q}")
        lines.append("")
        for letter, opt in zip("ABCD", options):
            lines.append(f"{letter}. {opt}")
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("## CORRIGÉ")
    lines.append("")
    for i, (q, options, correct) in enumerate(selected, 1):
        lines.append(f"{i}. {options[correct]}")
    lines.append("")

    return "\n".join(lines)


def build_set(subject, cfg, set_num):
    level_label, class_label, series, exam = cfg
    sections = [
        ("SECTION 1", [
            f"Question structurée 1 pour {subject} ({class_label}).",
            f"Question structurée 2 pour {subject} ({class_label}).",
            f"Question structurée 3 pour {subject} ({class_label}).",
            f"Question structurée 4 pour {subject} ({class_label}).",
            f"Question structurée 5 pour {subject} ({class_label}).",
        ]),
        ("SECTION 2", [
            f"Question structurée 6 pour {subject} ({class_label}).",
            f"Question structurée 7 pour {subject} ({class_label}).",
            f"Question structurée 8 pour {subject} ({class_label}).",
            f"Question structurée 9 pour {subject} ({class_label}).",
            f"Question structurée 10 pour {subject} ({class_label}).",
        ]),
        ("SECTION 3", [
            f"Question structurée 11 pour {subject} ({class_label}).",
            f"Question structurée 12 pour {subject} ({class_label}).",
            f"Question structurée 13 pour {subject} ({class_label}).",
            f"Question structurée 14 pour {subject} ({class_label}).",
            f"Question structurée 15 pour {subject} ({class_label}).",
        ]),
        ("SECTION 4", [
            f"Question structurée 16 pour {subject} ({class_label}).",
            f"Question structurée 17 pour {subject} ({class_label}).",
            f"Question structurée 18 pour {subject} ({class_label}).",
            f"Question structurée 19 pour {subject} ({class_label}).",
            f"Question structurée 20 pour {subject} ({class_label}).",
        ]),
    ]

    lines = [
        f"# CAMEROON {exam} {subject.upper()} SET {set_num}",
        "",
        f"## Structural Question Bank - Set {set_num}",
        "",
        f"**Level:** {level_label}",
        f"**Class:** {class_label}",
        f"**Series:** {series}",
        f"**Subject:** {subject}",
        f"**Exam:** {exam}",
        "",
        "**Instructions:**",
        "",
        "- Réponds à toutes les questions de manière claire et organisée.",
        "- Montre tous les calculs et raisonnements lorsque c'est nécessaire.",
        "- Utilise la terminologie et les normes de présentation de l'examen camerounais.",
        "- Les schémas, tableaux et graphiques doivent être inclus lorsque c'est utile.",
        "",
        "---",
        "",
    ]

    qnum = 1
    for title, questions in sections:
        lines.append(f"## {title}")
        lines.append("")
        for q in questions:
            lines.append(f"**Q{qnum}.** {q}")
            lines.append("")
        qnum += 1

    return "\n".join(lines)


def main():
    for dirname, subject, level_label, class_label, series, exam, level in CLASSES:
        d = BASE / dirname
        d.mkdir(exist_ok=True)
        cfg = (level_label, class_label, series, exam)
        for set_num in (1, 2, 3):
            path = d / f"mcq-{set_num}.md"
            path.write_text(build_mcq(subject, cfg, set_num))
            print(f"Created: {path}")
        for set_num in (4, 5, 6, 7):
            path = d / f"set-{set_num}.md"
            path.write_text(build_set(subject, cfg, set_num))
            print(f"Created: {path}")


if __name__ == "__main__":
    main()
