#!/usr/bin/env python3
"""
Generate genuine French MCQ (Paper 1) content for francophone subjects.
Each subject gets 3 MCQ papers (mcq-1, mcq-2, mcq-3) with real questions,
answer options, and answer keys appropriate to the BEPC/Bac curriculum.
"""

from pathlib import Path

BASE = Path("/home/victoire-ws/Documents/ChatGPT/productivity - goals/study-spark/content/papers")

# Each subject: (dir, subject_name, level_label, class_label, series_label, exam, questions)
# questions is a list of (question, [4 options], correct_index)
SUBJECTS = {
    "mathematiques": {
        "subject": "Mathématiques",
        "level": "Ordinary Level (Collège)",
        "class": "Troisième",
        "series": "Tronc Commun",
        "exam": "BEPC",
        "questions": [
            ("Résoudre l'équation : $3x - 7 = 2x + 5$.", ["$x = 12$", "$x = 2$", "$x = -2$", "$x = 5$"], 0),
            ("La valeur de $\\sqrt{144}$ est :", ["12", "14", "11", "13"], 0),
            ("Simplifier : $\\frac{3}{4} + \\frac{5}{6}$.", ["$\\frac{19}{12}$", "$\\frac{8}{10}$", "$\\frac{9}{12}$", "$\\frac{15}{24}$"], 0),
            ("Le PGCD de 24 et 36 est :", ["12", "6", "18", "72"], 0),
            ("Résoudre : $2x + 3 = 15$.", ["$x = 6$", "$x = 9$", "$x = 5$", "$x = 7$"], 0),
            ("$10\\%$ de 250 est :", ["25", "2,5", "250", "50"], 0),
            ("L'aire d'un carré de côté 5 cm est :", ["25 cm²", "20 cm²", "10 cm²", "50 cm²"], 0),
            ("Le volume d'un cube d'arête 3 cm est :", ["27 cm³", "9 cm³", "18 cm³", "12 cm³"], 0),
            ("Résoudre : $x^2 = 49$.", ["$x = 7$ ou $x = -7$", "$x = 7$", "$x = -7$", "$x = 24,5$"], 0),
            ("La médiane de la série 3, 5, 7, 9, 11 est :", ["7", "5", "9", "6"], 0),
            ("$\\frac{2}{3}$ de 90 est :", ["60", "30", "45", "135"], 0),
            ("Le périmètre d'un rectangle de 8 cm sur 5 cm est :", ["26 cm", "40 cm", "13 cm", "80 cm"], 0),
            ("Résoudre le système : $x + y = 10$ et $x - y = 4$.", ["$x = 7$, $y = 3$", "$x = 3$, $y = 7$", "$x = 6$, $y = 4$", "$x = 5$, $y = 5$"], 0),
            ("$3^4$ est égal à :", ["81", "12", "64", "27"], 0),
            ("La moyenne de 4, 6, 8, 10 est :", ["7", "6", "8", "9"], 0),
            ("Un angle droit mesure :", ["90°", "180°", "45°", "360°"], 0),
            ("Résoudre : $5x - 2 = 3x + 8$.", ["$x = 5$", "$x = 3$", "$x = 10$", "$x = 6$"], 0),
            ("Le nombre premier parmi les suivants est :", ["17", "15", "21", "9"], 0),
            ("$\\frac{1}{2} + \\frac{1}{3}$ est égal à :", ["$\\frac{5}{6}$", "$\\frac{2}{5}$", "$\\frac{1}{6}$", "$\\frac{3}{5}$"], 0),
            ("L'équation de la droite passant par l'origine et de pente 2 est :", ["$y = 2x$", "$y = x + 2$", "$y = 2x + 1$", "$x = 2y$"], 0),
            ("Le complément de 35° est :", ["55°", "145°", "65°", "125°"], 0),
            ("$0,5$ en fraction est :", ["$\\frac{1}{2}$", "$\\frac{5}{10}$", "$\\frac{1}{5}$", "$\\frac{2}{5}$"], 0),
            ("Le PPCM de 4 et 6 est :", ["12", "24", "6", "2"], 0),
            ("Résoudre : $\\frac{x}{4} = 3$.", ["$x = 12$", "$x = 7$", "$x = 1$", "$x = 3$"], 0),
            ("L'aire d'un triangle de base 10 cm et hauteur 6 cm est :", ["30 cm²", "60 cm²", "16 cm²", "15 cm²"], 0),
            ("$2^5$ est égal à :", ["32", "25", "10", "16"], 0),
            ("Le plus grand nombre parmi : 0,25 ; 0,5 ; 0,125 ; 0,75 est :", ["0,75", "0,5", "0,25", "0,125"], 0),
            ("Résoudre : $3(x - 2) = 9$.", ["$x = 5$", "$x = 3$", "$x = 11$", "$x = 1$"], 0),
            ("La somme des angles d'un triangle est :", ["180°", "90°", "360°", "270°"], 0),
            ("$\\sqrt{81}$ est égal à :", ["9", "8", "7", "10"], 0),
            ("Le coefficient de $x$ dans $5x + 3$ est :", ["5", "3", "8", "x"], 0),
            ("Résoudre : $x - 8 = 12$.", ["$x = 20$", "$x = 4$", "$x = 96$", "$x = 12$"], 0),
            ("$25\\%$ de 80 est :", ["20", "25", "40", "5"], 0),
            ("Le symétrique de 7 par rapport à 0 est :", ["-7", "7", "0", "14"], 0),
            ("L'aire d'un cercle de rayon 3 cm (π ≈ 3,14) est :", ["28,26 cm²", "18,84 cm²", "9,42 cm²", "56,52 cm²"], 0),
            ("Résoudre : $2x^2 = 32$.", ["$x = 4$ ou $x = -4$", "$x = 4$", "$x = 16$", "$x = 8$"], 0),
            ("Le nombre 0,75 en pourcentage est :", ["75%", "7,5%", "0,75%", "750%"], 0),
            ("La distance entre -3 et 5 sur la droite numérique est :", ["8", "2", "-8", "15"], 0),
            ("$\\frac{7}{8} - \\frac{3}{8}$ est égal à :", ["$\\frac{1}{2}$", "$\\frac{4}{8}$", "$\\frac{10}{8}$", "$\\frac{1}{4}$"], 0),
            ("Le périmètre d'un cercle de rayon 5 cm (π ≈ 3,14) est :", ["31,4 cm", "15,7 cm", "78,5 cm", "25 cm"], 0),
            ("Résoudre : $4x + 1 = 2x + 9$.", ["$x = 4$", "$x = 5$", "$x = 8$", "$x = 2$"], 0),
            ("Le plus petit multiple commun de 3 et 5 est :", ["15", "8", "30", "3"], 0),
            ("$(-3) \\times (-4)$ est égal à :", ["12", "-12", "7", "-7"], 0),
            ("L'aire d'un parallélogramme de base 8 cm et hauteur 5 cm est :", ["40 cm²", "13 cm²", "26 cm²", "80 cm²"], 0),
            ("Résoudre : $\\frac{2x}{3} = 8$.", ["$x = 12$", "$x = 24$", "$x = 6$", "$x = 4$"], 0),
            ("Le nombre 0,2 en fraction irréductible est :", ["$\\frac{1}{5}$", "$\\frac{2}{10}$", "$\\frac{1}{2}$", "$\\frac{2}{5}$"], 0),
            ("La valeur de $5!$ (factorielle) est :", ["120", "25", "15", "720"], 0),
            ("Résoudre : $x + 3 = 2x - 1$.", ["$x = 4$", "$x = 2$", "$x = -4$", "$x = 1$"], 0),
            ("Le PGCD de 18 et 27 est :", ["9", "3", "6", "54"], 0),
            ("L'aire d'un losange de diagonales 6 cm et 8 cm est :", ["24 cm²", "48 cm²", "14 cm²", "28 cm²"], 0),
            ("$\\frac{3}{5}$ de 100 est :", ["60", "40", "35", "65"], 0),
            ("Résoudre : $x^2 - 9 = 0$.", ["$x = 3$ ou $x = -3$", "$x = 3$", "$x = 9$", "$x = 4,5$"], 0),
            ("Le nombre 0,125 en fraction est :", ["$\\frac{1}{8}$", "$\\frac{1}{4}$", "$\\frac{1}{5}$", "$\\frac{1}{12}$"], 0),
            ("La somme de 2,5 et 3,75 est :", ["6,25", "5,25", "6,5", "5,75"], 0),
            ("Résoudre : $7x = 49$.", ["$x = 7$", "$x = 42$", "$x = 56$", "$x = 343$"], 0),
            ("Le volume d'un pavé droit de 4 cm × 3 cm × 2 cm est :", ["24 cm³", "9 cm³", "12 cm³", "48 cm³"], 0),
            ("$\\frac{2}{5} \\times \\frac{3}{4}$ est égal à :", ["$\\frac{3}{10}$", "$\\frac{6}{20}$", "$\\frac{5}{9}$", "$\\frac{1}{10}$"], 0),
            ("Le nombre 0,6 en pourcentage est :", ["60%", "6%", "0,6%", "600%"], 0),
            ("Résoudre : $x + 5 = 2x - 3$.", ["$x = 8$", "$x = 2$", "$x = -8$", "$x = 5$"], 0),
        ],
    },
    "physique-chimie": {
        "subject": "Physique-Chimie",
        "level": "Ordinary Level (Collège)",
        "class": "Troisième",
        "series": "Tronc Commun",
        "exam": "BEPC",
        "questions": [
            ("L'unité de la tension électrique est :", ["le volt", "l'ampère", "l'ohm", "le watt"], 0),
            ("L'intensité du courant se mesure avec :", ["un ampèremètre", "un voltmètre", "un ohmmètre", "un wattmètre"], 0),
            ("La formule de la loi d'Ohm est :", ["U = R × I", "U = R / I", "I = U × R", "R = U × I"], 0),
            ("L'unité de la résistance électrique est :", ["l'ohm", "le volt", "l'ampère", "le joule"], 0),
            ("La masse volumique se calcule par :", ["ρ = m / V", "ρ = m × V", "ρ = V / m", "ρ = m + V"], 0),
            ("L'unité de la force est :", ["le newton", "le kilogramme", "le pascal", "le joule"], 0),
            ("La pression se calcule par :", ["P = F / S", "P = F × S", "P = S / F", "P = F + S"], 0),
            ("L'unité de la pression est :", ["le pascal", "le newton", "le joule", "le watt"], 0),
            ("Le symbole chimique de l'eau est :", ["H₂O", "CO₂", "O₂", "H₂"], 0),
            ("Le pH d'une solution acide est :", ["inférieur à 7", "supérieur à 7", "égal à 7", "égal à 0"], 0),
            ("L'énergie cinétique se calcule par :", ["Ec = ½ mv²", "Ec = mv", "Ec = mgh", "Ec = ½ mgh"], 0),
            ("L'unité de l'énergie est :", ["le joule", "le watt", "le newton", "le pascal"], 0),
            ("La vitesse se calcule par :", ["v = d / t", "v = d × t", "v = t / d", "v = d + t"], 0),
            ("Le symbole chimique du dioxyde de carbone est :", ["CO₂", "O₂", "CO", "C₂O"], 0),
            ("Un corps pur est :", ["constitué d'une seule espèce chimique", "un mélange", "un alliage", "une solution"], 0),
            ("La température se mesure avec :", ["un thermomètre", "un baromètre", "un manomètre", "un hygromètre"], 0),
            ("L'unité de la température en SI est :", ["le kelvin", "le degré Celsius", "le degré Fahrenheit", "le joule"], 0),
            ("Le courant électrique est un déplacement de :", ["charges électriques", "molécules", "atomes", "neutrons"], 0),
            ("Dans un circuit en série, l'intensité est :", ["la même partout", "différente partout", "nulle", "maximale au début"], 0),
            ("Le symbole chimique du sel de cuisine (chlorure de sodium) est :", ["NaCl", "NaCl₂", "Na₂Cl", "ClNa₂"], 0),
            ("La puissance électrique se calcule par :", ["P = U × I", "P = U / I", "P = I / U", "P = U + I"], 0),
            ("L'unité de la puissance est :", ["le watt", "le joule", "le volt", "l'ampère"], 0),
            ("Le poids d'un corps se calcule par :", ["P = m × g", "P = m / g", "P = g / m", "P = m + g"], 0),
            ("La valeur de g (accélération de pesanteur) sur Terre est environ :", ["9,8 N/kg", "10 N/kg", "98 N/kg", "0,98 N/kg"], 0),
            ("Une solution basique a un pH :", ["supérieur à 7", "inférieur à 7", "égal à 7", "égal à 14"], 0),
            ("Le symbole chimique de l'oxygène est :", ["O", "O₂", "Ox", "Og"], 0),
            ("La distillation permet de :", ["séparer les constituants d'un mélange homogène", "mélanger deux liquides", "solidifier un liquide", "filtrer un solide"], 0),
            ("L'aimant attire :", ["le fer", "le cuivre", "l'aluminium", "le verre"], 0),
            ("Le courant alternatif change de sens :", ["périodiquement", "jamais", "une seule fois", "aléatoirement"], 0),
            ("L'unité de la fréquence est :", ["le hertz", "le watt", "le volt", "l'ohm"], 0),
            ("Le symbole chimique du carbone est :", ["C", "Ca", "Co", "Cr"], 0),
            ("La fusion est le passage de :", ["solide à liquide", "liquide à gaz", "gaz à liquide", "solide à gaz"], 0),
            ("La vaporisation est le passage de :", ["liquide à gaz", "solide à liquide", "gaz à solide", "liquide à solide"], 0),
            ("Le symbole chimique de l'azote est :", ["N", "Az", "Na", "Ni"], 0),
            ("Un isolant électrique est :", ["le plastique", "le cuivre", "le fer", "l'aluminium"], 0),
            ("Un conducteur électrique est :", ["le cuivre", "le verre", "le plastique", "le bois"], 0),
            ("L'énergie potentielle de pesanteur se calcule par :", ["Ep = mgh", "Ep = ½ mv²", "Ep = mv", "Ep = mgh²"], 0),
            ("Le symbole chimique du fer est :", ["Fe", "F", "Fr", "Ir"], 0),
            ("La condensation est le passage de :", ["gaz à liquide", "liquide à gaz", "solide à liquide", "gaz à solide"], 0),
            ("L'unité de la charge électrique est :", ["le coulomb", "le volt", "l'ampère", "l'ohm"], 0),
            ("Le symbole chimique de l'hydrogène est :", ["H", "Hy", "He", "Hg"], 0),
            ("La dilution consiste à :", ["ajouter de l'eau à une solution", "concentrer une solution", "chauffer une solution", "refroidir une solution"], 0),
            ("Le symbole chimique du calcium est :", ["Ca", "C", "Cl", "Cr"], 0),
            ("Un aimant possède :", ["deux pôles", "un pôle", "trois pôles", "aucun pôle"], 0),
            ("La sublimation est le passage de :", ["solide à gaz", "gaz à liquide", "liquide à solide", "gaz à solide"], 0),
            ("Le symbole chimique du sodium est :", ["Na", "So", "S", "N"], 0),
            ("L'énergie mécanique est la somme de :", ["l'énergie cinétique et potentielle", "l'énergie thermique et électrique", "l'énergie chimique et nucléaire", "l'énergie lumineuse et sonore"], 0),
            ("Le symbole chimique du chlore est :", ["Cl", "Ch", "C", "Cr"], 0),
            ("Un circuit électrique fermé permet :", ["le passage du courant", "l'arrêt du courant", "la coupure du courant", "aucun courant"], 0),
            ("Le symbole chimique du potassium est :", ["K", "P", "Po", "Ka"], 0),
            ("La masse se mesure avec :", ["une balance", "un thermomètre", "un baromètre", "un voltmètre"], 0),
            ("Le symbole chimique du zinc est :", ["Zn", "Z", "Zi", "Zr"], 0),
            ("L'unité de la masse en SI est :", ["le kilogramme", "le gramme", "la tonne", "le newton"], 0),
            ("Le symbole chimique du cuivre est :", ["Cu", "Co", "C", "Cp"], 0),
            ("La solidification est le passage de :", ["liquide à solide", "solide à liquide", "gaz à liquide", "liquide à gaz"], 0),
            ("Le symbole chimique de l'aluminium est :", ["Al", "A", "Am", "Ar"], 0),
            ("L'ampèremètre se branche :", ["en série", "en dérivation", "en parallèle", "n'importe comment"], 0),
            ("Le voltmètre se branche :", ["en dérivation", "en série", "en parallèle", "n'importe comment"], 0),
            ("Le symbole chimique du plomb est :", ["Pb", "Pl", "P", "Po"], 0),
            ("La lumière se propage :", ["en ligne droite", "en courbe", "en zigzag", "en cercle"], 0),
        ],
    },
    "svt": {
        "subject": "Sciences de la Vie et de la Terre",
        "level": "Ordinary Level (Collège)",
        "class": "Troisième",
        "series": "Tronc Commun",
        "exam": "BEPC",
        "questions": [
            ("L'unité de base du vivant est :", ["la cellule", "l'atome", "la molécule", "l'organe"], 0),
            ("La photosynthèse se déroule dans :", ["les chloroplastes", "les mitochondries", "le noyau", "la membrane"], 0),
            ("Le dioxygène est produit par :", ["la photosynthèse", "la respiration", "la digestion", "la fermentation"], 0),
            ("L'organe de la respiration chez l'homme est :", ["le poumon", "le cœur", "le foie", "le rein"], 0),
            ("Le sang est pompé par :", ["le cœur", "le poumon", "le cerveau", "le foie"], 0),
            ("L'unité de filtration du rein est :", ["le néphron", "le neurone", "l'alvéole", "le glomérule"], 0),
            ("La cellule nerveuse s'appelle :", ["le neurone", "le néphron", "le globule", "le gamète"], 0),
            ("L'ADN se trouve dans :", ["le noyau", "le cytoplasme", "la membrane", "la paroi"], 0),
            ("La reproduction sexuée fait intervenir :", ["deux gamètes", "un seul gamète", "aucun gamète", "des spores"], 0),
            ("Le gamète mâle chez l'homme est :", ["le spermatozoïde", "l'ovule", "le globule rouge", "le neurone"], 0),
            ("Le gamète femelle chez la femme est :", ["l'ovule", "le spermatozoïde", "le globule blanc", "le neurone"], 0),
            ("L'écosystème est constitué de :", ["le biotope et la biocénose", "uniquement des plantes", "uniquement des animaux", "uniquement de l'eau"], 0),
            ("Le prédateur est un être qui :", ["chasse et se nourrit d'autres êtres", "est chassé", "se nourrit de plantes", "décompose la matière"], 0),
            ("La chaîne alimentaire commence par :", ["un producteur", "un consommateur", "un décomposeur", "un prédateur"], 0),
            ("Le décomposeur transforme la matière organique en :", ["matière minérale", "matière organique", "énergie", "gaz carbonique"], 0),
            ("La fécondation est la fusion de :", ["deux gamètes", "deux cellules somatiques", "deux neurones", "deux globules"], 0),
            ("Le groupe sanguin universel donneur est :", ["O", "A", "B", "AB"], 0),
            ("Le groupe sanguin universel receveur est :", ["AB", "O", "A", "B"], 0),
            ("La vaccination consiste à :", ["injecter un antigène atténué", "injecter des anticorps", "prendre des antibiotiques", "faire une transfusion"], 0),
            ("L'antibiotique agit contre :", ["les bactéries", "les virus", "les parasites", "les champignons"], 0),
            ("Le virus du SIDA s'appelle :", ["le VIH", "le VHB", "le VHC", "le VPH"], 0),
            ("La digestion commence dans :", ["la bouche", "l'estomac", "l'intestin", "l'œsophage"], 0),
            ("L'enzyme digestive de la salive est :", ["l'amylase", "la pepsine", "la lipase", "la trypsine"], 0),
            ("La bile est produite par :", ["le foie", "l'estomac", "le pancréas", "la vésicule"], 0),
            ("L'insuline est produite par :", ["le pancréas", "le foie", "le rein", "la thyroïde"], 0),
            ("Le diabète est dû à un problème de :", ["l'insuline", "l'adrénaline", "la thyroxine", "l'œstrogène"], 0),
            ("La cellule végétale possède en plus de la cellule animale :", ["une paroi et des chloroplastes", "un noyau", "une membrane", "des mitochondries"], 0),
            ("La mitose permet :", ["la division cellulaire", "la formation des gamètes", "la respiration", "la digestion"], 0),
            ("La méiose permet :", ["la formation des gamètes", "la division cellulaire", "la croissance", "la régénération"], 0),
            ("Le chromosome est constitué de :", ["ADN et protéines", "ARN et lipides", "glucides et protéines", "eau et sels minéraux"], 0),
            ("Le nombre de chromosomes chez l'homme est :", ["46", "44", "48", "23"], 0),
            ("Le caryotype humain normal possède :", ["23 paires de chromosomes", "46 paires", "22 paires", "24 paires"], 0),
            ("La transpiration se fait par :", ["la peau", "le rein", "le poumon", "le foie"], 0),
            ("L'homéostasie est :", ["le maintien de l'équilibre interne", "la croissance", "la reproduction", "la digestion"], 0),
            ("Le réflexe est :", ["une réponse rapide et involontaire", "une réponse lente", "une action volontaire", "une pensée"], 0),
            ("L'arc réflexe passe par :", ["la moelle épinière", "le cerveau", "le cervelet", "le bulbe"], 0),
            ("Le cervelet contrôle :", ["l'équilibre", "la mémoire", "la respiration", "la digestion"], 0),
            ("Le bulbe rachidien contrôle :", ["la respiration", "la mémoire", "l'équilibre", "la vision"], 0),
            ("La géologie étudie :", ["la Terre", "les étoiles", "les plantes", "les animaux"], 0),
            ("Les roches magmatiques proviennent :", ["du refroidissement du magma", "de la sédimentation", "du métamorphisme", "de l'érosion"], 0),
            ("Le basalte est une roche :", ["volcanique", "sédimentaire", "métamorphique", "organique"], 0),
            ("Le granite est une roche :", ["plutonique", "volcanique", "sédimentaire", "métamorphique"], 0),
            ("Le calcaire est une roche :", ["sédimentaire", "volcanique", "plutonique", "métamorphique"], 0),
            ("Le fossile est :", ["un reste d'être vivant conservé", "une roche", "un minéral", "un volcan"], 0),
            ("La tectonique des plaques explique :", ["les séismes et volcans", "la photosynthèse", "la digestion", "la respiration"], 0),
            ("Le séisme est dû à :", ["la rupture des roches en profondeur", "la pluie", "le vent", "la chaleur"], 0),
            ("L'échelle de Richter mesure :", ["la magnitude d'un séisme", "la température", "la pression", "l'altitude"], 0),
            ("Le volcanisme est lié à :", ["la remontée du magma", "la pluie", "le vent", "la neige"], 0),
            ("L'érosion est :", ["l'usure des roches", "la formation des roches", "la fusion des roches", "la cristallisation"], 0),
            ("Le sol est formé par :", ["l'altération des roches", "la photosynthèse", "la respiration", "la transpiration"], 0),
            ("L'humus est :", ["de la matière organique décomposée", "une roche", "un minéral", "de l'eau"], 0),
            ("La couche d'ozone protège contre :", ["les UV", "les rayons X", "les infrarouges", "la lumière visible"], 0),
            ("L'effet de serre est dû à :", ["l'accumulation de CO₂", "la couche d'ozone", "les UV", "la pluie"], 0),
            ("Le réchauffement climatique est causé par :", ["l'augmentation des gaz à effet de serre", "la diminution de l'oxygène", "l'augmentation de l'azote", "la baisse du CO₂"], 0),
            ("La biodiversité est :", ["la variété des êtres vivants", "la quantité d'eau", "la température", "la pression"], 0),
            ("L'espèce menacée est :", ["une espèce en danger de disparition", "une espèce abondante", "une espèce nouvelle", "une espèce domestique"], 0),
            ("La contraception permet :", ["d'éviter une grossesse", "de favoriser la grossesse", "de guérir une maladie", "de stimuler la croissance"], 0),
            ("Le préservatif protège contre :", ["les IST et le VIH", "la grossesse uniquement", "le diabète", "le paludisme"], 0),
            ("Le paludisme est transmis par :", ["le moustique", "la mouche", "le rat", "le pou"], 0),
            ("Le plasmodium est :", ["le parasite du paludisme", "un virus", "une bactérie", "un champignon"], 0),
        ],
    },
    "histoire-geographie": {
        "subject": "Histoire-Géographie",
        "level": "Ordinary Level (Collège)",
        "class": "Troisième",
        "series": "Tronc Commun",
        "exam": "BEPC",
        "questions": [
            ("Le Cameroun est situé en :", ["Afrique centrale", "Afrique de l'Ouest", "Afrique de l'Est", "Afrique du Nord"], 0),
            ("La capitale politique du Cameroun est :", ["Yaoundé", "Douala", "Bafoussam", "Garoua"], 0),
            ("La capitale économique du Cameroun est :", ["Douala", "Yaoundé", "Kribi", "Buea"], 0),
            ("Le Cameroun a obtenu son indépendance en :", ["1960", "1958", "1962", "1972"], 0),
            ("Le premier président du Cameroun fut :", ["Ahmadou Ahidjo", "Paul Biya", "Ruben Um Nyobé", "Ernest Ouandié"], 0),
            ("Le Cameroun compte combien de régions ?", ["10", "8", "12", "6"], 0),
            ("Le fleuve le plus long du Cameroun est :", ["la Sanaga", "le Wouri", "le Nyong", "la Bénoué"], 0),
            ("Le mont Cameroun est :", ["un volcan", "un fleuve", "une ville", "un lac"], 0),
            ("L'altitude du mont Cameroun est environ :", ["4095 m", "2000 m", "5000 m", "3000 m"], 0),
            ("Le climat équatorial se caractérise par :", ["des pluies abondantes toute l'année", "une saison sèche longue", "des températures froides", "peu de pluie"], 0),
            ("Le Cameroun est surnommé :", ["l'Afrique en miniature", "le pays des mille collines", "la perle de l'Afrique", "le grenier de l'Afrique"], 0),
            ("La première guerre mondiale a eu lieu en :", ["1914-1918", "1939-1945", "1870-1871", "1918-1920"], 0),
            ("La deuxième guerre mondiale a eu lieu en :", ["1939-1945", "1914-1918", "1945-1950", "1929-1933"], 0),
            ("La Révolution française a eu lieu en :", ["1789", "1776", "1804", "1815"], 0),
            ("Napoléon Bonaparte a été couronné empereur en :", ["1804", "1789", "1815", "1799"], 0),
            ("La traite négrière transatlantique concernait :", ["l'Afrique et l'Amérique", "l'Europe et l'Asie", "l'Afrique et l'Asie", "l'Europe et l'Amérique"], 0),
            ("La colonisation du Cameroun par l'Allemagne a commencé en :", ["1884", "1916", "1900", "1870"], 0),
            ("Après la Première Guerre mondiale, le Cameroun fut partagé entre :", ["la France et l'Angleterre", "l'Allemagne et la France", "la France et l'Espagne", "l'Angleterre et l'Italie"], 0),
            ("Le Cameroun oriental était sous mandat :", ["français", "anglais", "allemand", "belge"], 0),
            ("Le Cameroun occidental était sous mandat :", ["anglais", "français", "allemand", "belge"], 0),
            ("Le référendum de 1961 a permis :", ["la réunification du Cameroun", "l'indépendance", "la colonisation", "la partition"], 0),
            ("La République fédérale du Cameroun a été créée en :", ["1961", "1960", "1972", "1984"], 0),
            ("Le Cameroun est devenu République unie en :", ["1972", "1961", "1984", "1960"], 0),
            ("Le Cameroun est devenu République du Cameroun en :", ["1984", "1972", "1961", "1990"], 0),
            ("Le multipartisme a été rétabli au Cameroun en :", ["1990", "1980", "1972", "2000"], 0),
            ("L'ONU a été créée en :", ["1945", "1919", "1939", "1950"], 0),
            ("La SDN a été créée en :", ["1919", "1945", "1939", "1900"], 0),
            ("L'OUA a été créée en :", ["1963", "1945", "1975", "1955"], 0),
            ("L'Union africaine a remplacé l'OUA en :", ["2002", "1990", "1980", "2010"], 0),
            ("La CEMAC est une organisation :", ["économique et monétaire", "politique", "militaire", "culturelle"], 0),
            ("Le siège de la CEMAC est à :", ["Yaoundé", "Douala", "Libreville", "N'Djamena"], 0),
            ("La monnaie utilisée au Cameroun est :", ["le franc CFA", "le dollar", "l'euro", "le naira"], 0),
            ("Le Cameroun est membre de :", ["l'ONU, l'UA et la CEMAC", "l'OTAN", "l'UE", "l'ALENA"], 0),
            ("Le relief du Cameroun comprend :", ["des montagnes, plateaux et plaines", "uniquement des plaines", "uniquement des montagnes", "uniquement des déserts"], 0),
            ("Le lac Tchad se situe au :", ["nord du Cameroun", "sud du Cameroun", "est du Cameroun", "ouest du Cameroun"], 0),
            ("La principale culture d'exportation du Cameroun est :", ["le cacao", "le blé", "le riz", "la pomme de terre"], 0),
            ("Le Cameroun est un grand producteur de :", ["café et cacao", "pétrole et diamant", "or et argent", "blé et maïs"], 0),
            ("Le port le plus important du Cameroun est :", ["Douala", "Kribi", "Limbé", "Garoua"], 0),
            ("Le barrage de Lagdo se trouve sur :", ["la Bénoué", "la Sanaga", "le Wouri", "le Nyong"], 0),
            ("Le barrage de Song Loulou se trouve sur :", ["la Sanaga", "la Bénoué", "le Wouri", "le Nyong"], 0),
            ("La population du Cameroun est d'environ :", ["27 millions", "10 millions", "50 millions", "5 millions"], 0),
            ("La densité de population est la plus forte :", ["dans les grandes villes", "dans le désert", "en montagne", "en forêt dense"], 0),
            ("L'exode rural est :", ["le départ des campagnes vers les villes", "le départ des villes vers les campagnes", "l'immigration", "l'émigration"], 0),
            ("Le taux de natalité est :", ["le nombre de naissances pour 1000 habitants", "le nombre de décès", "la croissance", "la densité"], 0),
            ("Le taux de mortalité est :", ["le nombre de décès pour 1000 habitants", "le nombre de naissances", "la densité", "la croissance"], 0),
            ("L'accroissement naturel est :", ["natalité - mortalité", "natalité + mortalité", "immigration - émigration", "densité × surface"], 0),
            ("La savane se trouve principalement :", ["au nord du Cameroun", "au sud du Cameroun", "à l'ouest", "sur le littoral"], 0),
            ("La forêt dense se trouve principalement :", ["au sud du Cameroun", "au nord", "à l'extrême-nord", "sur les hauts plateaux"], 0),
            ("Le climat soudano-sahélien se trouve :", ["au nord du Cameroun", "au sud", "à l'ouest", "sur le littoral"], 0),
            ("Le climat équatorial se trouve :", ["au sud du Cameroun", "au nord", "à l'extrême-nord", "sur les hauts plateaux"], 0),
            ("Le climat tropical humide se trouve :", ["dans le centre du Cameroun", "au nord", "au sud", "sur le littoral"], 0),
            ("L'agriculture vivrière produit :", ["du manioc, maïs et banane", "du cacao et café", "du coton et arachide", "du pétrole"], 0),
            ("L'agriculture de rente produit :", ["du cacao, café et coton", "du manioc et maïs", "de la banane plantain", "des légumes"], 0),
            ("Le pétrole est exploité :", ["dans le bassin du Rio del Rey", "au mont Cameroun", "à Yaoundé", "à Bafoussam"], 0),
            ("Le tourisme au Cameroun est favorisé par :", ["la diversité des paysages", "le désert", "la neige", "les glaciers"], 0),
            ("Le parc national de Waza se trouve :", ["à l'extrême-nord", "au sud", "à l'ouest", "sur le littoral"], 0),
            ("Le parc national de Korup se trouve :", ["au sud-ouest", "au nord", "à l'est", "au centre"], 0),
            ("La déforestation est :", ["la destruction de la forêt", "la plantation d'arbres", "la protection de la forêt", "la culture"], 0),
            ("Le développement durable vise :", ["à satisfaire les besoins sans compromettre l'avenir", "la croissance rapide", "l'exploitation maximale", "la consommation"], 0),
            ("La mondialisation est :", ["l'interdépendance croissante des économies", "l'isolement des pays", "la guerre", "la colonisation"], 0),
        ],
    },
    "francais": {
        "subject": "Français",
        "level": "Ordinary Level (Collège)",
        "class": "Troisième",
        "series": "Tronc Commun",
        "exam": "BEPC",
        "questions": [
            ("Le pluriel de « cheval » est :", ["chevaux", "chevals", "chevaus", "cheveaux"], 0),
            ("Le féminin de « acteur » est :", ["actrice", "acteuse", "actrice", "acteur"], 0),
            ("Le synonyme de « rapide » est :", ["vite", "lent", "lourd", "haut"], 0),
            ("L'antonyme de « chaud » est :", ["froid", "tiède", "brûlant", "doux"], 0),
            ("Le participe passé de « prendre » est :", ["pris", "prendu", "pris", "prenu"], 0),
            ("Le verbe « aller » au futur simple (je) est :", ["j'irai", "j'allai", "j'aille", "j'allais"], 0),
            ("Le verbe « être » au présent (nous) est :", ["nous sommes", "nous étions", "nous serons", "nous soyons"], 0),
            ("Le verbe « avoir » au présent (ils) est :", ["ils ont", "ils avaient", "ils auront", "ils aient"], 0),
            ("La phrase « Il fait beau » est :", ["une phrase déclarative", "une phrase interrogative", "une phrase impérative", "une phrase exclamative"], 0),
            ("La phrase « Viens ici ! » est :", ["impérative", "déclarative", "interrogative", "exclamative"], 0),
            ("Le nom commun de « beau » est :", ["la beauté", "le beau", "la beauté", "le bel"], 0),
            ("Le complément d'objet direct répond à la question :", ["quoi ?", "où ?", "quand ?", "comment ?"], 0),
            ("Le complément circonstanciel de lieu répond à la question :", ["où ?", "quoi ?", "qui ?", "combien ?"], 0),
            ("Le sujet de la phrase « Les enfants jouent » est :", ["les enfants", "jouent", "les", "enfants jouent"], 0),
            ("Le verbe « finir » au passé composé (il) est :", ["il a fini", "il finit", "il finira", "il finissait"], 0),
            ("Le mot « rapidement » est :", ["un adverbe", "un adjectif", "un nom", "un verbe"], 0),
            ("Le mot « joli » est :", ["un adjectif", "un adverbe", "un nom", "un verbe"], 0),
            ("Le mot « table » est :", ["un nom", "un verbe", "un adjectif", "un adverbe"], 0),
            ("Le mot « manger » est :", ["un verbe", "un nom", "un adjectif", "un adverbe"], 0),
            ("La comparaison utilise :", ["comme, tel, semblable à", "mais, ou, et", "car, donc", "ni, or"], 0),
            ("La métaphore est :", ["une comparaison sans outil", "une exagération", "une atténuation", "une répétition"], 0),
            ("L'hyperbole est :", ["une exagération", "une atténuation", "une comparaison", "une répétition"], 0),
            ("La litote est :", ["une atténuation", "une exagération", "une comparaison", "une métaphore"], 0),
            ("La personnification donne :", ["des attributs humains à un objet", "des attributs d'objet à un humain", "des attributs animaux", "aucun attribut"], 0),
            ("Le registre de langue familier utilise :", ["des expressions familières", "un vocabulaire soutenu", "un vocabulaire courant", "des termes techniques"], 0),
            ("Le registre soutenu utilise :", ["un vocabulaire recherché", "des expressions familières", "un langage courant", "de l'argot"], 0),
            ("Le texte narratif :", ["raconte une histoire", "explique une idée", "décrit un lieu", "convainc"], 0),
            ("Le texte argumentatif :", ["convainc et persuade", "raconte une histoire", "décrit", "donne des ordres"], 0),
            ("Le texte descriptif :", ["décrit un lieu, une personne", "raconte", "argumente", "explique"], 0),
            ("Le texte explicatif :", ["explique un phénomène", "raconte", "convainc", "décrit"], 0),
            ("Le discours direct utilise :", ["les guillemets et tirets", "les parenthèses", "les crochets", "les points de suspension"], 0),
            ("Le discours indirect introduit par :", ["que, si, de", "mais, ou", "et, donc", "ni, car"], 0),
            ("Le passé simple est utilisé :", ["dans le récit écrit", "dans la conversation", "au futur", "au présent"], 0),
            ("L'imparfait exprime :", ["une action passée en cours", "une action future", "une action présente", "une action terminée"], 0),
            ("Le futur simple exprime :", ["une action future", "une action passée", "une action présente", "une action habituelle"], 0),
            ("Le conditionnel présent exprime :", ["un souhait, une hypothèse", "une certitude", "un ordre", "une action passée"], 0),
            ("Le subjonctif exprime :", ["le doute, le souhait", "la certitude", "l'ordre", "la réalité"], 0),
            ("Le mot « néanmoins » est :", ["un adverbe de concession", "une conjonction", "un nom", "un adjectif"], 0),
            ("La proposition subordonnée relative est introduite par :", ["qui, que, dont, où", "parce que, si", "et, ou", "mais, donc"], 0),
            ("La proposition subordonnée complétive est introduite par :", ["que", "qui", "dont", "où"], 0),
            ("Le complément du nom est introduit par :", ["de, à, en", "et, ou", "mais, donc", "ni, car"], 0),
            ("L'attribut du sujet se construit avec :", ["être, paraître, sembler", "manger, boire", "courir, sauter", "voir, entendre"], 0),
            ("Le COD se place généralement :", ["après le verbe", "avant le verbe", "au début", "à la fin"], 0),
            ("Le COI est introduit par :", ["à, de", "et, ou", "mais, donc", "ni, car"], 0),
            ("Le mot « où » peut être :", ["un pronom relatif ou un adverbe", "une conjonction", "un nom", "un adjectif"], 0),
            ("La voix passive se forme avec :", ["être + participe passé", "avoir + participe passé", "aller + infinitif", "venir de + infinitif"], 0),
            ("Le participe présent se termine par :", ["-ant", "-é", "-ir", "-re"], 0),
            ("Le gérondif se forme avec :", ["en + participe présent", "avoir + participe passé", "être + participe passé", "aller + infinitif"], 0),
            ("Le mot « cependant » exprime :", ["l'opposition", "la cause", "la conséquence", "le but"], 0),
            ("Le mot « parce que » exprime :", ["la cause", "la conséquence", "l'opposition", "le but"], 0),
            ("Le mot « donc » exprime :", ["la conséquence", "la cause", "l'opposition", "le but"], 0),
            ("Le mot « afin que » exprime :", ["le but", "la cause", "la conséquence", "l'opposition"], 0),
            ("La ponctuation qui marque une pause courte est :", ["la virgule", "le point", "le point-virgule", "les deux-points"], 0),
            ("Le point d'interrogation termine :", ["une phrase interrogative", "une phrase déclarative", "une phrase impérative", "une phrase exclamative"], 0),
            ("Le point d'exclamation termine :", ["une phrase exclamative", "une phrase interrogative", "une phrase déclarative", "une phrase impérative"], 0),
            ("Le mot « hélas » exprime :", ["la tristesse, le regret", "la joie", "la colère", "la surprise"], 0),
            ("Le mot « bravo » exprime :", ["la félicitation", "la tristesse", "la colère", "la peur"], 0),
            ("Le nom « courage » est :", ["abstrait", "concret", "propre", "collectif"], 0),
            ("Le nom « table » est :", ["concret", "abstrait", "propre", "collectif"], 0),
            ("Le nom « Cameroun » est :", ["un nom propre", "un nom commun", "un nom abstrait", "un nom collectif"], 0),
        ],
    },
    "anglais-fr": {
        "subject": "Anglais",
        "level": "Ordinary Level (Collège)",
        "class": "Troisième",
        "series": "Tronc Commun",
        "exam": "BEPC",
        "questions": [
            ("The plural of « book » is :", ["books", "bookes", "book", "bookies"], 0),
            ("The past tense of « go » is :", ["went", "goed", "gone", "going"], 0),
            ("The past participle of « eat » is :", ["eaten", "ate", "eated", "eating"], 0),
            ("« She ___ a student. » (present of to be)", ["is", "are", "am", "be"], 0),
            ("« They ___ playing football. » (present continuous)", ["are", "is", "am", "be"], 0),
            ("The opposite of « big » is :", ["small", "large", "huge", "tall"], 0),
            ("The synonym of « happy » is :", ["glad", "sad", "angry", "tired"], 0),
            ("« I ___ to school every day. » (present simple)", ["go", "goes", "going", "gone"], 0),
            ("« He ___ his homework. » (present simple, 3rd person)", ["does", "do", "doing", "done"], 0),
            ("The plural of « child » is :", ["children", "childs", "childes", "childrens"], 0),
            ("The plural of « man » is :", ["men", "mans", "menes", "man"], 0),
            ("The plural of « woman » is :", ["women", "womans", "womens", "woman"], 0),
            ("The plural of « foot » is :", ["feet", "foots", "feets", "foot"], 0),
            ("The plural of « tooth » is :", ["teeth", "tooths", "teeths", "tooth"], 0),
            ("« There ___ a book on the table. »", ["is", "are", "am", "be"], 0),
            ("« There ___ many students in the class. »", ["are", "is", "am", "be"], 0),
            ("The comparative of « tall » is :", ["taller", "more tall", "tallest", "most tall"], 0),
            ("The superlative of « tall » is :", ["tallest", "taller", "more tall", "most tall"], 0),
            ("« I have ___ apple. »", ["an", "a", "the", "some"], 0),
            ("« He is ___ engineer. »", ["an", "a", "the", "some"], 0),
            ("The past tense of « see » is :", ["saw", "seen", "seed", "seeing"], 0),
            ("The past tense of « come » is :", ["came", "comed", "come", "coming"], 0),
            ("The past tense of « buy » is :", ["bought", "buyed", "boughten", "buying"], 0),
            ("The past tense of « think » is :", ["thought", "thinked", "thunk", "thinking"], 0),
            ("« She ___ to the market yesterday. »", ["went", "goes", "go", "going"], 0),
            ("« We ___ watching TV now. »", ["are", "is", "am", "be"], 0),
            ("The question form of « You like tea. » is :", ["Do you like tea?", "You like tea?", "Does you like tea?", "Are you like tea?"], 0),
            ("The negative of « He works. » is :", ["He does not work.", "He not works.", "He do not work.", "He works not."], 0),
            ("« I ___ a letter yesterday. » (write, past)", ["wrote", "written", "writed", "writing"], 0),
            ("The future of « go » is :", ["will go", "went", "gone", "going"], 0),
            ("« She will ___ to school. »", ["go", "goes", "going", "gone"], 0),
            ("The possessive of « John » is :", ["John's", "Johns", "John", "Johnes"], 0),
            ("« This is ___ book. » (belonging to me)", ["my", "mine", "me", "I"], 0),
            ("« This book is ___. » (belonging to me)", ["mine", "my", "me", "I"], 0),
            ("The pronoun for « the teacher » (he/she) is :", ["he or she", "it", "they", "we"], 0),
            ("The pronoun for « the books » is :", ["they", "it", "he", "she"], 0),
            ("« How ___ are you? » (age)", ["old", "tall", "big", "much"], 0),
            ("« How ___ does it cost? »", ["much", "many", "old", "tall"], 0),
            ("« How ___ books do you have? »", ["many", "much", "old", "tall"], 0),
            ("The time « 7:30 » is :", ["half past seven", "seven thirty", "thirty past seven", "half seven"], 0),
            ("The time « 8:15 » is :", ["quarter past eight", "eight fifteen", "quarter eight", "fifteen eight"], 0),
            ("« Good morning » is said :", ["in the morning", "at night", "in the afternoon", "in the evening"], 0),
            ("« Thank you » means :", ["merci", "bonjour", "au revoir", "s'il vous plaît"], 0),
            ("« Please » means :", ["s'il vous plaît", "merci", "bonjour", "excusez-moi"], 0),
            ("The color of the sky is :", ["blue", "red", "green", "black"], 0),
            ("The color of blood is :", ["red", "blue", "green", "yellow"], 0),
            ("« I am hungry » means :", ["j'ai faim", "j'ai soif", "j'ai sommeil", "j'ai chaud"], 0),
            ("« I am thirsty » means :", ["j'ai soif", "j'ai faim", "j'ai sommeil", "j'ai froid"], 0),
            ("The day after Monday is :", ["Tuesday", "Wednesday", "Sunday", "Friday"], 0),
            ("The first month of the year is :", ["January", "February", "March", "December"], 0),
            ("« She is taller than me » means :", ["elle est plus grande que moi", "elle est plus petite que moi", "elle est aussi grande que moi", "elle est grande"], 0),
            ("The past tense of « have » is :", ["had", "haved", "has", "having"], 0),
            ("« I have lived here ___ 2010. »", ["since", "for", "from", "at"], 0),
            ("« I have lived here ___ five years. »", ["for", "since", "from", "at"], 0),
            ("The present perfect of « finish » (I) is :", ["I have finished", "I finished", "I finish", "I am finishing"], 0),
            ("« ___ you like some tea? »", ["Would", "Do", "Are", "Is"], 0),
            ("The word « beautiful » is :", ["an adjective", "a noun", "a verb", "an adverb"], 0),
            ("The word « quickly » is :", ["an adverb", "an adjective", "a noun", "a verb"], 0),
            ("The word « happiness » is :", ["a noun", "an adjective", "a verb", "an adverb"], 0),
            ("« I am going to the market » — the market is :", ["a place", "a person", "a thing", "an idea"], 0),
        ],
    },
    "ecm": {
        "subject": "Éducation à la Citoyenneté et à la Morale",
        "level": "Ordinary Level (Collège)",
        "class": "Troisième",
        "series": "Tronc Commun",
        "exam": "BEPC",
        "questions": [
            ("La capitale du Cameroun est :", ["Yaoundé", "Douala", "Bafoussam", "Garoua"], 0),
            ("Le drapeau camerounais a :", ["trois couleurs", "deux couleurs", "quatre couleurs", "cinq couleurs"], 0),
            ("Les couleurs du drapeau camerounais sont :", ["vert, rouge, jaune", "bleu, blanc, rouge", "vert, blanc, rouge", "jaune, noir, vert"], 0),
            ("L'hymne national du Cameroun s'appelle :", ["Ô Cameroun, berceau de nos ancêtres", "La Marseillaise", "God Bless Africa", "L'Internationale"], 0),
            ("La devise du Cameroun est :", ["Paix - Travail - Patrie", "Liberté - Égalité - Fraternité", "Unité - Progrès - Justice", "Dieu et Patrie"], 0),
            ("Le président actuel du Cameroun est :", ["Paul Biya", "Ahmadou Ahidjo", "Ruben Um Nyobé", "Ernest Ouandié"], 0),
            ("Le Cameroun est une :", ["République", "monarchie", "empire", "fédération"], 0),
            ("Le pouvoir législatif est exercé par :", ["l'Assemblée nationale et le Sénat", "le président", "le gouvernement", "la justice"], 0),
            ("Le pouvoir exécutif est exercé par :", ["le président et le gouvernement", "l'Assemblée nationale", "le Sénat", "les tribunaux"], 0),
            ("Le pouvoir judiciaire est exercé par :", ["les tribunaux", "le président", "le gouvernement", "l'Assemblée"], 0),
            ("La séparation des pouvoirs vise à :", ["éviter la concentration des pouvoirs", "concentrer le pouvoir", "supprimer les pouvoirs", "créer un seul pouvoir"], 0),
            ("Le droit de vote s'acquiert au Cameroun à :", ["18 ans", "16 ans", "21 ans", "20 ans"], 0),
            ("Le suffrage universel signifie :", ["tous les citoyens votent", "seuls les riches votent", "seuls les hommes votent", "seuls les instruits votent"], 0),
            ("Le vote est :", ["un droit et un devoir", "un privilège", "une obligation", "un choix"], 0),
            ("La démocratie est :", ["le gouvernement du peuple par le peuple", "le gouvernement d'un seul", "le gouvernement des riches", "le gouvernement des militaires"], 0),
            ("Les droits de l'homme sont :", ["les droits fondamentaux de chaque personne", "des privilèges", "des obligations", "des interdictions"], 0),
            ("La Déclaration universelle des droits de l'homme a été adoptée en :", ["1948", "1789", "1960", "1919"], 0),
            ("Le droit à l'éducation est :", ["un droit fondamental", "un privilège", "une option", "une interdiction"], 0),
            ("Le droit à la santé est :", ["un droit fondamental", "un privilège", "une option", "une interdiction"], 0),
            ("Le devoir du citoyen est :", ["de respecter les lois", "de ne rien faire", "de s'enrichir", "de fuir"], 0),
            ("Payer ses impôts est :", ["un devoir civique", "un choix", "une option", "une interdiction"], 0),
            ("Le service national est :", ["un devoir civique", "un choix", "une option", "une interdiction"], 0),
            ("La corruption est :", ["un acte illégal", "un acte légal", "un devoir", "un droit"], 0),
            ("La lutte contre la corruption est :", ["un devoir de chaque citoyen", "un choix", "une option", "une interdiction"], 0),
            ("L'égalité entre hommes et femmes est :", ["un droit fondamental", "un privilège", "une option", "une interdiction"], 0),
            ("La tolérance signifie :", ["accepter les différences", "rejeter les autres", "se moquer", "ignorer"], 0),
            ("Le respect des autres est :", ["une valeur citoyenne", "un choix", "une option", "une interdiction"], 0),
            ("La solidarité signifie :", ["s'entraider", "s'isoler", "se concurrencer", "s'ignorer"], 0),
            ("La paix est :", ["l'absence de conflit et la sécurité", "la guerre", "la violence", "le chaos"], 0),
            ("Le dialogue est :", ["un moyen de résoudre les conflits", "une source de conflit", "une violence", "une fuite"], 0),
            ("La violence est :", ["interdite et condamnée", "autorisée", "un droit", "un devoir"], 0),
            ("Le harcèlement scolaire est :", ["interdit", "autorisé", "un droit", "un devoir"], 0),
            ("La protection de l'environnement est :", ["un devoir de chaque citoyen", "un choix", "une option", "une interdiction"], 0),
            ("Le tri des déchets est :", ["un geste écologique", "un choix", "une option", "une interdiction"], 0),
            ("L'économie d'eau est :", ["un geste écologique", "un choix", "une option", "une interdiction"], 0),
            ("La Constitution est :", ["la loi fondamentale d'un pays", "une loi ordinaire", "un décret", "un arrêté"], 0),
            ("La Constitution camerounaise actuelle date de :", ["1996", "1960", "1972", "1984"], 0),
            ("Le Cameroun est membre de :", ["l'ONU, l'UA et la CEMAC", "l'OTAN", "l'UE", "l'ALENA"], 0),
            ("L'ONU a pour but :", ["de maintenir la paix dans le monde", "de faire la guerre", "de coloniser", "de diviser"], 0),
            ("L'UNESCO s'occupe de :", ["l'éducation, la science et la culture", "la guerre", "l'économie", "la santé"], 0),
            ("L'OMS s'occupe de :", ["la santé", "l'éducation", "la culture", "l'économie"], 0),
            ("La citoyenneté mondiale signifie :", ["se sentir responsable du monde", "être citoyen d'un seul pays", "ne pas avoir de pays", "voyager"], 0),
            ("Le bénévolat est :", ["un engagement volontaire", "un travail payé", "une obligation", "une interdiction"], 0),
            ("L'association caritative :", ["aide les personnes dans le besoin", "fait du profit", "divise", "isole"], 0),
            ("Le don de sang est :", ["un acte de solidarité", "un choix", "une option", "une interdiction"], 0),
            ("La laïcité signifie :", ["la séparation de l'État et des religions", "une religion d'État", "l'athéisme", "l'interdiction des religions"], 0),
            ("La liberté de religion est :", ["un droit fondamental", "un privilège", "une option", "une interdiction"], 0),
            ("La liberté d'expression est :", ["un droit fondamental", "un privilège", "une option", "une interdiction"], 0),
            ("La liberté de la presse est :", ["un droit fondamental", "un privilège", "une option", "une interdiction"], 0),
            ("L'abus de la liberté d'expression est :", ["interdit", "autorisé", "un droit", "un devoir"], 0),
            ("La diffamation est :", ["interdite", "autorisée", "un droit", "un devoir"], 0),
            ("Le respect de la vie privée est :", ["un droit fondamental", "un privilège", "une option", "une interdiction"], 0),
            ("La protection des données personnelles est :", ["un droit", "un privilège", "une option", "une interdiction"], 0),
            ("Le cyberharcèlement est :", ["interdit", "autorisé", "un droit", "un devoir"], 0),
            ("L'utilisation responsable d'Internet est :", ["un devoir", "un choix", "une option", "une interdiction"], 0),
            ("Le civisme numérique signifie :", ["un comportement responsable en ligne", "l'anonymat total", "la liberté totale", "l'isolement"], 0),
            ("La participation aux élections est :", ["un devoir civique", "un choix", "une option", "une interdiction"], 0),
            ("Le respect des symboles de la République est :", ["un devoir civique", "un choix", "une option", "une interdiction"], 0),
            ("La patrie est :", ["le pays auquel on appartient", "un continent", "une ville", "une région"], 0),
            ("Le patriotisme est :", ["l'amour de sa patrie", "la haine des autres", "l'indifférence", "la fuite"], 0),
        ],
    },
    "informatique-fr": {
        "subject": "Informatique",
        "level": "Ordinary Level (Collège)",
        "class": "Troisième",
        "series": "Tronc Commun",
        "exam": "BEPC",
        "questions": [
            ("L'unité centrale de traitement s'appelle :", ["le processeur", "l'écran", "le clavier", "la souris"], 0),
            ("Le clavier est :", ["un périphérique d'entrée", "un périphérique de sortie", "une unité centrale", "un logiciel"], 0),
            ("L'écran est :", ["un périphérique de sortie", "un périphérique d'entrée", "une unité centrale", "un logiciel"], 0),
            ("La souris est :", ["un périphérique d'entrée", "un périphérique de sortie", "une unité centrale", "un logiciel"], 0),
            ("L'imprimante est :", ["un périphérique de sortie", "un périphérique d'entrée", "une unité centrale", "un logiciel"], 0),
            ("Le scanner est :", ["un périphérique d'entrée", "un périphérique de sortie", "une unité centrale", "un logiciel"], 0),
            ("La mémoire vive s'appelle :", ["la RAM", "le disque dur", "le processeur", "la ROM"], 0),
            ("La RAM est :", ["une mémoire volatile", "une mémoire permanente", "un périphérique", "un logiciel"], 0),
            ("Le disque dur est :", ["une mémoire de masse", "une mémoire volatile", "un périphérique d'entrée", "un logiciel"], 0),
            ("Le système d'exploitation est :", ["un logiciel de base", "un périphérique", "une mémoire", "un composant"], 0),
            ("Windows est :", ["un système d'exploitation", "un périphérique", "une mémoire", "un composant"], 0),
            ("Linux est :", ["un système d'exploitation", "un périphérique", "une mémoire", "un composant"], 0),
            ("Le logiciel de traitement de texte est :", ["Word", "Excel", "PowerPoint", "Photoshop"], 0),
            ("Le logiciel de tableur est :", ["Excel", "Word", "PowerPoint", "Paint"], 0),
            ("Le logiciel de présentation est :", ["PowerPoint", "Word", "Excel", "Access"], 0),
            ("Le navigateur web est :", ["Chrome", "Word", "Excel", "Paint"], 0),
            ("L'unité de mesure de la taille d'un fichier est :", ["l'octet", "le volt", "l'ampère", "le watt"], 0),
            ("1 Ko (kilooctet) équivaut à :", ["1024 octets", "1000 octets", "10 octets", "1 octet"], 0),
            ("1 Mo (mégaoctet) équivaut à :", ["1024 Ko", "1000 Ko", "10 Ko", "1 Ko"], 0),
            ("Le bit est :", ["la plus petite unité d'information", "une grande unité", "un périphérique", "un logiciel"], 0),
            ("Un octet est composé de :", ["8 bits", "4 bits", "16 bits", "2 bits"], 0),
            ("Le binaire utilise :", ["0 et 1", "0 à 9", "A à Z", "1 et 2"], 0),
            ("Le système décimal utilise :", ["0 à 9", "0 et 1", "A à F", "1 à 10"], 0),
            ("Le système hexadécimal utilise :", ["0 à 9 et A à F", "0 et 1", "0 à 9", "A à Z"], 0),
            ("L'adresse IP est :", ["l'adresse d'un ordinateur sur un réseau", "une adresse postale", "un mot de passe", "un nom"], 0),
            ("Le réseau Internet permet :", ["de connecter des ordinateurs dans le monde", "d'imprimer", "de scanner", "de calculer"], 0),
            ("Le Wi-Fi est :", ["une connexion sans fil", "un câble", "un logiciel", "une mémoire"], 0),
            ("L'e-mail est :", ["un courrier électronique", "un logiciel", "un périphérique", "une mémoire"], 0),
            ("Le mot de passe sert à :", ["protéger l'accès", "afficher l'écran", "imprimer", "scanner"], 0),
            ("Un mot de passe fort contient :", ["des lettres, chiffres et symboles", "uniquement des lettres", "uniquement des chiffres", "son prénom"], 0),
            ("Le virus informatique est :", ["un programme malveillant", "un logiciel utile", "un périphérique", "une mémoire"], 0),
            ("L'antivirus sert à :", ["protéger contre les virus", "imprimer", "scanner", "calculer"], 0),
            ("Le phishing est :", ["une tentative de fraude en ligne", "un jeu", "un logiciel", "un périphérique"], 0),
            ("Le spam est :", ["un courrier indésirable", "un jeu", "un logiciel", "un périphérique"], 0),
            ("Le fichier est :", ["un ensemble de données", "un périphérique", "une mémoire", "un composant"], 0),
            ("Le dossier (répertoire) sert à :", ["organiser les fichiers", "imprimer", "scanner", "calculer"], 0),
            ("L'extension d'un fichier texte est :", [".txt", ".jpg", ".mp3", ".exe"], 0),
            ("L'extension d'une image est :", [".jpg", ".txt", ".mp3", ".exe"], 0),
            ("L'extension d'un fichier audio est :", [".mp3", ".txt", ".jpg", ".exe"], 0),
            ("L'extension d'un programme exécutable est :", [".exe", ".txt", ".jpg", ".mp3"], 0),
            ("Le copier-coller se fait avec :", ["Ctrl+C et Ctrl+V", "Ctrl+X et Ctrl+Z", "Ctrl+P et Ctrl+S", "Ctrl+A et Ctrl+B"], 0),
            ("Le couper-coller se fait avec :", ["Ctrl+X et Ctrl+V", "Ctrl+C et Ctrl+V", "Ctrl+P et Ctrl+S", "Ctrl+A et Ctrl+B"], 0),
            ("L'annulation se fait avec :", ["Ctrl+Z", "Ctrl+C", "Ctrl+V", "Ctrl+P"], 0),
            ("L'impression se fait avec :", ["Ctrl+P", "Ctrl+C", "Ctrl+V", "Ctrl+Z"], 0),
            ("L'enregistrement se fait avec :", ["Ctrl+S", "Ctrl+C", "Ctrl+V", "Ctrl+P"], 0),
            ("La sélection de tout se fait avec :", ["Ctrl+A", "Ctrl+C", "Ctrl+V", "Ctrl+P"], 0),
            ("Le cloud computing est :", ["le stockage de données sur Internet", "un périphérique", "une mémoire", "un composant"], 0),
            ("Le stockage cloud permet :", ["d'accéder aux données à distance", "d'imprimer", "de scanner", "de calculer"], 0),
            ("La sauvegarde (backup) sert à :", ["protéger les données", "imprimer", "scanner", "calculer"], 0),
            ("L'ordinateur portable est :", ["un ordinateur mobile", "un périphérique", "une mémoire", "un logiciel"], 0),
            ("La tablette est :", ["un appareil tactile", "un périphérique", "une mémoire", "un logiciel"], 0),
            ("Le smartphone est :", ["un téléphone intelligent", "un périphérique", "une mémoire", "un logiciel"], 0),
            ("Le logiciel libre est :", ["un logiciel dont le code est ouvert", "un logiciel payant", "un virus", "un périphérique"], 0),
            ("Le logiciel propriétaire est :", ["un logiciel dont le code est fermé", "un logiciel libre", "un virus", "un périphérique"], 0),
            ("L'open source signifie :", ["code source ouvert", "code fermé", "payant", "gratuit uniquement"], 0),
            ("La programmation consiste à :", ["écrire des instructions pour l'ordinateur", "imprimer", "scanner", "calculer"], 0),
            ("Un algorithme est :", ["une suite d'instructions", "un périphérique", "une mémoire", "un composant"], 0),
            ("Le langage de programmation est :", ["un langage pour écrire des programmes", "une langue étrangère", "un périphérique", "une mémoire"], 0),
            ("Python est :", ["un langage de programmation", "un périphérique", "une mémoire", "un composant"], 0),
            ("Le HTML est :", ["un langage de création de pages web", "un périphérique", "une mémoire", "un composant"], 0),
        ],
    },
    "comptabilite": {
        "subject": "Comptabilité",
        "level": "Advanced Level (Lycée)",
        "class": "Première",
        "series": "Comptabilité",
        "exam": "Probatoire",
        "questions": [
            ("Le bilan est :", ["un tableau qui décrit le patrimoine", "un compte de résultat", "une facture", "un journal"], 0),
            ("L'actif du bilan comprend :", ["les biens et créances", "les dettes", "les capitaux propres", "les charges"], 0),
            ("Le passif du bilan comprend :", ["les dettes et capitaux propres", "les biens", "les créances", "les produits"], 0),
            ("Le compte de résultat présente :", ["les charges et produits", "l'actif et le passif", "les biens et dettes", "les recettes et dépenses"], 0),
            ("Le journal comptable enregistre :", ["les opérations au jour le jour", "le bilan", "le résultat", "les amortissements"], 0),
            ("Le grand livre regroupe :", ["tous les comptes", "les factures", "les bilans", "les résultats"], 0),
            ("La balance est :", ["un récapitulatif des comptes", "un bilan", "un résultat", "un journal"], 0),
            ("Le compte « caisse » est :", ["un compte d'actif", "un compte de passif", "un compte de charge", "un compte de produit"], 0),
            ("Le compte « banque » est :", ["un compte d'actif", "un compte de passif", "un compte de charge", "un compte de produit"], 0),
            ("Le compte « capital » est :", ["un compte de capitaux propres", "un compte d'actif", "un compte de charge", "un compte de produit"], 0),
            ("Le compte « ventes » est :", ["un compte de produit", "un compte de charge", "un compte d'actif", "un compte de passif"], 0),
            ("Le compte « achats » est :", ["un compte de charge", "un compte de produit", "un compte d'actif", "un compte de passif"], 0),
            ("La TVA est :", ["la taxe sur la valeur ajoutée", "une taxe foncière", "un impôt sur le revenu", "une taxe douanière"], 0),
            ("La TVA collectée est :", ["la TVA sur les ventes", "la TVA sur les achats", "une taxe", "un impôt"], 0),
            ("La TVA déductible est :", ["la TVA sur les achats", "la TVA sur les ventes", "une taxe", "un impôt"], 0),
            ("La TVA à payer est :", ["TVA collectée - TVA déductible", "TVA collectée + TVA déductible", "TVA déductible - TVA collectée", "TVA collectée"], 0),
            ("L'amortissement est :", ["la constatation de la dépréciation d'un bien", "une charge", "un produit", "une dette"], 0),
            ("L'amortissement concerne :", ["les immobilisations", "les stocks", "les créances", "la caisse"], 0),
            ("La provision est :", ["une charge probable", "un produit", "une dette", "un bien"], 0),
            ("Le résultat de l'exercice est :", ["produits - charges", "actif - passif", "recettes - dépenses", "ventes - achats"], 0),
            ("Le bénéfice est :", ["un résultat positif", "un résultat négatif", "une charge", "un produit"], 0),
            ("La perte est :", ["un résultat négatif", "un résultat positif", "une charge", "un produit"], 0),
            ("Le chiffre d'affaires est :", ["le total des ventes", "le total des achats", "le bénéfice", "la perte"], 0),
            ("La facture est :", ["un document commercial", "un bilan", "un résultat", "un journal"], 0),
            ("La facture d'achat est :", ["reçue du fournisseur", "envoyée au client", "un bilan", "un résultat"], 0),
            ("La facture de vente est :", ["envoyée au client", "reçue du fournisseur", "un bilan", "un résultat"], 0),
            ("L'avoir est :", ["une facture de remise", "une facture d'achat", "un bilan", "un résultat"], 0),
            ("Le rabais est :", ["une réduction sur le prix", "une taxe", "un impôt", "une charge"], 0),
            ("La remise est :", ["une réduction commerciale", "une taxe", "un impôt", "une charge"], 0),
            ("L'escompte est :", ["une réduction financière", "une réduction commerciale", "une taxe", "un impôt"], 0),
            ("Le compte « clients » est :", ["un compte de créance", "un compte de dette", "un compte de charge", "un compte de produit"], 0),
            ("Le compte « fournisseurs » est :", ["un compte de dette", "un compte de créance", "un compte de charge", "un compte de produit"], 0),
            ("Le compte « personnel » est :", ["un compte de dette", "un compte de créance", "un compte de charge", "un compte de produit"], 0),
            ("Le compte « État, TVA » est :", ["un compte de tiers", "un compte de charge", "un compte de produit", "un compte de banque"], 0),
            ("Le journal est tenu :", ["chronologiquement", "par ordre alphabétique", "par montant", "au hasard"], 0),
            ("La partie double signifie :", ["chaque opération affecte deux comptes", "deux journaux", "deux bilans", "deux résultats"], 0),
            ("Le débit d'un compte d'actif :", ["augmente le compte", "diminue le compte", "n'a aucun effet", "annule le compte"], 0),
            ("Le crédit d'un compte de passif :", ["augmente le compte", "diminue le compte", "n'a aucun effet", "annule le compte"], 0),
            ("Le débit d'un compte de charge :", ["augmente le compte", "diminue le compte", "n'a aucun effet", "annule le compte"], 0),
            ("Le crédit d'un compte de produit :", ["augmente le compte", "diminue le compte", "n'a aucun effet", "annule le compte"], 0),
            ("Le solde d'un compte est :", ["la différence entre débit et crédit", "le total du débit", "le total du crédit", "le nombre d'opérations"], 0),
            ("Un compte débiteur a :", ["un solde débiteur", "un solde créditeur", "un solde nul", "aucun solde"], 0),
            ("Un compte créditeur a :", ["un solde créditeur", "un solde débiteur", "un solde nul", "aucun solde"], 0),
            ("Le plan comptable est :", ["la liste normalisée des comptes", "un bilan", "un résultat", "un journal"], 0),
            ("Le système comptable OHADA est utilisé :", ["en Afrique francophone", "en Europe", "en Amérique", "en Asie"], 0),
            ("Le bilan se présente :", ["en deux colonnes (actif et passif)", "en une colonne", "en trois colonnes", "en tableau"], 0),
            ("L'actif immobilisé comprend :", ["les biens durables", "les stocks", "les créances", "la caisse"], 0),
            ("L'actif circulant comprend :", ["les stocks, créances et disponibilités", "les biens durables", "les capitaux propres", "les dettes"], 0),
            ("Les capitaux propres comprennent :", ["le capital et les réserves", "les dettes", "les biens", "les créances"], 0),
            ("Les dettes à long terme sont :", ["les emprunts", "les fournisseurs", "les clients", "la caisse"], 0),
            ("Les dettes à court terme sont :", ["les fournisseurs", "les emprunts", "le capital", "les réserves"], 0),
            ("Le fonds de roulement est :", ["actif circulant - dettes à court terme", "actif - passif", "produits - charges", "ventes - achats"], 0),
            ("Le besoin en fonds de roulement est :", ["stocks + créances - dettes à court terme", "actif - passif", "produits - charges", "ventes - achats"], 0),
            ("La trésorerie nette est :", ["fonds de roulement - besoin en fonds de roulement", "actif - passif", "produits - charges", "ventes - achats"], 0),
            ("Le seuil de rentabilité est :", ["le chiffre d'affaires où le résultat est nul", "le bénéfice", "la perte", "le capital"], 0),
            ("La marge brute est :", ["ventes - coût d'achat", "produits - charges", "actif - passif", "recettes - dépenses"], 0),
            ("Le coût de revient est :", ["le coût total de production", "le prix de vente", "le bénéfice", "la perte"], 0),
            ("Le prix de vente est :", ["coût de revient + marge", "coût de revient - marge", "coût de revient", "marge"], 0),
            ("La liasse fiscale comprend :", ["bilan, compte de résultat et annexes", "uniquement le bilan", "uniquement le résultat", "les factures"], 0),
            ("L'annexe est :", ["un document complémentaire du bilan", "un bilan", "un résultat", "un journal"], 0),
        ],
    },
    "economie-fr": {
        "subject": "Économie",
        "level": "Advanced Level (Lycée)",
        "class": "Première",
        "series": "Économie",
        "exam": "Probatoire",
        "questions": [
            ("L'économie étudie :", ["la production et la répartition des richesses", "la politique", "la religion", "la culture"], 0),
            ("Les besoins sont :", ["illimités", "limités", "inexistants", "rares"], 0),
            ("Les ressources sont :", ["limitées (rares)", "illimitées", "inexistantes", "abondantes"], 0),
            ("Le problème économique fondamental est :", ["la rareté", "l'abondance", "la richesse", "la pauvreté"], 0),
            ("Les biens économiques sont :", ["rares et utiles", "abondants", "gratuits", "inutiles"], 0),
            ("Les biens libres sont :", ["gratuits et abondants", "rares", "payants", "inutiles"], 0),
            ("La production est :", ["la création de biens et services", "la consommation", "l'épargne", "l'investissement"], 0),
            ("La consommation est :", ["l'utilisation des biens et services", "la production", "l'épargne", "l'investissement"], 0),
            ("L'épargne est :", ["la partie du revenu non consommée", "la consommation", "la production", "l'investissement"], 0),
            ("L'investissement est :", ["l'achat de biens de production", "la consommation", "l'épargne", "la production"], 0),
            ("Le PIB est :", ["la production totale d'un pays", "la population", "le chômage", "l'inflation"], 0),
            ("Le PIB par habitant est :", ["le PIB divisé par la population", "le PIB total", "la population", "le chômage"], 0),
            ("L'inflation est :", ["la hausse générale des prix", "la baisse des prix", "le chômage", "la croissance"], 0),
            ("La déflation est :", ["la baisse générale des prix", "la hausse des prix", "le chômage", "la croissance"], 0),
            ("Le chômage est :", ["l'absence d'emploi pour ceux qui cherchent", "le travail", "la production", "l'inflation"], 0),
            ("Le taux de chômage est :", ["le pourcentage de chômeurs dans la population active", "le nombre d'employés", "la population", "le PIB"], 0),
            ("La population active comprend :", ["les personnes en âge de travailler et qui travaillent ou cherchent", "toute la population", "les enfants", "les retraités"], 0),
            ("L'offre est :", ["la quantité de biens proposés", "la quantité demandée", "le prix", "la production"], 0),
            ("La demande est :", ["la quantité de biens désirés", "la quantité offerte", "le prix", "la production"], 0),
            ("Le prix d'équilibre est :", ["où l'offre égale la demande", "le prix le plus bas", "le prix le plus haut", "le prix fixe"], 0),
            ("La loi de l'offre et de la demande :", ["le prix varie selon l'offre et la demande", "le prix est fixe", "le prix baisse toujours", "le prix monte toujours"], 0),
            ("Le marché est :", ["le lieu de rencontre de l'offre et de la demande", "un magasin", "une usine", "une banque"], 0),
            ("La concurrence parfaite suppose :", ["beaucoup d'offreurs et de demandeurs", "un seul offreur", "peu d'offreurs", "un monopole"], 0),
            ("Le monopole est :", ["un seul offreur", "beaucoup d'offreurs", "deux offreurs", "aucun offreur"], 0),
            ("L'oligopole est :", ["peu d'offreurs", "un seul offreur", "beaucoup d'offreurs", "aucun offreur"], 0),
            ("La monnaie a pour fonction :", ["d'être un intermédiaire des échanges", "de produire", "de consommer", "d'investir"], 0),
            ("La monnaie fiduciaire est :", ["les billets et pièces", "les chèques", "les cartes", "la monnaie électronique"], 0),
            ("La monnaie scripturale est :", ["les dépôts en banque", "les billets", "les pièces", "l'or"], 0),
            ("La banque centrale :", ["émet la monnaie et contrôle le crédit", "prête aux particuliers", "produit des biens", "consomme"], 0),
            ("Le taux d'intérêt est :", ["le prix de l'argent emprunté", "le prix des biens", "le salaire", "le chômage"], 0),
            ("Le crédit est :", ["un prêt d'argent", "une épargne", "une consommation", "une production"], 0),
            ("La banque commerciale :", ["reçoit les dépôts et accorde des crédits", "émet la monnaie", "produit des biens", "fixe les prix"], 0),
            ("Le budget de l'État est :", ["les recettes et dépenses publiques", "le PIB", "le chômage", "l'inflation"], 0),
            ("Les impôts sont :", ["des prélèvements obligatoires", "des dons", "des salaires", "des épargnes"], 0),
            ("L'impôt direct est :", ["prélevé directement sur le revenu", "inclus dans le prix", "un don", "une épargne"], 0),
            ("L'impôt indirect est :", ["inclus dans le prix (TVA)", "prélevé sur le revenu", "un don", "une épargne"], 0),
            ("La politique budgétaire utilise :", ["le budget de l'État", "le taux d'intérêt", "la monnaie", "le crédit"], 0),
            ("La politique monétaire utilise :", ["le taux d'intérêt et la masse monétaire", "le budget", "les impôts", "les dépenses"], 0),
            ("La croissance économique est :", ["l'augmentation de la production", "la baisse de la production", "le chômage", "l'inflation"], 0),
            ("Le développement est :", ["l'amélioration des conditions de vie", "la croissance", "le chômage", "l'inflation"], 0),
            ("Le commerce international est :", ["les échanges entre pays", "le commerce local", "la production", "la consommation"], 0),
            ("L'exportation est :", ["la vente de biens à l'étranger", "l'achat de biens de l'étranger", "la production", "la consommation"], 0),
            ("L'importation est :", ["l'achat de biens de l'étranger", "la vente à l'étranger", "la production", "la consommation"], 0),
            ("La balance commerciale est :", ["exportations - importations", "PIB - consommation", "recettes - dépenses", "actif - passif"], 0),
            ("Le protectionnisme est :", ["la protection de l'économie nationale", "le libre-échange", "l'exportation", "l'importation"], 0),
            ("Le libre-échange est :", ["la libre circulation des biens", "le protectionnisme", "l'exportation", "l'importation"], 0),
            ("La mondialisation est :", ["l'interdépendance des économies", "l'isolement", "le protectionnisme", "la guerre"], 0),
            ("L'entreprise est :", ["une unité de production", "un consommateur", "une banque", "un État"], 0),
            ("Le capital de l'entreprise est :", ["les moyens de production", "les salaires", "les impôts", "les ventes"], 0),
            ("Le travail est :", ["un facteur de production", "un capital", "une ressource naturelle", "un impôt"], 0),
            ("Les facteurs de production sont :", ["le travail et le capital", "le travail et la consommation", "le capital et l'épargne", "la production et la vente"], 0),
            ("La productivité est :", ["la production par unité de facteur", "la production totale", "le chômage", "l'inflation"], 0),
            ("Le salaire est :", ["la rémunération du travail", "le prix des biens", "un impôt", "une épargne"], 0),
            ("Le profit est :", ["la rémunération du capital", "le salaire", "un impôt", "une épargne"], 0),
            ("La rente est :", ["la rémunération de la terre", "le salaire", "le profit", "un impôt"], 0),
            ("Le développement durable vise :", ["à satisfaire les besoins sans compromettre l'avenir", "la croissance rapide", "l'exploitation maximale", "la consommation"], 0),
            ("L'économie informelle est :", ["non enregistrée officiellement", "officielle", "légale", "formelle"], 0),
            ("La microfinance :", ["accorde des petits crédits", "émet la monnaie", "produit des biens", "fixe les prix"], 0),
            ("Le secteur primaire comprend :", ["l'agriculture et l'extraction", "l'industrie", "les services", "le commerce"], 0),
            ("Le secteur secondaire comprend :", ["l'industrie", "l'agriculture", "les services", "le commerce"], 0),
            ("Le secteur tertiaire comprend :", ["les services", "l'agriculture", "l'industrie", "l'extraction"], 0),
        ],
    },
    "philosophie": {
        "subject": "Philosophie",
        "level": "Advanced Level (Lycée)",
        "class": "Terminale",
        "series": "Philosophie",
        "exam": "Baccalauréat",
        "questions": [
            ("La philosophie signifie étymologiquement :", ["l'amour de la sagesse", "la science", "la religion", "la politique"], 0),
            ("Le premier philosophe grec est souvent considéré :", ["Thalès", "Socrate", "Platon", "Aristote"], 0),
            ("Socrate est connu pour :", ["la maïeutique", "la théorie des idées", "la logique", "le doute"], 0),
            ("Platon a écrit :", ["La République", "L'Éthique à Nicomaque", "Le Discours de la méthode", "Le Contrat social"], 0),
            ("Aristote est le fondateur de :", ["la logique", "le scepticisme", "l'idéalisme", "l'empirisme"], 0),
            ("Descartes est connu pour :", ["le cogito « je pense donc je suis »", "la théorie des idées", "la logique", "le contrat social"], 0),
            ("Le cogito de Descartes est :", ["« je pense donc je suis »", "« connais-toi toi-même »", "« tout est nombre »", "« rien ne se perd »"], 0),
            ("Kant a écrit :", ["La Critique de la raison pure", "La République", "Le Contrat social", "L'Éthique"], 0),
            ("Rousseau a écrit :", ["Le Contrat social", "La République", "La Critique", "Le Discours de la méthode"], 0),
            ("L'empirisme affirme que :", ["toute connaissance vient de l'expérience", "la raison est la seule source", "les idées sont innées", "rien n'est connaissable"], 0),
            ("Le rationalisme affirme que :", ["la raison est la source de la connaissance", "l'expérience est la seule source", "les idées sont innées", "rien n'est connaissable"], 0),
            ("Le scepticisme affirme que :", ["la connaissance certaine est impossible", "tout est connaissable", "la raison est la source", "l'expérience est la source"], 0),
            ("L'éthique étudie :", ["les principes moraux", "la nature", "la société", "la connaissance"], 0),
            ("La morale est :", ["l'ensemble des règles de conduite", "la science", "la politique", "la religion"], 0),
            ("Le devoir est :", ["une obligation morale", "un droit", "un choix", "une liberté"], 0),
            ("La liberté est :", ["la capacité d'agir selon sa volonté", "l'absence de choix", "une contrainte", "un devoir"], 0),
            ("Le libre arbitre est :", ["la liberté de choisir", "l'absence de choix", "une contrainte", "un devoir"], 0),
            ("La responsabilité est :", ["répondre de ses actes", "un droit", "une liberté", "un choix"], 0),
            ("La justice est :", ["le respect des droits de chacun", "la force", "la vengeance", "l'égalité"], 0),
            ("L'égalité signifie :", ["les mêmes droits pour tous", "les mêmes richesses", "la même force", "le même âge"], 0),
            ("L'équité est :", ["la justice adaptée aux situations", "l'égalité stricte", "la force", "la vengeance"], 0),
            ("La vérité est :", ["la conformité avec la réalité", "une opinion", "une croyance", "une illusion"], 0),
            ("L'opinion est :", ["une croyance non démontrée", "une vérité", "une certitude", "un fait"], 0),
            ("La démonstration est :", ["une preuve logique", "une opinion", "une croyance", "une illusion"], 0),
            ("Le doute méthodique de Descartes :", ["douter de tout pour trouver la vérité", "ne jamais douter", "croire sans preuve", "refuser la raison"], 0),
            ("La conscience est :", ["la connaissance de soi et du monde", "l'inconscience", "la mémoire", "l'imagination"], 0),
            ("L'inconscient est :", ["ce qui échappe à la conscience", "la conscience", "la mémoire", "l'imagination"], 0),
            ("Freud a développé :", ["la psychanalyse", "la logique", "l'idéalisme", "l'empirisme"], 0),
            ("La perception est :", ["la connaissance par les sens", "la raison", "la mémoire", "l'imagination"], 0),
            ("L'imagination est :", ["la capacité de créer des images", "la perception", "la raison", "la mémoire"], 0),
            ("La mémoire est :", ["la capacité de conserver le passé", "l'imagination", "la perception", "la raison"], 0),
            ("Le langage est :", ["un système de signes pour communiquer", "la pensée", "la perception", "la mémoire"], 0),
            ("Le travail est :", ["une activité de transformation de la nature", "un loisir", "une contrainte", "un jeu"], 0),
            ("La technique est :", ["l'ensemble des moyens de production", "la science", "l'art", "la religion"], 0),
            ("L'art est :", ["la création de la beauté", "la technique", "la science", "la religion"], 0),
            ("La beauté est :", ["ce qui plaît universellement", "ce qui est utile", "ce qui est vrai", "ce qui est bon"], 0),
            ("La religion est :", ["un système de croyances", "une science", "une technique", "un art"], 0),
            ("La foi est :", ["une croyance sans preuve", "une certitude", "une démonstration", "une opinion"], 0),
            ("La politique est :", ["l'organisation de la vie en société", "la religion", "la science", "l'art"], 0),
            ("L'État est :", ["une organisation politique de la société", "une famille", "une entreprise", "une religion"], 0),
            ("Le contrat social de Rousseau :", ["l'accord des citoyens pour vivre ensemble", "un contrat commercial", "une loi", "un décret"], 0),
            ("La souveraineté est :", ["le pouvoir suprême de l'État", "un droit", "une liberté", "un devoir"], 0),
            ("La démocratie est :", ["le pouvoir du peuple", "le pouvoir d'un seul", "le pouvoir des riches", "le pouvoir des militaires"], 0),
            ("La philosophie africaine :", ["réfléchit sur les réalités africaines", "est une religion", "est une science", "est un art"], 0),
            ("L'ubuntu est :", ["une valeur africaine de solidarité", "une religion", "une science", "un art"], 0),
            ("La sagesse est :", ["la connaissance pratique de la vie", "la science", "la richesse", "le pouvoir"], 0),
            ("Le bonheur est :", ["le but de la vie selon les philosophes", "la richesse", "le pouvoir", "la gloire"], 0),
            ("L'hédonisme affirme que :", ["le plaisir est le bien suprême", "le devoir est suprême", "la raison est suprême", "la foi est suprême"], 0),
            ("Le stoïcisme affirme que :", ["la vertu est le bien suprême", "le plaisir est suprême", "la richesse est suprême", "le pouvoir est suprême"], 0),
            ("L'utilitarisme affirme que :", ["l'utile est le critère du bien", "le devoir est suprême", "le plaisir est suprême", "la foi est suprême"], 0),
            ("L'éthique de Kant repose sur :", ["l'impératif catégorique", "le plaisir", "l'utilité", "la foi"], 0),
            ("L'impératif catégorique de Kant :", ["agis selon une maxime universalisable", "agis pour ton plaisir", "agis pour ton intérêt", "agis par peur"], 0),
            ("La raison est :", ["la faculté de penser et de juger", "la mémoire", "l'imagination", "la perception"], 0),
            ("L'intelligence est :", ["la capacité de comprendre et résoudre", "la mémoire", "l'imagination", "la perception"], 0),
            ("La philosophie des sciences étudie :", ["les fondements de la science", "la religion", "l'art", "la politique"], 0),
            ("La science est :", ["une connaissance méthodique et vérifiable", "une opinion", "une croyance", "une illusion"], 0),
            ("L'hypothèse scientifique est :", ["une supposition à vérifier", "une certitude", "une opinion", "une croyance"], 0),
            ("L'expérience scientifique :", ["vérifie les hypothèses", "crée des opinions", "est inutile", "est une croyance"], 0),
            ("La philosophie morale étudie :", ["les principes du bien et du mal", "la nature", "la société", "la connaissance"], 0),
            ("Le temps est :", ["une réalité mesurable et vécue", "une illusion", "un objet", "une idée"], 0),
            ("La mort est :", ["la fin de la vie", "une illusion", "un objet", "une idée"], 0),
        ],
    },
    "ses": {
        "subject": "Sciences Économiques et Sociales",
        "level": "Advanced Level (Lycée)",
        "class": "Terminale",
        "series": "Sciences Économiques et Sociales",
        "exam": "Baccalauréat",
        "questions": [
            ("Les SES étudient :", ["l'économie, la sociologie et la science politique", "la biologie", "la chimie", "la physique"], 0),
            ("La sociologie étudie :", ["les faits sociaux", "les atomes", "les cellules", "les planètes"], 0),
            ("La science politique étudie :", ["le pouvoir et l'État", "les atomes", "les cellules", "les planètes"], 0),
            ("Le fait social selon Durkheim :", ["des manières d'agir extérieures à l'individu", "des faits biologiques", "des faits physiques", "des faits chimiques"], 0),
            ("Durkheim a étudié :", ["le suicide", "les atomes", "les cellules", "les planètes"], 0),
            ("Weber a étudié :", ["l'éthique protestante et le capitalisme", "le suicide", "les atomes", "les cellules"], 0),
            ("Marx a analysé :", ["la lutte des classes", "le suicide", "les atomes", "les planètes"], 0),
            ("La socialisation est :", ["l'apprentissage des normes et valeurs", "la biologie", "la chimie", "la physique"], 0),
            ("Les normes sociales sont :", ["des règles de conduite", "des lois physiques", "des réactions chimiques", "des cellules"], 0),
            ("Les valeurs sont :", ["des idéaux partagés", "des lois", "des prix", "des salaires"], 0),
            ("La stratification sociale est :", ["la hiérarchie des groupes sociaux", "la géologie", "la biologie", "la chimie"], 0),
            ("Les classes sociales selon Marx :", ["bourgeoisie et prolétariat", "riches et pauvres", "jeunes et vieux", "hommes et femmes"], 0),
            ("La mobilité sociale est :", ["le changement de position sociale", "le déplacement géographique", "la croissance", "l'inflation"], 0),
            ("L'ascenseur social est :", ["la mobilité sociale ascendante", "un moyen de transport", "une machine", "un bâtiment"], 0),
            ("La famille est :", ["une institution sociale", "une entreprise", "un État", "une religion"], 0),
            ("La socialisation primaire se fait :", ["dans la famille", "à l'école", "au travail", "à la retraite"], 0),
            ("La socialisation secondaire se fait :", ["à l'école, au travail", "dans la famille", "à la naissance", "dans le ventre"], 0),
            ("L'école est :", ["une instance de socialisation", "une entreprise", "un État", "une religion"], 0),
            ("Les médias sont :", ["des instances de socialisation", "des entreprises", "des États", "des religions"], 0),
            ("La culture est :", ["l'ensemble des valeurs et pratiques d'un groupe", "la biologie", "la chimie", "la physique"], 0),
            ("La socialisation différenciée :", ["varie selon le genre, la classe", "est identique pour tous", "n'existe pas", "est biologique"], 0),
            ("Le capital social est :", ["le réseau de relations", "l'argent", "les biens", "les machines"], 0),
            ("Le capital culturel est :", ["les connaissances et diplômes", "l'argent", "les biens", "les machines"], 0),
            ("Bourdieu a développé :", ["la notion de capital culturel", "la théorie des idées", "la logique", "le cogito"], 0),
            ("La déviance est :", ["la transgression des normes", "la conformité", "la socialisation", "l'intégration"], 0),
            ("L'anomie selon Durkheim :", ["l'absence de normes", "l'excès de normes", "la conformité", "l'intégration"], 0),
            ("Le contrôle social est :", ["les mécanismes qui assurent la conformité", "la liberté totale", "l'anarchie", "la déviance"], 0),
            ("La délinquance est :", ["la transgression de la loi", "la conformité", "la socialisation", "l'intégration"], 0),
            ("Le chômage est :", ["l'absence d'emploi pour les actifs", "le travail", "la production", "l'inflation"], 0),
            ("Le taux de chômage est :", ["chômeurs / population active", "chômeurs / population totale", "employés / population", "actifs / population"], 0),
            ("Le halo du chômage est :", ["les personnes proches du chômage", "les employés", "les retraités", "les enfants"], 0),
            ("La précarité est :", ["l'instabilité de l'emploi", "la stabilité", "la richesse", "le chômage"], 0),
            ("Le CDI est :", ["un contrat à durée indéterminée", "un contrat court", "un stage", "un intérim"], 0),
            ("Le CDD est :", ["un contrat à durée déterminée", "un contrat permanent", "un stage", "un intérim"], 0),
            ("Le salaire est :", ["la rémunération du travail", "le profit", "la rente", "un impôt"], 0),
            ("Le SMIG est :", ["le salaire minimum", "le salaire moyen", "le salaire maximum", "le profit"], 0),
            ("La productivité est :", ["la production par unité de facteur", "la production totale", "le chômage", "l'inflation"], 0),
            ("La croissance économique est :", ["l'augmentation de la production", "la baisse de la production", "le chômage", "l'inflation"], 0),
            ("Le PIB est :", ["la production totale d'un pays", "la population", "le chômage", "l'inflation"], 0),
            ("Le développement est :", ["l'amélioration des conditions de vie", "la croissance", "le chômage", "l'inflation"], 0),
            ("L'IDH mesure :", ["le développement humain", "la production", "le chômage", "l'inflation"], 0),
            ("L'IDH comprend :", ["santé, éducation, revenu", "production, chômage, inflation", "population, surface, climat", "exportations, importations, PIB"], 0),
            ("La mondialisation est :", ["l'interdépendance des économies", "l'isolement", "le protectionnisme", "la guerre"], 0),
            ("Le commerce international :", ["les échanges entre pays", "le commerce local", "la production", "la consommation"], 0),
            ("La balance commerciale est :", ["exportations - importations", "PIB - consommation", "recettes - dépenses", "actif - passif"], 0),
            ("Le protectionnisme :", ["protège l'économie nationale", "favorise le libre-échange", "augmente les importations", "supprime les frontières"], 0),
            ("Le libre-échange :", ["la libre circulation des biens", "le protectionnisme", "l'isolement", "la guerre"], 0),
            ("L'État-providence :", ["intervient dans l'économie et le social", "ne fait rien", "produit des biens", "consomme"], 0),
            ("La protection sociale :", ["protège contre les risques sociaux", "protège les frontières", "augmente les impôts", "réduit les salaires"], 0),
            ("La sécurité sociale :", ["couvre les risques sociaux", "est une entreprise", "est un État", "est une religion"], 0),
            ("Les cotisations sociales :", ["financent la protection sociale", "sont des salaires", "sont des profits", "sont des rentes"], 0),
            ("La redistribution :", ["transfère des revenus", "produit des biens", "consomme", "investit"], 0),
            ("Les inégalités sont :", ["des différences d'accès aux ressources", "des égalités", "des libertés", "des devoirs"], 0),
            ("L'égalité des chances :", ["donne les mêmes opportunités", "donne les mêmes revenus", "supprime les différences", "est impossible"], 0),
            ("La discrimination est :", ["un traitement inégal injustifié", "une égalité", "une liberté", "un devoir"], 0),
            ("Le genre :", ["les rôles sociaux liés au sexe", "le sexe biologique", "l'âge", "la classe"], 0),
            ("Les inégalités de genre :", ["des différences entre hommes et femmes", "des égalités", "des libertés", "des devoirs"], 0),
            ("La pauvreté est :", ["le manque de ressources", "la richesse", "l'égalité", "la liberté"], 0),
            ("Le seuil de pauvreté :", ["le niveau de revenu sous lequel on est pauvre", "le salaire moyen", "le PIB", "le chômage"], 0),
            ("Le développement durable :", ["satisfait les besoins sans compromettre l'avenir", "la croissance rapide", "l'exploitation maximale", "la consommation"], 0),
        ],
    },
    "mathematiques-appliquees": {
        "subject": "Mathématiques Appliquées",
        "level": "Advanced Level (Lycée)",
        "class": "Terminale",
        "series": "Mathématiques Appliquées",
        "exam": "Baccalauréat",
        "questions": [
            ("La dérivée de $x^3$ est :", ["$3x^2$", "$x^2$", "$3x$", "$3x^3$"], 0),
            ("La dérivée de $\\sin(x)$ est :", ["$\\cos(x)$", "$-\\cos(x)$", "$\\sin(x)$", "$-\\sin(x)$"], 0),
            ("La dérivée de $\\cos(x)$ est :", ["$-\\sin(x)$", "$\\sin(x)$", "$\\cos(x)$", "$-\\cos(x)$"], 0),
            ("La dérivée de $e^x$ est :", ["$e^x$", "$x e^x$", "$e^{x-1}$", "$\\ln(x)$"], 0),
            ("La dérivée de $\\ln(x)$ est :", ["$\\frac{1}{x}$", "$x$", "$\\ln(x)$", "$\\frac{1}{\\ln(x)}$"], 0),
            ("L'intégrale de $x^2$ est :", ["$\\frac{x^3}{3} + C$", "$\\frac{x^2}{2} + C$", "$x^3 + C$", "$2x + C$"], 0),
            ("L'intégrale de $\\cos(x)$ est :", ["$\\sin(x) + C$", "$-\\sin(x) + C$", "$\\cos(x) + C$", "$-\\cos(x) + C$"], 0),
            ("L'intégrale de $\\frac{1}{x}$ est :", ["$\\ln|x| + C$", "$x + C$", "$\\frac{1}{x^2} + C$", "$e^x + C$"], 0),
            ("La limite de $\\frac{\\sin(x)}{x}$ quand $x \\to 0$ est :", ["1", "0", "$\\infty$", "n'existe pas"], 0),
            ("La limite de $\\frac{1}{x}$ quand $x \\to \\infty$ est :", ["0", "$\\infty$", "1", "n'existe pas"], 0),
            ("La fonction $f(x) = x^2$ est :", ["paire", "impaire", "ni paire ni impaire", "constante"], 0),
            ("La fonction $f(x) = x^3$ est :", ["impaire", "paire", "ni paire ni impaire", "constante"], 0),
            ("La dérivée de $x^n$ est :", ["$n x^{n-1}$", "$x^{n-1}$", "$n x^n$", "$(n-1)x^n$"], 0),
            ("L'équation $x^2 - 4 = 0$ a pour solutions :", ["$x = 2$ et $x = -2$", "$x = 2$", "$x = 4$", "$x = 16$"], 0),
            ("Le discriminant de $ax^2 + bx + c = 0$ est :", ["$b^2 - 4ac$", "$b^2 + 4ac$", "$4ac - b^2$", "$b - 4ac$"], 0),
            ("Si $\\Delta > 0$, l'équation du second degré a :", ["deux solutions réelles", "une solution", "aucune solution", "une solution complexe"], 0),
            ("Si $\\Delta = 0$, l'équation du second degré a :", ["une solution double", "deux solutions", "aucune solution", "deux solutions complexes"], 0),
            ("Si $\\Delta < 0$, l'équation du second degré a :", ["aucune solution réelle", "deux solutions réelles", "une solution", "une solution double"], 0),
            ("La dérivée de $\\tan(x)$ est :", ["$\\frac{1}{\\cos^2(x)}$", "$\\sin(x)$", "$\\cos(x)$", "$-\\frac{1}{\\sin^2(x)}$"], 0),
            ("L'intégrale de $e^x$ est :", ["$e^x + C$", "$\\frac{e^x}{x} + C$", "$x e^x + C$", "$\\ln(x) + C$"], 0),
            ("La fonction exponentielle $e^x$ est :", ["strictement croissante", "strictement décroissante", "constante", "périodique"], 0),
            ("La fonction logarithme $\\ln(x)$ est définie pour :", ["$x > 0$", "$x \\geq 0$", "$x \\neq 0$", "tout $x$"], 0),
            ("$\\ln(1)$ est égal à :", ["0", "1", "$e$", "$-1$"], 0),
            ("$\\ln(e)$ est égal à :", ["1", "0", "$e$", "$-1$"], 0),
            ("$e^0$ est égal à :", ["1", "0", "$e$", "$-1$"], 0),
            ("La dérivée de $\\frac{1}{x}$ est :", ["$-\\frac{1}{x^2}$", "$\\frac{1}{x^2}$", "$-\\frac{1}{x}$", "$\\ln(x)$"], 0),
            ("L'intégrale de $\\sin(x)$ est :", ["$-\\cos(x) + C$", "$\\cos(x) + C$", "$\\sin(x) + C$", "$-\\sin(x) + C$"], 0),
            ("La limite de $\\frac{x^2 - 1}{x - 1}$ quand $x \\to 1$ est :", ["2", "0", "1", "$\\infty$"], 0),
            ("La fonction $f(x) = \\frac{1}{x}$ est :", ["impaire", "paire", "ni paire ni impaire", "constante"], 0),
            ("Le nombre dérivé de $f$ en $a$ est :", ["$\\lim_{h \\to 0} \\frac{f(a+h) - f(a)}{h}$", "$f(a)$", "$\\frac{f(a)}{a}$", "$f'(a) \\times a$"], 0),
            ("La tangente à la courbe en $a$ a pour pente :", ["$f'(a)$", "$f(a)$", "$a$", "$f'(a) \\times a$"], 0),
            ("L'équation de la tangente en $a$ est :", ["$y = f'(a)(x - a) + f(a)$", "$y = f(a)x$", "$y = f'(a)x$", "$y = f(a) + x$"], 0),
            ("La fonction $f(x) = x^2$ est croissante sur :", ["$[0, +\\infty[$", "$]-\\infty, 0]$", "$\\mathbb{R}$", "$]-\\infty, +\\infty[$"], 0),
            ("La fonction $f(x) = x^2$ est décroissante sur :", ["$]-\\infty, 0]$", "$[0, +\\infty[$", "$\\mathbb{R}$", "nulle part"], 0),
            ("Le point d'inflexion est :", ["où la courbure change", "le maximum", "le minimum", "l'origine"], 0),
            ("La dérivée seconde de $x^3$ est :", ["$6x$", "$3x^2$", "$3x$", "$6$"], 0),
            ("La fonction $f(x) = e^x$ a pour limite en $+\\infty$ :", ["$+\\infty$", "0", "1", "$e$"], 0),
            ("La fonction $f(x) = e^x$ a pour limite en $-\\infty$ :", ["0", "$+\\infty$", "1", "$e$"], 0),
            ("La fonction $f(x) = \\ln(x)$ a pour limite en $+\\infty$ :", ["$+\\infty$", "0", "1", "$-\\infty$"], 0),
            ("La fonction $f(x) = \\ln(x)$ a pour limite en $0^+$ :", ["$-\\infty$", "$+\\infty$", "0", "1"], 0),
            ("L'asymptote horizontale de $f(x) = \\frac{1}{x}$ est :", ["$y = 0$", "$x = 0$", "$y = 1$", "$y = x$"], 0),
            ("L'asymptote verticale de $f(x) = \\frac{1}{x}$ est :", ["$x = 0$", "$y = 0$", "$x = 1$", "$y = 1$"], 0),
            ("La suite $u_n = 2n + 1$ est :", ["arithmétique", "géométrique", "ni l'un ni l'autre", "constante"], 0),
            ("La suite $u_n = 3 \\times 2^n$ est :", ["géométrique", "arithmétique", "ni l'un ni l'autre", "constante"], 0),
            ("La raison de la suite $u_n = 2n + 1$ est :", ["2", "1", "3", "n"], 0),
            ("La raison de la suite $u_n = 3 \\times 2^n$ est :", ["2", "3", "6", "n"], 0),
            ("La somme des $n$ premiers termes d'une suite arithmétique de raison $r$ est :", ["$\\frac{n(u_1 + u_n)}{2}$", "$n \\times r$", "$u_1 \\times r^n$", "$\\frac{n}{2} \\times r$"], 0),
            ("La somme des $n$ premiers termes d'une suite géométrique de raison $q$ est :", ["$u_1 \\frac{1 - q^n}{1 - q}$", "$n \\times u_1$", "$u_1 \\times q^n$", "$\\frac{n(u_1 + u_n)}{2}$"], 0),
            ("La probabilité d'un événement certain est :", ["1", "0", "0,5", "$\\infty$"], 0),
            ("La probabilité d'un événement impossible est :", ["0", "1", "0,5", "$\\infty$"], 0),
            ("La somme des probabilités d'un univers est :", ["1", "0", "0,5", "$\\infty$"], 0),
            ("Deux événements incompatibles :", ["ne peuvent pas se produire ensemble", "se produisent toujours ensemble", "sont certains", "sont impossibles"], 0),
            ("La probabilité de $A \\cup B$ si $A$ et $B$ sont incompatibles est :", ["$P(A) + P(B)$", "$P(A) \\times P(B)$", "$P(A) - P(B)$", "$P(A) / P(B)$"], 0),
            ("La probabilité conditionnelle $P(A|B)$ est :", ["$\\frac{P(A \\cap B)}{P(B)}$", "$P(A) \\times P(B)$", "$P(A) + P(B)$", "$\\frac{P(B)}{P(A)}$"], 0),
            ("L'espérance d'une variable aléatoire est :", ["la moyenne pondérée", "le maximum", "le minimum", "la variance"], 0),
            ("La variance mesure :", ["la dispersion", "la moyenne", "le maximum", "le minimum"], 0),
            ("L'écart-type est :", ["la racine carrée de la variance", "la variance", "la moyenne", "le maximum"], 0),
            ("La loi binomiale $B(n, p)$ a pour espérance :", ["$np$", "$n + p$", "$n - p$", "$p^n$"], 0),
            ("La loi normale est :", ["une loi continue", "une loi discrète", "une loi constante", "une loi nulle"], 0),
            ("La courbe de la loi normale est :", ["en cloche", "linéaire", "exponentielle", "constante"], 0),
        ],
    },
}

def build_mcq(subject_key, cfg, set_num):
    """Build MCQ content for a given set number."""
    subject = cfg["subject"]
    level = cfg["level"]
    class_label = cfg["class"]
    series = cfg["series"]
    exam = cfg["exam"]
    questions = cfg["questions"]

    # Rotate questions per set so each set is distinct
    n = len(questions)
    start = (set_num - 1) * 20 % n
    selected = [questions[(start + i) % n] for i in range(20)]

    lines = [
        f"# CAMEROON {exam} {subject.upper()} P1 SET {set_num}",
        "",
        "## Multiple Choice Question Bank",
        "",
        f"**Level:** {level}",
        f"**Class:** {class_label}",
        f"**Series:** {series}",
        f"**Subject:** {subject}",
        f"**Exam:** {exam}",
        "",
        "**Instructions:**",
        "",
        "- Choisis la bonne réponse A, B, C ou D pour chaque question.",
        "- Reporte clairement tes réponses sur la feuille de réponses fournie.",
        "- Chaque question vaut le même nombre de points. Aucun point n'est retiré pour une mauvaise réponse.",
        "- Utilise le corrigé à la fin de l'épreuve pour vérifier tes réponses.",
        "",
        "---",
        "",
        "## QUESTIONS",
        "",
    ]

    for i, (q, options, correct) in enumerate(selected, 1):
        lines.append(f"**Q{i}.** {q}")
        lines.append("")
        for letter, opt in zip("ABCD", options):
            lines.append(f"{letter}. {opt}")
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("## CORRIGÉ")
    lines.append("")
    for i, (q, options, correct) in enumerate(selected, 1):
        lines.append(f"{i}. {options[correct]}")
    lines.append("")

    return "\n".join(lines)


def main():
    for subject_key, cfg in SUBJECTS.items():
        d = BASE / subject_key
        d.mkdir(exist_ok=True)
        for set_num in (1, 2, 3):
            path = d / f"mcq-{set_num}.md"
            content = build_mcq(subject_key, cfg, set_num)
            path.write_text(content)
            print(f"Created: {path}")


if __name__ == "__main__":
    main()
