#!/usr/bin/env python3
"""
Generate French Lycée (advanced) content for the separate subjects used in
séries C/D: Physique, Chimie, SVT, Mathématiques, Français, Informatique.
Each gets 3 MCQ + 4 structural sets (sets 4-7) at Terminale level.
"""

from pathlib import Path

BASE = Path("/home/victoire-ws/Documents/ChatGPT/productivity - goals/study-spark/content/papers")

# dir -> (subject, level_label, class, series, exam, mcq_questions, sections)
SUBJECTS = {
    "physique": {
        "subject": "Physique", "level": "Advanced Level (Lycée)",
        "class": "Terminale", "series": "C, D, E, TI", "exam": "Baccalauréat",
        "mcq": [
            ("L'unité de la force est :", ["le newton", "le joule", "le watt", "le pascal"], 0),
            ("La formule de l'énergie cinétique est :", ["Ec = ½ mv²", "Ec = mv", "Ec = mgh", "Ec = ½ mgh"], 0),
            ("La loi de Coulomb s'écrit :", ["F = k·q₁q₂/r²", "F = k·r²/q₁q₂", "F = q₁q₂·r²", "F = k·q₁q₂·r"], 0),
            ("L'unité de la charge électrique est :", ["le coulomb", "le volt", "l'ampère", "l'ohm"], 0),
            ("La force de Lorentz s'exerce sur :", ["une charge en mouvement dans un champ", "une charge immobile", "un aimant", "un conducteur"], 0),
            ("La loi de Faraday concerne :", ["l'induction électromagnétique", "la gravitation", "l'optique", "la thermique"], 0),
            ("La loi de Lenz stipule que :", ["le courant induit s'oppose à sa cause", "le courant induit favorise sa cause", "il n'y a pas de courant induit", "le courant est nul"], 0),
            ("L'unité de la fréquence est :", ["le hertz", "le watt", "le volt", "l'ohm"], 0),
            ("La période T et la fréquence f sont liées par :", ["T = 1/f", "T = f", "T = 2f", "T = f²"], 0),
            ("La longueur d'onde λ et la fréquence f sont liées par :", ["λ = v/f", "λ = v·f", "λ = f/v", "λ = v+f"], 0),
            ("La vitesse de la lumière dans le vide est environ :", ["3×10⁸ m/s", "3×10⁶ m/s", "3×10¹⁰ m/s", "300 m/s"], 0),
            ("L'optique géométrique étudie :", ["la propagation de la lumière", "les ondes sonores", "les forces", "l'électricité"], 0),
            ("La loi de Snell-Descartes concerne :", ["la réfraction", "la gravitation", "l'induction", "la thermique"], 0),
            ("L'indice de réfraction du vide est :", ["1", "0", "1,5", "3"], 0),
            ("La vergence d'une lentille s'exprime en :", ["dioptries", "newtons", "watts", "ohms"], 0),
            ("La relation de conjugaison concerne :", ["les lentilles", "les forces", "les charges", "les ondes"], 0),
            ("La quantité de mouvement est :", ["p = mv", "p = m/v", "p = v/m", "p = m+v"], 0),
            ("Le théorème de l'énergie cinétique :", ["ΔEc = W", "ΔEc = P", "ΔEc = F", "ΔEc = m"], 0),
            ("Le travail d'une force constante est :", ["W = F·d·cos(θ)", "W = F·d", "W = F/d", "W = d/F"], 0),
            ("L'unité du travail est :", ["le joule", "le watt", "le newton", "le pascal"], 0),
            ("La puissance est :", ["P = W/t", "P = W·t", "P = t/W", "P = W+t"], 0),
            ("L'unité de la puissance est :", ["le watt", "le joule", "le newton", "le volt"], 0),
            ("Le moment d'une force s'exprime en :", ["N·m", "N/m", "N·m²", "N"], 0),
            ("L'équilibre d'un solide exige :", ["la somme des forces et moments nulle", "une force nulle", "un moment nul", "une vitesse nulle"], 0),
            ("Le champ gravitationnel est :", ["g = G·M/r²", "g = G·M·r²", "g = r²/G·M", "g = G·r²/M"], 0),
            ("La constante de gravitation G vaut :", ["6,67×10⁻¹¹ N·m²/kg²", "9,8 N/kg", "3×10⁸ m/s", "1,6×10⁻¹⁹ C"], 0),
            ("Le mouvement uniforme a :", ["une vitesse constante", "une accélération constante", "une vitesse nulle", "une accélération nulle"], 0),
            ("Le mouvement uniformément accéléré a :", ["une accélération constante", "une vitesse constante", "une vitesse nulle", "une accélération nulle"], 0),
            ("L'accélération est :", ["a = Δv/Δt", "a = Δv·Δt", "a = Δt/Δv", "a = v·t"], 0),
            ("L'unité de l'accélération est :", ["m/s²", "m/s", "m", "s"], 0),
            ("La radioactivité α émet :", ["un noyau d'hélium", "un électron", "un photon", "un neutron"], 0),
            ("La radioactivité β⁻ émet :", ["un électron", "un positron", "un photon", "un neutron"], 0),
            ("La radioactivité γ émet :", ["un photon", "un électron", "un proton", "un neutron"], 0),
            ("La demi-vie est :", ["le temps pour que la moitié se désintègre", "le temps total de désintégration", "la moitié de la masse", "la moitié de l'énergie"], 0),
            ("L'énergie de liaison est :", ["l'énergie pour séparer les nucléons", "l'énergie cinétique", "l'énergie potentielle", "l'énergie thermique"], 0),
            ("Le défaut de masse est :", ["la différence entre masse des nucléons et du noyau", "la masse totale", "la masse des électrons", "la masse nulle"], 0),
            ("L'équivalence masse-énergie est :", ["E = mc²", "E = mc", "E = m/c²", "E = c²/m"], 0),
            ("La fission nucléaire :", ["divise un noyau lourd", "fusionne des noyaux légers", "émet des électrons", "absorbe des photons"], 0),
            ("La fusion nucléaire :", ["fusionne des noyaux légers", "divise un noyau lourd", "émet des électrons", "absorbe des photons"], 0),
            ("Le circuit RLC série :", ["contient résistance, bobine et condensateur", "contient uniquement une résistance", "contient uniquement une bobine", "contient uniquement un condensateur"], 0),
            ("La résonance dans un circuit RLC :", ["l'impédance est minimale", "l'impédance est maximale", "le courant est nul", "la tension est nulle"], 0),
            ("L'impédance Z d'un circuit :", ["Z = U/I", "Z = U·I", "Z = I/U", "Z = U+I"], 0),
            ("L'unité de l'impédance est :", ["l'ohm", "le volt", "l'ampère", "le watt"], 0),
            ("Le facteur de puissance est :", ["cos(φ)", "sin(φ)", "tan(φ)", "φ"], 0),
            ("L'énergie électrique est :", ["E = P·t", "E = P/t", "E = t/P", "E = P+t"], 0),
            ("L'effet photoélectrique :", ["émission d'électrons par la lumière", "absorption de photons", "émission de photons", "réflexion"], 0),
            ("Le photon a une énergie :", ["E = h·f", "E = h/f", "E = f/h", "E = h+f"], 0),
            ("La constante de Planck h vaut :", ["6,63×10⁻³⁴ J·s", "6,67×10⁻¹¹", "9,8", "3×10⁸"], 0),
            ("L'effet Doppler concerne :", ["le changement de fréquence d'une onde", "la réfraction", "la réflexion", "l'absorption"], 0),
            ("Les ondes mécaniques :", ["nécessitent un milieu", "se propagent dans le vide", "sont des particules", "sont des charges"], 0),
            ("Les ondes électromagnétiques :", ["se propagent dans le vide", "nécessitent un milieu", "sont des particules", "sont des charges"], 0),
            ("Le son est :", ["une onde mécanique", "une onde électromagnétique", "une particule", "une charge"], 0),
            ("La vitesse du son dans l'air est environ :", ["340 m/s", "3×10⁸ m/s", "1500 m/s", "100 m/s"], 0),
            ("L'intensité sonore se mesure en :", ["décibels", "watts", "newtons", "pascals"], 0),
            ("Le champ électrique E s'exprime en :", ["V/m", "V", "A", "Ω"], 0),
            ("Le potentiel électrique s'exprime en :", ["volts", "ampères", "ohms", "watts"], 0),
            ("La capacité d'un condensateur s'exprime en :", ["farads", "ohms", "henrys", "volts"], 0),
            ("L'inductance d'une bobine s'exprime en :", ["henrys", "farads", "ohms", "volts"], 0),
            ("Le flux magnétique s'exprime en :", ["webers", "teslas", "henrys", "farads"], 0),
            ("Le champ magnétique s'exprime en :", ["teslas", "webers", "henrys", "farads"], 0),
        ],
        "sections": [
            ("MÉCANIQUE", [
                "Un solide de masse 2 kg glisse sur un plan incliné de 30°. Calculer les forces en jeu et l'accélération.",
                "Une voiture de 1 200 kg passe de 0 à 90 km/h en 10 s. Calculer l'accélération et la force résultante.",
                "Un projectile est lancé avec une vitesse initiale. Étudier son mouvement et calculer sa portée.",
                "Appliquer le théorème de l'énergie cinétique à un solide en mouvement.",
                "Calculer le moment d'une force et déterminer l'équilibre d'un solide.",
            ]),
            ("ÉLECTRICITÉ ET MAGNÉTISME", [
                "Étudier un circuit RLC série et déterminer la fréquence de résonance.",
                "Calculer l'impédance d'un circuit et le déphasage courant-tension.",
                "Appliquer la loi de Coulomb à deux charges ponctuelles.",
                "Calculer la force de Lorentz sur une charge en mouvement.",
                "Expliquer le phénomène d'induction électromagnétique et appliquer la loi de Faraday.",
            ]),
            ("ONDES ET OPTIQUE", [
                "Étudier la propagation d'une onde et calculer sa vitesse, période et longueur d'onde.",
                "Appliquer les lois de Snell-Descartes à la réfraction.",
                "Déterminer la vergence d'une lentille et la position de l'image.",
                "Expliquer l'effet Doppler et ses applications.",
                "Étudier les interférences et la diffraction des ondes.",
            ]),
            ("PHYSIQUE MODERNE ET NUCLÉAIRE", [
                "Expliquer les différents types de radioactivité (α, β, γ).",
                "Calculer l'énergie de liaison et le défaut de masse d'un noyau.",
                "Écrire et équilibrer une réaction de fission nucléaire.",
                "Expliquer le principe de la fusion nucléaire.",
                "Appliquer l'effet photoélectrique et calculer l'énergie des photons.",
            ]),
        ],
    },
    "chimie": {
        "subject": "Chimie", "level": "Advanced Level (Lycée)",
        "class": "Terminale", "series": "C, D, E, TI", "exam": "Baccalauréat",
        "mcq": [
            ("Le nombre d'Avogadro est :", ["6,02×10²³", "6,67×10⁻¹¹", "3×10⁸", "9,8"], 0),
            ("La mole est :", ["l'unité de quantité de matière", "l'unité de masse", "l'unité de volume", "l'unité de température"], 0),
            ("La masse molaire s'exprime en :", ["g/mol", "g", "mol", "kg"], 0),
            ("Le volume molaire d'un gaz dans les CNTP est :", ["22,4 L/mol", "1 L/mol", "6,02 L/mol", "100 L/mol"], 0),
            ("La concentration molaire est :", ["C = n/V", "C = n·V", "C = V/n", "C = n+V"], 0),
            ("La concentration massique est :", ["Cm = m/V", "Cm = m·V", "Cm = V/m", "Cm = m+V"], 0),
            ("Le pH d'une solution est :", ["pH = -log[H⁺]", "pH = log[H⁺]", "pH = [H⁺]", "pH = 1/[H⁺]"], 0),
            ("Une solution neutre a un pH :", ["égal à 7", "inférieur à 7", "supérieur à 7", "égal à 0"], 0),
            ("La constante d'acidité Ka :", ["mesure la force d'un acide", "mesure la température", "mesure la masse", "mesure le volume"], 0),
            ("Un acide fort :", ["se dissocie totalement", "se dissocie partiellement", "ne se dissocie pas", "est basique"], 0),
            ("Une base faible :", ["se dissocie partiellement", "se dissocie totalement", "ne se dissocie pas", "est acide"], 0),
            ("La réaction d'oxydoréduction :", ["échange des électrons", "échange des protons", "échange des neutrons", "échange de la chaleur"], 0),
            ("L'oxydation est :", ["une perte d'électrons", "un gain d'électrons", "un gain de protons", "une perte de protons"], 0),
            ("La réduction est :", ["un gain d'électrons", "une perte d'électrons", "un gain de protons", "une perte de protons"], 0),
            ("L'oxydant est :", ["l'espèce qui capte des électrons", "l'espèce qui cède des électrons", "l'espèce neutre", "l'espèce chargée"], 0),
            ("Le réducteur est :", ["l'espèce qui cède des électrons", "l'espèce qui capte des électrons", "l'espèce neutre", "l'espèce chargée"], 0),
            ("Le nombre d'oxydation :", ["mesure l'état d'oxydation", "mesure la masse", "mesure le volume", "mesure la température"], 0),
            ("L'électrolyse :", ["transforme l'énergie électrique en chimique", "produit de l'électricité", "est une combustion", "est une distillation"], 0),
            ("La pile électrochimique :", ["transforme l'énergie chimique en électrique", "consomme de l'électricité", "est une électrolyse", "est une combustion"], 0),
            ("L'anode est :", ["l'électrode où a lieu l'oxydation", "l'électrode où a lieu la réduction", "l'électrode neutre", "le pôle négatif"], 0),
            ("La cathode est :", ["l'électrode où a lieu la réduction", "l'électrode où a lieu l'oxydation", "l'électrode neutre", "le pôle positif"], 0),
            ("La cinétique chimique étudie :", ["la vitesse des réactions", "l'équilibre", "la thermodynamique", "la structure"], 0),
            ("La vitesse d'une réaction :", ["diminue avec le temps", "augmente avec le temps", "est constante", "est nulle"], 0),
            ("Un catalyseur :", ["accélère la réaction sans être consommé", "ralentit la réaction", "est consommé", "n'a aucun effet"], 0),
            ("La température :", ["augmente la vitesse de réaction", "diminue la vitesse", "n'a aucun effet", "arrête la réaction"], 0),
            ("L'équilibre chimique :", ["les vitesses directe et inverse sont égales", "la réaction s'arrête", "les concentrations sont nulles", "la réaction est totale"], 0),
            ("La constante d'équilibre K :", ["caractérise l'équilibre", "mesure la vitesse", "mesure la température", "mesure la masse"], 0),
            ("Le principe de Le Chatelier :", ["un système réagit pour s'opposer à une perturbation", "un système ne réagit pas", "un système accélère", "un système s'arrête"], 0),
            ("La thermochimie étudie :", ["les échanges de chaleur", "la vitesse", "l'équilibre", "la structure"], 0),
            ("Une réaction exothermique :", ["libère de la chaleur", "absorbe de la chaleur", "ne dégage rien", "est froide"], 0),
            ("Une réaction endothermique :", ["absorbe de la chaleur", "libère de la chaleur", "ne dégage rien", "est chaude"], 0),
            ("L'enthalpie de réaction ΔH :", ["mesure la chaleur échangée", "mesure la vitesse", "mesure la masse", "mesure le volume"], 0),
            ("La chimie organique étudie :", ["les composés du carbone", "les métaux", "les gaz rares", "les sels"], 0),
            ("Le carbone a une valence :", ["4", "2", "3", "1"], 0),
            ("L'isomérie :", ["même formule brute, structure différente", "formule différente", "même structure", "même masse"], 0),
            ("Les alcanes ont pour formule générale :", ["CnH₂n₊₂", "CnH₂n", "CnH₂n₋₂", "CnHn"], 0),
            ("Les alcènes ont pour formule générale :", ["CnH₂n", "CnH₂n₊₂", "CnH₂n₋₂", "CnHn"], 0),
            ("Les alcynes ont pour formule générale :", ["CnH₂n₋₂", "CnH₂n", "CnH₂n₊₂", "CnHn"], 0),
            ("Le groupe fonctionnel des alcools est :", ["-OH", "-COOH", "-CHO", "-NH₂"], 0),
            ("Le groupe fonctionnel des acides carboxyliques est :", ["-COOH", "-OH", "-CHO", "-NH₂"], 0),
            ("Le groupe fonctionnel des aldéhydes est :", ["-CHO", "-OH", "-COOH", "-NH₂"], 0),
            ("Le groupe fonctionnel des amines est :", ["-NH₂", "-OH", "-COOH", "-CHO"], 0),
            ("L'estérification :", ["acide + alcool → ester + eau", "acide + base → sel", "alcool → alcène", "alcane → alcool"], 0),
            ("L'hydrolyse d'un ester :", ["ester + eau → acide + alcool", "ester → alcool", "ester → acide", "ester → sel"], 0),
            ("La saponification :", ["ester + base → savon + alcool", "acide + alcool → ester", "alcool → alcène", "alcane → alcool"], 0),
            ("La polymérisation :", ["assemble des monomères", "divise des polymères", "est une combustion", "est une distillation"], 0),
            ("Le monomère est :", ["l'unité de base du polymère", "le polymère", "le produit final", "un catalyseur"], 0),
            ("La distillation :", ["sépare les constituants d'un mélange", "mélange deux liquides", "solidifie", "cristallise"], 0),
            ("La chromatographie :", ["sépare les constituants d'un mélange", "mélange", "solidifie", "cristallise"], 0),
            ("Le titrage :", ["détermine une concentration", "mesure la masse", "mesure le volume", "mesure la température"], 0),
            ("Le point d'équivalence :", ["les réactifs sont en proportions stœchiométriques", "la réaction s'arrête", "le pH est nul", "la température est maximale"], 0),
            ("La spectrophotométrie :", ["mesure l'absorbance", "mesure la masse", "mesure le volume", "mesure la température"], 0),
            ("La loi de Beer-Lambert :", ["A = ε·l·C", "A = ε·l/C", "A = C/ε·l", "A = ε·C/l"], 0),
            ("L'absorbance est :", ["proportionnelle à la concentration", "inversement proportionnelle", "constante", "nulle"], 0),
            ("Le tableau d'avancement :", ["suit l'évolution d'une réaction", "mesure la vitesse", "mesure la température", "mesure la masse"], 0),
            ("L'avancement maximal :", ["quand le réactif limitant est consommé", "quand la réaction s'arrête", "quand le pH est nul", "quand la température est maximale"], 0),
            ("Le réactif limitant :", ["est entièrement consommé", "reste en excès", "est le catalyseur", "est le produit"], 0),
            ("Le rendement d'une réaction :", ["quantité obtenue / quantité théorique", "quantité théorique / obtenue", "quantité obtenue × théorique", "quantité théorique"], 0),
            ("La chimie verte :", ["réduit l'impact environnemental", "augmente les déchets", "utilise des toxiques", "est polluante"], 0),
            ("L'atome de carbone peut former :", ["4 liaisons", "2 liaisons", "3 liaisons", "1 liaison"], 0),
        ],
        "sections": [
            ("CHIMIE GÉNÉRALE ET QUANTITATIVE", [
                "Calculer la quantité de matière, la masse et le volume d'un gaz dans les CNTP.",
                "Préparer une solution de concentration donnée par dissolution et par dilution.",
                "Déterminer la concentration d'une solution par titrage.",
                "Établir un tableau d'avancement pour une réaction chimique.",
                "Calculer le rendement d'une réaction.",
            ]),
            ("ACIDES, BASES ET ÉQUILIBRES", [
                "Calculer le pH d'une solution d'acide fort et d'une base forte.",
                "Expliquer la notion d'équilibre acido-basique et calculer Ka.",
                "Déterminer le pH d'une solution tampon.",
                "Étudier l'équilibre chimique et appliquer le principe de Le Chatelier.",
                "Réaliser un titrage acido-basique et déterminer le point d'équivalence.",
            ]),
            ("OXYDORÉDUCTION ET ÉLECTROCHIMIE", [
                "Équilibrer une équation d'oxydoréduction.",
                "Déterminer les nombres d'oxydation dans une réaction.",
                "Expliquer le fonctionnement d'une pile électrochimique.",
                "Décrire le processus d'électrolyse.",
                "Calculer la quantité d'électricité et la masse déposée lors d'une électrolyse.",
            ]),
            ("CHIMIE ORGANIQUE", [
                "Nommer et représenter les alcanes, alcènes et alcynes.",
                "Identifier les groupes fonctionnels des composés organiques.",
                "Écrire et équilibrer une réaction d'estérification.",
                "Expliquer la saponification et ses applications.",
                "Décrire la polymérisation et ses applications.",
            ]),
        ],
    },
    "svt-terminale": {
        "subject": "Sciences de la Vie et de la Terre", "level": "Advanced Level (Lycée)",
        "class": "Terminale", "series": "C, D, TI", "exam": "Baccalauréat",
        "mcq": [
            ("L'ADN est composé de :", ["nucléotides", "acides aminés", "glucides", "lipides"], 0),
            ("Les nucléotides de l'ADN contiennent :", ["A, T, G, C", "A, U, G, C", "A, T, G, U", "A, U, T, C"], 0),
            ("L'ARN contient :", ["l'uracile au lieu de la thymine", "la thymine au lieu de l'uracile", "les mêmes bases que l'ADN", "aucune base"], 0),
            ("La réplication de l'ADN est :", ["semi-conservative", "conservative", "dispersive", "nulle"], 0),
            ("La transcription :", ["ADN → ARN", "ARN → protéine", "ADN → protéine", "protéine → ADN"], 0),
            ("La traduction :", ["ARN → protéine", "ADN → ARN", "ADN → protéine", "protéine → ARN"], 0),
            ("Le codon est :", ["un triplet de nucléotides", "un acide aminé", "un gène", "un chromosome"], 0),
            ("Le gène est :", ["un segment d'ADN", "une protéine", "un chromosome", "un acide aminé"], 0),
            ("La mutation :", ["modifie la séquence d'ADN", "est toujours nocive", "est toujours bénéfique", "n'a aucun effet"], 0),
            ("Le caryotype humain a :", ["46 chromosomes", "23 chromosomes", "48 chromosomes", "44 chromosomes"], 0),
            ("Les chromosomes sexuels chez l'homme sont :", ["XY", "XX", "YY", "X"], 0),
            ("Les chromosomes sexuels chez la femme sont :", ["XX", "XY", "YY", "X"], 0),
            ("La méiose produit :", ["4 cellules haploïdes", "2 cellules diploïdes", "4 cellules diploïdes", "2 cellules haploïdes"], 0),
            ("La mitose produit :", ["2 cellules diploïdes identiques", "4 cellules haploïdes", "2 cellules haploïdes", "4 cellules diploïdes"], 0),
            ("Le brassage génétique :", ["crée de la diversité", "élimine la diversité", "est nul", "est constant"], 0),
            ("L'immunité innée :", ["est non spécifique", "est spécifique", "est acquise", "est absente"], 0),
            ("L'immunité adaptative :", ["est spécifique", "est non spécifique", "est innée", "est absente"], 0),
            ("Les lymphocytes B produisent :", ["des anticorps", "des antigènes", "des globules rouges", "des plaquettes"], 0),
            ("Les lymphocytes T :", ["détruisent les cellules infectées", "produisent des anticorps", "transportent l'oxygène", "coagulent le sang"], 0),
            ("L'antigène est :", ["une substance reconnue comme étrangère", "un anticorps", "un globule", "une hormone"], 0),
            ("L'anticorps est :", ["une protéine qui neutralise l'antigène", "un antigène", "un globule", "une hormone"], 0),
            ("La vaccination :", ["stimule l'immunité adaptative", "détruit les anticorps", "est inutile", "affaiblit l'immunité"], 0),
            ("Le VIH :", ["détruit les lymphocytes T", "produit des anticorps", "est une bactérie", "est un parasite"], 0),
            ("Le SIDA est causé par :", ["le VIH", "une bactérie", "un parasite", "un champignon"], 0),
            ("La neurotransmission :", ["transmet l'influx nerveux", "produit des hormones", "transporte l'oxygène", "coagule le sang"], 0),
            ("Le neurone :", ["transmet l'influx nerveux", "produit des hormones", "transporte l'oxygène", "coagule le sang"], 0),
            ("La synapse :", ["zone de contact entre neurones", "le corps du neurone", "l'axone", "la dendrite"], 0),
            ("Les hormones :", ["sont des messagers chimiques", "sont des neurones", "sont des globules", "sont des anticorps"], 0),
            ("Le système endocrinien :", ["produit des hormones", "transmet l'influx nerveux", "transporte l'oxygène", "coagule le sang"], 0),
            ("La glycémie est :", ["le taux de glucose dans le sang", "le taux de sel", "le taux de protéines", "le taux de lipides"], 0),
            ("L'insuline :", ["diminue la glycémie", "augmente la glycémie", "n'a aucun effet", "est un glucide"], 0),
            ("Le glucagon :", ["augmente la glycémie", "diminue la glycémie", "n'a aucun effet", "est un glucide"], 0),
            ("Le diabète :", ["trouble de la régulation de la glycémie", "une maladie du cœur", "une maladie des reins", "une maladie des poumons"], 0),
            ("La reproduction sexuée :", ["fait intervenir deux gamètes", "un seul gamète", "aucun gamète", "des spores"], 0),
            ("La fécondation :", ["fusion de deux gamètes", "division cellulaire", "production de gamètes", "respiration"], 0),
            ("La contraception :", ["évite une grossesse", "favorise la grossesse", "guérit une maladie", "stimule la croissance"], 0),
            ("Les IST :", ["sont transmises sexuellement", "sont héréditaires", "sont alimentaires", "sont respiratoires"], 0),
            ("Le préservatif :", ["protège contre les IST et le VIH", "protège uniquement la grossesse", "est inutile", "est dangereux"], 0),
            ("La tectonique des plaques :", ["explique les séismes et volcans", "explique la photosynthèse", "explique la digestion", "explique la respiration"], 0),
            ("Le séisme :", ["rupture des roches en profondeur", "éruption volcanique", "pluie", "vent"], 0),
            ("Le volcan :", ["remontée du magma", "séisme", "pluie", "vent"], 0),
            ("Les roches magmatiques :", ["refroidissement du magma", "sédimentation", "métamorphisme", "érosion"], 0),
            ("Les roches sédimentaires :", ["accumulation de sédiments", "refroidissement du magma", "métamorphisme", "éruption"], 0),
            ("Les roches métamorphiques :", ["transformation sous pression/température", "refroidissement du magma", "sédimentation", "érosion"], 0),
            ("Le fossile :", ["reste d'être vivant conservé", "une roche", "un minéral", "un volcan"], 0),
            ("La datation relative :", ["ordonne les événements dans le temps", "donne un âge absolu", "mesure la température", "mesure la masse"], 0),
            ("La datation absolue :", ["donne un âge en années", "ordonne les événements", "mesure la température", "mesure la masse"], 0),
            ("La dérive des continents :", ["les continents se déplacent", "les continents sont fixes", "les océans disparaissent", "la Terre est plate"], 0),
            ("L'expansion océanique :", ["les fonds océaniques s'écartent", "les océans rétrécissent", "les continents se rapprochent", "la Terre rétrécit"], 0),
            ("La subduction :", ["plongement d'une plaque sous une autre", "écartement des plaques", "collision", "érosion"], 0),
            ("La biodiversité :", ["variété des êtres vivants", "quantité d'eau", "température", "pression"], 0),
            ("L'évolution :", ["transformation des espèces au fil du temps", "fixité des espèces", "disparition des espèces", "création"], 0),
            ("La sélection naturelle :", ["survit des individus adaptés", "survit des individus faibles", "tous survivent", "aucun ne survit"], 0),
            ("L'adaptation :", ["caractère favorisant la survie", "un défaut", "un hasard", "une maladie"], 0),
            ("L'écosystème :", ["biotope + biocénose", "uniquement les plantes", "uniquement les animaux", "uniquement l'eau"], 0),
            ("La chaîne alimentaire :", ["commence par un producteur", "commence par un prédateur", "commence par un décomposeur", "n'a pas de début"], 0),
            ("Le réchauffement climatique :", ["augmentation des gaz à effet de serre", "baisse de température", "augmentation de l'oxygène", "baisse du CO₂"], 0),
            ("Le développement durable :", ["satisfait les besoins sans compromettre l'avenir", "exploite au maximum", "consomme", "pollue"], 0),
            ("La génétique des populations :", ["étudie la fréquence des allèles", "étudie les fossiles", "étudie les roches", "étudie le climat"], 0),
            ("La loi de Hardy-Weinberg :", ["décrit l'équilibre génétique", "décrit l'évolution", "décrit la sélection", "décrit la mutation"], 0),
        ],
        "sections": [
            ("GÉNÉTIQUE ET BIOLOGIE MOLÉCULAIRE", [
                "Décrire la structure de l'ADN et expliquer la réplication.",
                "Expliquer le mécanisme de la transcription et de la traduction.",
                "Résoudre un exercice de génétique mendélienne.",
                "Expliquer les différents types de mutations et leurs conséquences.",
                "Analyser un caryotype et identifier les anomalies.",
            ]),
            ("IMMUNOLOGIE", [
                "Décrire les mécanismes de l'immunité innée et adaptative.",
                "Expliquer le rôle des lymphocytes B et T.",
                "Décrire le fonctionnement de la vaccination.",
                "Expliquer l'infection par le VIH et le développement du SIDA.",
                "Expliquer les réactions de rejet de greffe.",
            ]),
            ("PHYSIOLOGIE ET RÉGULATION", [
                "Décrire le fonctionnement du système nerveux et la transmission synaptique.",
                "Expliquer la régulation de la glycémie.",
                "Décrire le fonctionnement du système endocrinien.",
                "Expliquer la régulation de la température corporelle.",
                "Décrire le fonctionnement de la reproduction humaine.",
            ]),
            ("GÉOLOGIE ET ÉVOLUTION", [
                "Expliquer la théorie de la tectonique des plaques.",
                "Décrire les différents types de roches et leur formation.",
                "Expliquer les méthodes de datation relative et absolue.",
                "Décrire les mécanismes de l'évolution et la sélection naturelle.",
                "Expliquer les preuves de l'évolution des espèces.",
            ]),
        ],
    },
    "mathematiques": {
        "subject": "Mathématiques", "level": "Advanced Level (Lycée)",
        "class": "Terminale", "series": "C, D, E, TI", "exam": "Baccalauréat",
        "mcq": [
            ("La dérivée de $x^3$ est :", ["$3x^2$", "$x^2$", "$3x$", "$3x^3$"], 0),
            ("La dérivée de $\\sin(x)$ est :", ["$\\cos(x)$", "$-\\cos(x)$", "$\\sin(x)$", "$-\\sin(x)$"], 0),
            ("La dérivée de $\\cos(x)$ est :", ["$-\\sin(x)$", "$\\sin(x)$", "$\\cos(x)$", "$-\\cos(x)$"], 0),
            ("La dérivée de $e^x$ est :", ["$e^x$", "$x e^x$", "$e^{x-1}$", "$\\ln(x)$"], 0),
            ("La dérivée de $\\ln(x)$ est :", ["$\\frac{1}{x}$", "$x$", "$\\ln(x)$", "$\\frac{1}{\\ln(x)}$"], 0),
            ("L'intégrale de $x^2$ est :", ["$\\frac{x^3}{3} + C$", "$\\frac{x^2}{2} + C$", "$x^3 + C$", "$2x + C$"], 0),
            ("L'intégrale de $\\cos(x)$ est :", ["$\\sin(x) + C$", "$-\\sin(x) + C$", "$\\cos(x) + C$", "$-\\cos(x) + C$"], 0),
            ("L'intégrale de $\\frac{1}{x}$ est :", ["$\\ln|x| + C$", "$x + C$", "$\\frac{1}{x^2} + C$", "$e^x + C$"], 0),
            ("La limite de $\\frac{\\sin(x)}{x}$ quand $x \\to 0$ est :", ["1", "0", "$\\infty$", "n'existe pas"], 0),
            ("La limite de $\\frac{1}{x}$ quand $x \\to \\infty$ est :", ["0", "$\\infty$", "1", "n'existe pas"], 0),
            ("La fonction $f(x) = x^2$ est :", ["paire", "impaire", "ni paire ni impaire", "constante"], 0),
            ("La fonction $f(x) = x^3$ est :", ["impaire", "paire", "ni paire ni impaire", "constante"], 0),
            ("La dérivée de $x^n$ est :", ["$n x^{n-1}$", "$x^{n-1}$", "$n x^n$", "$(n-1)x^n$"], 0),
            ("L'équation $x^2 - 4 = 0$ a pour solutions :", ["$x = 2$ et $x = -2$", "$x = 2$", "$x = 4$", "$x = 16$"], 0),
            ("Le discriminant de $ax^2 + bx + c = 0$ est :", ["$b^2 - 4ac$", "$b^2 + 4ac$", "$4ac - b^2$", "$b - 4ac$"], 0),
            ("Si $\\Delta > 0$, l'équation du second degré a :", ["deux solutions réelles", "une solution", "aucune solution", "une solution complexe"], 0),
            ("Si $\\Delta = 0$, l'équation du second degré a :", ["une solution double", "deux solutions", "aucune solution", "deux solutions complexes"], 0),
            ("Si $\\Delta < 0$, l'équation du second degré a :", ["aucune solution réelle", "deux solutions réelles", "une solution", "une solution double"], 0),
            ("La dérivée de $\\tan(x)$ est :", ["$\\frac{1}{\\cos^2(x)}$", "$\\sin(x)$", "$\\cos(x)$", "$-\\frac{1}{\\sin^2(x)}$"], 0),
            ("L'intégrale de $e^x$ est :", ["$e^x + C$", "$\\frac{e^x}{x} + C$", "$x e^x + C$", "$\\ln(x) + C$"], 0),
            ("La fonction exponentielle $e^x$ est :", ["strictement croissante", "strictement décroissante", "constante", "périodique"], 0),
            ("La fonction logarithme $\\ln(x)$ est définie pour :", ["$x > 0$", "$x \\geq 0$", "$x \\neq 0$", "tout $x$"], 0),
            ("$\\ln(1)$ est égal à :", ["0", "1", "$e$", "$-1$"], 0),
            ("$\\ln(e)$ est égal à :", ["1", "0", "$e$", "$-1$"], 0),
            ("$e^0$ est égal à :", ["1", "0", "$e$", "$-1$"], 0),
            ("La dérivée de $\\frac{1}{x}$ est :", ["$-\\frac{1}{x^2}$", "$\\frac{1}{x^2}$", "$-\\frac{1}{x}$", "$\\ln(x)$"], 0),
            ("L'intégrale de $\\sin(x)$ est :", ["$-\\cos(x) + C$", "$\\cos(x) + C$", "$\\sin(x) + C$", "$-\\sin(x) + C$"], 0),
            ("La limite de $\\frac{x^2 - 1}{x - 1}$ quand $x \\to 1$ est :", ["2", "0", "1", "$\\infty$"], 0),
            ("La fonction $f(x) = \\frac{1}{x}$ est :", ["impaire", "paire", "ni paire ni impaire", "constante"], 0),
            ("Le nombre dérivé de $f$ en $a$ est :", ["$\\lim_{h \\to 0} \\frac{f(a+h) - f(a)}{h}$", "$f(a)$", "$\\frac{f(a)}{a}$", "$f'(a) \\times a$"], 0),
            ("La tangente à la courbe en $a$ a pour pente :", ["$f'(a)$", "$f(a)$", "$a$", "$f'(a) \\times a$"], 0),
            ("L'équation de la tangente en $a$ est :", ["$y = f'(a)(x - a) + f(a)$", "$y = f(a)x$", "$y = f'(a)x$", "$y = f(a) + x$"], 0),
            ("La fonction $f(x) = x^2$ est croissante sur :", ["$[0, +\\infty[$", "$]-\\infty, 0]$", "$\\mathbb{R}$", "$]-\\infty, +\\infty[$"], 0),
            ("La fonction $f(x) = x^2$ est décroissante sur :", ["$]-\\infty, 0]$", "$[0, +\\infty[$", "$\\mathbb{R}$", "nulle part"], 0),
            ("Le point d'inflexion est :", ["où la courbure change", "le maximum", "le minimum", "l'origine"], 0),
            ("La dérivée seconde de $x^3$ est :", ["$6x$", "$3x^2$", "$3x$", "$6$"], 0),
            ("La fonction $f(x) = e^x$ a pour limite en $+\\infty$ :", ["$+\\infty$", "0", "1", "$e$"], 0),
            ("La fonction $f(x) = e^x$ a pour limite en $-\\infty$ :", ["0", "$+\\infty$", "1", "$e$"], 0),
            ("La fonction $f(x) = \\ln(x)$ a pour limite en $+\\infty$ :", ["$+\\infty$", "0", "1", "$-\\infty$"], 0),
            ("La fonction $f(x) = \\ln(x)$ a pour limite en $0^+$ :", ["$-\\infty$", "$+\\infty$", "0", "1"], 0),
            ("L'asymptote horizontale de $f(x) = \\frac{1}{x}$ est :", ["$y = 0$", "$x = 0$", "$y = 1$", "$y = x$"], 0),
            ("L'asymptote verticale de $f(x) = \\frac{1}{x}$ est :", ["$x = 0$", "$y = 0$", "$x = 1$", "$y = 1$"], 0),
            ("La suite $u_n = 2n + 1$ est :", ["arithmétique", "géométrique", "ni l'un ni l'autre", "constante"], 0),
            ("La suite $u_n = 3 \\times 2^n$ est :", ["géométrique", "arithmétique", "ni l'un ni l'autre", "constante"], 0),
            ("La raison de la suite $u_n = 2n + 1$ est :", ["2", "1", "3", "n"], 0),
            ("La raison de la suite $u_n = 3 \\times 2^n$ est :", ["2", "3", "6", "n"], 0),
            ("La somme des $n$ premiers termes d'une suite arithmétique de raison $r$ est :", ["$\\frac{n(u_1 + u_n)}{2}$", "$n \\times r$", "$u_1 \\times r^n$", "$\\frac{n}{2} \\times r$"], 0),
            ("La somme des $n$ premiers termes d'une suite géométrique de raison $q$ est :", ["$u_1 \\frac{1 - q^n}{1 - q}$", "$n \\times u_1$", "$u_1 \\times q^n$", "$\\frac{n(u_1 + u_n)}{2}$"], 0),
            ("La probabilité d'un événement certain est :", ["1", "0", "0,5", "$\\infty$"], 0),
            ("La probabilité d'un événement impossible est :", ["0", "1", "0,5", "$\\infty$"], 0),
            ("La somme des probabilités d'un univers est :", ["1", "0", "0,5", "$\\infty$"], 0),
            ("Deux événements incompatibles :", ["ne peuvent pas se produire ensemble", "se produisent toujours ensemble", "sont certains", "sont impossibles"], 0),
            ("La probabilité de $A \\cup B$ si $A$ et $B$ sont incompatibles est :", ["$P(A) + P(B)$", "$P(A) \\times P(B)$", "$P(A) - P(B)$", "$P(A) / P(B)$"], 0),
            ("La probabilité conditionnelle $P(A|B)$ est :", ["$\\frac{P(A \\cap B)}{P(B)}$", "$P(A) \\times P(B)$", "$P(A) + P(B)$", "$\\frac{P(B)}{P(A)}$"], 0),
            ("L'espérance d'une variable aléatoire est :", ["la moyenne pondérée", "le maximum", "le minimum", "la variance"], 0),
            ("La variance mesure :", ["la dispersion", "la moyenne", "le maximum", "le minimum"], 0),
            ("L'écart-type est :", ["la racine carrée de la variance", "la variance", "la moyenne", "le maximum"], 0),
            ("La loi binomiale $B(n, p)$ a pour espérance :", ["$np$", "$n + p$", "$n - p$", "$p^n$"], 0),
            ("La loi normale est :", ["une loi continue", "une loi discrète", "une loi constante", "une loi nulle"], 0),
            ("La courbe de la loi normale est :", ["en cloche", "linéaire", "exponentielle", "constante"], 0),
        ],
        "sections": [
            ("ANALYSE", [
                "Étudier les variations de la fonction $f(x) = x^3 - 3x + 2$ et tracer sa courbe.",
                "Calculer $\\lim_{x \\to +\\infty} \\frac{2x^2 + 3x - 1}{x^2 + 1}$.",
                "Calculer l'intégrale $\\int_0^1 (3x^2 + 2x) \\, dx$.",
                "Déterminer l'équation de la tangente à la courbe de $f(x) = \\ln(x)$ au point d'abscisse 1.",
                "Étudier la fonction $f(x) = \\frac{x}{x + 1}$ et tracer sa courbe.",
            ]),
            ("ALGÈBRE ET SUITES", [
                "Résoudre l'équation $x^2 - 5x + 6 = 0$.",
                "Étudier la suite $u_n = 2n + 3$ : nature, raison, terme général.",
                "Étudier la suite $u_n = 3 \\times 2^n$ : nature, raison, somme des n premiers termes.",
                "Résoudre le système : $\\begin{cases} x + 2y = 5 \\\\ 3x - y = 1 \\end{cases}$.",
                "Factoriser et résoudre : $x^3 - 4x = 0$.",
            ]),
            ("PROBABILITÉS ET STATISTIQUES", [
                "Une urne contient 5 boules rouges et 3 bleues. On tire 2 boules sans remise. Calculer la probabilité d'obtenir 2 boules rouges.",
                "Une variable aléatoire X suit la loi binomiale B(10 ; 0,4). Calculer son espérance et sa variance.",
                "Calculer la moyenne, la variance et l'écart-type de la série : 2, 4, 6, 8, 10.",
                "Deux événements A et B sont indépendants avec P(A) = 0,3 et P(B) = 0,5. Calculer P(A ∩ B).",
                "Une loi normale a pour moyenne 50 et écart-type 10. Calculer P(40 ≤ X ≤ 60).",
            ]),
            ("GÉOMÉTRIE ET COMPLEXES", [
                "Résoudre une équation dans l'ensemble des nombres complexes.",
                "Calculer le module et l'argument d'un nombre complexe.",
                "Déterminer l'image d'un point par une transformation géométrique.",
                "Calculer un produit scalaire et une norme dans l'espace.",
                "Résoudre un problème de géométrie dans l'espace.",
            ]),
        ],
    },
    "francais": {
        "subject": "Français", "level": "Advanced Level (Lycée)",
        "class": "Terminale", "series": "A1, A2, A4, ABI, C, D", "exam": "Baccalauréat",
        "mcq": [
            ("Le commentaire composé consiste à :", ["analyser un texte", "résumer un texte", "inventer un texte", "traduire un texte"], 0),
            ("La dissertation :", ["développe une réflexion argumentée", "résume un texte", "décrit un lieu", "raconte une histoire"], 0),
            ("La contraction de texte :", ["réduit un texte en respectant l'essentiel", "développe un texte", "traduit un texte", "invente un texte"], 0),
            ("Le registre lyrique exprime :", ["les sentiments personnels", "la peur", "le rire", "la colère"], 0),
            ("Le registre tragique :", ["la fatalité et la mort", "la joie", "le comique", "l'ironie"], 0),
            ("Le registre comique :", ["provoque le rire", "provoque la peur", "exprime la tristesse", "exprime la colère"], 0),
            ("Le registre épique :", ["héroïsme et grandeur", "le rire", "la peur", "la tristesse"], 0),
            ("Le registre pathétique :", ["susciter l'émotion et la pitié", "provoquer le rire", "exprimer la colère", "décrire"], 0),
            ("Le registre ironique :", ["dire le contraire de ce qu'on pense", "exprimer la joie", "décrire", "raconter"], 0),
            ("La tragédie classique respecte :", ["la règle des trois unités", "aucune règle", "la liberté totale", "le comique"], 0),
            ("La règle des trois unités :", ["temps, lieu, action", "temps, lieu, personnage", "action, personnage, décor", "temps, action, dialogue"], 0),
            ("La catharsis :", ["la purgation des passions", "le rire", "la peur", "la colère"], 0),
            ("Le théâtre de l'absurde :", ["l'absurdité de la condition humaine", "le réalisme", "le romantisme", "le classicisme"], 0),
            ("Le romantisme :", ["l'expression des sentiments", "la raison", "la mesure", "le classicisme"], 0),
            ("Le réalisme :", ["la représentation fidèle de la réalité", "l'idéalisation", "le rêve", "le fantastique"], 0),
            ("Le naturalisme :", ["l'application de la méthode scientifique", "l'idéalisation", "le rêve", "le fantastique"], 0),
            ("Le symbolisme :", ["les symboles et les correspondances", "le réalisme", "le naturalisme", "le classicisme"], 0),
            ("Le surréalisme :", ["l'inconscient et le rêve", "la raison", "la mesure", "le classicisme"], 0),
            ("La poésie lyrique :", ["exprime les sentiments", "raconte une histoire", "décrit", "argumente"], 0),
            ("Le sonnet :", ["14 vers", "12 vers", "10 vers", "16 vers"], 0),
            ("L'alexandrin :", ["12 syllabes", "10 syllabes", "8 syllabes", "14 syllabes"], 0),
            ("Le décasyllabe :", ["10 syllabes", "12 syllabes", "8 syllabes", "14 syllabes"], 0),
            ("L'octosyllabe :", ["8 syllabes", "10 syllabes", "12 syllabes", "14 syllabes"], 0),
            ("La rime plate :", ["aabb", "abab", "abba", "aaaa"], 0),
            ("La rime croisée :", ["abab", "aabb", "abba", "aaaa"], 0),
            ("La rime embrassée :", ["abba", "aabb", "abab", "aaaa"], 0),
            ("L'enjambement :", ["le rejet d'un mot à la ligne suivante", "la fin du vers", "la rime", "la césure"], 0),
            ("La métaphore filée :", ["une métaphore prolongée", "une comparaison", "une hyperbole", "une litote"], 0),
            ("L'oxymore :", ["l'union de termes contradictoires", "une comparaison", "une hyperbole", "une litote"], 0),
            ("L'antithèse :", ["l'opposition de deux idées", "l'union de contraires", "une exagération", "une atténuation"], 0),
            ("Le chiasme :", ["une structure croisée", "une répétition", "une exagération", "une atténuation"], 0),
            ("L'anaphore :", ["la répétition d'un mot en début de phrase", "une exagération", "une atténuation", "une comparaison"], 0),
            ("La gradation :", ["une progression croissante ou décroissante", "une répétition", "une exagération", "une atténuation"], 0),
            ("L'euphémisme :", ["atténue une réalité désagréable", "exagère", "compare", "oppose"], 0),
            ("La métonymie :", ["remplace un terme par un autre lié", "compare", "exagère", "atténue"], 0),
            ("La synecdoque :", ["la partie pour le tout", "le tout pour la partie", "une comparaison", "une exagération"], 0),
            ("Le discours narratif :", ["raconte une histoire", "argumente", "décrit", "explique"], 0),
            ("Le discours argumentatif :", ["convainc et persuade", "raconte", "décrit", "explique"], 0),
            ("Le discours descriptif :", ["décrit un lieu, une personne", "raconte", "argumente", "explique"], 0),
            ("Le discours explicatif :", ["explique un phénomène", "raconte", "convainc", "décrit"], 0),
            ("Le point de vue interne :", ["le narrateur voit par les yeux d'un personnage", "le narrateur voit tout", "le narrateur est absent", "le narrateur juge"], 0),
            ("Le point de vue omniscient :", ["le narrateur sait tout", "le narrateur voit par un personnage", "le narrateur est absent", "le narrateur juge"], 0),
            ("Le point de vue externe :", ["le narrateur observe de l'extérieur", "le narrateur sait tout", "le narrateur voit par un personnage", "le narrateur juge"], 0),
            ("Le narrateur interne :", ["est un personnage de l'histoire", "est extérieur", "est omniscient", "est absent"], 0),
            ("Le narrateur externe :", ["n'est pas un personnage", "est un personnage", "est omniscient", "est le héros"], 0),
            ("La focalisation zéro :", ["le narrateur omniscient", "le narrateur interne", "le narrateur externe", "le narrateur absent"], 0),
            ("La focalisation interne :", ["le narrateur voit par un personnage", "le narrateur omniscient", "le narrateur externe", "le narrateur absent"], 0),
            ("La focalisation externe :", ["le narrateur observe de l'extérieur", "le narrateur omniscient", "le narrateur interne", "le narrateur absent"], 0),
            ("Le classicisme :", ["la mesure et la raison", "l'expression des sentiments", "le rêve", "l'absurde"], 0),
            ("Le siècle des Lumières :", ["la raison et la critique", "le sentiment", "le rêve", "l'absurde"], 0),
            ("L'humanisme :", ["la confiance en l'homme", "la foi", "le doute", "l'absurde"], 0),
            ("Le baroque :", ["le mouvement et l'instabilité", "la mesure", "la raison", "le classicisme"], 0),
            ("La littérature africaine :", ["reflète les réalités africaines", "est européenne", "est asiatique", "est américaine"], 0),
            ("La négritude :", ["la valorisation de la culture noire", "le rejet de la culture", "la colonisation", "l'esclavage"], 0),
            ("Senghor est :", ["un poète de la négritude", "un romancier", "un dramaturge", "un essayiste"], 0),
            ("Le roman :", ["un récit en prose", "un poème", "une pièce de théâtre", "un essai"], 0),
            ("La nouvelle :", ["un récit court", "un roman", "un poème", "une pièce"], 0),
            ("L'essai :", ["une réflexion argumentée", "un récit", "un poème", "une pièce"], 0),
            ("La fable :", ["un récit allégorique avec morale", "un roman", "une pièce", "un essai"], 0),
            ("La satire :", ["critique les défauts", "loue les qualités", "raconte", "décrit"], 0),
        ],
        "sections": [
            ("COMMENTAIRE COMPOSÉ", [
                "Commenter un texte poétique en analysant la forme et le fond.",
                "Commenter un extrait de roman en étudiant la narration et les personnages.",
                "Commenter une scène de théâtre en analysant le dialogue et les didascalies.",
                "Analyser les procédés stylistiques d'un texte argumentatif.",
                "Commenter un texte en respectant la méthode (introduction, développement, conclusion).",
            ]),
            ("DISSERTATION", [
                "Dissertation : « La littérature doit-elle être engagée ? »",
                "Dissertation : « Le théâtre est-il le miroir de la société ? »",
                "Dissertation : « La poésie est-elle l'expression des sentiments ? »",
                "Dissertation : « Le roman reflète-t-il la réalité ? »",
                "Dissertation : « La littérature africaine a-t-elle une mission ? »",
            ]),
            ("CONTRACTION ET SUIVI DE TEXTE", [
                "Contracter un texte en respectant le nombre de mots imposé.",
                "Résumer un texte argumentatif en conservant les idées essentielles.",
                "Suivre un texte et répondre à des questions de compréhension.",
                "Analyser la structure d'un texte et dégager son plan.",
                "Reformuler les idées d'un texte sans le recopier.",
            ]),
            ("EXPRESSION ÉCRITE ET ORALE", [
                "Rédiger un paragraphe argumentatif sur un sujet donné.",
                "Écrire une lettre ouverte sur un sujet de société.",
                "Préparer et présenter un exposé oral.",
                "Rédiger un compte rendu de lecture.",
                "Écrire un dialogue argumentatif entre deux personnages.",
            ]),
        ],
    },
    "informatique-fr": {
        "subject": "Informatique", "level": "Advanced Level (Lycée)",
        "class": "Terminale", "series": "TI, C, D, E", "exam": "Baccalauréat",
        "mcq": [
            ("Un algorithme est :", ["une suite d'instructions", "un périphérique", "une mémoire", "un composant"], 0),
            ("La variable est :", ["un espace mémoire nommé", "un périphérique", "une mémoire", "un composant"], 0),
            ("Le type entier :", ["représente des nombres entiers", "représente des nombres décimaux", "représente du texte", "représente un booléen"], 0),
            ("Le type réel :", ["représente des nombres décimaux", "représente des entiers", "représente du texte", "représente un booléen"], 0),
            ("Le type chaîne :", ["représente du texte", "représente des entiers", "représente des décimaux", "représente un booléen"], 0),
            ("Le type booléen :", ["vrai ou faux", "des nombres", "du texte", "des caractères"], 0),
            ("La structure conditionnelle :", ["si... alors... sinon", "pour... faire", "tant que... faire", "répéter... jusqu'à"], 0),
            ("La boucle « pour » :", ["répète un nombre fixe de fois", "répète tant qu'une condition est vraie", "est une condition", "est une variable"], 0),
            ("La boucle « tant que » :", ["répète tant qu'une condition est vraie", "répète un nombre fixe de fois", "est une condition", "est une variable"], 0),
            ("L'opérateur de comparaison est :", ["=", "+", "*", "/"], 0),
            ("L'opérateur d'affectation :", ["attribue une valeur à une variable", "compare deux valeurs", "additionne", "multiplie"], 0),
            ("Le tableau :", ["une collection de valeurs", "une variable", "une condition", "une boucle"], 0),
            ("L'indice d'un tableau commence à :", ["0 ou 1", "10", "-1", "n'importe où"], 0),
            ("La fonction :", ["un bloc de code réutilisable", "une variable", "une condition", "une boucle"], 0),
            ("Le paramètre d'une fonction :", ["une donnée d'entrée", "une sortie", "une condition", "une boucle"], 0),
            ("La récursivité :", ["une fonction qui s'appelle elle-même", "une boucle", "une condition", "une variable"], 0),
            ("La complexité algorithmique :", ["mesure l'efficacité", "mesure la taille", "mesure la vitesse du processeur", "mesure la mémoire"], 0),
            ("Le tri à bulles :", ["un algorithme de tri", "une recherche", "une boucle", "une condition"], 0),
            ("La recherche dichotomique :", ["recherche dans un tableau trié", "recherche aléatoire", "un tri", "une boucle"], 0),
            ("La structure de données Pile :", ["LIFO (dernier entré, premier sorti)", "FIFO (premier entré, premier sorti)", "une file", "un tableau"], 0),
            ("La structure de données File :", ["FIFO (premier entré, premier sorti)", "LIFO (dernier entré, premier sorti)", "une pile", "un tableau"], 0),
            ("L'arbre binaire :", ["une structure hiérarchique", "une pile", "une file", "un tableau"], 0),
            ("Le graphe :", ["un ensemble de nœuds et d'arêtes", "une pile", "une file", "un tableau"], 0),
            ("La base de données :", ["un ensemble structuré de données", "un fichier", "un programme", "un périphérique"], 0),
            ("Le SGBD :", ["système de gestion de base de données", "un fichier", "un programme", "un périphérique"], 0),
            ("Le langage SQL :", ["interroge les bases de données", "crée des pages web", "est un système d'exploitation", "est un périphérique"], 0),
            ("La requête SELECT :", ["interroge les données", "insère des données", "supprime des données", "modifie des données"], 0),
            ("La requête INSERT :", ["insère des données", "interroge les données", "supprime des données", "modifie des données"], 0),
            ("La requête UPDATE :", ["modifie des données", "interroge les données", "insère des données", "supprime des données"], 0),
            ("La requête DELETE :", ["supprime des données", "interroge les données", "insère des données", "modifie des données"], 0),
            ("La clé primaire :", ["identifie de façon unique une ligne", "est une colonne", "est une table", "est une requête"], 0),
            ("La clé étrangère :", ["relie deux tables", "identifie une ligne", "est une colonne", "est une requête"], 0),
            ("Le réseau informatique :", ["connecte des ordinateurs", "est un fichier", "est un programme", "est une mémoire"], 0),
            ("Le protocole :", ["règle de communication", "un fichier", "un programme", "une mémoire"], 0),
            ("Le protocole TCP/IP :", ["la base d'Internet", "un fichier", "un programme", "une mémoire"], 0),
            ("L'adresse IP :", ["identifie un ordinateur sur un réseau", "un fichier", "un programme", "une mémoire"], 0),
            ("Le DNS :", ["traduit les noms en adresses IP", "un fichier", "un programme", "une mémoire"], 0),
            ("Le HTML :", ["langage de création de pages web", "un système d'exploitation", "un protocole", "une base de données"], 0),
            ("Le CSS :", ["met en forme les pages web", "crée le contenu", "est un système d'exploitation", "est un protocole"], 0),
            ("Le JavaScript :", ["rend les pages web interactives", "crée le contenu", "met en forme", "est un système d'exploitation"], 0),
            ("Le client-serveur :", ["un modèle de communication", "un fichier", "un programme", "une mémoire"], 0),
            ("Le cloud computing :", ["le stockage et le calcul à distance", "un fichier", "un programme", "une mémoire"], 0),
            ("La cybersécurité :", ["protège les systèmes", "crée des virus", "est un jeu", "est un fichier"], 0),
            ("Le chiffrement :", ["protège les données", "crée des virus", "est un jeu", "est un fichier"], 0),
            ("L'authentification :", ["vérifie l'identité", "crée des virus", "est un jeu", "est un fichier"], 0),
            ("Le pare-feu :", ["protège le réseau", "crée des virus", "est un jeu", "est un fichier"], 0),
            ("L'intelligence artificielle :", ["simule l'intelligence humaine", "est un jeu", "est un fichier", "est une mémoire"], 0),
            ("Le machine learning :", ["l'apprentissage automatique", "est un jeu", "est un fichier", "est une mémoire"], 0),
            ("Le système d'exploitation :", ["gère les ressources de l'ordinateur", "est un fichier", "est un jeu", "est une mémoire"], 0),
            ("Le processus :", ["un programme en cours d'exécution", "un fichier", "un jeu", "une mémoire"], 0),
            ("Le thread :", ["un fil d'exécution", "un fichier", "un jeu", "une mémoire"], 0),
            ("La mémoire virtuelle :", ["étend la mémoire physique", "est un fichier", "est un jeu", "est un périphérique"], 0),
            ("Le compilateur :", ["traduit le code en langage machine", "exécute le code", "est un fichier", "est un jeu"], 0),
            ("L'interpréteur :", ["exécute le code ligne par ligne", "traduit tout le code", "est un fichier", "est un jeu"], 0),
            ("Le débogage :", ["corrige les erreurs", "crée des erreurs", "est un jeu", "est un fichier"], 0),
            ("Le test unitaire :", ["teste une unité de code", "teste tout le système", "est un jeu", "est un fichier"], 0),
            ("La documentation :", ["explique le code", "est inutile", "est un jeu", "est un fichier"], 0),
            ("Le versionnage :", ["gère les versions du code", "est inutile", "est un jeu", "est un fichier"], 0),
            ("Git est :", ["un outil de versionnage", "un jeu", "un fichier", "une mémoire"], 0),
            ("Le dépôt (repository) :", ["stocke le code versionné", "est un jeu", "est un fichier", "est une mémoire"], 0),
        ],
        "sections": [
            ("ALGORITHMIQUE ET PROGRAMMATION", [
                "Écrire un algorithme pour calculer la somme des n premiers entiers.",
                "Écrire un algorithme pour déterminer si un nombre est premier.",
                "Écrire un algorithme de tri d'un tableau.",
                "Écrire une fonction récursive pour calculer la factorielle.",
                "Écrire un algorithme de recherche dichotomique.",
            ]),
            ("STRUCTURES DE DONNÉES", [
                "Implémenter une pile et une file.",
                "Parcourir un arbre binaire.",
                "Représenter et parcourir un graphe.",
                "Implémenter une liste chaînée.",
                "Comparer les complexités des structures de données.",
            ]),
            ("BASES DE DONNÉES", [
                "Créer une base de données et ses tables.",
                "Écrire des requêtes SQL pour interroger les données.",
                "Écrire des requêtes SQL pour insérer, modifier et supprimer.",
                "Définir les clés primaires et étrangères.",
                "Normaliser une base de données.",
            ]),
            ("RÉSEAUX ET WEB", [
                "Expliquer le fonctionnement d'un réseau et les protocoles.",
                "Créer une page web en HTML et CSS.",
                "Expliquer le modèle client-serveur.",
                "Décrire les principes de la cybersécurité.",
                "Expliquer le fonctionnement du cloud computing.",
            ]),
        ],
    },
}


def build_mcq(subject_key, cfg, set_num):
    subject = cfg["subject"]
    level = cfg["level"]
    class_label = cfg["class"]
    series = cfg["series"]
    exam = cfg["exam"]
    questions = cfg["mcq"]

    n = len(questions)
    start = (set_num - 1) * 20 % n
    selected = [questions[(start + i) % n] for i in range(20)]

    lines = [
        f"# CAMEROON {exam} {subject.upper()} P1 SET {set_num}",
        "",
        "## Multiple Choice Question Bank",
        "",
        f"**Level:** {level}",
        f"**Class:** {class_label}",
        f"**Series:** {series}",
        f"**Subject:** {subject}",
        f"**Exam:** {exam}",
        "",
        "**Instructions:**",
        "",
        "- Choisis la bonne réponse A, B, C ou D pour chaque question.",
        "- Reporte clairement tes réponses sur la feuille de réponses fournie.",
        "- Chaque question vaut le même nombre de points. Aucun point n'est retiré pour une mauvaise réponse.",
        "- Utilise le corrigé à la fin de l'épreuve pour vérifier tes réponses.",
        "",
        "---",
        "",
        "## QUESTIONS",
        "",
    ]

    for i, (q, options, correct) in enumerate(selected, 1):
        lines.append(f"**Q{i}.** {q}")
        lines.append("")
        for letter, opt in zip("ABCD", options):
            lines.append(f"{letter}. {opt}")
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("## CORRIGÉ")
    lines.append("")
    for i, (q, options, correct) in enumerate(selected, 1):
        lines.append(f"{i}. {options[correct]}")
    lines.append("")

    return "\n".join(lines)


def build_set(subject_key, cfg, set_num):
    subject = cfg["subject"]
    level = cfg["level"]
    class_label = cfg["class"]
    series = cfg["series"]
    exam = cfg["exam"]
    sections = cfg["sections"]

    n = len(sections)
    start = (set_num - 1) % n
    ordered = [sections[(start + i) % n] for i in range(n)]

    lines = [
        f"# CAMEROON {exam} {subject.upper()} SET {set_num}",
        "",
        f"## Structural Question Bank - Set {set_num}",
        "",
        f"**Level:** {level}",
        f"**Class:** {class_label}",
        f"**Series:** {series}",
        f"**Subject:** {subject}",
        f"**Exam:** {exam}",
        "",
        "**Instructions:**",
        "",
        "- Réponds à toutes les questions de manière claire et organisée.",
        "- Montre tous les calculs et raisonnements lorsque c'est nécessaire.",
        "- Utilise la terminologie et les normes de présentation de l'examen camerounais.",
        "- Les schémas, tableaux et graphiques doivent être inclus lorsque c'est utile.",
        "",
        "---",
        "",
    ]

    qnum = 1
    for section_title, questions in ordered:
        lines.append(f"## SECTION {qnum}: {section_title}")
        lines.append("")
        for q in questions:
            lines.append(f"**Q{qnum}.** {q}")
            lines.append("")
        qnum += 1

    return "\n".join(lines)


def main():
    for subject_key, cfg in SUBJECTS.items():
        d = BASE / (subject_key + "-terminale" if subject_key == "svt" else subject_key)
        d.mkdir(exist_ok=True)
        for set_num in (1, 2, 3):
            path = d / f"mcq-{set_num}.md"
            path.write_text(build_mcq(subject_key, cfg, set_num))
            print(f"Created: {path}")
        for set_num in (4, 5, 6, 7):
            path = d / f"set-{set_num}.md"
            path.write_text(build_set(subject_key, cfg, set_num))
            print(f"Created: {path}")


if __name__ == "__main__":
    main()
